### ISSUE TITLE
Dngrep search not searching inside ".git" folder

### ISSUE THREAD

**Issue by enthusedcoder** [dnGrep/dnGrep#1009]
Hello.  So, I was hoping to use DNGrep to perform some text substitutions within files that are in a git repository that has been cloned.  As you know, each git repository has a ".git" folder in the root folder that stores git config info, and there is information here that I wanted dngrep to go and modify.  However, despite the fact that I am pretty sure I configured dngrep correctly in order to accomplish this, it would seem that dngrep just isn't processing the contents of the .git folder, as the file within that folder that contains matches to the text I enter is not being returned by dngrep.  See below:

![image](https://github.com/dnGrep/dnGrep/assets/127647168/4c3f224d-eab3-466a-991a-07614af6cfd8)

**Comment by doug24** [comment]
In the filters section, near the top-right, uncheck "Use .gitignore".  When that is checked, dnGrep skips the .git folder.

**Comment by enthusedcoder** [comment]
> In the filters section, near the top-right, uncheck "Use .gitignore". When that is checked, dnGrep skips the .git folder.

Ahhh.  So it does.  Thank you sir.
