### ISSUE TITLE
[Request] Use system locale to display date/time

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#1011]
It would be greatly appreciated if possible.

To me, this looks like May 12th rather than Dec 3rd, and I would prefer to view the time in 24hr format.

![Screenshot 2023-12-14 131139](https://github.com/dnGrep/dnGrep/assets/1332009/4fdc0df5-e343-4c82-8099-77717b8a518c)

**Comment by doug24** [comment]
Yes, I'll fix it.  I thought this was set to use the current locale, but this string is formatted in the xaml code, and xaml defaults to the InvariantCulture.   

When fixed, both the date and time will use the settings defined in your Windows Control Panel Region settings.  The English - UK settings will correct the date and month positions and change the clock to 24-hour format.

**Comment by doug24** [comment]
Fixed in [v4.1.4](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)
