### ISSUE TITLE
Test Result Failure

### ISSUE THREAD

**Issue by PaltryProgrammer** [dnGrep/dnGrep#1014]
greetings kind regards
thank you for providing dnGrep
i am no doubt mistaken and i apologize as i can not determine my error as it seems to me the unlikely has occurred id est a regex error . please see attached images and GIF . in the "Simple" example i expect `<aaa>` to be replaced w/ `aaa` but instead as you can see it is not . also attached is  GIF demonstrating Visual Studio performing the more complex RegEx as expected id est i am attempting to replace the angled brackets w/ quotes and remove the `SDL3` path .
thank you kindly
![Failure Test Replace Simple Example](https://github.com/dnGrep/dnGrep/assets/48535920/52cb555b-9d55-4b3a-bf70-a598d3f4710b)
![Failed Test Replace Result](https://github.com/dnGrep/dnGrep/assets/48535920/97d680c8-2b8c-41cf-a967-5994b477cebc)
![Success In Visual Studio](https://github.com/dnGrep/dnGrep/assets/48535920/03356d0c-247c-4073-8d93-3c83ce6fdc01)
![About dnGrep](https://github.com/dnGrep/dnGrep/assets/48535920/e3183bf2-81e6-4668-85d1-40ac4d9f46ec)

**Comment by doug24** [comment]
It's the whole word option again - remember #813 from 11 months ago?  We made a change for a new way to define whole words in a regular expression. I didn't make the same change to the regular expression replace method. It's a simple change and I'll put it in the January release in a couple of weeks.  In the meantime, you can try unchecking the whole word option.

**Comment by doug24** [comment]
Fixed in [v4.1.4](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)
