### ISSUE TITLE
Very unexpected behavior on program update

### ISSUE THREAD

**Issue by DerellLicht** [dnGrep/dnGrep#1026]
I just upgraded to V4.1.4.0 ... since the program was already installed, I assumed that it would recognize that it was already installed, and upgrade the existing copy - by default... like all other Windows programs do these days!!

Instead, it un-installed my existing copy, and installed the program in the default location - in Program Files - which changes where the configuration files are stored...

This is *absolutely* unexpected and improper behavior, *definitely* counts as a bug!!
Thank the gods it didn't remove my custom files when it removed the rest of the program, but the only reason I understood what was going on was because I've been editing theme files!!

Since the installer obviously knew where it was already installed, it needs to install the upgrade in the same location... 
Please fix this bug for the next upgrade...

**Comment by doug24** [comment]
I have fix for this for the next release.  Actually, it will take two releases before it works correctly. The first will write the registry value for the installation directory, and the second will read and use that value.

**Comment by doug24** [comment]
Available in [release 4.1.27](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.27.0)

**Comment by DerellLicht** [comment]
Thank you very much!!!  Excellent work...
