### ISSUE TITLE
dnGrep 4.1.7 not starting

### ISSUE THREAD

**Issue by kumar007git** [dnGrep/dnGrep#1031]
dnGrep 4.1.7 is not starting. It is being blocked as malicious by anti virus software. It's not running on any of my multiple PCs, all of which have different windows OS and different anti virus.

Even Windows OS shows me the dialog box saying App is not safe, 'Run', 'Don't Run' dialog box. Old versions did not do that.

I reverted back to 4.1.4 and this version works just fine. 4.1.7 needs to be fixed.

Thanks.

**Comment by doug24** [comment]
What URL did you download the package from?  
Does the SHA-256 match what is on the github release page?
What antivirus are you running? 

v4.1.7 has been downloaded 1,878 times from the github release page, and so far, you are the only one reporting a problem.

The msi packages were scanned by the code signing provider before they were signed and put on the github release page.

They were scanned again by Microsoft as part the WinGet release process.

The changes from 4.1.4 to 4.17 were minor.  

If anyone else is seeing issues, please report them here.

**Comment by kumar007git** [comment]
Hi Doug,
I downloaded from Github releases page for 4.1.7. I went to https://dngrep.github.io/ and clicked on download button which took me to https://github.com/dnGrep/dnGrep/releases/tag/v4.1.7.0 which is where I downloaded from. I did not check the hash of the downloaded files. I actually used the portable version in zip file.

I use Norton, McAfee, and Windows Defender, not on the same computer but on different computers, one anti virus each on a computer.

I reverted back to 4.1.4 and it had no problem starting up.

**Comment by fade2gray** [comment]
Windows 11 22H2 / Windows Defender.
No issues reported downloading/installing 4.1.7.x64 over 4.0.189.

**Comment by doug24** [comment]
Ah, OK then this is not an issue.

Please google "ws.reputation.1 norton"  

From the Broadcom website (owner of Symmantic/Norton), with my emphsis:

> When using Symantec Endpoint Protection (SEP), the SEP client may log WS.Reputation.1 detections on **legitimate executable files or installers from trusted vendors. Depending on policy settings, these files may be quarantined or deleted.**
> 
> The WS.Reputation.1 detection indicates a suspicious file and not a traditional anti-virus/malware detection. This SEP detection is from the Insight (File Reputation) feature of the SEP client. This detection conveys that the file's global reputation within the larger Broadcom community is not yet trusted based on information such as age, hash, and number of times seen. 
> 
> The most common cause of this is a change to the file, such as a new version of an application. When the new application version is deployed to a SEP endpoint, SEP client will look up the file from the Broadcom Insight database. If the file is too new or doesn't have enough usage to determine if the file is trustworthy, the SEP client returns a detection of WS.Reputation.1. **However, this does not indicate that the file is a threat, only that it is not trusted based on the prevalence in the larger Broadcom community based on usage, age, and other factors.**
> 
> However, the WS.Reputation.1 detection can and will effectively catch new legitimate threats in the wild, so please only follow this KB if you are 100% sure that the software being detected is legitimate and was supplied from a valid, trustworthy source. 
>

**Comment by doug24** [comment]
If you want to run these settings on your antivirus, then you should probably stay a month or two behind the latest release.
