### ISSUE TITLE
Regex replace with new line

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#104]
_From [ahen...@gmail.com](https://code.google.com/u/118378448538159476673/) on September 01, 2011 06:30:15_

What steps will reproduce the problem? ---------------------------------------
1. In a text file, have a string like this: "This is my test file, here should be a new line!"
2. Use "Regex" search option.
3. Search for word "here"
4. Replace with "\n", the new line character.
## What is the expected output? 

This is my test file, 
 should be a new line!
## What do you see instead?

This is my test file, \n should be a new line! What version of the product are you using? On what operating system? --------------------------------------------------------------------
Version 2.5.0, Windows XP SP3 Please provide any additional information below.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=100_

**Comment by majkinetor** [comment]
I can't make this work ?

![image](https://user-images.githubusercontent.com/85767/88791298-cc89b600-d199-11ea-83ba-472184e5e2c3.png)

**Comment by majkinetor** [comment]
Oh, sorry, I didn't realize I can insert actual new line in replacement edit control.

Ignore above.

**Comment by JVimes** [comment]
There might be a usability problem here, though. It could either handle inline newlines, or warn the user (when the Multiline checkbox is checked). I duno'.
