### ISSUE TITLE
Copy settings

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#1042]
This may be the wrong place for this.
I am migrating to a new PC and want to copy all of my settings.
How can I do this?  I didn't see anything in the Wiki about that, and my searches were unable to find anything.

Thank you

**Comment by doug24** [comment]
In dnGrep, on the About menu, find "Application data and logs".  That will open the folder you need. You can copy the whole folder.

dnGREP.Settings.dat
bookmarks.xml
Scripts directory
Filters directory
This folder also contains additional theme files.  Sunset.xaml is installed by dnGrep.

If you installed dnGrep in Program Files, this folder is:
C:\Users\_username_\AppData\Roaming\dnGREP

If you installed to a location outside Program Files or use a portable zip version, the files listed above will be in the same folder where the dnGrep.exe file is, or a subfolder from there.

**Comment by mdell-seradex** [comment]
Thank you very much.
