### ISSUE TITLE
Support 3MF files

### ISSUE THREAD

**Issue by ingoiot** [dnGrep/dnGrep#1044]
could you please add 3mf files to the supported ones?
They are just renamed ZIP files and work when i rename them.
It would just be convenient not to have to rename the file everytime i want to search them.

tnx

**Comment by doug24** [comment]
You should be able to add the 3mf file extension to the list of Archive files in the dnGrep Options dialog.  Then dnGrep will open those files and search the contents the same as zip files.

**Comment by ingoiot** [comment]
tnx, worked.
