### ISSUE TITLE
Issues searching large files

### ISSUE THREAD

**Issue by devilmanzato** [dnGrep/dnGrep#1047]
Good afternoon, 
I've been using dnGrep for a while and it's been great. However, I've started noticing that I'm having issues to search inside files that are bigger than 100 MB. 

If I do a regular grep against the same folder, I see results from another file, which was scanned by dnGrep during it's search.
This is the search I'm performing on dnGrep:

![image](https://github.com/dnGrep/dnGrep/assets/60189196/63788baa-0552-4583-a2f6-b40bfeaec042)

And this was a grep output, showing that I have the same word on another file:
![image](https://github.com/dnGrep/dnGrep/assets/60189196/281a034b-f31c-4e15-aafc-76233101bfe6)

This specific file has 107 MB. 
I've tried to search as Text and also as a regular expression, enabled and disabled "Search parallel",  increased the match timeout exception for regular expressions to 60 seconds. 

The dnGrep logs show as if it is a successful search, but doesn't show the file in the results.
I'm testing from a machine that has 16gb of memory (about 8 GB available), and plenty of hard drive space available.
I've tried to search on older threads, but couldn't find a similar issue. Could this be something related to my search terms?

**Comment by doug24** [comment]
I don't see anything obvious that you are doing wrong.  I have a test file I use regularly that is 219 MB, and 819,000 lines, so I don't think it is just the size of the file.

If you leave the 'Search for' field empty, then dnGrep will list all the files that meet the filter criteria, and it would search.   Does your file show up in the list?

If that doesn't help, can you zip your file and attach it here?

**Comment by devilmanzato** [comment]
When I leave the Search For empty, I do see the file listed.
Unfortunately, I can't attach the file here, as it contains sensitive information. I'm trying to anonymize the file so I could share it.
Even if I limit the search to the file specifically (instead of searching the folder), it doesn't find anything.

**Comment by doug24** [comment]
That would be great if you can, I'll need something to reproduce the problem.

You can also check the dnGrep log file - from the About menu in dnGrep -> Application data and logs to open the folder.

**Comment by devilmanzato** [comment]
I've tried to check the logs, but it returns as a successful search: 

```xml
<logevent time="2024-02-12 18:04:33.0487" level="Info" logger="dnGREP.Common.GrepCore">
  <message>Maximum concurrent tasks used in search: 8</message>
</logevent>
<logevent time="2024-02-12 18:04:33.0487" level="Info" logger="dnGREP.WPF.MainViewModel">
  <message>Search completed in 6.783s – 14 matches found in 1 files of 49 searched. Search for: sandisk	6.783s	14	1	49</message>
</logevent>```

Is there a "debug" level of logs that I could enable?

**Comment by doug24** [comment]
No, that's all the logs.

Is there anything strange with the file encoding?  If you open the file in Notepad++, Notepad3, or similar, what encoding is reported there?  

Try setting the encoding in dnGrep to a specific encoding rather than Auto Detection (you'll have to try a several - no way to guess what it is).

**Comment by devilmanzato** [comment]
Opened the file on Notepad++ and it reported UTF-8 as encoding.
After I've set the encoding to Unicode (UTF-8) on dnGrep it searched in the file.

**Comment by doug24** [comment]
Yes, I think it would be helpful if you can.  Not sure if I can fix it, however.

Unfortunately, files do not identify how they are encoded unless they are UTF-8 with a byte order mark.  Most text files just get encoded however the writer wants and it's up to the reader to guess the encoding.

There is something fooling the encoding detection code - maybe the first 1k of the file is not representative of the majority of the content?
