### ISSUE TITLE
Question with translation to Catalan

### ISSUE THREAD

**Issue by Csavie** [dnGrep/dnGrep#1055]
Hi,

I'm doing the translation to Catalan with Weblate, and I'm at 51%. I'm testing it via download .resx file.

My question is that some strings are correctly translated in dnGrep, but others not. For example the word 'Settings' in Main Menu. Here you can see that with catalan language (parts in yellow), the word 'Settings' is not translated:

![Settings](https://github.com/dnGrep/dnGrep/assets/86087176/29febd58-5242-4d36-b65a-e657896a6893)

Here you can see that word 'Settings' is translated in Weblate:

![Weblate](https://github.com/dnGrep/dnGrep/assets/86087176/bb6457c6-2598-4ec9-974d-bcd19d83ebe4)

The same happens with all other strings in Main Menu, and many other strings. I see inside the file "dngrep-dngrep-application-ca.resx" (that's the file I reload from Options) that contains:

  <data name="Main_Menu_Settings" xml:space="preserve">
    <value>_Configuració</value>
    <comment>Main window, main menu item label (accel)</comment>
  </data>

I'm doing something wrong?

Csavie

**Comment by doug24** [comment]
It sounds like what you are doing is correct, but I'm wondering if you have an older copy of the translation file? 

It appears to be working for me - here is what I did:

In Weblate, I selected the Catalan translation, and selected Files -> Download Translation from the top of the page.  This gives me the dngrep-dngrep-application-ca.resx file at 111 KB.

Start dnGrep, open the Options dialog and next to the Language setting, click the Load from file... button.  Select the file downloaded.

Oh, try this - in dnGrep, change the language something other than Catalan, save the setting and restart dnGrep.  Now, without using the language selection drop-down, click the Load from file... button, and select your file.

![image](https://github.com/dnGrep/dnGrep/assets/17227248/f3788d8b-e74c-470e-9d1b-865ea10f86b7)

**Comment by Csavie** [comment]
Doug,

Yeaaaa,this worked. 

But after doing this I can't save the Options, I close Options, and :

-If I enter at Options, there is 'catalan' language in drop-down, I can save, but at restart, dnGrep returns with the partial translation.
- If I close the dnGrep and restart, the language is the language previously selected.

Is possible that the partial transation is inside file 'dnGREP.Localization.resources.dll' and when catala is selected in drop-down read this file in place the .resx.


Csavie

**Comment by doug24** [comment]
You will need to load the external file each time you start dnGrep, it does not 'save' and reload from the file automatically.

**Comment by Csavie** [comment]
I tried to "compile" the resx file with RESGEN,EXE and AL.EXE, but with no success, surely the versions of this programs I have, are not the correct ones.
I will wait the new official version of dnGrep. 

Csavie.
