### ISSUE TITLE
V4.1.27.0 - possible issue with About menu

### ISSUE THREAD

**Issue by DerellLicht** [dnGrep/dnGrep#1060]
I'm not sure how long this issue has been present, I just discovered it now, when I went to look for the Help option...

If I hover the mouse button over the About button, it does not highlight, and I cannot select that menu... what is interesting, though, is if I *slowly* move the mouse cursor up to the About menu, there is a very narrow region all around the menu item (about 2-3 pixels in width) where I *do* get the menu highlight, and every thing works fine, but that box is difficult to actually access, as it is so narrow.

Note: all of the other menu items (Settings, Scripts, Bookmarks) all work fine on mouse hover.

tbh, I am not entirely sure that this isn't related to WindowBlinds in some way, though I'm not able to reproduce it in any other program... I *think* you use the standard WinAPI menu settings, so it should "just work"... 

Anyway, maybe you could just check to see if you have the same issue??  Thanks!!

**Comment by doug24** [comment]
No, I do not have that problem, the whole menu button is active.  Same if the preview window is docked to the right.

![capture-000261](https://github.com/dnGrep/dnGrep/assets/17227248/3ea7f613-d1f8-4e73-87ad-ae8777af0743)

**Comment by DerellLicht** [comment]
hmmm... well, okay... mark this inactive for now; I'll see if I can get any other clues...

**Comment by DerellLicht** [comment]
Okay, I'm using V4.1.47.0, as well as a different WindowBlinds theme, and this issue is no longer present... this appears to have been an issue with the WB theme that I was using back then.  Closing the issue.
