### ISSUE TITLE
Exclude search results that are invalid from results?

### ISSUE THREAD

**Issue by Dxhs** [dnGrep/dnGrep#1061]
The result list is sometimes flooded with red-marked lines. At my workplace, a lot of PDFs are scanned documents and therefore unsearchable, and I don't need the results from these documents.

![image](https://github.com/dnGrep/dnGrep/assets/13475068/9af5c12f-2480-4b29-9e5e-62ca8e55f9af)

**Comment by Tix2garr** [comment]
I'm relatively new to dnGrep, so was **just** looking in the help piece and noticed in Options (F8) > Search results, there is a checkbox for "Show files with search errors in results panel".  I would _guess_ unchecking that would solve your problem.  

I'm not certain if Settings > Personalize needs to be checked or not, though.  I haven't gotten any errors (that I recall), so don't know if that's one of the things that would be toggled to show/not show.

Michael

**Comment by doug24** [comment]
Michael is correct, you want to uncheck "Show files with search errors in results panel".  The red exclamation mark will still show in the status bar indicating that not all files were searched, and if you want to know more, you can check the dnGrep error log file.

Personalize is not needed in this case.  That is used to declutter the main window by hiding controls and filters that you rarely or never use.  You select what controls and filters to hide in the Options dialog.

**Comment by thewriteway** [comment]
I'm glad there was an issue raised for this so now I know what to do to turn it off.
