### ISSUE TITLE
How to lower priority and limit number of subprocesses when running dnGrep - Win10 almost freezing

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#1062]
As I found out my Windows 10 system is almost freezing when I run dnGrep to search a pattern in all *.pdfs on my partition.

I quick look into Task Manager shows me that dnGrep opens many, many pdftotext.exe sub processes.

How can I limit the number of possible sub processes?

Can I limit the process priority?

Can I limit the CPU load?

if not: Can these features be added in the next version?

**Comment by doug24** [comment]
You can limit the number of search threads which will limit the number of pdftotext.exe processes at any one time.  

In the Options dialog, Search options section: "Maximum number of parallel searches".  

Or on the main window, uncheck "Search parallel" and you will have only one.
