### ISSUE TITLE
 快捷键如何自定义? 

### ISSUE THREAD

**Issue by zbb7001** [dnGrep/dnGrep#1063]
- dnGrep能否增加`索引`选项?
- 快捷键如何自定义? 比如说`F3`键和`F4`键，`F3`键可以用，而`F4`键因为和哪个软件冲突，就不能用，我却不知如何修改。

![image](https://github.com/dnGrep/dnGrep/assets/101622397/740618b0-f2e6-46aa-a218-9464a3de477c)
- `A`：能否直接在此处选择文字并复制？ （现在只能将段落全部复制）

**Comment by doug24** [comment]
No, there is no option to customize the shortcut or function keys. When dnGrep has focus, it should be the only application responding to these key presses - if some other application is handling them, they are wrong and mis-using the system. That is not a problem dnGrep can fix.

No, there is no option in this window (the results tree) to select text and copy it.  You can do that with the preview pane which is synchronized with the selected line/paragraph in the results tree.

**Comment by zbb7001** [comment]
### 感谢您的回复！
- 请问后期会加入`索引`功能吗？
  - 有时在使用`dnGrep`进行搜索时，电脑会有点卡顿，会不会加入索引会有所改善？当然了，没有人会期待`dnGrep`如同`Evething`一样，对我来说，dnGrep已经做得非常好了。

**Comment by doug24** [comment]
Sorry, the translation makes this confusing - what feature?  I do not plan to add the capability to allow the user to change the function key mapping.  I also do not plan to implement word selection in the results tree - that control is very complicated already, lots of work to change, and the preview control already has that capability. 

If dnGrep using too many resources on your computer, you can limit the number of threads it uses during a search as I answered here: https://github.com/dnGrep/dnGrep/issues/1062.  

dnGrep does not use indexing, it does a full search each time.  You can use the "Everything" application to index file names on your computer and then dnGrep can use Everything to find the files.  But that is already the faster part of the search process, so do not expect a significant improvement doing that.  More of the time is spent reading and searching the text, or doing other tasks like converting PDF to text.
