### ISSUE TITLE
Request: Add option to the More menu

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#1064]
Would it be possible to append the number of matches to each of the listed files when selecting `More > Copy file names`, or create a new report option that would achieve the same?

**Comment by doug24** [comment]
I think adding a new menu item `Copy file names with match count` may be the way to go.  

Do you want it to include the same message as on the results list, such as `(4 matches on 3 lines)`, or just the number of matches, or something else?

**Comment by fade2gray** [comment]
Matches and lines would be great. Thank you.

**Comment by doug24** [comment]
Added in [4.1.47](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.47.0)
