### ISSUE TITLE
Request: Add extra option to the Sort menu

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#1067]
Would it be possible to add sort by `[read-only]` to the available options, and also be included with my request at #1064 (sorry for not thinking about it then)?

**Comment by doug24** [comment]
A read-only sort would only create two buckets.  But yes, I guess I can see how that may be useful.

**Comment by fade2gray** [comment]
> I guess I can see how that may be useful.

Absolutely, for my use case. 😊

**Comment by doug24** [comment]
Added in [4.1.47](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.47.0)
