### ISSUE TITLE
`.git` folder is not always excluded when `Use .gitignore` is checked

### ISSUE THREAD

**Issue by yyjdelete** [dnGrep/dnGrep#1076]
Tested with 4.1.27.0 and master(e2713e0)

Debug show if `gitignore.IsEmpty`, it will call `EnumerateAllFiles` instead of `EnumerateFilesWithFilters`, which do not excluded `.git` folder
https://github.com/dnGrep/dnGrep/blob/e2713e0138398b68b181f7ea2ce1abb42442b3ce/dnGREP.Common/SafeDirectory.cs#L122-L130

**Comment by doug24** [comment]
Thanks, I will take a look.

**Comment by doug24** [comment]
Fixed in [4.1.92](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.92.0)
