### ISSUE TITLE
Issue removing all archive extensions in settings

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#1087]
If all extensions are deleted from the list of archives and settings are then saved, when returning to settings the list is found to have been repopulated. A workaround to avoid this is to replace the list with an asterisk.

**Comment by doug24** [comment]
I never thought that someone would want to do this. It is probably falling into the code initializing data when a new settings file is created. I'll look at it.

**Comment by fade2gray** [comment]
I only discovered it by chance. I needed to search within a zip file and lazily did a Ctrl+A Del, rather than just removing the zip extension, used the *.zip pattern match, but didn't get the result I expected.

**Comment by doug24** [comment]
Fixed in [v4.2.6](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.6.0)
