### ISSUE TITLE
File contains corrupted data.

### ISSUE THREAD

**Issue by atqooh** [dnGrep/dnGrep#1092]
How to skip "File contains corrupted data." 
![image](https://github.com/dnGrep/dnGrep/assets/36100023/48b3d7fe-90cc-42e6-8b16-7484eff570eb)

**Comment by doug24** [comment]
A few suggestions:

In the Options dialog, in the Search results section, uncheck "Show files with search errors in results panel".

 If all the files in this folder have the same error, you can exclude the directory from the search by putting the folder name in the "Patterns to exclude" box:
\ALL CLOUD CHANNELS\*

You can also create an "ignore" file to exclude that folder.  [See more here](https://github.com/dnGrep/dnGrep/wiki/File-Filters).
