### ISSUE TITLE
Feature Request : adding options to disable autocomplete

### ISSUE THREAD

**Issue by tommy030314** [dnGrep/dnGrep#1101]
The autocomplete feature sometimes gets in the way. It would be nice to have an option to disable it

**Comment by doug24** [comment]
OK, will add in the next release.

**Comment by tommy030314** [comment]
Thanks!

**Comment by doug24** [comment]
Fixed in [v4.2.6](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.6.0)
