### ISSUE TITLE
add self create plugin

### ISSUE THREAD

**Issue by huahua74** [dnGrep/dnGrep#1110]
[Apache Tika] does not support MSG file in Unicode. I tend to add the other Apache MSG Conversion from 
https://github.com/YujiSoftware/msg2txt?tab=readme-ov-file
it is based on the jar project @
http://jar.fyicenter.com/2732_Msg2txt-Apache_POI_Outlook_Email_Example.html

the batch file will convert "abc.msg" to "abc.txt" in the same folder. How will dnGREP read the "abc.txt"?  can I add anything  in the {outputFile}?

I create a plugin file as below. 
Name=MSG
Application=xx\dnGrep.4.1.92.0.x64\Plugins\MsgSearch\bin\msg2txt-1.1.0\bin\msg2txt.bat
Arguments="{inputFile}" /t
Extensions=msg

**Comment by doug24** [comment]
Is msg2txt.bat something you wrote - I don't see it on the sites you linked. 

Either way, can you modify msg2txt.bat?  Try adding the command `type abc.txt` to the end of the batch file, which will copy the contents of the file to standard output.   Then delete the generated abc.txt to clean up.

Your plugin file should be good as-is.  With no {outputFile} argument, dnGrep will look for the text in the standard output of the conversion command.

**Comment by huahua74** [comment]
thanks, I can now pass the output to dnGREP as following

> Name=Msg2Txt
> Application=cmd.exe
> Arguments= /c msg2txt.bat "{inputFile}"
> WorkingDirectory=C:\_a\dnGrep.4.1.92.0.x64\Plugins\msg2txt\bin
> Extensions=msg

However, the utf8 does NOT readable. I have added the 
chcp 65001
type {outputFile}

everything fine in the cmd console window, but does NOT work in dnGREP preview, and cannot been searched. 

I change the "Move... --> Encoding --> UTF8", but does not change the result.

**Comment by doug24** [comment]
If you attach you batch file here, I can take a look at it.  And a sample .msg file, if possible.

I'm not sure how to read your text file - how will dnGrep know the name of the file the external application created? In this case it is the original file name with the extension changed, but that may not always be so. 

Here's another idea - use the {outputFile} option on the command line which will give you the name of the file dnGrep will look for as the converted file. That will be a second argument to your batch file. In your batch file, change the name of the generated txt file to the name provided by dnGrep (and remove the `type` command).

**Comment by huahua74** [comment]
How I use the  - use the {outputFile} option on the command?? shall I ass in the xx.plugin, Arguments= /c msg2txt.bat "{inputFile}" "{outputFile}"?

the batch file will convert the "c:\a\bcd.msg" to "c:\a\bcd.txt", then type "c:\a\bcd.txt", then remove "c:\a\bcd.txt". In the whole process, the batch will only read  "c:\a\bcd.msg", but not change  "c:\a\bcd.msg".  the batch file was revised from https://github.com/YujiSoftware/msg2txt/releases/download/1.1.0/msg2txt-1.1.0.zip

:execute

@rem Execute msg2txt
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %MSG2TXT_OPTS%  -classpath "%CLASSPATH%" org.apache.poi.examples.hsmf.Msg2txt /t %*

_set str=%*
set str=%str:.msg=.txt% 
chcp 65001
type %str%
del %str%_

just add italic part in the msg2txt.bat. A sample result like the attachment.
[1.txt](https://github.com/dnGrep/dnGrep/files/15268595/1.txt)

**Comment by doug24** [comment]
The {outputFile} will be the full path and file name for a file under the %temp% directory.  dnGrep uses this file for the preview window and will delete the temp subdirectory when it is done.  The file name is constructed using the source file name, adding a unique identifier (in case the same file name exists in more than one search folder), and changing the extension to .txt. It will look something like this:
`C:\Users\user\AppData\Local\Temp\dnGrep-temp-YpxPXZQk9sur\dnGREP-Msg2Txt\msgfile.txt`

You add the {outputFile} to the batch file command line.  Here is my .plugin file:
```
Name=Msg2Txt
Application=cmd.exe
Arguments=/c msg2txt.bat "{inputFile}" "{outputFile}"
WorkingDirectory=C:\Repos\dnGrep\Plugins\MsgSearch\msg2txt-1.1.0\bin
Extensions=msg
```

I modified the msg2txt.bat as follows:
```
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %MSG2TXT_OPTS%  -classpath "%CLASSPATH%" org.apache.poi.examples.hsmf.Msg2txt %1

for %%f in (%1) do set filename=%%~dpnf
set "textfile=%filename%.txt"
move "%textfile%" %2
```

Note the last argument on the %JAVA_EXE% line is changed from `%*` to `%1` - you want to pass just the first batch file argument to the app, not all the arguments.

Then construct the file name we know the java app has created in variable `textfile`.  The `for` line gets the full path and file name without the extension.  The next line adds the .txt extension. Finally, move that file to the location and file name that dnGrep supplied in batch file argument 2: {outputFile}.

And it works - I was able to extract Simplified Chinese characters from a .msg file and the text file is UTF-8 encoded.

**Comment by huahua74** [comment]
Great! it works, many thanks! just wonder whether we can do the same to ApacheTika. I will post it to the other chain

**Comment by huahua74** [comment]
Further improve the script, so the file will be saved in the temp folder of dnGREP directly, avoid messing the original folder
```

for %%f in (%2) do set outputPath=%%~dpf
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %MSG2TXT_OPTS%  -classpath "%CLASSPATH%" org.apache.poi.examples.hsmf.Msg2txt /t  --output=%outputPath% %1
for %%f in (%1) do set filename1=%%~nf
for %%f in (%2) do set filename2=%%~nf
move "%outputPath%%filename1%.txt" "%outputPath%%filename2%.txt"
```
