### ISSUE TITLE
Regex: Support for matching only first occurrence (non global)

### ISSUE THREAD

**Issue by htcfreek** [dnGrep/dnGrep#1116]
Currently the regex search matches all occurrences in a search string. But it would be very helpful to have the "match only first occurrence" behavior.

### Match only first:
![20240514_180616.jpg](https://github.com/dnGrep/dnGrep/assets/61519853/28e7f615-0fdd-4c2a-89d3-2bdcb0cd840e)

### Match all:
![20240514_180647.jpg](https://github.com/dnGrep/dnGrep/assets/61519853/a16a6855-85c1-4f49-a305-a4c29ec6ea93)

**Comment by doug24** [comment]
I'm trying to understand your regex and how this is working - what dialect is this?  
How does this work - where in your test string is the string "Appl"?

**Comment by htcfreek** [comment]
1. TecRegex works the same inside ydnGrep.

2 The string `[Appl` is not important for this issue. But to answer your question it is iat the end of the file and not on the screenshot.
```
shshssh = zzz

[Application]
Version = 10.5
```

The goal is to catch the only first `Version = 10.5` inside the first `[Setup]` section of an ini like file.

**Comment by fade2gray** [comment]
I can't get any results unless `[Setup] Version = 10.5 Appl` is included at the end of the test string.

FYI: The decimal separator between the 10 and the 5 hasn't been escaped.

https://regex101.com/r/gSCNDe/2

**Comment by doug24** [comment]
To end the search at [Application] the regex would have to be something like:
`(?<=\[Setup\].+Version\s*=\s*)10\.5(?=.+?\[Appl.*\])`

As you have found, the .net regex does not support the `g` option flag, it is always global.

I can take a look at implementing this in code.

**Comment by htcfreek** [comment]
> I can't get any results unless [Setup] Version = 10.5 Appl is included at the end of the test string.

@fade2gray 
In dnGrep you must enable "treat dot as new line".

**Comment by htcfreek** [comment]
@doug24 

> To end the search at [Application] the regex would have to be something like:
> `(?<=\[Setup\].+Version\s*=\s*)10\.5(?=.+?\[Appl.*\])`

That makes sense.

> As you have found, the .net regex does not support the `g` option flag, it is always global.
> 
> I can take a look at implementing this in code.

Do you use `Regex.Match()` or `Regex.Matches()`? (I didn't find the code part.)

With `Regex.Match()` you get only the first match and to switch to the next one you need `.Next()`.

**Comment by doug24** [comment]
dnGrep creates a Regex instance, and then calls Matches on that:
```
    Regex regex = new(searchPattern, regexOptions, GrepCore.MatchTimeout);
    var matches = regex.Matches(textToSearch);
    foreach (Match match in matches.Cast<Match>())
    {
       ...
    }
```
There are issues with multiline/not multiline.  When not in multiline mode, dnGrep searches each line of a file separately, so it would need to quit after the first match, then stop processing more lines.

**Comment by doug24** [comment]
Added in [v4.2.29](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.29.0)
