### ISSUE TITLE
Everything search string not correctly restored on relaunch

### ISSUE THREAD

**Issue by Dromantor** [dnGrep/dnGrep#1126]
After an application restart the Everything search string is surrounded with quotes, which breaks the search string.

## Example 1:

Initial:
![grafik](https://github.com/dnGrep/dnGrep/assets/1822013/a1230df5-248d-42dd-b0b2-84cc03184c5d)

After relaunch:
![grafik](https://github.com/dnGrep/dnGrep/assets/1822013/7432fd56-74b8-497e-aa7f-d57c1bae9b4b)

## Example 2:

Initial:
![grafik](https://github.com/dnGrep/dnGrep/assets/1822013/a2298ee8-6c6d-4e26-8785-ddce5021e7a0)

After relaunch:
![grafik](https://github.com/dnGrep/dnGrep/assets/1822013/1faa3d42-8e10-408d-a1fd-c282c0ae4634)

**Comment by doug24** [comment]
Right, it shouldn't be doing that.  The code was treating like it was a file path, not a path and file filter.

**Comment by doug24** [comment]
Fixed in [v4.2.29](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.29.0)
