### ISSUE TITLE
Preview in sidebar broken on Byte search

### ISSUE THREAD

**Issue by Dromantor** [dnGrep/dnGrep#1127]
Initial:
![grafik](https://github.com/dnGrep/dnGrep/assets/1822013/561b3977-1195-491b-ae4a-31cf7e22d3d8)

"Preview file" toggled off and on again:
![grafik](https://github.com/dnGrep/dnGrep/assets/1822013/b5cd069c-ba71-4d64-8ca7-f9ee8a4c4f76)

**Comment by doug24** [comment]
Yes, that should not happen, I will fix the exception.

Just to be clear, dnGrep does not support showing Byte search results in the preview window, so toggling the preview window on and off will not show anything in the preview windows.  The search results are shown in the tree and if you want to see the whole file as binary you can open it in an external application.

**Comment by Dromantor** [comment]
Just wondered why the preview didn't work with byte search, so my first impulse was to just toggle the preview.

Some error message like "preview not available on Byte search" would be great then, else you could think it's broken.

Nevertheless, thanks for the quick fix 👍 Can be closed if you want.

**Comment by doug24** [comment]
Fixed in [v4.2.29](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.29.0)
