### ISSUE TITLE
search *.zip failed

### ISSUE THREAD

**Issue by ragebear00** [dnGrep/dnGrep#1133]
when searching for "*.zip", no result can be found. Test the same, it works for "*.pdf", "*.png" and ...

![image](https://github.com/dnGrep/dnGrep/assets/168278723/2f0e1e9d-ec93-4a07-8a52-8167656101d1)

**Comment by fade2gray** [comment]
In Settings > Options, find the list of archive extensions, remove zip from the list and save.

**Comment by doug24** [comment]
Yes, what @fade2gray said.  dnGrep treats archives as compressed folders, not files.  To find them as a file, you have to remove them from the list of archives.

**Comment by fade2gray** [comment]
@doug24 I had to remind myself of this when I couldn't remember where on a drive I had saved some .zip files, but I can find no mention of the situation under [Home/Archive Search](https://github.com/dnGrep/dnGrep/wiki/Archive-Search) or [Options/Archive and Plugins](https://github.com/dnGrep/dnGrep/wiki/Archive-and-Plugin-Options) in the wiki.

**Comment by doug24** [comment]
@fade2gray - thank-you, I've updated those pages.
