### ISSUE TITLE
Searching contents of files in password protected 7z or zip archives

### ISSUE THREAD

**Issue by liny888** [dnGrep/dnGrep#1134]
Can I know whether it is possible to search contents of files in password protected 7z or zip archives?

**Comment by fade2gray** [comment]
I have just tested with a password protected .zip archive created with 7zip and, no, you can't search for text within it.

**Comment by doug24** [comment]
Searching password protected archives is currently not supported in dnGrep.  

The archive can be opened if you supply the password, but this would be a pretty big change, and I don't know if it would be a good idea. You cannot tell if an archive is password protected until after it has been opened, and you try to access a file from the archive.  dnGrep would have to stop and ask for a password for each protected archive found.  dnGrep opens the same archive multiple times to first search and then show the results, so dnGrep would have to cache the password for the duration of the search or session to reuse it.  Previously protected files may be written to the Windows temp directory.

**Comment by liny888** [comment]
Thanks for your prompt replies

**Comment by liny888** [comment]
Sorry to resurrect this - I am wondering, if I only have 1 7z file that I want to index and search, any workaround?

**Comment by doug24** [comment]
I think your only choices would be to extract the files and search them outside of the 7z file or recompress them in a new archive without a password.

**Comment by liny888** [comment]
> I think your only choices would be to extract the files and search them outside of the 7z file or recompress them in a new archive without a password.

Thanks

**Comment by adityazainud** [comment]
Sorry to comment on this. But I think it will be a nice addition to be able to index an encrypted 7z or zip files. Only index for subsequent extraction. WinRar does that..

> Sorry to resurrect this - I am wondering, if I only have 1 encrypted 7z file that I want to index and search, any workaround?

**Comment by doug24** [comment]
I'm not sure what you mean by "index".  Are you suggesting that dnGrep should store a list of files and file attributes in the encrypted archive?  That would be a much bigger change than providing a way for the user to enter passwords for encrypted archives.

dnGrep does not build indexes of files (like Everything) or index the content of files (like Apache Lucene).  Each search is started from file filters and when a matching file is found, the file is opened and searched using the search text.  The search result is a set of files with matches, and for each file the location of matches in the file.  When you open a result in the results tree or preview window, dnGrep goes back, reopens the file and extracts the results.  Those search results are discarded at the start of the next search or app exit.

**Comment by fade2gray** [comment]
![pw_protected_zip](https://github.com/dnGrep/dnGrep/assets/1332009/d47dc554-6441-4bab-8121-e515223edabe)

**Comment by doug24** [comment]
I have a couple problems with this:
1) This will not work for 7z files, which require a password to open the archive. So, the behavior between zip and 7z will be different.
2) In order to evaluate some of the file filters in dnGrep, the file needs to be read - which requires a password. So, for password protected zip files, dnGrep would have to skip some filters.

I have always thought of the 'list files' feature as the way to see what files would be searched if there was a search term supplied. That breaks down if this was implemented - you can't search those files without a password.  

No one has ever asked for searching password protected archives before - but maybe there is some desire?  Please comment or thumbs up if you would like to see this feature.

**Comment by fade2gray** [comment]
> This will not work for 7z files, which require a password to open the archive. So, the behavior between zip and 7z will be different.

???
![pw_protected_7z](https://github.com/dnGrep/dnGrep/assets/1332009/6b37ebb8-df94-4bb1-9947-b242bc623a1d)

Personally, I don't see any benefit in including it as a feature, particularly if it requires a lot of overhead in implementing it.

**Comment by doug24** [comment]
I guess I need to update 7zip.  I'm running 23.01, and it will not open the 7z file without a password.  And Windows explorer does nothing.  

If I try to open it with the 7zip API without a password, it throws an exception.

**Comment by fade2gray** [comment]
Likewise, 23.01


https://github.com/dnGrep/dnGrep/assets/1332009/52d54acd-4c95-4917-a252-cb4f0de35d31
