### ISSUE TITLE
search/replace of filenames

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#114]
_From [samuel.z...@gmail.com](https://code.google.com/u/113379871931581493662/) on February 14, 2012 07:38:43_

It would be great if you could also search/replace filenames.
Maybe just a checkbox in the Mainform "include filenames" would be enough.

I really like your software btw : )

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=110_

**Comment by PhiLhoSoft** [comment]
I am not sure adding "replace file names" features to dnGrep is such a good idea. Not fan of "Swiss knife" tools trying to do everything and more. Better stick to Unix philosophy of small tools.
Renaming files goes a bit beyond the initial goal of dnGrep, and there are already tons of good file renamers around.
Personally, I use mostly the Flexible Renamer freeware which is what its name says: very flexible!

**Comment by Werekorden** [comment]
I also would really appreciated a file/replace option for folder and filenames.

**Comment by doug24** [comment]
Can you describe how you picture this working? I'm not sure I understand...  you've run a search - either searching by file name (by leaving the 'Search for' field empty), or by file contents, and you have a list of files in the search results.  Now you want to replace/change the names of the files in the results?
