### ISSUE TITLE
Installer and uninstaller hangs

### ISSUE THREAD

**Issue by skataben** [dnGrep/dnGrep#1143]
Running dnGREP.4.2.29.x64.msi installer hangs when removing temporary files.

After rebooting, the uninstaller hangs at "Please wait while the Setup Wizard removes dnGrep 4.2.25 (x64).

Win 11 23H2

**Comment by skataben** [comment]
Running `winget install -e --id dnGrep.dnGrep` also hangs at Please wait while Windows configures dnGrep 4.2.29 (x64)

**Comment by doug24** [comment]
I don't know has happened.  There were no installer changes in v4.2.29, but several in v4.2.6.  I tested the installer changes in 4.2.6 extensively for new and upgrade installations. The v4.2.6 msi installers have been downloaded about 4300 times, and v4.2.29 about 700 times so far.  

I don't understand the message "Please wait while the Setup Wizard removes dnGrep 4.2.25 (x64)." - there was no 4.2.25 release, so I can't see how this would happen.

Winget downloads and install from the msi, so I wouldn't expect any difference using Winget.

The only thing I can suggest is just general suggestions for fixing installer problems: reboot and uninstall dnGrep completely.  Make sure the files have been removed from the installation directory.  If there are orphaned keys in the installer database, then it is painful to clean up.  Google for suggestions.
