### ISSUE TITLE
please make the options dialog resizable (and remember size and position)

### ISSUE THREAD

**Issue by rhoehener** [dnGrep/dnGrep#1144]

**Comment by doug24** [comment]
I will take a look at this. I seem to recall there are some layout issues and that's why I made it auto size to content on width, and fixed size so the width cannot be changed.

**Comment by doug24** [comment]
Added in [v4.2.46](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.46.0)

**Comment by rhoehener** [comment]
works great so far, thanks a lot!
