### ISSUE TITLE
option (checkbox) to keep focus in search field instead of moving it to the result tree

### ISSUE THREAD

**Issue by rhoehener** [dnGrep/dnGrep#1145]
support quickly searching for multiple variations of something

**Comment by doug24** [comment]
I think the focus moves to the Search button whether you start the search using the button or the Enter key.  But point taken, I'll look at moving it back to the search field.

**Comment by doug24** [comment]
Added in [v4.2.46](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.46.0)

**Comment by rhoehener** [comment]
fantastic, love it! thank you!
