### ISSUE TITLE
Version 4.2.29.0: When searching for empty lines "^\r\n", only the first empty line is found

### ISSUE THREAD

**Issue by BambuschJ** [dnGrep/dnGrep#1147]
Hello Doug,

I have a problem with the new version 4.2.29.0.

When searching for an empty line, only the first occurring empty line is found.
In the old version, dnGrep found all occurring blank lines.

With kind regards / Best regards

J. Bambusch

PS: dnGrep is a great tool - please keep it up - THANK YOU!!!
I will report the tool to the German c't magazine and ask them to bring a report

![dnGrep_SuR_Repead_Data](https://github.com/dnGrep/dnGrep/assets/92531071/02994b8d-0015-4b5f-8815-80249a09b286)
![dnGrep_SuR_Repead_Maske00](https://github.com/dnGrep/dnGrep/assets/92531071/8b9b7549-603d-4459-a6fd-819c28b128be)
![dnGrep_SuR_Repead_Maske01](https://github.com/dnGrep/dnGrep/assets/92531071/a53b002e-c1ff-4a76-836e-d591172b89e6)
[SAP_ZLABST_4ZZZP_20240618-1759.txt](https://github.com/user-attachments/files/15889698/SAP_ZLABST_4ZZZP_20240618-1759.txt)

**Comment by BambuschJ** [comment]
Hello Doug,
version 4.2.6.0 is working fine

Best regards
J. Bambusch
![dnGrep_SuR_Repead_Maske01_V4 2 6 0](https://github.com/dnGrep/dnGrep/assets/92531071/4c3d7c6f-40e2-4416-8624-8ffebb4c0a75)

**Comment by doug24** [comment]
Please see the [release notes](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.29.0) and check the "Global" checkbox.

**Comment by BambuschJ** [comment]
Hello Doug,
that is of course correct - 
**Those who can read have a clear advantage**
Best regards
J. Bambusch

**Comment by doug24** [comment]
I'm sure you won't be the last one to have this problem.  And you weren't the first either - after testing the global feature I forgot to check the Global checkbox and was surprised I was getting only one match per file. :)
