### ISSUE TITLE
Multiple Search pattern strings. One of each line

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#116]
_From [bennoach...@gmail.com](https://code.google.com/u/106265092333552823159/) on April 08, 2012 16:55:28_

Hello

I have searched a Grep tool for Windows and cam across to dnGrep. DnGrep is a realy cool tool. One thing I can not do with it, is to search for multiple files with multiple search strings. For example I have three search strings:
'HELLO1'
'DNGREP'
'FOO'
If I start "Search" the algorithm should start with the first search string 'HELLO1' and search it over select files, than with the next search string 'DNGREP' and search it over the same selected files again. Each result should then view on the tree view.

The reason lies in the fact that with this solution I can copy-paste a list of search strings and can search for all at once.

Could this idea fit your concept or have you other ideas to solve something like this?

Best regards
Benno

PS: For testing purposes I checked out the code and changed it. So that's no urgent thing...

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=112_

**Comment by doug24** [comment]
you can do this now with Boolean Operators in 2.9.196
