### ISSUE TITLE
The searching history incorrectly auto-adds quotation marks

### ISSUE THREAD

**Issue by hw770** [dnGrep/dnGrep#1160]
## description
After searching with everything mode and restarting, the searching history incorrectly auto-adds quotation marks

> before restart:

![image](https://github.com/dnGrep/dnGrep/assets/151506788/6efa7c8e-53a9-44eb-8e09-08cc200c16dd)

> after restart:

![image](https://github.com/dnGrep/dnGrep/assets/151506788/15f3f7ff-4fca-45aa-aac1-2b2676265e41)

No searching results due to the quotation marks.

## Info
version 4.2.6.0

**Comment by doug24** [comment]
This looks like #1126 that was fixed in [v4.2.29](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.29.0), can you try it or [v4.2.46](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.46.0)
