### ISSUE TITLE
Which editor control is dnGrep using?

### ISSUE THREAD

**Issue by raelb** [dnGrep/dnGrep#1161]
First, I want to say thanks - I'm using dnGrep more and more nowadays. The functionality is really good, especially showing the code snippets in results.

I like the code editor. Is this part of dnGrep or using another control? It would be nice if this editor was made into a standalone text editor (i.e. open multiple files..)...

**Comment by doug24** [comment]
The editor in the preview pane, replace dialog, and script editor is [AvalonEdit](https://github.com/icsharpcode/AvalonEdit).  It is a good library and used a lot, but then there are not a lot of choices for a code editor library running on WPF. 

dnGrep does use a fork as the project maintenance has slowed and I needed to get some things fixed.  

It was written for [SharpDevelop](https://github.com/icsharpcode/SharpDevelop), an IDE for .NET, but that project has been archived. 

Maybe the most recognizable project using AvalonEdit is ILSpy, also from isharpcode.

**Comment by raelb** [comment]
Ok, thanks for the info
