### ISSUE TITLE
Opening file with custom editor (VSCode) no longer works

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#1162]
Version 4.2.46.0

Worked previously, but don't know what version.

> Could not open the file with the custom editor.
Check editor path via "Options…".

![CustomEditorError](https://github.com/user-attachments/assets/1203336f-8ce8-4f67-a5c1-a91ec80cff64)

**Comment by doug24** [comment]
I don't know, it's working fine for me. Same command and arguments, but mine is in a different directory.

VS Code:
> Version: 1.91.1 (user setup)
> Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
> Date: 2024-07-09T22:06:49.809Z
> Electron: 29.4.0
> ElectronBuildId: 9728852
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Windows_NT x64 10.0.22631###

**Comment by fade2gray** [comment]
My VSCode details are exactly the same, except for - Version: 1.91.1 (system setup)

> ... mine is in a different directory

Any chance your path does not have spaces in it?

**Comment by doug24** [comment]
It does have spaces:
C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe

**Comment by doug24** [comment]
How exactly are you trying to call the custom editor? Have you tried both double-clicking on a line below the file node, and with the right-click context menu?

What happens? Nothing at all?  Is there anything in the Grep_Error_Log.xml file?

If you remove VSCode and try a different external application like does it work?

**Comment by fade2gray** [comment]
Works on my old Win10 box with the following ...

VSCode:
Version: 1.85.2 (system setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

dnGrep Version 4.0.69.0

![CustumEditorSettings](https://github.com/user-attachments/assets/aaac9f9b-21e8-4dc5-9924-cd7a8bd6cf1a)

**Comment by fade2gray** [comment]
> Have you tried both double-clicking on a line below the file node

That works (wasn't aware of that method).

> , and with the right-click context menu?

This doesn't.
