### ISSUE TITLE
Apparent Replacement Failure

### ISSUE THREAD

**Issue by PaltryProgrammer** [dnGrep/dnGrep#1165]
Version 4.2.46.0
greetings kind regards
thank you for providing dnGrep . i utilize it often bit only for Search. i am now attempting Replace for the first time . it is failing . please see attached video of the attempt and evidence of the apparent failure .
thank you kindly
![Apparent Replacement Failure](https://github.com/user-attachments/assets/c1c5216b-ba07-41fd-9b31-53537d49b854)

**Comment by doug24** [comment]
I don't know what is going on.  I use that "Replace in all files" frequently myself and it's always worked.  I just tried it now, and it worked - changing files in a git repo.

Can you try running a test in another directory, somewhere outside your current project?  The files are not tagged by dnGrep as read-only, but that appears to be what is happening - the modified files cannot be written.

Also, can you check Grep_Error_Log.xml?  (About menu -> Application data and logs). There isn't a log message for successful replace, but maybe there is an error logged?

**Comment by doug24** [comment]
Ah, I know what it is, you've been bitten by the "Global" flag. When the Global flag is unchecked, search (and replace) will stop after the first match in each file.  You are finding and replacing the first instance of bwpSoftware, and when you search again after the replace you are finding a new first instance of bwpSoftware.

Check the Global checkbox and you will find all instances of bwpSoftware in each file.  Then replace will replace them all.
