### ISSUE TITLE
multiple replacement / gui is sometimes changing replacement char

### ISSUE THREAD

**Issue by WernerHermann68** [dnGrep/dnGrep#1166]
Hi there ! 
first ... thanks a lot for this nice software.

i have used the Win64 portable version and it helped a lot to change the content of XML files.
Though ... i ran into trouble :D

first i did *not* used scripts or the "global" marker when i started.
i needed to replace "weird" ascii chars to "german umlaut" chars  like öÖüÜ
( an "o" with a  double-point above )

cause i did  not  used scripts and did multiple runs ... something less nice happened. 

the job was to replace an ascii char  x ( x is a placeholder here for a random weird unreadable char  ! )
with a small (!)  "ö"  ( o-umlaut    html code: &**o**uml; ).

so after the first run it refreshed the GUI and sometimes (!)  after this refresh it put a big 
"Ö" (big letter) in the replacement field ( o-umlaut    html code: &**O**uml; ) ... but is should stick
to the small letter "ö" .  

After i figured out "global" and "scripts" i could avoid this problem.
i tried several version back to dnGrep.3.2.279.0 ... and i saw this behavior with these older version too.  

i hope  this explanation is useful :D
and like i wrote ... i found a work around and i am the backup-hero ...so no big trouble
 ...just  a little confusion in the beginning .

**Comment by doug24** [comment]
I haven't been able to reproduce this, but I did notice that the most-recently-used lists are case-insensitive. If you have an 'x' in the list, it won't save an 'X". Or if you have an 'ö', it won't save an 'Ö'. I'm surprised I haven't noticed this, and if anyone else has, they didn't raise an issue for it.  

I'm wondering if this has something to do with it.  What is in your most recently used Replace text?  Is it the big Ö or little ö?

If you find any pattern for when this happens to you, I would appreciate the detailed steps to reproduce it.

**Comment by WernerHermann68** [comment]
damn ... i am sorry.
i cant reproduce it right now with the same dataset ..searching for "÷" ( acsii version of an ö ?)   ...replacing with "ö"
( 7000 dirs, 19.000 mdxml-files, searching found  7000 cases in the first run, 50 in the second ( NO global ) )

i tried it several times ...but this time i dont see it either.
i am sorry to keep you busy ( though i would swear i have seen it 2 weeks ago ... more than once before i started to use
global + scripts )

lets close this topic and just keep it in mind in the case you hear ist again.
again ... i am sorry.

**Comment by doug24** [comment]
No problem, thanks for posting.
