### ISSUE TITLE
Cleaner directory structure

### ISSUE THREAD

**Issue by wordpure** [dnGrep/dnGrep#1174]
Currently, there are more than 20 multi-language folders and over 200 files in the installation directory, which makes the root directory look quite confusing.

Is it possible to optimize the folder structure?

For example

- move all multilingual folders to the translation folder
- move all settings files (folders) to the userData folder
- move all dlls to the dependencies folder.

![图片](https://github.com/user-attachments/assets/062121b7-24a3-40ce-84bf-8ea4a48476ac)

![图片](https://github.com/user-attachments/assets/b48cb04b-1fb2-40dd-860a-0235f4fc14e3)

**Comment by doug24** [comment]
No, I don't think so.  Besides being a lot of work, these file locations are set by the .NET build and publish processes for the .NET assembly loader. I think moving them is just asking for problems.

**Comment by wordpure** [comment]
I don't know much about .net development and thought the directory structure could set by simply modifying the configuration file, but I didn't realize that there were all these problems you mentioned.

The directory structure has little impact on practical use, and there is no need to put too much effort into it, so I will close this issue.
