### ISSUE TITLE
Script set muilt folder  will case not valid

### ISSUE THREAD

**Issue by vvyoko** [dnGrep/dnGrep#1185]
`set folder D:\OneDrive|F:\Documents\Downloads`

use that the Folder will like
`"D:\OneDrive|F:\Documents\Downloads"`

Search will case error
`The search path in the 'Folder:' field is not valid, search canceled.`

Need delete both sides `"` by myself

**Comment by fade2gray** [comment]
Use a comma `'` instead of a vertical bar `|` - `D:\OneDrive, F:\Documents\Downloads`

**Comment by doug24** [comment]
Yes, there are two bugs here: First, the code shouldn't be trying to add quotes to the path or paths you have entered, it should assume the user has added any needed quotes.  Second, when the path is invalid, the script is not terminating and showing an error message correctly.

**Comment by doug24** [comment]
Fixed in [4.2.84](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.84.0)
