### ISSUE TITLE
提交BUG, 搜索替换中文会乱码

### ISSUE THREAD

**Issue by xxxdo1** [dnGrep/dnGrep#1197]
替换4个中文字符, 乱码

![image](https://github.com/user-attachments/assets/99f6dc12-b44b-4c57-a86b-2489e7b268ba)

**Comment by doug24** [comment]
What type of file is this?

It is most likely an encoding problem.  What is the original encoding of the file? (mouse over the filename in the results tree, and it is in the tooltip) Does this encoding support the characters you are inserting?

On the main window in the "More..." filters section, try changing the encoding from Auto detection to something else like UTF-8.

**Comment by xxxDo1** [comment]
源文件编码是UTF8

![image](https://github.com/user-attachments/assets/889da191-4b3f-4e20-99ef-c56c632a87b8)
