### ISSUE TITLE
替换, 功能建议

### ISSUE THREAD

**Issue by xxxdo1** [dnGrep/dnGrep#1198]
点击替换按钮, 不显示替换文本对话框, 直接替换当前选中的2个文件, 想要替换所有文件则可以Ctrl+A, 先全选文件再替换, 这样省去了很多操作步骤

替换上一个文件, 替换下一个文件, 可以放在按钮子菜单中, 像搜索按钮那样

打开替换文本对话框也可以放在按钮子菜单中

![image](https://github.com/user-attachments/assets/8f1f6ac3-deb9-4589-ade0-8d4fd77a4bac)

**Comment by doug24** [comment]
I will think about it.  I think opening the Replace dialog should remain the default behavior, as this was a feature with many requests at the time it was done. Personally, I rarely use it: I click the Replace button and then click "Replace in all files".  Just two mouse clicks. 

Your suggestion makes sense if you just want to replace in one file.  But doing more than a couple of files one by one this way seems just as tedious.

**Comment by xxxDo1** [comment]
这种方式很便捷啊, 满足了常用键盘鼠标结合操作的用户
将替换所有文件的选项放进按钮子菜单, 也同样可以满足鼠标用户, 也是只需要点击两次鼠标即可

**Comment by doug24** [comment]
No commitment, but I will look into adding a Replace option similar to how the Sort button works. There would be two options to choose from: the existing replace dialog or replace in selected files. Users can choose which option will be invoked by the Replace button and can change at any time.

When replacing in selected files, once the replace is complete, the file(s) will be removed from the search results - the file is changed and the search results for it are invalid. 

I do not recommend using ctrl+A to select all the nodes in the result tree. Yes, it is there and works OK when there are just a few files in the tree.  But the results tree is virtualized, meaning there are no tree nodes for files outside the current visible list. This is done for performance- there could be thousands of files in the results, and it is very slow to render them all.  Doing a 'select all' forces the tree to render them all and you can demonstrate for yourself how slow it can be.  If you want to replace in all files, it is much better to use the replace dialog and click the "Replace in all files" button as I mentioned above.

Also, there is an option in the Options dialog to change the layout of the Replace dialog to an abbreviated form without the individual file preview. You can still choose which files to replace if you do not want all or choose to replace in all.

**Comment by doug24** [comment]
In [v4.2.95](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.95.0)
