### ISSUE TITLE
folder name with \ suffix is considered as different path

### ISSUE THREAD

**Issue by iamqiz** [dnGrep/dnGrep#1203]
see picture below, if add \ suffix to the folder name , the plus button no longer highlight

![PixPin_2024-10-03_06-42-50](https://github.com/user-attachments/assets/e5242572-0bdc-4b78-ace0-3e912cec946c)

**Comment by doug24** [comment]
OK, I will look at fixing this.

**Comment by doug24** [comment]
In [v4.2.95](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.95.0)

**Comment by iamqiz** [comment]
@doug24 nice! thanks!
