### ISSUE TITLE
Doc word document read failed

### ISSUE THREAD

**Issue by MarcoPanoniVVF** [dnGrep/dnGrep#1208]
Hello,
I've downloaded dnGrep v. 4.2.59.0, my pc configuration is Win11 H23 x64.
The only settings that I've modified is just for .odt and .ods files
I've noticed an issue with .doc file as shown under

Search result
![Screenshot 2024-10-08 081643](https://github.com/user-attachments/assets/247c321f-6101-47c1-985d-4ee074856341)

My settings
![Screenshot 2024-10-08 082757](https://github.com/user-attachments/assets/aa41df70-5516-4626-b1fb-d08b167e3e3f)

Could you help me?
Thanks

**Comment by doug24** [comment]
Do you have Microsoft Word installed? The "Word" extension requires the use of Microsoft Word. The Grep_Error_Log.xml in the dnGrep app data folder probably has more information - go to the "Application data and logs" menu item under the About menu to find the error log file.

If you do not have Word, then I recommend installing Apache Tika ([instructions](https://github.com/dnGrep/dnGrep/discussions/1049)) to extract text from Word files.  You will probably want to install Tika anyway - it will also extract text from Open Document files, which will be a much better than treating odt and ods files as archives (remove those extensions from the archives list and add them to the Tika plugin).

**Comment by MarcoPanoniVVF** [comment]
I'll try Apache Tika
Thanky for you help!
