### ISSUE TITLE
[ Question ] How to correctly search for *.png via folder

### ISSUE THREAD

**Issue by Xelbayria** [dnGrep/dnGrep#1215]
- **Version 4.2.95.0**

The path is `4.0.1.jar\assets\myfolder\textures\...`

dnGrep should have show me a list of `*.png` found in that folder but it did not find any. I even clear out the search pattern in both **Pattern to match** and **Search For** and take a look at the list found in `4.0.1.jar\...` and there are no textures folder. 

Just `assets\myfolder\models\block\...` and several more folders that have `*.json`

**Comment by doug24** [comment]
It would be easier to tell what's wrong if you had shown your search filters.  Do you have "Include binary files" checked?  `*.png` are not text files.

Here's what I would do:

![image](https://github.com/user-attachments/assets/a4260394-f714-4da4-b5bd-9dc952ca9c44)

**Comment by Xelbayria** [comment]
ah. I was wondering what is "Binary Files". "Include binary files" is the answer and it does its job. Thanks for the answer! 

Now I can use dnGrep to find the files I Need in *.jar! Excellent software!

**Comment by Xelbayria** [comment]
What's the correct RegEx for **Pattern To Match**. You can see it in the picture. I can't get it work using varying RegEx. 

I got **Patterns To Exclude** working correctly with RegEx

**Comment by doug24** [comment]
A regex like the wildcard pattern *.png is `.*\.png$`

To use regular expressions in the **Patterns to match** and **Patterns to exclude** you must set the radio button for **Regular expressions** just below **Patterns to exclude**.  In the picture above it is set to **Wildcard**.

**Comment by Xelbayria** [comment]
> A regex like the wildcard pattern *.png is `.*\.png$`
> 
> To use regular expressions in the **Patterns to match** and **Patterns to exclude** you must set the radio button for **Regular expressions** just below **Patterns to exclude**. In the picture above it is set to **Wildcard**.

I'll try that. and I am aware of `Regular Expressions`, i've set it to that from `Wildcard`

**Comment by doug24** [comment]
Is terrestria-7.0.1.jar a jar file or a directory?  It looks like it is a jar file unless you expanded the jar into a directory named terrestria-7.0.1.jar.

If it is a jar file, you need to check the box "Search in archives" to search file inside the jar file.

**Comment by Xelbayria** [comment]
> Is terrestria-7.0.1.jar a jar file or a directory? It looks like it is a jar file unless you expanded the jar into a directory named terrestria-7.0.1.jar.
> 
> If it is a jar file, you need to check the box "Search in archives" to search file inside the jar file.

"Search in archives" works. again, thanks for helping out.

**Comment by Xelbayria** [comment]
I cannot find the wiki for `.gitignore`. I'm trying to find out how to use it.

**Comment by doug24** [comment]
.gitignore is only used if you are searching in a git repository.  If you have a git repository, you probably already have a .gitignore file there.  If you aren't searching in a git repository, don't check the **Use .gitignore** checkbox and you save time dnGrep would spend looking for it.

There are two other options for exclusion filters - see https://github.com/dnGrep/dnGrep/wiki/File-Filters
