### ISSUE TITLE
User-defined editor requires elevation

### ISSUE THREAD

**Issue by iamqiz** [dnGrep/dnGrep#1226]
if my custom editor path contain space, for example
```
C:\APP\Microsoft VS Code\Code.exe
```
then when i open file by right-click the search result & click the vscode, then it will arise error

if i change its path to `C:\APP_portable\other\vscode\VSCode-win32-x64-1.93.1\Code.exe` (no space in path) then it work

**Comment by doug24** [comment]
Something else must be wrong. I have two editors defined, both have spaces in them, and both work:
`C:\Program Files\Notepad++\notepad++.exe`
`C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe`

I checked the code, and it is adding quotes to the file path in all cases (containing a space or not).

**Comment by iamqiz** [comment]
in log file, it say " The requested operation needs to be promoted" (translated from chinese)
so how to solve it?
```
<logevent time="2024-11-12 23:27:30.6272" level="Error" logger="dnGREP.WPF.MainViewModel">
  <message>Failed to open file.</message>
  <exception>System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'C:\\APP\\Microsoft VS Code\\Code.exe' with working directory 'C:\Program Files\dnGrep'. 请求的操作需要提升。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at dnGREP.Common.Utils.OpenFile(OpenFileArgs args) in C:\projects\dngrep\dnGREP.Common\Utils.cs:line 1582
   at dnGREP.WPF.MainViewModel.OpenFile(FormattedGrepResult result, Boolean useCustomEditor, String customEditorName) in C:\projects\dngrep\dnGrep.WPF\ViewModels\MainViewModel.cs:line 1007</exception>
</logevent>
```

**Comment by doug24** [comment]
That error message in English is "The requested operation requires elevation".  That means you need to be running as Administrator to start the process. 

You can try this: run dnGrep as Administrator, and then try to open a file with Code.exe from that location.

I don't know why your installation of Code.exe in that location would require running as Administrator, but probably something in the way it was installed there, or some permission set in Windows.

**Comment by iamqiz** [comment]
Oh, I see !  I previously set the vscode `C:\APP\Microsoft VS Code\Code.exe` to start as an administrator ! 
but Why does it not pop up the UAC window to require elevation?

**Comment by iamqiz** [comment]
is it possible to popup UAC window to require elevation instead of reporting an error?

**Comment by doug24** [comment]
Added in [v4.2.121](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.121.0)

**Comment by iamqiz** [comment]
@doug24 it work! good job! thanks! 🤩
