### ISSUE TITLE
jetty-osgi-boot OSGi bundle version 12.0.x release location

### ISSUE THREAD

**Issue by ffays** [dnGrep/dnGrep#1231]
I would like to know if there is location where the **jetty-osgi-boot** OSGi bundle, with  the compiled classes of the **org.eclipse.jetty.osgi** package version **12.0.5** are available?

I.e. I do not found the [JettyBootstrapActivator](https://javadoc.jetty.org/jetty-12/org/eclipse/jetty/osgi/JettyBootstrapActivator.html) class file in any Jar of the current jetty-home-12.0.15.zip archive published on [Jetty Downloads](https://jetty.org/download.html) . And  the most recent release for [Maven Repository: org.eclipse.jetty.osgi » jetty-osgi-boot](https://mvnrepository.com/artifact/org.eclipse.jetty.osgi/jetty-osgi-boot) is the version 11.0.24

Am I missing something?

**Comment by doug24** [comment]
Looks like you posted to the wrong project. This has nothing to do with
dnGrep.

**Comment by ffays** [comment]
Sorry my bad!

It is indeed for Jetty. I used dnGrep to perform my search that worked seamlessly!

Please close the ticket!

**Comment by ffays** [comment]
Closing the ticket
