### ISSUE TITLE
How to search in *.pdf files for TWO INDEPENDENT patterns?

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#1239]
Assume I want to search for all *.pdf files on my partition which contain the two patterns

**foobar** 
and
**blahblah**

How can I achieve this?

When I enter in "Search for" entry field:

**foobar blahblah**

then only pdfs are found which contain the two patterns in exact this sequence immediately one after the other.
But dngrep does NOT find the PDFs where **foobar** is e.g. in line 5 and **blahblah** in line 342

Any chance to apply this multi-pattern search?

**Comment by doug24** [comment]
That sounds exactly like what the [Boolean Operators](https://github.com/dnGrep/dnGrep/wiki/Boolean-Operators) search does.

Check the Boolean operators and Multiline checkboxes. 
Then Search for: **foobar AND blahblah**
