### ISSUE TITLE
Feature Request: Multi-select in results list using Ctrl/Shift

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#135]
_From [john.bu...@gmail.com](https://code.google.com/u/105739626209254255375/) on May 04, 2012 18:41:08_

I wanted to request the ability to select multiple items in the results list using Ctrl and Shift, allowing me to drag multiple files out of dnGrep and into other programs or Windows Explorer.  I can currently drag single files, but it'd be handy to be able to drag multiple files.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=132_

**Comment by doug24** [comment]
Included in 2.9.40
