### ISSUE TITLE
installation fails with "The system cannot open the device or file specified"

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#143]
_From [ahz...@gmail.com](https://code.google.com/u/112749914714431718909/) on May 18, 2012 12:37:39_

What steps will reproduce the problem? 1. Try to install dnGREP 2.6.3 (x86).msi What version of the product are you using? On what operating system? 2.6.3
Microsoft Windows 7 Enterprise 64-bit Please provide any additional information below. I am not sure what device or file is the problem?

I can retry or cancel.  Retry does not help.  If I click cancel, it gives me error code 2755 for "unexpected error."

The installation failed the same for me on another, similar machine at the same office.

A previous version of dnGREP installed fine.  I had been using it for many months.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=140_

**Comment by sergeevabc** [comment]
What is “Startup acceleration” anyway? Some background service running or what?

**Comment by JVimes** [comment]
Yep. Without it, the app took too long to launch, so Denis moved it into a service.
