### ISSUE TITLE
dnGrep doesn't work with Windows 7 "snap" feature

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#151]
_From [john.bu...@gmail.com](https://code.google.com/u/105739626209254255375/) on July 11, 2012 09:58:37_

What steps will reproduce the problem? 1. In Windows 7, drag the window to the top or sides of the screen. What is the expected output? What do you see instead? Expected: top maximizes, sides snap to half of screen.
Actual: No window snapping. What version of the product are you using? On what operating system? 2.6.3 Please provide any additional information below. For more on Windows 7's "Snap" feature see: http://windows.microsoft.com/en-us/windows7/products/features/snap?SignedIn=1

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=148_

**Comment by doug24** [comment]
Should be fixed in the 2.9.21 beta if anyone wants to test.

**Comment by JVimes** [comment]
Fixed in Windows 10 snap, which has gotta be the same was Windows 7 snap. Thanks Doug!
