### ISSUE TITLE
Preview window doesn't always show the correct line when first clicking in result window

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#157]
_From [Volker...@googlemail.com](https://code.google.com/u/111404087183216460455/) on September 05, 2012 11:15:44_

With option "show result tree expanded" enabled, clicking the first time inside the result window on a specific line will select the file instead and the preview window shows the begin of the file and not the line of the result.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=154_

**Comment by doug24** [comment]
Tested with 2.9.143 and this has been fixed
