### ISSUE TITLE
x64 version of program crashes on x64 system, during resize

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#164]
_From [dan.mill...@gmail.com](https://code.google.com/u/109064454512807864172/) on January 09, 2013 14:40:12_

What steps will reproduce the problem? 1. run dnGREP (program starts up, but window is too small for contents)
2. wait about 5 seconds
3. program crashes: "dnGREP has stopped working" What is the expected output? What do you see instead? I expected the program to work, instead it crashed What version of the product are you using? On what operating system? dnGREP 2.6.3 x64
Windows 7 Home Premium, 64bit Please provide any additional information below.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=161_

**Comment by doug24** [comment]
Unable to reproduce, I believe this is no longer an issue.
