### ISSUE TITLE
Search results repeatedly auto-scroll to the right, hiding node drop-down triangles (annoying)

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#175]
_From [john.bur...@gmail.com](https://code.google.com/u/111143864140587478122/) on February 11, 2013 13:37:29_

What steps will reproduce the problem? 1. Do a search with wide enough results to cause a horizontal scroll bar (expanding nodes to show match text helps).
2. Expand the last result.  This should cause the horizontal scroll bar if it wasn't here already.
3. Click on any of the files, or the lines of match results.
4. If these instructions are confusing, here is a video of the bug: http://goo.gl/ZUnFB What is the expected output? What do you see instead? I don't expect the scroll-pane to move horizontally just by highlighting items in the list, but it moves slightly to the right, obscuring the triangles that allow me to expand/collapse nodes.  And it does this every time I click an item in the list, so it gets annoying. What version of the product are you using? On what operating system? 2.7.1 beta Please provide any additional information below.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=172_

**Comment by doug24** [comment]
I don't know what your video shows , but the auto-scroll to the right issue is fixed in 2.9.21 and later.

**Comment by JVimes** [comment]
Verified fixed.
