### ISSUE TITLE
Search fails if unable to access a sub-directory due to permissions

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#177]
_From [chris.ma...@gmail.com](https://code.google.com/u/117559745111458734878/) on February 20, 2013 16:51:41_

What steps will reproduce the problem? 1. Specify a top level directory
2. include search sub directories
3. ensure one of the sub directories has permissions set so your user cannot read into that directory. What is the expected output? What do you see instead? I would expect the search to continue and search the directories it has access to.  What does occur is that the entire search fails and no results are returned.  I also get a runtime error when exiting the application. What version of the product are you using? On what operating system? 2.6.3 on WinXP (Yes still on XP :-) ) Please provide any additional information below. N/A

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=174_

**Comment by doug24** [comment]
This has been fixed - not sure when.  Directory and file access errors are logged in the log file.
