### ISSUE TITLE
dnGrep

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#178]
_From [ruoy...@gmail.com](https://code.google.com/u/101619115598160438302/) on February 21, 2013 19:43:46_

What steps will reproduce the problem? 1. Install the dnGrep (standalone or MSI) in Windows 7 Professional SP1
2. start the dnGrep
3. A Windows dialog window pops up saying dnGrep has stopped working. What is the expected output? What do you see instead? When dnGrep started, after a few seconds (5?), a window says dnGrep has stopped working. Then dnGrep crashed. What version of the product are you using? On what operating system? I tried v2.6.3, both standalone and msi. And v2.7.1 msi. The crash keeps happening. Please provide any additional information below. I have installed the .NET Framework 4.0 Full. I will post the log in windows Event Viewer.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=175_

**Comment by doug24** [comment]
.net 4.5.2 is now the minimum required version, closing issue
