### ISSUE TITLE
Suggestion: Match/ignore patterns in main UI

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#179]
_From [john.bur...@gmail.com](https://code.google.com/u/111143864140587478122/) on February 22, 2013 15:08:38_

I use the match/ignore fields somewhat frequently, so I miss having those on the main UI.  If this is a common use-case, perhaps it would be good to move the match/ignore fields to the main window or, alternatively, give the ability to pin the "search in" panel into the main UI (when un-pinned, keep it as a dropdown).  I'm interested to hear what people think.

**Attachment:** [2013-02-22_14h56_37.png](http://code.google.com/p/dngrep/issues/detail?id=176)

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=176_

**Comment by JVimes** [comment]
Issue #1 should solve the root problem. I guess the question is, are there any filter fields we really should hide on lost focus?

**Comment by doug24** [comment]
Included in 2.9.31
