### ISSUE TITLE
Feature request: Search for multiple words

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#183]
_From [mrbe...@gmail.com](https://code.google.com/u/101796214887804367057/) on April 23, 2013 07:02:31_

Let's consider text file with keywords:
LINE1: keyword01, keyword02, ..., keyword0n
LINE2: keyword11, keyword12, ..., keyword1n
...
LINEn: keywordn1, keywordm2, ..., keywordnn

I want to find the line which contains these keywords: keyword13, keyword17 and keyword19 where these keywords may be in arbitrary order.

In Linux/UNIX systems I would just use: 
grep keyword13 FILE | grep keyword17 FILE | grep keyword19 FILE

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=180_

**Comment by doug24** [comment]
added in 2.9.196, with Boolean Operators
