### ISSUE TITLE
Search button disabled when folder name differs from sibling in certain way

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#184]
_From [john.bur...@gmail.com](https://code.google.com/u/111143864140587478122/) on April 23, 2013 13:33:20_

What steps will reproduce the problem? 1. Place two folders next to each other, one named "Folder" and the other "Folder, server".
2. Try to search the second folder What is the expected output? What do you see instead? I'd expect to be able to search, but instead the Search button is disabled. What version of the product are you using? On what operating system? 2.7.1 Beta 2, Windows 7 64-bit. Please provide any additional information below. Attached is a screen shot of the original folders I discovered the bug with.

**Attachment:** [2013-04-23_13h30_24.png](http://code.google.com/p/dngrep/issues/detail?id=181)

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=181_

**Comment by doug24** [comment]
I'm not sure there is a good solution for this: the search location box allows you to enter multiple start locations using comma separated paths - so the code thinks that ", server" is the second path, which is not valid.

Adding image from web.archive.org:
![2013-04-23_13h30_24](https://user-images.githubusercontent.com/17227248/59816193-0ec2a180-92d0-11e9-8c7e-6065327bd367.png)

**Comment by JVimes** [comment]
What if we use vertical bar instead of comma for delimiter, since bar is not allowed in path names? That might be a good idea in the other text boxes that accept multiple paths/wildcard patterns, too.

**Comment by doug24** [comment]
I suspect this is a not a common problem.  I don't think I would like to remove using comma and semicolon as list separators, it seems like a standard use.  I have two ideas that could be investigated:
1) Make the path evaluation a bit smarter: when a path specification contains embedded commas or semicolons, first test to see if the whole path exists before splitting it.  Multiple commas and/or semicolons in the path spec would really complicate this - where some are part of the path, and some are list separators.
2) Require paths or filenames with embedded commas or semicolons to be enclosed in quotes.  Outside a quoted string the comma or semicolon would always be a list separator.  The current implementation strips out quotes before splitting the path on commas and semicolons.

Need to see how these options would affect the code.

**Comment by JVimes** [comment]
I like option 2. Option 1 seems like it might have ambiguous edge cases.

**Comment by doug24** [comment]
went with option 2, enclose path in quotes  - added in 2.9.215
