### ISSUE TITLE
Checking "search in all files and subfolders" resets encoding

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#185]
_From [treww5](https://code.google.com/u/treww5/) on April 24, 2013 13:45:42_

What steps will reproduce the problem? 1.Click on "Path to search in" button 
2.Select an enconding instance, for example, "unicode"
3.Check  "search in all files and subfolders" checkbox What is the expected output? What do you see instead? Encoding combo is reset to empty and is disabled, so you can't search in all files and folders according to the desired encoding. In my case, I was searching for a unicode string in a folder and its subfolders. I would never find it if encoding is reset. The workarround is uncheck  "search in all files and subfolders" and check include subfolders, hidden files and binary files What version of the product are you using? On what operating system? AboutDlg says 2.7.0.0, But I downloaded dnGREP 2.7.1 (x86).msi Please provide any additional information below.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=182_

**Comment by doug24** [comment]
This has been fixed in the 2.9.21 beta

**Comment by JVimes** [comment]
Verified fixed
