### ISSUE TITLE
Settings.dat file shall save last set encoding setting

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#186]
_From [saulius....@gmail.com](https://code.google.com/u/113306502124907666108/) on May 03, 2013 05:05:37_

Becouse othervise it highlight not right place. And not at once you understand that this is becouse wrong encoding. I am not sure what is default encoding. But I would suggest UTF-8.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=183_

**Comment by doug24** [comment]
This has been fixed in the 2.9.21 beta

**Comment by JVimes** [comment]
Verified fixed.
