### ISSUE TITLE
Bug in HEX Search

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#187]
_From [emretina...@gmail.com](https://code.google.com/u/101769624074866842853/) on May 07, 2013 07:06:45_

What steps will reproduce the problem? 1. Scan \xAA\xBB\x00\x00\x00 2. 3. What is the expected output? What do you see instead? It stops right after first NULL. It should search for all the NULLs. What version of the product are you using? On what operating system? Win 8 x64, version 2.7 Please provide any additional information below. Thanks for this great app, we really love it!

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=184_

**Comment by doug24** [comment]
I don't understand this issue - if anyone has more information, please re-open it and comment.
