### ISSUE TITLE
Options window always appears on main monitor

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#190]
_From [kevindpath](https://code.google.com/u/kevindpath/) on May 20, 2013 08:24:39_

What steps will reproduce the problem? 1. launch dnGREP (it will appear it the same position it was in when you last closed it)
2. click Bookmarks (it will open on top of the main window)
3. click Options (it will appear on the main monitor) What is the expected output? What do you see instead? The Options window should appear on top of the main window since it is a modal form. You shouldn't have to drag your mouse to a new screen every time you want to tweak a setting. I use multiple monitors and I rarely have my search window on my main monitor. What version of the product are you using? On what operating system? dnGREP 2.7.1 (x64)
Windows 7 Professional SP1 Please provide any additional information below.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=187_

**Comment by doug24** [comment]
Just a small change, but fixed in the 2.9.24 beta release

**Comment by JVimes** [comment]
Verified fixed.
