### ISSUE TITLE
Type-ahead feature forces the case of the first character

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#192]
_From [john.bu...@gmail.com](https://code.google.com/u/105739626209254255375/) on May 23, 2013 13:21:05_

What steps will reproduce the problem? 1. Make sure there's a previous search for something with a capital letter (like "Application") in the previous searches drop-down.
2. Try to do a new search for "asdf", without a capital "a". What is the expected output? What do you see instead? I would expect to be able to type in "asdf", all in lower case.  But instead, the text field becomes "Asdf".  The "a" becomes capitalized as soon as the type-ahead suggestion is loaded into the text box, even though it's unloaded as soon as I type the "s". What version of the product are you using? On what operating system? 2.7.1 Beta 2, Windows 7 Please provide any additional information below.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=189_

**Comment by PhiLhoSoft** [comment]
Ah, I just commented on #211 which happens to be a duplicate of this one...
And, yes, I would prefer an history of n (setting?) last searches / replaces. I have this in the SciTE editor, for example, and it is very useful. Might need an option to forget or keep this history after closing the instance.
One thing SciTE doesn't have, and that can be useful: to recall the matching replace expression when a search expression is selected.

BTW, thank you for this excellent software. Too bad you lack time to maintain it, but it is already extremely useful as it is.

**Comment by doug24** [comment]
I made a simple change for the 2.9.21 beta.  Filling the text box from the search history no longer forces the case of the history item, and I think that this should be much less irritating now.   It doesn't do everything suggested above, but I would like to hear any feedback if this works for you, of if we need to more extensive changes in this area?

**Comment by JVimes** [comment]
Verified fixed. The other issues differ from this one, but feel free to submit a new issue for each.
