### ISSUE TITLE
request - current file being searched - info

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#193]
_From [tkac...@gmail.com](https://code.google.com/u/103999680520968182090/) on June 20, 2013 02:03:39_

It would be nice if app shows what file is currently beiing proccessed so that user doesn't think that app has been hanging while working on some big archive for example

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=190_

**Comment by doug24** [comment]
Changes for this issue are in 2.9.42 beta.

**Comment by JVimes** [comment]
Verified implemented
