### ISSUE TITLE
Anomalous execution of RegEx's; File filters not working as expected.

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#194]
_From [frac...@gmail.com](https://code.google.com/u/112754595436592065380/) on July 15, 2013 13:01:56_

What steps will reproduce the problem? (see below) What is the expected output? What do you see instead? (see below) What version of the product are you using? On what operating system? dnGREP 2.6.3 (x86) Standalone Please provide any additional information below. 1) Anomalous execution of RegEx's.
    To illustrate, here is a very simple test that has been verified with Expresso and fnr.exe:
    Search a directory using:(?isx-mn)(?<=[ ]CHAR[ ])[^\s]*(?=\s)
    and replace with:ANSI

```
Note the options specified:(?isx-mn). These options appear to be ignored, regardless of selection in dnGREP's "Search/options" field.

With or without (?isx-mn) present, the RegEx will not Work without "Multiline" selected in the "Search/options". (This is incorrect.)
```

2) File filters not working as expected. 
    Under "File filter"/"Paths that match", with "Regex" selected and, "(.ansi.ged|.1252.ged)" works correctly and finds file in two groups. With "Asterisk pattern" selected", and using *ansi.ged, *1252.ged" the second group of files is not found.

3) When  "File filters" is turned off, all of the previous field values are grayed-out and cleared.
The problem is that "File filters" can easily be turned off by mistake and the original setting have to all be re-entered. For example, if "Search in all files and subfolders" is accidentally selected or if a path with a filename is inadvertently pasted in the "Search in" field (a typo) "File filters" will be turned off.

4) Most of the previous setting are restored when dnGREP is restarted, except for "File filters/Encoding".

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=191_

**Comment by doug24** [comment]
1. .net regular expressions do not use processor commands like (?isx-mn)
2, 3, 4 are no longer issues
