### ISSUE TITLE
Shell integration: Selecting multiple folders

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#195]
_From [unhch...@gmail.com](https://code.google.com/u/102716323846891083946/) on July 15, 2013 18:14:37_

What steps will reproduce the problem? Select multiple folders, then use the context menu to open dnGREP. What is the expected output? What do you see instead? Currently dnGREP opens one window for each folder selected this way, but I'd prefer it open one window with those folders separated by a semicolon. If I drag the selected folders into the path box of an existing window, it does this. What version of the product are you using? On what operating system? dnGREP 2.7.1 Beta 2, Windows 7 SP1

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=192_

**Comment by klonos** [comment]
Also **yes please** 😄

I have tried the drag-n-drop functionality mentioned in the original ticket description, but it doesn't seem to work with latest 4.x

Drag-n-dropping from Explorer windows to an open dnGrep window and having the context menu available with multiple folders selected in Explorer are perfectly valid options, but I would like to propose a 3rd one: clicking on the "Browser for folders or files" button ("..."):

![image](https://user-images.githubusercontent.com/2423362/27257331-9ffb6642-5415-11e7-84ca-d0ef7974c282.png)

This dialog should either allow multiple folder selection (holding the SHIFT/CTRL keyboard keys), or something custom like this:

![ocgks](https://user-images.githubusercontent.com/2423362/27257335-f949d71a-5415-11e7-98c5-3b0c232696da.png)
