### ISSUE TITLE
dngrep stopped working for no obvious reason

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#196]
_From [omegat...@gmail.com](https://code.google.com/u/104763487637795491186/) on July 17, 2013 10:51:35_

What steps will reproduce the problem? 1. Try to run or install dngrep What is the expected output? What do you see instead? It stopped working, trying to load something at startup and failing.  I uninstalled it and then tried to reinstall from a freshly-downloaded version, but it does not work.  I expect to see it install normally.  Instead the installer gets stuck at 2/3 progress, pops up a box that says:

Error: Something broke down in the program. See event log for details.

and then stays there doing nothing.  If I press Cancel, it still does nothing.  If I open Task Manager and kill dngrep.exe as admin, I get "There is a problem with this Windows Installer package..." and then it rolls back the installation. What version of the product are you using? On what operating system? dnGREP 2.7.1 (x64).msi
Windows 7 Pro SP1 64-bit Please provide any additional information below.

**Attachment:** [Event Viewer log.txt](http://code.google.com/p/dngrep/issues/detail?id=193)

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=193_

**Comment by klonos** [comment]
I think that it is safe to close this issue after 4 years.

**Comment by doug24** [comment]
Agreed, this is no longer a problem

**Comment by JVimes** [comment]
Thanks! There may be more obsolete bugs.
