### ISSUE TITLE
Re-open dnGrep after maximizing window, window no longer maximized

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#199]
_From [john.bu...@gmail.com](https://code.google.com/u/105739626209254255375/) on August 16, 2013 14:33:44_

What steps will reproduce the problem? 1. Maximize the dnGrep window
2. Close dnGrep
3. Open dnGrep What is the expected output? What do you see instead? I'd expect the window to be maximized. Instead, it's un-maximized and partially off-screen (see screen shot). What version of the product are you using? On what operating system? 2.7.1 BETA2 Please provide any additional information below.

**Attachment:** [2013-08-16_14h30_05.png](http://code.google.com/p/dngrep/issues/detail?id=196)

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=196_

**Comment by doug24** [comment]
This has been fixed in the 2.9.21 beta.

**Comment by JVimes** [comment]
Verified fixed.
