### ISSUE TITLE
Can´t stop search operation.

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#203]
_From [rbs.rio...@gmail.com](https://code.google.com/u/100329628482067245431/) on November 05, 2013 17:40:36_
- Can´t cancel search operation. (v.2.7.0.0) because UI button is not active.
- Maybe is better the process of file searching in another thread.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=200_

**Comment by doug24** [comment]
Changes for this issue are in 2.9.42 beta.  I added more checks for the Cancel while search is in progress. You can now also see what file is currently in progress in the status bar.

There are a couple places that can't be interrupted and may take a long time to complete. These include expanding an archive file, and some regular expression searches where there are many matches.

**Comment by JVimes** [comment]
Verified fixed.
