### ISSUE TITLE
Enhancement request: add option to copy all displayed search results for a file

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#205]
_From [rlusi...@gmail.com](https://code.google.com/u/117177785423969790142/) on November 21, 2013 10:58:29_

DNGrep is a great program I use all the time, but there is one thing which prevents me from using it as a total "grep solution": the ability to copy all the search results to the clipboard for a file or all files.

I can copy any single line of text to the clipboard, but if there are many matches then I have to do them one-by-one. If I use the command line grep program I can send the output to file and then process it, but currently I don't have the option to do that in dnGrep.

I therefore propose the following features:
(minimal set)

From context menu of the results display on a file:

```
File search results to clipboard
All file search results to clipboard (so you don't need to have a new UI for all items)
```

(optional-somewhat more functionality)

```
Search results to clipboard (no context)
All file search results to clipboard (no context)
```

Another option on the latter would be to put the clipboard context/no context option in preferences - this would simplify the UI.

I really like dnGrep a lot, but this one change would keep me from having to install Cygwin on all my boxes. Thank you so much for your effort on this program.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=202_

**Comment by doug24** [comment]
Included in 2.9.40
