### ISSUE TITLE
Latest stable build published to Chocolatey package repository

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#209]
_From [jac...@gmail.com](https://code.google.com/u/111346757428844522383/) on April 17, 2014 07:42:20_

This way dnGREP could be installed via Chocolatey or Micrisoft OneGet and not manually via MSI installer.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=206_

**Comment by doug24** [comment]
[Chocolatey package](https://chocolatey.org/packages/dngrep) is being updated regularly by @majkinetor
