### ISSUE TITLE
RegEx search fails with dnGREP 2.7.2.0

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#210]
_From [patdiw...@gmail.com](https://code.google.com/u/114410339354706192064/) on April 25, 2014 11:55:18_

What steps will reproduce the problem? 1. Create a file and add following text
24.4.2014 11:45:21.435;T1;End runSingle Job Wfd ID:1895 JobId:166078 JobType:RunWorkFlow Runtime:5.375 Queued:0.015 Total:5.390
2. Search file with following RegEx
[3-9]\d*?.\d\d\d$
3. dnGREP 2.7.2.0 fails to find anything. But dnGREP 2.6.3.0 works. What is the expected output? What do you see instead? It should find the last 5 characters in above line What version of the product are you using? On what operating system? dnGREP 2.7.2.0 on Windows 7 Enterprise Please provide any additional information below. dnGREP 2.6.3.0 works.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=207_

**Comment by doug24** [comment]
Included in 2.9.28
