### ISSUE TITLE
Autocomplete in "search for" text box is ignoring case sensitive search

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#211]
_From [Volker...@googlemail.com](https://code.google.com/u/111404087183216460455/) on April 26, 2014 10:22:01_

Example:
I searched for "pointer._to._register" in the past, so it's now in the history of the "Search For" text box.

Now when I want to search for the term "Pointer" with case sensitive search enabled, it's almost impossible to enter this string because everytime I enter an uppercase P, it's automatically replaced with a lower case p when autocomplete suggests "pointer._to._register".

Suggestion: when case sensitive search is enabled, the autocomplete suggestions should consider the case of the entered characters.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=208_

**Comment by PhiLhoSoft** [comment]
Ah, I came here to open this very bug, I see it is already there.

My suggestion:

- If search is case sensitive, don't auto-complete with strings not matching the case. Ie. if I type 'p', I don't want autocompletion with 'Pew', only with 'phew'.
- If search is not case sensitive, it is OK to suggest 'Pew' when typing 'p', but if I continue as 'ph', just revert the initial letter to 'p' (currently, it makes typing 'Phew').

Workaround for the above case: I have to go back to the start of the field and replace 'P' with 'p'.

**Comment by doug24** [comment]
Included in 2.9.21
