### ISSUE TITLE
Suggestion: copy complete output window to clipboard or save it to file

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#212]
_From [Volker...@googlemail.com](https://code.google.com/u/111404087183216460455/) on April 26, 2014 10:26:39_

There a cases when I would like to copy the complete output window to the clipboard or save it to a file. However currently it's only possible to copy one single line to the clipboard.
-> it would be nice to have such options

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=209_

**Comment by sergeevabc** [comment]
Of course, there should be an action “Save results to file…” without tricky CSV delimiters like it is now.
It is something crucial one looks for when works with files in general and with text utilities in particular.
GUI greps such as [AstroGrep][1] does it perfectly, CLI greps allow to pipe `grep ... > file`, and dnGrep? 

[1]: http://astrogrep.sourceforge.net/

**Comment by doug24** [comment]
Included in 2.9.40
