### ISSUE TITLE
Update version-checker to look at GitHub releases

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#216]
When checking for a new version, we're still checking the old Google Code page. Let's check [the GitHub releases section](https://github.com/dnGrep/dnGrep/releases) now. And we should use the [API](https://developer.github.com/v3/repos/releases/) rather than web scraping.

**Comment by doug24** [comment]
I can make a fairly easy change to check the GitHub releases using https://api.github.com/repos/dnGrep/dnGrep/releases and query the tag_name field from the json.  At least that will get notifications working going forward.  Too bad the old versions don't get notified anymore. 

I think changing to Squirrel.Windows could be a good thing, but will require a lot more work in the app and in the build process.

**Comment by JVimes** [comment]
Ya, switching to Squirrel isn't trivial (moved it to #255). I like your plan. The most important thing is people know there's a new version, and can easily download its installer.

**Comment by doug24** [comment]
Included in 2.9.31
