### ISSUE TITLE
Keep unix line endings

### ISSUE THREAD

**Issue by Karsonito** [dnGrep/dnGrep#217]
dnGrep replaces unix EOLs with windows EOLs (\n >> \r\n) when replaces text
Is it possible to keep current line endings?

**Comment by doug24** [comment]
This should be fixed in the 2.9.24 beta.  Replace will keep the original EOL based on the first line in the file.  Based on my testing, works with unix, windows, and mac line ends (if anyone still has one of those).

**Comment by JVimes** [comment]
Verified fixed.
