### ISSUE TITLE
Restrict search to certain files

### ISSUE THREAD

**Issue by rovf** [dnGrep/dnGrep#218]
It would be great if we could restrict the search only to files, the names of which match (or do not match) a certain pattern.

This pattern could be specified by, i.e., a list of wildcard patterns or a regexp.

**Comment by JVimes** [comment]
I think that can be done from the "search in" settings. Click the funnel icon to the right of the Search In textbox, and some settings will show, including "paths that match" and "paths to ignore", which I think is what you're looking for. It can be used to filter the resulting files based on path, including the filename. There's a radio button to pick either regex or asterisk pattern. More info in the [Search Window](https://github.com/dnGrep/dnGrep/wiki/Search-Window) section of the help wiki. Is that the same as what you're looking for?

![](https://raw.githubusercontent.com/wiki/dnGrep/dnGrep/Images/file-filter.png)

**Comment by rovf** [comment]
On Thu, Jan 22, 2015, at 22:27, JVimes wrote:
> I think that can be done from the "search in" settings. Click the funnel
> icon to the right of the Search In textbox, 

Ah, the one which looks like a loudspeaker! I didn't notice it. Yes,
that's it!!! Thanks a lot!

Ronald

**Comment by JVimes** [comment]
Ya, I think the funnel is supposed to be an analogy for "filter", but it's not the most recognizable symbol in the world. Especially when small. Glad to help ☺
