### ISSUE TITLE
Why not support regular expression for replace action?

### ISSUE THREAD

**Issue by t3dbundy** [dnGrep/dnGrep#219]

**Comment by JVimes** [comment]
Regular expression replacements are supported, but see the note in the [regex section](https://github.com/dnGrep/dnGrep/wiki/Regular-Expressions) of the help wiki about Microsoft regex, which uses dollar signs instead of slashes to insert matches and captured groups. Hope this helps.

**Comment by JVimes** [comment]
I'm closing this issue, but post again if you have repro steps of something that doesn't work.
