### ISSUE TITLE
Error popups from path lengths greater than MAX_PATH

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#220]
A modal, generic error dialog pops up for each file whose path lenght is greater than [MAX_PATH](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). Excluding the offending directories doesn't seem to help. Errors are logged to the windows event log but not to dnGrep's xml log file. The popups can be very numerous and you can't cancel the search to stop the flood of them because they're modal. [Possible workaround](http://stackoverflow.com/a/27694470/316760) using a different path format (is it fragile?).

**Comment by doug24** [comment]
Long paths are support in version 2.9.115
