### ISSUE TITLE
dnGrep doesn't play well with window snapping or window management apps

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#225]
[WinDock](http://www.ivanyu.ca/windock/) allows you to easily place windows into predefined sections of the screen. Keeps everything aligned and tidy. But it can't seem to affect dnGrep's window position at all. I'm guessing we're doing something special regarding window placement/size and should instead "play by the rules" better.

**Comment by JVimes** [comment]
This is probably the same root cause as #151.

**Comment by doug24** [comment]
I believe this has been fixed now.
