### ISSUE TITLE
Wildcards should also be directly available from main screen

### ISSUE THREAD

**Issue by rekna1** [dnGrep/dnGrep#227]
I think many of us (esp. developers) very often need to specify different wildcards, so it would be better if you also could specify them from the main screen directly, without having to open the drop down filter window. Also the option for searching in subfolders should be made available directly in the main screen as well.

**Comment by JVimes** [comment]
Good suggestion. The whole search filters panel used to toggle open/closed rather than close after each tweak. Issue #1 covers plans to put it back, so I'm going to mark this as duplicate. Feel free to follow the thread there. Thanks!
