### ISSUE TITLE
Working example of XPath search

### ISSUE THREAD

**Issue by Fluffums** [dnGrep/dnGrep#228]
Are there any examples of the XPath search test working? Perhaps some sample screenshots could be posted on the [appropriate wiki page](https://github.com/dnGrep/dnGrep/wiki/XPath) to make clear that it does work for some, as well as providing a starting point for those attempting to understand what sort of XPath queries dnGrep can handle.

My first attempts to use the XPath search on files failed, so I thought I'd test out my XPath search to troubleshoot. With the most basic search of '//child' against the following sample text, I was told "No matches found."

```
<parent>
<child>Test</child>
</parent>
```

![2015-07-06 16_03_57-test](https://cloud.githubusercontent.com/assets/5520906/8532175/655623da-23fa-11e5-80ae-be5d2d46b38c.png)

Windows Pro 7 SP1
dnGREP 2.7.2.0

**Comment by JVimes** [comment]
Thanks for reporting. Looks like that wiki page got mangled during migration from Google Code.  And it's examples showed zero-based indexes (should be 1-based). I think I have it fixed now. Still, there seems to be a bug in the Replace feature with XPath, which I logged as #229.

Your example works for me if I include the XML declaration at the top:
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<parent>
<child>Test</child>
</parent>
```

Still, it seems like dnGrep should at least warn the user of the missing XML declaration and perhaps use a default (tricky for some encodings). I logged this suggestion as #230. Feel free to add any comments you have.

Hope this helps.
