### ISSUE TITLE
Feature request: Either show entire line or have ability to copy an entire line

### ISSUE THREAD

**Issue by smeggysmeg** [dnGrep/dnGrep#231]
Hi there. This is a feature request rather than a bug.

At present, dnGrep places an ellipsis at the end of a long line if it's too long to display in dnGrep. In my situation, the content I want to view, and which I was actually searching for, is somewhere after that ellipsis, but the file is too large for me to otherwise open in another editor (it's a database dump). If I try to copy the line, it doesn't copy the entire line - instead, it copies the truncated line and the ellipsis.

Can we either have the ability to see the entire line, and not have the ellipsis, or have the option to copy the entire line for use elsewhere?

Thanks!

**Comment by JVimes** [comment]
Great suggestion. I'm trying to reproduce the problem but getting a horizontal scroll bar in the results instead of ellipsis. Have you tried the [latest beta][1]? And how long is the line? Maybe there's a maximum I'm not hitting.

[1]:https://github.com/dnGrep/dnGrep/releases

**Comment by smeggysmeg** [comment]
I'm using 2.8.16.0. This a huge and clumsily made database dump. The line in question is 1024555 characters long, but there are even longer lines.

Heh, like I said, most conventional text editors can't seem to handle these files. I've tried splitting them up, which helps, but an external grep-like search tool seems to be the best way to find things.

**Comment by JVimes** [comment]
That did it, I can repro now. I used this PowerShell script to generate a really long line:
```
$stream = [System.IO.StreamWriter] "test.txt"
for($i = 0; $i -lt 1024555; $i++)
    { $stream.Write($i%10) }
$stream.Close()
```
The limit in the UI might be necessary for responsiveness or memory usage. And there may be a limit on the clipboard. Whoever looks into this will need to see if our limits are reasonable or should be expanded.

In the meantime, if you have a text editor that can handle the files and takes the file and line number as arguements, I suggest setting up the Custom Editor option. Then  you can double click the line in the search results and it'll open in the editor. Here's the example for Notepad++:

<img width="340" alt="2015-09-03_23h18_55" src="https://cloud.githubusercontent.com/assets/6148201/9677068/666de926-5292-11e5-9ce1-f11e15071c85.png">

**Comment by smeggysmeg** [comment]
I guess that makes for a decent workaround. I can only open these files, so far, in Wordpad. Notepad++ actually has a fairly low maximum filesize limit.

**Comment by JVimes** [comment]
Interesting. I'll be surprised if Wordpad has a parameter to open to a specific line. But hopefully there's an editor out there that will (and will handle the files). [This thread](http://stackoverflow.com/a/163941) has some viewers that handle large files.

For some of your largest files, what kind of maximum line length and line count are we talking about? And file size? It'll be good to know what a demanding scenario looks like.

**Comment by doug24** [comment]
I made a number of changes for this feature in the 2.9.21 beta.  Note that the OP is talking about line lengths over 1 million characters.  There really isn't any way an application like dnGrep can display such long lines.  I did make changes to the preview window to show the matches in the first 500 characters (as it was before), and then additional matches with their position in the line.  However, there may be hundreds or thousands of matches in one line, so only the first 20-25 matches are shown.  After that, it will so just the count of remaining matches.   

The entire line is now preserved, so you can copy and paste it somewhere else.   From what I've read, there is no limit other than memory to the length of text that can be copied to the clipboard.   You can also save the entire line with the CSV export.

**Comment by JVimes** [comment]
@doug24 v2.9.24 spins indefinitely searching for 1234 in this file with one really long line: [test.txt](https://github.com/dnGrep/dnGrep/files/895084/test.txt). The old version, v2.8.16, finishes searching in ~1sec. Any ideas? Thanks for all your help!

**Comment by doug24** [comment]
I was afraid something like that might happen.  There are 102456 matches on one line.  The code is getting the line number for each match by looking for the next newline from the start index of each match.  Pretty inefficient when there is just one very long line.  If you turn off the option for 'show verbose match count' , it finishes quickly again.

I'll have to think about it...

**Comment by JVimes** [comment]
Makes sense. I created #252 to track it. This issue (of this thread), though, I verified as fixed (Ctrl+C copies all 1,024,555 characters).
