### ISSUE TITLE
Replacement in files located in multiple root paths is not working

### ISSUE THREAD

**Issue by wernerus** [dnGrep/dnGrep#232]
The replacement of text in files which are located below different root paths is not working properly. 
The pure search however is working!
Example to reproduce: Two files with a specific search text are located in different root directories. I want to search for the text and replace it in both files in one operation.
1. I put two path information in text box "Search in", divided by semicolon
2. Clicking "Search" finds my text to search in multiple files which are each below one of the given root path
![step_1_search_clicked](https://cloud.githubusercontent.com/assets/14799478/10039010/629e2cb6-61ce-11e5-8aa4-34a19e0c9d1e.png)
3.  Clicking "Replace" only replace the text in the first file! 

![step_2_replacement_clicked](https://cloud.githubusercontent.com/assets/14799478/10039011/629ef826-61ce-11e5-8b4d-b15784ba1c81.png)

**Comment by doug24** [comment]
This has been fixed in the 2.9.21 beta, if anyone would like to test.

**Comment by JVimes** [comment]
Verified fixed. Awesome 👍
