### ISSUE TITLE
"show file path in results panel" doesn't work if "search in" control ends in "\"

### ISSUE THREAD

**Issue by rkhwaja** [dnGrep/dnGrep#234]
If "show file path in results panel" is checked and you search in "c:\src", the full path appears. However, if you search in "c:\src\", just the filename appears.

If "show file path in results panel" is unchecked, it behaves correctly.

**Comment by rkhwaja** [comment]
It's still broken on the 2.8.16.0 beta

**Comment by doug24** [comment]
should be fixed now in the 2.9.21 beta.

**Comment by JVimes** [comment]
Not sure I understand. 😕  "c:\src" is the same as "c:\src". Was there supposed to be a trailing slash on one of those?

Also, I'm not seeing a full pathname:
![image](https://cloud.githubusercontent.com/assets/6148201/24686661/8ad25524-1972-11e7-868c-183a090bcf93.png)

**Comment by doug24** [comment]
Yes, one of those c:\src should have had a trailing backslash.  The other thing to note is that the path shown in the results is relative to the search path, so you need to have files at multiple levels.

Here are two screen shots from v2.7.2 showing the problem.   Without the trailing backslash, the paths are shown:
![image](https://cloud.githubusercontent.com/assets/17227248/24687193/4786fda6-196d-11e7-88e7-2bec6ba2513d.png)

With the trailing backslash, the relative path disappears:
![image](https://cloud.githubusercontent.com/assets/17227248/24687217/6d4028ec-196d-11e7-9baa-affae31ac55b.png)

Now, in the current release, the relative path is shown when the search path has a trailing backslash:
![image](https://cloud.githubusercontent.com/assets/17227248/24687357/0dcff2c4-196e-11e7-979a-a08d322312cc.png)

**Comment by JVimes** [comment]
Ah, yep. Thanks. Verified fixed.
