### ISSUE TITLE
<Message>Configuration system failed to initialize</Message>

### ISSUE THREAD

**Issue by pferrill** [dnGrep/dnGrep#235]
On startup I'm getting this error:

 <Message>'.', hexadecimal value 0x00, is an invalid character. Line 17, position 1. (C:\Users\paul\AppData\Local\Denis_Stankovski\dnGREP.exe_Url_40tgm0acjipcyzfzuxvjjkfz414ssbvv\2.8.16.0\user.config line 17)</Message>

**Comment by doug24** [comment]
Corrupt user config file.
