### ISSUE TITLE
Remember window size and position.

### ISSUE THREAD

**Issue by klonos** [dnGrep/dnGrep#236]
It is annoying how each time I launch the application, it has a different position from the last time it was used. I have my Windows task bar docked vertically to the left of the screen and the dnGrep window is always launched partially hidden behind it. I want it always maximized for example.

**Comment by JVimes** [comment]
Might need to address this at the same time as #225, which relates to window positioning. Unfortunately Windows itself doesn't relaunch apps in the same window position as before, though it's been suggested in the Windows 10 Feedback app (everyone please suggest/up-vote there). Hopefully there's a way we can handle that ourselves and play nicely with window management apps.

**Comment by klonos** [comment]
I think this is fixed in the latest beta 👍
