### ISSUE TITLE
Option to set double-click action to open with custom editor.

### ISSUE THREAD

**Issue by klonos** [dnGrep/dnGrep#237]
I want do jump straight to the line number when the file opens with the default double-click action. I have already configured the custom editor options and they work fine, but I have to right-click and select "Open with custom editor". I want to set that as the default.

**Comment by JVimes** [comment]
That currently works for me. I'm using Notepad++ and my configuration is:
![2016-05-25_11h46_29](https://cloud.githubusercontent.com/assets/6148201/15550375/57ed5ae2-226e-11e6-9683-b7e1c64f847a.png)

Double clicking on a search hit brings up Notepad++ at the line number
![2016-05-25_11h47_39](https://cloud.githubusercontent.com/assets/6148201/15550415/92c5d0f4-226e-11e6-9ee2-90a895cfc8e5.png)

**Comment by klonos** [comment]
...you are right. I had multiple instances of dnGrep open and had configured my custom editor and respective arguments in one of them. It wasn't till I closed all windows and started dnGrep when it started working.

**Comment by JVimes** [comment]
Glad it's working. Wouldn't hurt to see if there's an issue on settings not being synced in real-time across instances. Might not get implemented soon, but wouldn't hurt to report.

**Comment by klonos** [comment]
Sure. That's precisely what the issue is. If you open two instances and change any setting from one instance (I tied the external editor and the check for updates settings) then save, then switch to the other instance and open the options dialog, the settings are not reflected there.

- open two instances
- open the options dialog from one of them
- remove the custom editor path and arguments and uncheck the updates option
- save and close the options dialog
- switch to the other instance
- open the options dialog -> settings are still there

Bare in mind that I initiate my dnGrep instances via the context menu of folders.
