### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by insanetesterftw** [dnGrep/dnGrep#239]
The license that appears on the installation is **GPLv3** but the license that appears on the About box is **GPLv2**. What's the correct one? 

The About box also shows the date of release of the most recent version as **2013** and not **2015**.

The author field will also need to be updated.

**Comment by JVimes** [comment]
Thanks for reporting, @insanetesterftw. Which version are you on? Where are you seeing the v3 license? I see v2 in About box, and v2 license.txt in the source repository. Don't see license installed on my machine, but maybe there's somewhere I'm not checking.

The About box has the copyright date (2013) but doesn't have the release date. I'll leave it up to @stankovski if the author field should be changed. It's mostly his creation, although there's been a few contributions. The project is kind of just floating, waiting for pull requests right now.
