### ISSUE TITLE
Feature request: show separators for disjoint blocks

### ISSUE THREAD

**Issue by PhiLhoSoft** [dnGrep/dnGrep#240]
Here is what currently a search result looks like:
![dngrep-current](https://cloud.githubusercontent.com/assets/1087902/17018025/28aaa786-4f36-11e6-83b4-1509106945a9.png)
It isn't so bad: by looking at the line number, we can see we have three "blocks".
But too often, I am inattentive, looking at that as it was a text editor, and wondering why some lines are next to others...
I would appreciate if dnGrep displayed a fine discrete line between these blocks, ie. when line numbers jump. Example:
![dngrep-wanted](https://cloud.githubusercontent.com/assets/1087902/17018090/707e2448-4f36-11e6-8661-a63a4ad9d847.png)
You can see there are four matches, but only three "blocks", two matches are near, in the same run of line numbers.
Visually separating these blocks might help in reading the search results.

Thanks again for this fine software.

**Comment by JVimes** [comment]
Great suggestion. Love it.

**Comment by klonos** [comment]
👍

**Comment by doug24** [comment]
Great suggestion, this is included in the 2.9.21 beta

**Comment by JVimes** [comment]
Verified implemented. 😸
