### ISSUE TITLE
Problem finding/highlighting searched-for words

### ISSUE THREAD

**Issue by grymoire** [dnGrep/dnGrep#241]
I'm using dnGrep in a simple grep-like action - searching for a simple word (not a regex).
The results shows certain letters highlighted in yellow, and certain lines boldface.
However, neither one really matches the word I am searching for. Sometimes the yellow highlights the searched-for word, but most of the time it does not.

In the attached picture, I searched for "role". Line 16 has "sibi" highlighted, when "role" should be highlighted.
Line 38 is bold with "agem" highlighted, when line 37 has the word "role" - and line 37 is not bold. Line 38 does not have the letters "role".

I checked and the MS Word plugin is enabled (I didn't change anything.)

![dngep](https://cloud.githubusercontent.com/assets/3128144/17897460/4d67ace4-6922-11e6-81a2-201c91798327.JPG)

Windows 8.1 Enterprise.  Microsoft Office Professional Plus 2013. dnGrep 2.7.2 84-bit
I did install the beta first. When I had a problem, I uninstalled it, and installed  2.7.2 instead.
I did a typical install. I did not find a Grep_Error_Log.xml file.

**Comment by JVimes** [comment]
Thanks for reporting. Definitely a bug. Probably to do with either the Word plugin, multi-byte characters, or both. Very similar to #207.

In the meantime, try manually selecting a different encoding in the Filter drop-down (![2016-08-23_09h25_23](https://cloud.githubusercontent.com/assets/6148201/17898034/86accb2e-6913-11e6-84ef-4c177b33ac6d.png)). There's a slight chance that might work around it.

**Comment by JVimes** [comment]
Oh, forgot to ask, @grymoire, could you attach a simple Word doc that demonstrates the bug? According to [this page](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/), Word docs can be drag-and-drop attached to issues (might have to edit the original question, above).

**Comment by grymoire** [comment]
I tried using the Western European encoding. No change. Same with Unicode. and Unicode 8.

There is something odd going on with the filters. 
Example - I added a *.doc path limitation. One of the *.docx files was encrypted, BTW.  dnGrep still asked for the password when it opened the *.docx file, even though I limited the search to *.doc.

Also - I saved one of the *.docx file into a *.rtf format - and that seems to work OK. So I can confirm it's a problem with the  Word plugin.

I also saved the Word file as a PDF file, and dnGrep works correctly with that format, so I have a work-around.

I'm sorry - attaching a file will be difficult. These files hold sensitive customer information.
I created a test file, and in this file, the second instance of "role" was not highlighted. correctly.
The bug can be seen below.
![role](https://cloud.githubusercontent.com/assets/3128144/17899327/fcd7ea26-6928-11e6-8787-8e858fbdf947.JPG)

Here is the attached file.
[roletest.docx](https://github.com/dnGrep/dnGrep/files/432934/roletest.docx)

**Comment by JVimes** [comment]
That test file is perfect, thanks! Looks like each newline offsets subsequent highlighting by a character. For the future developer, I'd first check if this is the same situation as #207, but in the Word plugin. If so, let's consolidate that code.

**Comment by klonos** [comment]
Sounds like an off-by-one error somewhere.

**Comment by JVimes** [comment]
Ya, maybe counting `/r/n` as one character?
