### ISSUE TITLE
Update standalone version

### ISSUE THREAD

**Issue by sergeevabc** [dnGrep/dnGrep#244]
Both dnGrep [wiki][1] and [official site][2] promise the product is available as a standalone (i.e. portable) version.
But the only ZIP listed in [Releases][3] section dates back to 2012, new versions are supplied as installers.
It’s so confusing and misleading, we should fix it.

[1]: https://github.com/dnGrep/dnGrep/wiki
[2]: http://dngrep.github.io/
[3]: https://github.com/dnGrep/dnGrep/releases

**Comment by JVimes** [comment]
Thanks for mentioning. That got lost when we moved to a continuous build system. I removed those messages, for now, to avoid confusion. For whoever works on this, we'll need to update the AppVeyor build to produce stand-alone ZIPs, again, then put the messaging back on the website.

**Comment by sergeevabc** [comment]
Six months passed. Err… Hello?

**Comment by JVimes** [comment]
@sergeevabc There is no stand alone installer anymore. I've removed that info from the website and wiki. Please log a feature request for it, though. I don't personally have time for it, but a developer might in the future.
