### ISSUE TITLE
Bulk Replace sections and saving to new files

### ISSUE THREAD

**Issue by weedkiller** [dnGrep/dnGrep#245]
Hi, I was trying bulk replace of sections in HTML and save to new files for later verification.

For example, all tags (in html file)  including the content with `<Div class="testing comment">` or classes with `<Div class="testifail">` should be replaced with `<!-- commented \\Section failed test. -->` and saved in a new file. 

Can you tell is this possible, 

I used `powershell get-childitem *.html  | foreach {$_.Name} ` > dnGrep to bulk feed dnGrepand then replace all open documents... but not sure how to save.

**Comment by JVimes** [comment]
This is not possible using DnGrep (it requires user interaction). I think PowerShell has all the tools you need for replacing text in files (and outputting to new files). I'd look into PowerShell scripting.
