### ISSUE TITLE
Allow file pattern to be specified in 'search in' field

### ISSUE THREAD

**Issue by majkinetor** [dnGrep/dnGrep#249]
It is highly unpractical to have to click filter icon just to specify something you need almost 100% of the time, a glob. 

Search in field should handle this automatically, i.e. search in `c:\window\*.txt` should automatically populate the filter with `*.txt`.

**Comment by JVimes** [comment]
It is a big problem, having to re-open the filter pane so often. This should be fixed when Issue #1 is implemented (use a toggling "Expander" in the main UI).

But I do like the idea of allowing wildcards in the "Search in" field. Rather than move things from "Search in" down to "paths that match", I think we should either allow wildcards in both, or combine the fields into one text field (they seem to support the same behavior). Curious what folks think.

**Comment by majkinetor** [comment]
The suggested option is how most of the other tools work, hence its more intuitive. Not once I specified glob there just to realize there is nothing found.

**Comment by majkinetor** [comment]
Also, shell behaves that way.

**Comment by JVimes** [comment]
Maybe I'm not picturing it correctly. Is there a tool I can try, in order to see what you mean?

**Comment by doug24** [comment]
added in 2.9.215

**Comment by majkinetor** [comment]
When i specify <path\*.md> I get only md's in the current folder even with recursion is on. When I move *.md to filter, it goes recurse ?

Why is that ?

**Comment by doug24** [comment]
Back before the wildcards were added,:  when the text in the "Folder" field is a file or set of files, then dnGrep searches just those files, and the "paths to match" and recursion is ignored.  You are saying, just search these files.

Now with wildcards: if you use the wildcard on the file extension, it gets resolved to a set of files in that directory, and dnGrep stops looking for more files.  If the wildcards resolve to directory names, it will then search those directories.

**Comment by majkinetor** [comment]
Sounds legit. Thx.

**Comment by majkinetor** [comment]
However, current implementation doesn't resolve this issue :)

**Comment by doug24** [comment]
Aren't you using Everything for selecting files to search?   :)

**Comment by majkinetor** [comment]
Yeah... that doesn't seem to work correctly either :)
