### ISSUE TITLE
Default ClearType to "on"

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#251]
The ClearType setting makes zoomed results look much better (no pixelation). Let's default it to "on". Also, is there even a reason to turn it off? I vote let's remove the option from the Options window, unless we know of a specific reason for it.

![image](https://cloud.githubusercontent.com/assets/6148201/24558180/7bd54dac-15f7-11e7-995c-6e52dcd6229a.png)

**Comment by doug24** [comment]
Included 2.9.28
