### ISSUE TITLE
Verbose line count slows down on really long lines

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#252]
v2.9.24 spins indefinitely searching for 1234 in this file with one really long line: [test.txt](https://github.com/dnGrep/dnGrep/files/895084/test.txt). The old version, v2.8.16, finishes searching in ~1sec.

This is caused by current implementation of #243, per discussion [here](https://github.com/dnGrep/dnGrep/issues/231#issuecomment-291740636):

> The code is getting the line number for each match by looking for the next newline from the start index of each match. Pretty inefficient when there is just one very long line. If you turn off the option for 'show verbose match count' , it finishes quickly again.

If it's easy, it would be good to have a unit test that searches something like [test.txt](https://github.com/dnGrep/dnGrep/files/895084/test.txt), and just checks that it doesn't pass a certain, very liberal timeout. Just to catch cases where the search went way too long.

**Comment by doug24** [comment]
Included 2.9.31
