### ISSUE TITLE
Suggestion: Write highlighted Text after research with regex expression

### ISSUE THREAD

**Issue by fabbrin** [dnGrep/dnGrep#257]
Hi, i'm trying to add functionality to dnGrep. ( I use it to check timestamp in data log file, i.e 2017-02-20 16:05:02.462)
I would add the possibility to check if two timestamp are inside an interval for example 7 second. At the first, i extract all timestamp with regular expression. IT'S OK! In the second step, i would extract the yellow highlighted text from the result.

Anyone do have a suggestion which files .cs i would work? To extract this result? #

**Comment by doug24** [comment]
I assume you don't want to write out all matching text every time a search is done. That could consume a lot of resources.  Maybe you can use the export to CSV on the ">>" button menu?  If really want just the timestamps with no context, you could follow the process used in the GetResultsAsCSV method in the Utils class in dnGrep.Common.

The highlighted text is done in the FormattedGrepLine class, but that is a view made to display the search results in the UI.  The "view" of the data is lazy loaded when the user views the lines in the tree, or in the preview window.  dnGrep does not attempt to hold all the matching files and lines in memory - that could be an extremely large about of data.

If you want the actual search results, look at the GrepSearchResult class in dnGrep.Common.  A GrepSearchResult maps to a file, and contains one or more GrepMatch  items.  A GrepMatch is maps to a line in the file, with the start and end positions of the matched text.   The GrepSearchResult doesn't contain the actual lines of text.  To get those, you need to open the file and read the matching lines - which is what FormattedGrepLine does when the user opens a node in the tree view of results.

**Comment by fabbrin** [comment]
Thank you, I have follow your suggestion. I have fix my problem! Can i ask you a suggestion to fix bookmarks? For example, i add correctly a bookmark to "bookmark"menu. when i try to remove, i'm not able to delete it.

**Comment by doug24** [comment]
I don't know, it is working for me.  Select a bookmark in the bookmarks dialog, and click the Delete button.

**Comment by fabbrin** [comment]
Yes, it's fine also for me. I have some problems when i check star's
button. Indeed, i add correctly the bookmarks but when i decide to delete
it. It is not working.

Regards

Il 19 Apr 2017 16:00, "doug24" <notifications@github.com> ha scritto:

**Comment by JVimes** [comment]
@fabbrin Does it happen with the [latest installer](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.28.0)? What are the exact steps? Thanks.

**Comment by fabbrin** [comment]
Thank you for your reply. I don't have problem with the installer. I have
problem with the source code. The installer is ok, when i try to use dnGrep
as debug from source code i have find this problem with the bookmarks.
Indeed i add correctly the bookmarks but when i decide to delete it,  i
have to remove it with the star's button.

Regards

Il 19 Apr 2017 17:48, "John" <notifications@github.com> ha scritto:

**Comment by JVimes** [comment]
@fabbrin Log a new issue with the repro steps. Thanks!

Repro steps:
1. Run in debugger
2. Create bookmark via the Star button on main UI.
3. Try to delete the bookmark

Expected: You can. Actual: Delete button does nothing.

**Comment by fabbrin** [comment]
Thanks for all. i FIX my first issue about highlighted text.
