### ISSUE TITLE
Bookmarks error. Only with source code

### ISSUE THREAD

**Issue by fabbrin** [dnGrep/dnGrep#260]
Hi, i have a problem with bookmarks only with source code (NO INSTALLER version)

Repro steps:

1.Run in debugger
2.Create bookmark via the Star button on main UI.
3.Try to delete the bookmark

Expected: You can. 
Actual: Delete button does nothing.

Indeed when i try to edit a bookmarks, another bookmarks is created.

Regards

**Comment by doug24** [comment]
Fixed in 2.9.40
