### ISSUE TITLE
Bookmark button (star button) changes

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#261]
The star button should have a big, square hit zone, rather than a small, star-shaped one:
![image](https://cloud.githubusercontent.com/assets/6148201/25213146/cb2f74a0-254b-11e7-87b5-6a86c9f1f7a7.png)

Also, right now it looks like part of the Test tool (right next to the Test button). I think we should move it.

In browsers, people are used to seeing the star in the upper right, next to the address bar:
![image](https://cloud.githubusercontent.com/assets/6148201/25212820/05d32220-254a-11e7-97b9-9d122054b541.png)

Is there a more intuitive spot we could put it? Ideas I had:

**Idea 1**
![image](https://cloud.githubusercontent.com/assets/6148201/25213385/8c78c6f6-254d-11e7-983c-a8178f69b60c.png)

 **Idea 2**
![image](https://cloud.githubusercontent.com/assets/6148201/25213374/7858d472-254d-11e7-991d-5426d116af07.png)

**Comment by JVimes** [comment]
@doug24 Here's a change I'm thinking of making. Any preference on moving the star away from the Test button? Thanks!

**Comment by doug24** [comment]
For your idea 2 - I did a quick prototype of putting it the Search group box header - it seems kind of big there, in your picture it looks like you made it smaller?  It seems a bit crowded there, but it is close to other important things.
![image](https://cloud.githubusercontent.com/assets/17227248/25213711/3965ad90-2547-11e7-9345-7229f2120c98.png)

The bookmarks are more about the search and replace strings - what about to the left under the Test button? - the search and replace text boxes don't need to be full width

**Comment by fabbrin** [comment]
Sorry for the inconvenience, there are problem with bookmarks only with source code (NO INSTALLER version)

Repro steps:

1.Run in debugger
2.Create bookmark via the Star button on main UI.
3.Try to delete the bookmark

Expected: You can.
Actual: Delete button does nothing.

Indeed when i try to edit a bookmarks, another bookmarks is created.

Regards

**Comment by doug24** [comment]
I thought some more about the location of the Star button, and I think it does go with the Test button and the search fields.  I think the intended use of the Bookmarks are to save complicated regular expressions (or XPath) - so you might use the Test dialog to build and test the expression, and then bookmark it to save it for later use.  While you can save plain text searches, but there isn't as much value in that.

If the Bookmarks dialog was a drop-down to quickly find and select a bookmark (there is another issue for this), it would be nice if that drop-down button was next to the Star button.   I was thinking that they could be to the right of the 'Search for:' drop-down and below the Test button.  That puts it more in context with what it does, and is similar to the bookmarks button on web browsers.

I haven't looked at fabbrin's issue in the code yet, but it seems to be working as it should in the 2.9.28 build.

**Comment by JVimes** [comment]
@doug24 I did shrink the star in that mockup. "Bookmark dropdown with Star" is a step in the right direction (is that #171?). The current UI associates the Star much more strongly with Test than with what it directly affect: Search, Replace, and File Pattern. File pattern is far away in the UI, so what about putting the bookmark dropd-down above everything that it affects? I think that'll be much more intuitive. And then if we want bookmarks to affect another field, someday, it'll remain intuitive. And it's _very_ browser-like in appearance:

![image](https://cloud.githubusercontent.com/assets/6148201/25241575/b4478bd4-25b3-11e7-90b9-6341dced3dbc.png)

Side note: Fabbrin's issue is a development bug, not product bug. Happen when debugging, only.

**Comment by JVimes** [comment]
@doug24 BTW, I'm happy to implement these changes, unless it robs you of joy 😉

**Comment by doug24** [comment]
Sure, go ahead, that looks good.  I've starting working on the multi-select issues, so there's plenty to do...

**Comment by JVimes** [comment]
Sounds good. I'll fix the hitspot as part of this issue, just to get it in soon, and move the bigger UI changes to #171.

**Comment by doug24** [comment]
Included in 2.9.40
