### ISSUE TITLE
Image Background TreeView 

### ISSUE THREAD

**Issue by fabbrin** [dnGrep/dnGrep#265]
Hi, i have a question about TreeView panel. I would show a image in background pannel when the dnGrep start. Furthmore i would remove this when i click the search button. (Remove it until next restart of the app). Anyone have a suggetion to improve this?

Thank you,

Regards

**Comment by JVimes** [comment]
To show/hide the image, maybe [this approach](http://stackoverflow.com/a/6239327/316760) would work. The triggers will need to be bound to something in MainViewModel. Probably SearchResults.Count. Hope this helps.
