### ISSUE TITLE
"Include archives" checkbox

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#273]
Current archive searching behavior is a bit [confusing](https://github.com/dnGrep/dnGrep/issues/188#issuecomment-307284829), so let's add a "Include archives" checkbox just below the "Include binary files" checkbox, and then treat archives just like folders.

Hide this checkbox if the archive-searching plugin is not present.

**Comment by klonos** [comment]
I've been following the GitHub queue, so I saw this ticket when created. I never needed it till now, so I never commended, but **yes please** 😄

**Comment by doug24** [comment]
That's good to hear, I'm working on it now.

**Comment by doug24** [comment]
Fixed in 2.9.68 and later releases
