### ISSUE TITLE
Unknown publisher issue

### ISSUE THREAD

**Issue by Just1n** [dnGrep/dnGrep#276]
Can this be fixed?
I got this issue when I'm going to install dnGrop.

**Comment by JVimes** [comment]
I get it, too, and have to click "more > Run anyway". I think the fix would require buying a signing certificate (which aren't cheap, eventually expire, and have to be repurchased). If anyone knows a free way to fix the problem, please post.

**Comment by doug24** [comment]
fixed in v3.0.0
