### ISSUE TITLE
Replacing text in UTF8 files add BOM to files without 

### ISSUE THREAD

**Issue by greg2fs** [dnGrep/dnGrep#280]
Hello, I'm using dngrep to modify a set of php files from my website (php files need to have no BOM) and everytime it adds BOM to them so I need to resave each fil one by one.
Thanks

**Comment by doug24** [comment]
What version of dnGrep are you using?
Can you attach sample files (before and after replace) that shows the problem?

**Comment by greg2fs** [comment]
So sorry, after updated it works, I was using an old version...
