### ISSUE TITLE
Show the results in a full tree

### ISSUE THREAD

**Issue by rkhwaja** [dnGrep/dnGrep#281]
The result files are shown in breadth-first search order. I would mostly prefer depth-first search, although maybe some prefer the current display.
We could get the advantages of both by displaying the result files in a tree, with each node displaying the aggregate count for all the files and directories under that directory.

**Comment by doug24** [comment]
The ordering problem is fixed with the sorting options in 2.9.189.
Personally, I don't like the idea of showing results in a full tree:  I want to have results in a flattened list (like the top level nodes in the tree) so I don't have to search down the tree to find the files.
