### ISSUE TITLE
Part of the content inserted at the beginning of the file

### ISSUE THREAD

**Issue by greg2fs** [dnGrep/dnGrep#282]
Hello, I modifed several php files  with dngrep to replace $cnx by $GLOBALS['cnx'] and a part of the script as been inserted at the beginning of several files.
I'm using 2.9.53.0 version.
Attached are the before and after files.
[before.txt](https://github.com/dnGrep/dnGrep/files/1144150/before.txt)
[after.txt](https://github.com/dnGrep/dnGrep/files/1144149/after.txt)

**Comment by doug24** [comment]
Yes, this is a known problem.  The PR for issue #277 fixes this problem.  

Thanks for the sample files!  I ran your file through my dev code, and here's the result.
[fixed.txt](https://github.com/dnGrep/dnGrep/files/1145634/fixed.txt)

**Comment by greg2fs** [comment]
ok, thank you

**Comment by doug24** [comment]
This is fixed in the 2.9.64 beta, I'll leave this open while people get a chance to test it.

**Comment by doug24** [comment]
Fixed in 2.9.64 and later releases
