### ISSUE TITLE
Feature Request: Excel Docs

### ISSUE THREAD

**Issue by DarthFutuza** [dnGrep/dnGrep#285]
Was hoping you might add a plugin to search through Excel worksheets (just like the Word doc one).

**Comment by doug24** [comment]
A couple of thoughts:

dnGrep is a very text oriented tool, particularly search processing and the results presentation.  So I think the approach would have to be to parse the text out of the worksheets and then run the search on the plain text (much like the Word and PDF plug-ins do).

One problem is how to format the plain text so it is somewhat useful in the dnGrep results pane.  This would be something like separating the column data with tab characters, but I don't think there is any way to get things to line up nicely with different sizes of text or numbers in the cells.  So depending on your Excel data, it may be hard to read the results.

Is it sufficient to search for just the current values in the worksheets?   Or do you see a need to search formulas, or anything else?

If I did this, I would probably limit support to the newer file formats (*.xlsx, etc.) and not support the older (*.xls) files. 

The current Word plug-in uses a quite old technology of COM Interop and it's got a lot of problems.  I have dnGrep on three Windows 10 machines and the Work plugin works on only one of them, the other two refuse to load the Word assemblies.  And when it does work, the plug-in is actually using the Word program to load the files. That means every file you search gets put on the recently accessed files jump list.  Yuck. 

I think a better approach would be to use the Open XML standard to read the files within dnGrep without using COM Interop.  That means you could also search without having Excel installed.   But the old doc and xls files aren't Open XML files, so they won't work.

I'm also thinking we could add Word (and maybe PowerPoint?) support using Open XML, too.  Once again formatting is a big issue again, converting the documents to plain text in a somewhat recognizable format.

**Comment by JVimes** [comment]
I vote for supporting only Office Open XML. Wikipedia says it's the default since Office 2007.

I think knowing there's a hit in the file is probably 80% of the benefit. Showing the result in a useful way is second priority.

**Comment by doug24** [comment]
This is now available in 2.9.77.   Please give it try and let me know what you think.

There is support for .xls, .xlsx, .xlsm, .docx, and .docm (yes, even the old .xls binary files, thanks to the ExcelDataReader project).

When searching Word and Excel files, make you have the "include binary" files option selected.

When searching for numeric values in Excel:  be aware that Excel rounds the displayed values, but the conversion to text will export the actual value - so there may be differences between what you see in Excel vs. what you are able to search for.

**Comment by JVimes** [comment]
If the rounding behavior becomes a real issue, we could brainstorm possible solutions (match rounded values? Do a quick, fuzzy check first?). But let's see if it's more than an academic issue. Thanks, Doug! You're amazing.

**Comment by DarthFutuza** [comment]
I'll give it a try and let you know if I run into any issues.  Thanks for the update Doug!  I'm more interested in actual values, and not rounded values for what I tend to use dnGrep for so it doesn't matter to me, but other users might care.
