### ISSUE TITLE
fails to start after upgrade from Windows 7 to 10

### ISSUE THREAD

**Issue by az0** [dnGrep/dnGrep#286]
I had dnGrep 2.9.40 x64, and it worked well.  Then my machine was upgraded from Windows 7 to Windows 10, and then dnGrep refused to start. It throws the error 

> Something broke down in the program. See the event log for details
![2018-02-14 10_39_56-greenshot dngrep](https://user-images.githubusercontent.com/933680/36331936-2fef06e2-132d-11e8-8ed5-c8986c5e757f.png)

I tried an update to 2.9.40 x64, but the installer stops most of the way through. At the same time, there is a popup dialog box with the same error message. The installer's cancel button does not work, so apparently I have to kill the installer process.

![2018-02-16 15_17_42-dngrep 2 9 68 x64 setup](https://user-images.githubusercontent.com/933680/36331898-06c6bbb6-132d-11e8-84b4-79b47b1c74da.png)

Here is the event log

````
<Error time="2/16/2018 15:21:26 PM">
  <Message>Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.</Message>
  <Parameter value="System.Windows.Markup.XamlParseException   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)&#xD;&#xA;   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)&#xD;&#xA;   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)&#xD;&#xA;   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)&#xD;&#xA;   at dnGREP.WPF.MainForm..ctor(Boolean isVisible)&#xD;&#xA;   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e)" />
</Error>
````

**Comment by doug24** [comment]
I have 2.9.68 on three different Windows 10 machines, so it seems like it should work for you too.  Did you try uninstalling the older version first?   Uninstall, the make sure the C:\Program Files\dnGREP is folder is empty.  It probably would be good to remove or rename the dnGREP.Settings.dat file in %appdata%\dnGREP as well.  Then try the installer again...

**Comment by az0** [comment]
I am sure it works on some Windows 10 machines, but there is idiosyncrasy on my mine.

I uninstalled 2.9.68, removed the two folders, and tried installing again, but I got the same result. I noticed that `%APPDATA%\dnGrep\logs\Grep_Error_Log.xml` was created (after I deleted that folder). The contents look the same as the Windows event viewer

````
<Error time="2/19/2018 10:17:24 AM">
  <Message>Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.</Message>
  <Parameter value="System.Windows.Markup.XamlParseException   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)&#xD;&#xA;   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)&#xD;&#xA;   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)&#xD;&#xA;   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)&#xD;&#xA;   at dnGREP.WPF.MainForm..ctor(Boolean isVisible)&#xD;&#xA;   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e)" />
</Error>
````

Google found a similar issue here, but I am not sure what "refresh my install" means
https://github.com/extesy/DeckTracker/issues/153

I also found symptoms like this with SourceTree (which also does not work on my system), so I will try to update .NET. Right now I have .NET 4, 4.5, 4.5.1, and 4.5.2.
https://community.atlassian.com/t5/Sourcetree-questions/Unable-to-Open-Sourcetree-After-Windows-10-Upgrade/qaq-p/665007

**Comment by az0** [comment]
I installed .NET Framework 4.7.1. Though Add/Remove programs still shows 4.5.x and does not show 4.7, dnGrep and Sourcetree now start.
