### ISSUE TITLE
Feature Request: add integration with Everything index server

### ISSUE THREAD

**Issue by doug24** [dnGrep/dnGrep#291]
If anyone wants to contribute suggestions or requirements, please respond to this issue.

[Everything](http://www.voidtools.com/) is an file system index server and client.  The goal of the integration with dnGrep is to provide faster lookup of files for processing.

This would be a completely optional add-on to dnGrep.  If dnGrep detects that Everything is installed, then it would offer an alternative for filter options in addition to the "Regex" and "Asterisk pattern" filters.  And you could switch in and out of using Everything.

I haven't spent much time looking at it yet, but first thought is to use the dnGrep "Folder" text box to enter Everything search commands, like in the Everything client.  It would pass the search text through as-is to the Everything API, returning a list of files to process.  

The other dnGrep filters would be applied to the results returned from Everything, so a user can add additional filers if they want.  The 'Paths to match' and 'Paths to ignore' are assumed to be regular expressions. 

From the list of files, dnGrep would continue with the normal processing.

@majkinetor

**Comment by JVimes** [comment]
Also, it's worth going through existing UI(s) for Everything and making sure we'd be adding value. I haven't used them, so just thinking out loud, here.

**Comment by doug24** [comment]
So I ran into some issues in working on this: not really with Everything, but with what dnGrep expects to find in the "Search in Folder" box.  The short story is that having something other than rooted paths in there causes problems for searching, replacing, copying files, moving files.  And I found I broke the "Undo" a year ago - I guess no one uses it. ;)   But should be fixed now.

I haven't created a pull request yet, as I'm not real confident I'm finished with testing.  But if anyone wants to help by testing this, I would be really grateful.  Here's a build you can run, if anyone would like to help with testing.   This build includes the changes for Everything, and the mods to the Preview Window.
 
[dnGREP 2.9.82 (x64).msi.zip](https://github.com/dnGrep/dnGrep/files/1867015/dnGREP.2.9.82.x64.msi.zip)

**Comment by majkinetor** [comment]
I will test it. Just tell me what needs to be done as I don't understand what kind of test you need. Undo ?
I can create automatic GUI tests in AHK if needed.

**Comment by doug24** [comment]
Run it as you normally would, I want to verify that that I haven't broken any features.  That would be in both the original mode, and in Everything mode.
For Everything, I'm interested in knowing if the path/file search works as you would expect in the Everything client.  
The Undo should reverse all Replace changes.  It has not worked at all since I made the change to allow replace in multiple directory hierarchies.  Now, it should undo all Replace changes.
The Copy and Move files operations depend on the path/file search.  If there is a single rooted path there (like c:\source\repos\dnGrep) when copying or moving files the directory structure of the source files is preserved under the new folder location.  However, if the path spec is an Everything search like "\work *.xml", then there is no common root folder to determine the folder structure of the source files - they could be from anywhere.  So for this case the Copy and Move files will put all the files in the same destination directory - and increase the chance of file name duplication.

**Comment by majkinetor** [comment]
OK.  I can't promise any ETA at this moment but I will try my best to do something and will probably involve Autohotkey.

**Comment by majkinetor** [comment]
OK, first impression:

It took me several minutes to figure out what is going on.  Paths to match should be disabled as it seems not to be used. Or, you could inject Folder infront of the search (or perhaps via other API functions) and let the query live in "paths to match" box to be consistent with overall experience.


Everything also has RegEx mode, not sure how to enable it.

It is 60% faster on 10GB folder

---

**Astersik patern**: 
Folder: `C:\Work`
Paths to match: `*.ps1`
SearchFor: `request`
1st run: Files 15217, Found 293 in 14s

**Everything**
Folder:  `C:\Work\ *.ps1`
Paths to match: ``
SearchFor: `request`
1st run: Files 15211, Found 293 in 6s

Folder:  `C:\ *.ps1` ~ 180 GB SSD drive. 18K files, found 733
Everything: 8s
Asterisk: waited several minutes and aborted.

**Comment by doug24** [comment]
Thanks for the comments!  Yes, I was thinking about disabling the 'Paths to match' field.  My thought was (as you discovered) that the "Folder" field would work just like the Everything client.

To do a regex search with Everything, try this:
`C:\work\ regex:f.*\.ps1`

**Comment by majkinetor** [comment]
Thx for regex tip. 

Probably anything not used should be hidden. Alternative, perhaps some of it can be reused via API but it requires way more work then what we have now which looks clean to me. I would at least hide paths to match as users will be confused where to type otherwise and maybe change label from Folder to "Everything search"

Thanks for doing this, I think there is no harm to release it ASAP.
