### ISSUE TITLE
Feature Request: please allow to dock the Preview Window

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#293]
Good afternoon
Thanks a lot for this great Software!, it's lightweight, fast and very useful.

The preview Windows is a little bit annoying to handle. I guess most users have the search result tree on one side and the preview Windows on the other side, so that they navigate through the tree (using the up / down cursor) while the preview automatically displays the matches.

Therefore it would be useful if the preview Window 

- either is a separate Window so that it gets recognized by the Windows OS and therefore automatically gets placed by the OS if we use Win-Left or Win-Right

- or if the preview Windows could be docked on the left or right side of the dnGrep's main Window.

Thanks a lot, kind regards,
Thomas

**Comment by JVimes** [comment]
I like option # 1 (make the window be a "normal" window). I use window snapping tools, a lot.

**Comment by doug24** [comment]
I think this might be a pretty simple to make the preview window a normal window.  I'll give it try, and you can tell me if it works better for what you want to do with it.

**Comment by JVimes** [comment]
@doug24 I think so, too. Make sure to set the Owner of the child window to App.Current.MainWindow (or whatever the syntax is). Make sure the behavior is sensible on minimize/restore/exit of the main window. Thanks!

**Comment by doug24** [comment]
OK, I take it back, this is anything but simple.  :)

In the existing code, the preview window owner is not set.  But if I add this:
    `preview.Owner = App.Current.MainWindow;`
Then the preview window is always on top of the main window, which is not good when the windows overlap.  So I don't think we want that.

There is code that moves the preview window to the top whenever the main window is activated.  That's strange behavior, too.  I want the window with input focus to be on top, so I took that out.  

Then there is code that changes the preview window state to match the main window state.  So if you minimize the main window, the preview window minimizes.  That may be OK in some cases, but what if you were minimizing the main window to get a better look at the preview window?  Maximizing the main window would also maximize the preview window - that doesn't make sense.  I think that code needs to go too.

I added code to bring the preview window to the front when a file or line is selected in the main window results.  And restore it if the preview window has been minimized.

Now, the two windows appear to work independently, and with behavior I would expect.  I'll keep testing for a while.

**Comment by JVimes** [comment]
Ah, thanks Doug. [Owner](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.owner?view=netframework-4.7.1#System_Windows_Window_Owner) takes care of minimize behavior but enforces child overlap. It almost made our lives easy! I found no acceptable workarounds.

Here's what I vote we do, instead:

* Don't set Owner.
* Remove most/all existing window management code.
* When parent window is minimized, child window is minimized. Done in a parent event handler, I think.
* When child window is minimized, parent is *not* minimized. No code necessary, but test by hand.
* When parent window is closed, child window is closed. Just requires `ShutdownMode="OnMainWindowClose"` in `<Application>` tag in App.xaml, I think.

**Comment by schittli** [comment]
Maybe, the usual solution for this kind of problem would solve the problem, too:
such windows are usually ... just dockable :-)

**Comment by JVimes** [comment]
@schittli Sorry, not sure I understand. When un-docked, we still have a floating child window to configure.
