### ISSUE TITLE
Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by becklesd** [dnGrep/dnGrep#299]
**All searches fail** with the following error in the log file:

>  <Message>Failed in search in files</Message>
  <Exception>
    <Message>Specified argument was out of the range of valid values.
Parameter name: MaxDegreeOfParallelism</Message>
    <Source>mscorlib</Source>
    <Stack>   at System.Threading.Tasks.ParallelOptions.set_MaxDegreeOfParallelism(Int32 value)
   at dnGREP.Common.GrepCore.Search(IEnumerable`1 files, SearchType searchType, String searchPattern, GrepSearchOption searchOptions, Int32 codePage)</Stack>
  </Exception>

**Comment by doug24** [comment]
I'm guessing it tried to set MaxDegreeOfParallelism to zero.  I should have put a minimum value limit on the calculation.  Try this: open the "More" options on the main screen, and uncheck "Search Parallel'

![image](https://user-images.githubusercontent.com/17227248/40571727-f6d32b72-6052-11e8-9f04-0150bf251336.png)

**Comment by becklesd** [comment]
Thanks. Your suggestion has worked.

**Comment by JVimes** [comment]
This should be in the [latest build](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.100.0). :)
