### ISSUE TITLE
Not working with RAR5 compressed files

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#303]
Although Dngrep seems to work with files compressed with Zip and RAR4 files, it doesn't work with files compressed with RAR5

**Comment by doug24** [comment]
What version of dnGrep are you using?  I think it should be supported in the latest version, 2.9.93.0.

dnGrep uses 7-Zip for decompression.  According to [this page](https://www.7-zip.org/faq.html), versions of 7-Zip later than 9.20 do support RAR5.  I upgraded the 7z.dll in dnGrip from 9.2 to 18.1 (yes, really!) in April 2018.

If you are using dnGrep 2.9.93, can you attach a RAR5 compressed file with a few text files in it for testing?  I don't have any way to create a test archive since I think requires a commercial app to create them.

**Comment by harryray33** [comment]
Thanks. I can't seem to get it to work. 

I'm using the latest version...I've attached a couple of text files and the RAR5 compressed file.

I've changed the extension on the RAR file to docx as RAR files can't be uploaded...just change the extension back to .rar













[USBSafelyRemove.log.txt](https://github.com/dnGrep/dnGrep/files/2285911/USBSafelyRemove.log.txt)
[TV Show Season Premieres & Finales Calendar _ SideReel--03-08-2018.txt](https://github.com/dnGrep/dnGrep/files/2285909/TV.Show.Season.Premieres.Finales.Calendar._.SideReel--03-08-2018.txt)


[text files.rar.docx](https://github.com/dnGrep/dnGrep/files/2285919/text.files.rar.docx)

**Comment by harryray33** [comment]
I tried out  7zip on my rar5 file and yes, it does unpack it but I just can't get it to work on Dngrep...

Possibly me just being dumb?? :0)

**Comment by harryray33** [comment]
I don't know if this will help...entry taken from log file.

<Error time="8/14/2018 22:17:37 PM">
  <Message>Failed to search inside archive 'C:\Users\user\Desktop\New folder\from 7 aug.rar'</Message>
  <Parameter value="System.ArgumentException   at SevenZip.FileChecker.CheckSignature(Stream stream, Int32&amp; offset, Boolean&amp; isExecutable)&#xD;&#xA;   at SevenZip.SevenZipExtractor.Init(Stream stream)&#xD;&#xA;   at dnGREP.Engines.Archive.GrepEngineArchive.Search(Stream input, String file, String searchPattern, SearchType searchType, GrepSearchOption searchOptions, Encoding encoding)" />
</Error>

**Comment by doug24** [comment]
No, it's not you, it is that they changed the file signature when going from rar4 to rar5 (see the [hex signature here](https://en.wikipedia.org/wiki/List_of_file_signatures).  There is an interface library called SevenZipSharp.dll that allows .NET code to call the native 7z.dll.  That library contains the readable archive formats, and it missing the signature for rar5.  I'll need to figure out how to add it, and rebuild the library.  I'll try to get to it, but sure when it will happen.

**Comment by JVimes** [comment]
@doug24 Is this something we should report to the SevenZipSharp devs?

**Comment by harryray33** [comment]
I had this issue with another Grep programme Lookdisk (which I don't like as much as this one) and after I contacted the guy that wrote it he kindly adjusted it so that it now works with RAR5 ..Although as far as I can see SevenZipSharp wasn't used in Lookdisk.

**Comment by harryray33** [comment]
Thinking about it, I suppose it may be an idea to report it, it does seem like a major mistake...As i mentioned, same problem with lookdisk but not with SevenZipSharp.dll it must have been with one of the other 7zip files.

The main 7zip programme does support RAR5 though!!

**Comment by doug24** [comment]
@harryray33 no, it's not a mistake.  RAR5 was introduced in September 2013 and SevenZipSharp is much older than that, and has not seen many updates.  SevenZipSharp is not part of 7-Zip, it is a independently developed project.

@JVimes I have not found any active development on SevenZipSharp.  The original code was on Codeplex, and the original author abandoned it 8 or 9 years ago.  There are about 10 forks of the original SevenZipSharp on github, and https://github.com/tomap/SevenZipSharp appears to be the most up to date, but it hasn't been updated in almost a year and the main page says he is looking for a new maintainer.  There is one pull request that has been sitting for 10 months that may have what we need, but the PR has changed 172 files in the project... hopefully most are just file reformats, but it will take some time to evaluate. 

I hate to be cynical, but this is the consequence of free, open source software.  Eventually the maintainers get busy with other things, and there isn't any incentive to continue.

**Comment by JVimes** [comment]
Ya, makes sense. That's too bad. Maybe there's a new kid on the block for .NET archive handling. Or, a RAR specific library.

**Comment by harryray33** [comment]
I left a message on the 7zip forum and got this reply.

Tere are two handlers in 7-zip for rar files:
1) rar before rar5
1) rar for rar5
So SevenZipSharp must check both handlers, if it want to open any rar archive.
There were some reasons to do it so in 7-Zip code.

**Comment by doug24** [comment]
I found another [SevenZipSharp fork](https://github.com/arttarasov/SevenZipSharp) that has active development, and they have already added support for RAR5.

**Comment by harryray33** [comment]
Thanks so much. I had a look through but I couldn't find the file....Does it have to be compiled? I'm afraid that's totally beyond me :0(

Or is it hidden somewhere?

**Comment by harryray33** [comment]
I found a file squid-box.sevenzipsharp.1.1.106.nupkg which I downloaded and I found a sevensharpzip.dll file (much bigger than the one in DNgrep)
I tried replacing the existing file with this one in the archive search folder but still can't get it to work.
Am I doing something wrong (very likely)?

**Comment by harryray33** [comment]
Also found this file...still not working though.

**Comment by harryray33** [comment]
sevenzipsharp.net45.1.0.17.nupkg

**Comment by doug24** [comment]
I didn't mean for you to do all of that.  I put the code into dnGrep, so it's probably easiest to wait for the next build.  I tested it with the rar file you posted above.  

If you do want to try it what you've started, you will also need to put the 18.5 version of 7z.dll in the archive folder. If you are on a 64 bit machine, rename it to 7z64.dll.

**Comment by harryray33** [comment]
Doug, thank you so much....I'll wait till you post the next build.

**Comment by harryray33** [comment]
Btw, yes, I'm using 64 bit....

**Comment by JVimes** [comment]
This should be in the [latest build](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.100.0). :)
