### ISSUE TITLE
Only matching whole words

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#307]
I can only seem to get DNgrep to work if I tick the match whole word box. for example, search for the word beverage..If I tick whole word it finds it, if I untick whole word it wont find it.
If I search for part of a word ie: beverag it wont give me any result at all.

Also, it only seems to find words when the regex box is ticked but not if the text box is ticked.

Can you also tell me how I go about searching for two different words within the file ?

**Comment by harryray33** [comment]
I think it maybe the way I'm using regex...I've worked out that I can use (?=.*word1)(?=.*word2) to find more than one word but is there an easier way such as using an operator such as AND or OR?
My knowledge of regex is fairly basic.

Still can't quite get it to work when text is ticked but I'll read through your help page thoroughly.

Btw. love this grep...really useful.

**Comment by harryray33** [comment]
It would be nice, when setting a bookmark, to be able to save the settings to relate to that bookmark as well.

**Comment by doug24** [comment]
It's not clear what you are trying to do with that regular expression. If you are just trying to match something ending in 'word1' or 'word2', then the regex you are looking for is simply 
word[12]

The 'Text' search will just match the exact string of character you enter.  You can refine it by making match whole word and/or case sensitive.  It should work just like you would expect in a text editor or word processor.
