### ISSUE TITLE
making dnGREP cross platform

### ISSUE THREAD

**Issue by Foadsf** [dnGrep/dnGrep#310]
I was wondering if there is a way to make dnGREP cross-platform, also available on macOs and Linux?

**Comment by doug24** [comment]
No, I don't think that would be possible, it would take a huge re-write of the application.  There are a lot of calls to native Windows dlls, and the UI would have to be changed to something portable.

**Comment by Foadsf** [comment]
@doug24 sad to hear that. maybe this can be a join project with [Okular ](https://okular.kde.org/)or [Sumatra PDF](https://www.sumatrapdfreader.org/free-pdf-reader.html)? 

related issues for [Okular ](https://bugs.kde.org/show_bug.cgi?id=174314)and [Sumatra PDF](https://github.com/sumatrapdfreader/sumatrapdf/issues/493)

**Comment by mattalexx** [comment]
You could mount the filesystem in a Windows VM or container and search that way.
