### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ErwinMeulman** [dnGrep/dnGrep#312]
Is it easy to get a dark theme mode?

**Comment by doug24** [comment]
It's not currently possible without code changes.  It's not difficult, but will require quite a number of changes.

**Comment by JVimes** [comment]
Suggest making it follow Windows 10's dark vs light theme setting.

**Comment by ErwinMeulman** [comment]
I LOVE THE NEW DARKMODE !! THANKS

**Comment by doug24** [comment]
In release 2.9.143 and later.  Closing this now, if anyone finds issues with the themes, please open a new issue.
