### ISSUE TITLE
PDF-search: Wrong letters shown in "results panel" in case of german Umlaut-letters

### ISSUE THREAD

**Issue by pantak1** [dnGrep/dnGrep#313]
dnGREP Version: 2.9.100.0:
When searching PDF-files, which contain german Umlaut-characters (ä, ö, ü ...), the preview in the results-panel is showing wrong characters at the right position where the character was found.
Attached the PDF-file and a screenshot of dnGREP-search.
More info about Encoding of german characters here:
http://www.426.ch/cgi-bin/moin.cgi/German-Characters
https://www.fileformat.info/info/unicode/char/00e4/index.htm
[a-Umlaut.pdf](https://github.com/dnGrep/dnGrep/files/2774198/a-Umlaut.pdf)
![a-umlaut-dngrep](https://user-images.githubusercontent.com/46825664/51407780-1e8d5c80-1b5d-11e9-9d28-caf9f0eb1a85.png)

**Comment by doug24** [comment]
dnGrep does not actually read PDF files: it uses an external program to convert the PDF to plain text, and then searches the plain text file.  I'm sure that the encoding is lost in the PDF to text conversion.  

This will be difficult to fix. It will probably require re-writing the PdfEnging plug-in to use a different library or program to parse the PDF file.

**Comment by pantak1** [comment]
Yes, I know that the external program in plugins\pdfsearch\pdftotext.exe is doing the conversion.
I have done this conversion with this program manually and the resulting text-file is OK.
This means the character was converted right to ä (see attached [a-Umlaut.txt](https://github.com/dnGrep/dnGrep/files/2775740/a-Umlaut.txt)).
A dnGREP search for the ä in this text-file shows the right character (see following picture):
![a-umlaut txt-dngrep](https://user-images.githubusercontent.com/46825664/51429623-cfa0ff00-1c10-11e9-9c25-a9b65f63befe.png)
So the  encoding is not lost in the manually PDF to text conversion.
Maybe the dnGREP engine calling this pdftotext.exe converter is doing something wrong.

**Comment by doug24** [comment]
OK, I'll take a look at it.  Thank-you for the test file.

**Comment by pantak1** [comment]
Thank you very much for the correction !
