### ISSUE TITLE
What's new?

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#319]
Thanks for the new build....Can you tell me what's new in this build?

Thanks.

**Comment by JVimes** [comment]
It's on the [releases][1] page, if you mouse over/click the issue number, but I should make it more clear. I'll go ahead and edit the description to make it better. Sorry about that.

**Before:**

![image](https://user-images.githubusercontent.com/6148201/51757048-a9031e00-207f-11e9-813b-7ca346b85a74.png)

**Now:**

![image](https://user-images.githubusercontent.com/6148201/51757087-c0daa200-207f-11e9-8a2f-91b985103bd7.png)

[1]: https://github.com/dnGrep/dnGrep/releases
