### ISSUE TITLE
cannot search d:\

### ISSUE THREAD

**Issue by PaulSoderlind** [dnGrep/dnGrep#320]
since upgrading to 2.9.115.0, I cannot search a whole drive (eg. `d:\`) anymore. In contrast searching `d:\Folder1` works nicely (and recurses through the subfolders)

**Comment by doug24** [comment]
I should have asked this first:  is there anything in the dnGrep log file?  
%appdata% \dnGREP\logs  (c:\users\nnnn\AppData\Roaming\dnGREP\logs)

**Comment by PaulSoderlind** [comment]
>  is there anything in the dnGrep log file?
Just some old cruft. Nothing changes if I delete this file.

>Can you try searching for all text files by using *.txt as the path pattern and leaving the 'Search for' field empty?
gives `Searched 0 files. Found 0 files in 0.21s.`

The same happens if I search any other drive (C:\, etc).

There is nothing special with the drives: NTFS (win64 10).

**Comment by PaulSoderlind** [comment]
one more piece of evidence:

searching D:\ actually works when I click `Include hidden folders` 

However, most of the folders are regular folders, not hidden.

**Comment by doug24** [comment]
The `Include Hidden` flag is the key.  The root folder of the drive does actually have the `Hidden` file system attribute set, but I don't think previous version of dnGrep was checking directory attributes only file attributes.  I added a special check for root directories, and pass them even if the `Include Hidden` flag is not checked.  PR #321 has been created.
