### ISSUE TITLE
shortkey to close the preview window

### ISSUE THREAD

**Issue by yantaozhao** [dnGrep/dnGrep#322]
Need a feature: `ESC` or `q` key to quickly close the preview window, same as the result of click the close button.

**Comment by doug24** [comment]
I will get to this soon.  I noticed while testing that if you have the preview window open, and press `ESC` with focus on the main window, it will close the preview, but the app will crash when you click another file to preview or when you exit the main window.

**Comment by doug24** [comment]
Fixed in 2.9.127.0
