### ISSUE TITLE
Copy Results - include hits

### ISSUE THREAD

**Issue by justAuser2** [dnGrep/dnGrep#327]
Hi there,  I created this gitHub account just so I could make a suggestion on this very good tool.

When I complete a search and I find 100+ files with numerous results, I want to copy the file name and the number of results.  Ideally, the file name can be tab separated (so I can immediately cut&paste into excel say) but that's not necessary as I can workaround by doing that step in Notepad++.

Would it be possible to add this capability as an option when I select-all results and right click to bring up the context menu?  I was hoping Copy Lines of text would work, but that option just seems to copy the first 12 lines of a file (could not determine which file out of the 100+ selected!).

I'm using Version 2.9.127.0.

Thank you!

**Comment by doug24** [comment]
Can you give this a try:  after running a search, click the `>>`  button next to the `Cancel` button.  Choose the last item `Save Results`   The will create a file, and you have a choice of three file formats - use the "Report file format".   That file will have the count of all the matches in each file.  It also has a lot more information than you want, so it would take a lot editing to remove it.

The problem I have with your request is creating a feature for your unique case.  It would be much better to have a configurable export/copy feature that allows the user to select what data to include, and some options for the format.  I'll think about that - but I am in the middle of other things right now.

**Comment by justAuser2** [comment]
Yes, that was a work around I ended up using.  Thanks for the suggestion though!  I do agree with you, it would be better to have it configurable on what would be exported.  If you do go down this route, can I suggest you consider adding a switch to suppress non-ascii characters on export?  I had to work around that one too. 

Thank you again though!
