### ISSUE TITLE
Add flag to include unicode search

### ISSUE THREAD

**Issue by Hexaae** [dnGrep/dnGrep#328]
Please, can you add a flaggable option to search ALSO for Unicode text?
I know I can use Regex search and add "." before-after every letter of the search string, but an option to automatically search for the Text ALSO in Unicode mode would be very handy.

E.g.
Regex search: "s.e.a.r.c.h.e.d. .t.e.x.t." will work fine but it's not the fastest solution

P.S.
Of course when Unicode search is also flagged, search will be a bit slower, I understand.

**Comment by doug24** [comment]
I don't think that should be necessary, it sounds like your file is being read with the wrong encoding.  Can you attach a sample file that demonstrates the problem?

**Comment by Hexaae** [comment]
I sometimes need to find Unicode text into generic/unknown binary files, hence no encoding.
Would still be useful such a generic option IMHO, since Unicode strings are often used and embedded in binary files.

**Comment by doug24** [comment]
dnGrep does searches on _text_ not on binary data.  So even when searching in binary files, the binary data is converted to text using some encoding. Without knowing the format of the binary file, it is impossible to guess what data is text and what the encoding is

For text files dnGrep can determine the correct encoding most of the time, but it doesn't work on binary files, so it just falls back to Windows default encoding - in my locale it is "Western European (Windows)"  also known as CodePage 1252 - and decodes the binary file as text using that encoding.  

But you can choose a different encoding from the encoding list under the 'More...'  expander panel.  Unicode is an option and that may work for your binary files, or some other encoding may work better.  I've seen binary files with some data in single byte characters and some with multi byte characters, so one encoding may not work for all embedded strings in one binary file.  

I'm attaching a sample file (in the zip).  I think it shows the behavior you describe.  If you set the encoding selection in dnGrep to 'Auto detection (default)' a regex search for "h.t.t.p" works, but a text search for "http" does not.   If you change the encoding selection to "Unicode", then a text search for "http" does work.

[sample.zip](https://github.com/dnGrep/dnGrep/files/3026983/sample.zip)

**Comment by Hexaae** [comment]
Thank you!
Actually using: encoding = Unicode Big Endian, Text mode, seems the best combo to search for text into binary files (every char typically $00 separated).
