### ISSUE TITLE
Can only find whole word or part of word when phonetics is checked

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#335]
I have a RAR file containing the following text
metricsUUID":"b4620aed-a3e0-459d-8e94-c39180610258

When I search for metrics I get no result but if I search for metricsuuid and tick the whole word box it finds it..This is with regex box checked but it wont find it with the text box checked.

If I check the phonetic box it fins the wholeword, metricsuuid and also part of the word, metric.

I'm completely confused...any ideas please?

**Comment by harryray33** [comment]
I also searched for the same word, metrics, in a directory and it would find the word if the whole word box was checked but again if I search for a part of the word it wont find it.
The phonetic option for this other file didn't work

**Comment by doug24** [comment]
Personally, I don't use the Phonetic search for anything, I just don't find it useful.   But, I put your string in a text file, and searched for "metrics" using Regex, Text and Phonetic (not WholeWord), and all three search methods found the string.  

Is this a text file or binary file?  What is the encoding?  It's impossible to reproduce your problem without a sample file.

**Comment by harryray33** [comment]
Thanks, it's a RAR file with a .js file inside...I've been trying to attach the file but I can't seem to do it!!

**Comment by doug24** [comment]
It's probably a file type that github does not allow.  Can you put your RAR file in a zip file?

**Comment by harryray33** [comment]
[storage.rar.txt](https://github.com/dnGrep/dnGrep/files/3109561/storage.rar.txt)
Hope this works!! Please change the name to storage.rar

**Comment by harryray33** [comment]
I just tried it with plain text files and it finds whole words (in this case "annum") but not "annu"

**Comment by harryray33** [comment]
And again works with phonetic enabled....I've also been experimenting with Grepwin programme and grepwin seems to find everything each time.

**Comment by harryray33** [comment]
I uninstalled and then re-installed Dngrep and it now seems to be working....
