### ISSUE TITLE
finding file name

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#339]
I'm searching within a RAR archive, although I can find the contents of a file I can't seem to find the file where the contents are.

I'm searching for 'tester' which is in the readme.txt file...I can find tester but if I search for the file readme.txt I don't get a result.

**Comment by doug24** [comment]
dnGrep will search for filenames in directories (by name or name pattern) when you leave the 'Search for' field empty.   But searching for filenames in archives is not currently a feature.

The way this is currently implemented is that dnGrep returns the list of files it would have searched if there had been search text.  In this mode, it does not open archive files to also search the archive content list.

**Comment by harryray33** [comment]
Thanks for that and the reply regarding the Boolean operators...I find that the Boolean way is easier for simple search operations.

If I need to search for just file names I'm using another basic grep programme which has a couple of check boxes to search for either files or content...Do you also have plans to implement this in the future as well as the Boolean?

Many thanks.

**Comment by harryray33** [comment]
Just a thought but an option  (checkbox) to find words that aren't in consecutive order would be useful,

**Comment by doug24** [comment]
Added feature to search for files in archives in 2.9.189
