### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by StoyanDimitrov** [dnGrep/dnGrep#346]
The exact error states
> Index was outside the bounds of the array.

[test.zip](https://github.com/dnGrep/dnGrep/files/3376420/test.zip) contains the target file that rise the error. The encoding of the file is cp-1251 and I believe this is the key, although not all characters trigger the issue. The search term (search type Text) doesn't matter. I use "test". Last version of the app, Win10, 1803.

STR:
1. unzip the file in an empty folder,
2. point the application to search in this folder only,
3. in "Search" section of the application select "Text",
4. in search for field insert "test",
5. hit the "Search" button,
6. observe the result pane.

Edit
Is it safe to assume there is no match in the files that rise this error?

**Comment by doug24** [comment]
I took at look at this, and there is an incorrect constant value in the character set detection code.  Easy fix, but I'm going to see if I can queue up a couple other fixes for a new release.

**Comment by doug24** [comment]
Fixed in release 2.9.160
