### ISSUE TITLE
Change FileShare mode for plain text

### ISSUE THREAD

**Issue by kvknyazev** [dnGrep/dnGrep#349]
Hi! I'm trying to use dnGrep for searching in logs, some logs is still opened for writing and dnGrep can't open such files, but Far can. I suggest to try FileShare.ReadWrite mode for plain text files, probably it can help open used files.
Thanks

**Comment by doug24** [comment]
Yes, you are right.  I will add that.

**Comment by kvknyazev** [comment]
Thanks! Now i can search among used files, but can not preview them. May be add this mode to preview too?

**Comment by doug24** [comment]
Yes, I missed that, and will fix it.  
The Replace window also does not open the files already open for write, and I'm going to leave it that way to not allow replace in these files.

**Comment by doug24** [comment]
Fixed in release 2.9.163
