### ISSUE TITLE
Feature request - save search settings per folder

### ISSUE THREAD

**Issue by kvknyazev** [dnGrep/dnGrep#353]
Hello! I have two folders that i periodically search about text. First is source code, second is logs. Search options is different but permanent by every folder. It would be great if options will be saved for every folder and restored after selecting path! By options i mean all parameters, including extensions, archives, encoding. Probably, this behavior may be controlled by check control in application's Options.

**Comment by doug24** [comment]
This may not be too hard to implement.  I'm thinking about a map between the path name and a bookmark.  You could have more than one path mapped to the same bookmark.  I'm not sure about automatically associating a path with a bookmark, however.  Would the path get mapped every time a bookmark is used when the option is enabled?  Or should there be a second step to save the path to bookmark mapping?

**Comment by kvknyazev** [comment]
I like bookmark's idea, just add Encoding (may be Search in archive too) and option to automatically activate bookmark for specified folders? With capability to specify asterisk to include sub-folders like "c:\logs\*"

**Comment by doug24** [comment]
added in 2.9.215
