### ISSUE TITLE
Feature request: add a option to disable text highlighting in results panel

### ISSUE THREAD

**Issue by zhoujin7** [dnGrep/dnGrep#358]
Feature request: add a option to disable text highlighting in results panel highlighting.

I want to read the whole txt in results panel, but text highlighting distracts for reading.

**Comment by JVimes** [comment]
Would this new option really just be working around a poor design choice, i.e. the bright yellow highlight color? If so, it would be nice to fix the root problem by picking a subtler color. A new option would need to be supported thereafter.

**Comment by doug24** [comment]
added in 2.9.215
