### ISSUE TITLE
LISP highlighting

### ISSUE THREAD

**Issue by ErwinMeulman** [dnGrep/dnGrep#360]
A search a lot of (auto)LISP *.lsp files for AutoCAD, with Notepad++ I can highlight the text but a can't see a option within dnGrep.

**Comment by doug24** [comment]
Not currently supported, but, I can add a syntax definition for lisp files.

**Comment by doug24** [comment]
LISP syntax files have been added to release 2.9.174.   This should include most or all of the AutoCad LISP syntax as well.
