### ISSUE TITLE
Suggestion: allow to set 'Show result lines in Context' in the main User-interface

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#361]
#### Thanks a lot for this great and very useful tool!

I have a small suggestion:
#### it would be useful to set 'Show result lines in Context' spontaneously, directly in the main User Interface

On the Main User-interface, the Checkbox to enable / disable this feature is not needed, because we can set `0`, something like this would be enough:

`Context Lines before: ___ after: ___`

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
Two things about this request:
dnGrep's main interface is already quite busy, and I'm reluctant to add more options to it.  It would likely add another 'row' of controls to the UI, decreasing the available space for the results.

Would you expect the current set of results to dynamically refresh when you change the number of context lines?  The current implementation does not dynamically change, you must re-run the search and re-open the results.  The context lines are read and cached when a search result is expanded in the results view.  dnGrep does not cache the whole file, only matched line and context lines.  Making it dynamic would make this change more difficult.

**Comment by schittli** [comment]
Hello doug24, thanks a lot for your answer!

I think it is _not_ necessary to dynamically refresh the results when the number of context lines changes: Users probably can estimate this parameter very well before searching.

Because this setting is 'hidden' in the Options, I've set it to display context lines, but usually, I don't need it. Therefore I had the idea that it would help to easily change this search parameter.

Because you have great Tooltips, I thought the two text boxes for the two small numbers of context Lines could have space here:

`O Regex O XPath O Text O Phonetic • Context: [__] / [__]`


**Just in case you think about dynamically refresh the results:**
I think that most users work with less than 10 context lines, therefore I would probably program it that way:

1. In the _options_ the user can define how many context lines should be read into a cache
2. In the _main window_, the user can set how many lines are actually displayed in the results. If possible, dngrep refresh the results, otherwise the user has to restart the search process

I guess this would be a unique feature,
but I think it is not necessary :-)

Thanks a lot!, kind regards, Thomas

**Comment by doug24** [comment]
added in 2.9.215

**Comment by schittli** [comment]
**Thank you very much!**, I use it often and think, it's very useful.
