### ISSUE TITLE
Replace fields with textarea

### ISSUE THREAD

**Issue by saudiqbal** [dnGrep/dnGrep#362]
It would be nice to have textarea for "Search for" and "Replace with" instead of a regular one line field. Most of the time I use multiple lines of code to search and replace, this way I can see the pasted code in both fields.

**Comment by saudiqbal** [comment]
![main](https://user-images.githubusercontent.com/6971514/65075150-52c35200-d964-11e9-9297-612dc8b00dfb.jpg)

**Comment by saudiqbal** [comment]
Or an option to choose between the two. This way everyone is satisfied.

**Comment by doug24** [comment]
Isn't this the way dnGrep works currently?   Check the Multiline option, and you can paste text with newlines, or you can hit Enter when typing text.  Here is a sample from 2.9.163

![image](https://user-images.githubusercontent.com/17227248/65103584-85307780-d983-11e9-8609-e57fd0dea5f1.png)

**Comment by saudiqbal** [comment]
Oops, my bad, I just downloaded it and never knew I could do it, Thanks for clarifying.
