### ISSUE TITLE
Is it possible to specify which extension to search in?

### ISSUE THREAD

**Issue by saudiqbal** [dnGrep/dnGrep#363]
I only want search and replace operation in .html files and I don't see any option to define extensions.

**Comment by doug24** [comment]
Sure, it's right at the top:

![image](https://user-images.githubusercontent.com/17227248/65104330-ea856800-d985-11e9-8bcd-a82bcb49849c.png)

**Comment by saudiqbal** [comment]
Awesome, thanks for this great software.
