### ISSUE TITLE
Regex with Group: Highlight the group match only

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#365]
**Thank you very much for this very useful and very fast Tool!**

#### I guess this would be a cool feature:
If a user defines a group in Regex, then dnGrep just highlights the matched Group strings.

#### Example: Find all PowerShell Script *Function Names / Signatures*
A PowerShell Script Function looks like this:
```
Function Get-Item($Parameter)
{
  …
}
```

To just highlight `Get-Item($Parameter)`, we could use this Regex:
```
Function\s+(.*)
```

#### Idea for the implementation
dnGrep could use [Regex.GetGroupNames()](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.getgroupnames?view=netframework-4.8)
to detect if the User has defined Regex Groups and if he has, use the matches to highlight the found strings in all found groups.

All the best!
Kind regards,
Thomas

**Comment by doug24** [comment]
I have been looking at this issue, and I'm wondering if this would be too confusing to highlight only the match groups?  Note that when you do a replace, the whole match will be replaced, not just the match groups.  Here is your example highlighting just the group, and the resulting replace:

![image](https://user-images.githubusercontent.com/17227248/76042180-db30b180-5f08-11ea-8647-a51fb3a1e782.png)

I'm wondering if it wouldn't be better to highlight the match as is done now, but then also do a different highlight on the groups - maybe a different background, text color or overline/underline.

There is a another problem:  if the regex contains two or more adjacent match groups, then the highlight will run together and look like one match or one group. We will need some way to distinguish the first group from the second group and so on. 

Any comments?

**Comment by schittli** [comment]
Good morning @doug24 
Thank you very much for investigating this issue!, yes, I think your idea is very useful.

I have tested various online regex tools how they highlight matches and https://regex101.com/ does it very well I think. I explain some examples:
#### Ex1: https://regex101.com/r/LsTMPs/1
**(1)** For the Full Match, they use always the blue colour
**(2)** Each group gets a different colour
**(3)** This could be tricky: They colourize the Full Match, but if the text is part of a group, then the text gets the group colour
![image](https://user-images.githubusercontent.com/8282673/76068285-2d1d1a00-5f91-11ea-922e-821a27d4cde2.png)

#### Ex2: https://regex101.com/r/Oljx2i/1
**(1), (2), (3)** The highlight of the full match colour alternates in its brightness. _I don't know if that's necessary or just nice to have._
**(4), (5)** A Group Color does never change
![image](https://user-images.githubusercontent.com/8282673/76068644-cc421180-5f91-11ea-8ce7-cdb58f690d8b.png)

#### Ex3: https://regex101.com/r/ifU5Ns/1
I always find it very hard to select colours, so I have another example with many groups and colours - I think, they have a nice looking colour scheme :-)
![image](https://user-images.githubusercontent.com/8282673/76069393-1a0b4980-5f93-11ea-8935-11182b21e6bd.png)

Does this help?

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
I added this to release 2.9.226, let me know how it works for you.

Your examples were very helpful, I know I wouldn't have gotten the nested groups right without that third example.  

I didn't use the same colors, I used a set of 10 colors and recycle them if there are more than 10 capture groups (Regex101 does the same).

**Comment by schittli** [comment]
Hello Doug
**thank you very much for your work!**, 
it works perfectly fine and it looks good, too :-)

Kind regards,
Thomas
