### ISSUE TITLE
Preview Window becomes Full Size

### ISSUE THREAD

**Issue by Alan111S** [dnGrep/dnGrep#373]
Somehow my Preview Results Window has become so big that it takes over the whole application. 

The only way I can fix it is by editing the dnGrep Settings file and setting   
<item key="PreviewFileContent">False</item>

How do I get the Preview Window back to a reasonable size?

**Comment by doug24** [comment]
I assume you are running 2.9.174.
Close all your dnGrep windows.
Go to: C:\Users\_username_\AppData\Local\dnGrep
In that directory there will be one or more directories starting with 'dnGREP.exe_Url_', find the one that contains a directory named '2.9.174', and open it. It should contain a file 'user.config'
Edit the user.config file, and find the "PreviewBounds" setting.  Change the value to 
<value>100, 100, 200, 200</value> or something similar.
Save the file and close it.
Start dnGrep - can you see the Preview Window, and resize it?
Exit dnGrep and restart it - does the Preview Window return to your last size and position?

**Comment by Alan111S** [comment]
Hi Doug

That didn't work, but I renamed the file and the app created a new one, and the window is OK now

The settings that are different:-
Old file - 
            <setting name="PreviewBounds" serializeAs="String">
                <value>100,100,200,200</value>
            <setting name="MainFormExBounds" serializeAs="String">
                <value>313,133,1605,807</value>
            <setting name="PreviewDockedWidth" serializeAs="String">
                <value>1947.9788814013923</value>
Now -
            <setting name="PreviewBounds" serializeAs="String">
                <value>0,0,0,0</value>
            <setting name="MainFormExBounds" serializeAs="String">
                <value>100,100,1200,800</value>
            <setting name="PreviewDockedWidth" serializeAs="String">
                <value>360</value>

**Comment by doug24** [comment]
Oh, I misunderstood - I thought you had the preview window undocked.  So I had you change the undocked bounds, not the docked width.

Good to hear it's working now.

**Comment by doug24** [comment]
fixed in 2.9.181
