### ISSUE TITLE
Startup windows size problem

### ISSUE THREAD

**Issue by ErwinMeulman** [dnGrep/dnGrep#374]
How to fix?
![dnGREP_startup_problem](https://user-images.githubusercontent.com/22874090/67461701-448ce380-f63e-11e9-8a8a-2d5107322866.png)

**Comment by doug24** [comment]
Close all your dnGrep windows.
Go to: C:\Users_username_\AppData\Local\dnGrep
In that directory there will be one or more directories starting with 'dnGREP.exe_Url_', find the one that contains a directory named '2.9.174', and open it. It should contain a file 'user.config'
Delete or rename the user.config file
Restart dnGrep.

**Comment by doug24** [comment]
If anyone is wondering: what happened here is the preview window width is greater than or equal to the main window width.  There should be a limit on how far left or right the preview window splitter can move.

**Comment by doug24** [comment]
fixed in 2.9.181
