### ISSUE TITLE
XPATH search and remove in HTML files

### ISSUE THREAD

**Issue by Schiiba** [dnGrep/dnGrep#375]
### **Thank's for sharing this great Tool,** 

My goal is to **cleanup** a set of **HTML** files using **XPATH** patterns.
**Your tool is among the rare ones that allows the XPATH based searching and replace**.

The search stops whenever html text don't seems to be fully compliant with the tool expected syntax.

First trial : a missing \</meta\> before  the end of header (\</head\>) and search stops
Second trial :  within a <script>...</script> it stops because it found an "=" but expected a ";"

My XPATH search pattern is :  //*[@id="div_border_bottom"]/table/tbody/tr[9]
My Replace pattern is : empty ; expecting that found nodes will be removed) 
 
**So, is there a way to get XPATH searches succesfully done without checking the syntax compliance of html within the nodes/elements that are outside of the search pattern expected node ?**

A second question could be : 
Is there a way to specify multiple XPATHes in a single search field to replace them with "nothing"? 

**_Faithfully_**
André

**Comment by Schiiba** [comment]
### **_Thanks Doug  for your information_**,

 I will postpone my cleaning project !

My first (wrong) assumption was that if the Web browser generates the XPATH for selected nodes in old HTML  and is also able to find this nodes with that XPATH in a query within the browser console 
( Ex.   $x("//*[@id=\"div_border_bottom\"]/table/tbody/tr[9]"))
than  it should be possible for search and replace tools to implement a similar successfull search with the XPATH on the same html files.

I use mainly Opera browser, the underlying XPATH  library and implementation may be different from those (.NET) used in dnGREP ?

 
**_Faithfully_**
André

**Comment by doug24** [comment]
Yes, the implementation in Opera (or any other browser) will be different from .NET.  They of course have to be able to parse any HTML with much less restriction than valid XML.   dnGrep uses the .NET class XPathDocument to parse documents, and it requires valid XML.

 There is a  third party library, HTML Agility Pack, that does support XPATH queries.  Adding that option is not a small amount of work, and there is quite a backlog of enhancement requests on dnGrep right now.

**Comment by Schiiba** [comment]
This clarifies all my questions.  Also it seems to be a  marginal need to search XPATH on HTML oldies  and not worthy to spend the precious time resource in such enhancement.

### **DnGrep is already very powerfull while working on multiple files and the huge set of file types !**
### Thanks Doug  for that Great DnGREP.
