### ISSUE TITLE
dnGREP.2.9.181.x64.msi installation

### ISSUE THREAD

**Issue by TQM-Service** [dnGrep/dnGrep#379]
Basic conditions:
OS name Microsoft Windows 7 Professional
Version 6.1.7601 Service Pack 1 Build 7601
it is installed dnGrep 2.9.163.x64
during the installation of dnGREP.2.9.181.x64.msi the installation process hangs (see logfile information)
  actions: Deleting the old version incl. user profile files
reinsatllation of the new version
>> same mistake
----- LOG-File------

[logs_TQMLTOF11_20191106.txt](https://github.com/dnGrep/dnGrep/files/3814898/logs_TQMLTOF11_20191106.txt)

**Comment by rkhwaja** [comment]
I'm seeing the same error upgrading using chocolatey on windows 7

**Comment by majkinetor** [comment]
Yeah, few reports on chocolatey for Win7.

**Comment by doug24** [comment]
Should be fixed in 2.9.184, but I don't have any Windows 7, 8, 8.1, Server 2012, or Server 2012 R2 to test on.

**Comment by TQM-Service** [comment]
it works, tested on windows 7
very good work
