### ISSUE TITLE
Enhancement to tree view (delete nodes)

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#38]
_From [martin.a...@gmail.com](https://code.google.com/u/105625344035276866121/) on December 31, 2009 10:37:30_

Another suggestion:
Jedit has a similar tree view for search results, and it lets you delete
nodes from the right button menu.

This is useful when you are working through a long list of matches, since
you can delete the files and/or matches that have been dealt with, or are
not of interest.

(BTW: Happy New Year!)
Martin

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=34_

**Comment by majkinetor** [comment]
Could you support deleting with DELETE hotkey and selecting multiple nodes ? I frequently want to delete set of files that are irrelevant.
