### ISSUE TITLE
Searching in multiple directories 

### ISSUE THREAD

**Issue by ThomasAllan** [dnGrep/dnGrep#381]
I have two directories from different servers that contain similar log information. 

I would like to scan both directories for a pattern to match. This is possible in 
grepWin by using the search in string `\\192.168.1.5\Program Files (x86)\Broadbeam\BDS.4.6.0.55\LOG|\\192.168.1.6\Program Files (x86)\Broadbeam\BDS.4.6.0.55\LOG`. 

I have seen in #71:
> _From [denis.st...@gmail.com](https://code.google.com/u/104090849551033406634/) on July 02, 2010 13:37:53_
> 
> Done. Can be performed by separating folders with semicolon in the search folder text box.

But cant seem to be able to get this to work?

**Comment by doug24** [comment]
You are using a semi-colon or a comma as a list separator, right?   Like this:
`\\192.168.1.5\Program Files (x86)\Broadbeam\BDS.4.6.0.55\LOG;\\192.168.1.6\Program Files (x86)\Broadbeam\BDS.4.6.0.55\LOG`

This does work, I've tested it with both local drives and network (UNC) drives like you are using.

What, specifically does not work for you?   Is the Search button enabled (it will be disabled if the path is invalid).  Does it not find the files you expect?

**Comment by ThomasAllan** [comment]
Thanks for your help @doug24! It would help if I was doing a semi-colon instead of a colon
