### ISSUE TITLE
Endless mscorsvw.exe invocation loop during installation

### ISSUE THREAD

**Issue by brkerez** [dnGrep/dnGrep#387]
OS Name:     Microsoft Windows 10 Pro (1909)
OS Version:  10.0.18363 N/A Build 18363

Dngrep v2.9.189.0 [chocolatey](https://chocolatey.org/packages/dngrep) installation 
timed out because of endless loop of `mscorsvw.exe` invocations. It was running for almost an hour before I stopped it by killing the installer.

It does not seem as Chocolatey-specific problem as this loop seemed to be caused by the dngrep installer alone.

I do not know many details but according to Process Hacker it seems that the dngrep installer process invoked `ngen.exe` which was invoking `mscorsvw.exe` instances again and again.

Here is a screenshot from Process Hacker exactly at the moment when one instance of `mscorsvw.exe` is terminating (red one) and a new one is starting (green one).

![image](https://user-images.githubusercontent.com/313735/72662546-d19acb00-39e8-11ea-8fae-3cd8ace8922f.png)

This terminate/invoke cycle was running forever and the time between termination/new instance start was a few seconds if I remember well.

Here is a Process Hacker screenshot of Chocolatey process which invoked the dngrep installer 

![image](https://user-images.githubusercontent.com/313735/72662567-f55e1100-39e8-11ea-92f2-3f51bb871e57.png)

**Comment by JVimes** [comment]
I'm not an active contributor, but I was curious so I tried. It works on my machines, taking only seconds. All I can think of is maybe antivirus or another tool is interfering, or something is wrong with the .NET installation. You could try installing while Windows is in safe mode.

A person on an [unrelated thread](https://stackoverflow.com/questions/6469724/how-to-kill-mscorsvw-exe) talks about running `ngen.exe queue status` during their problem. I found ngen.exe under <code>C:\Windows\Microsoft.NET\Framework\v<strong>[VERSION]</strong>\\</code>. My latest version is the same as your screen shot, 4.0.30319. I do have multiple version folders, each with ngen.exe.

**Comment by doug24** [comment]
Yes, the dnGrep installer requests ngen to run on the installed assemblies, but that is not a recent change.  It's not clear what changes in this release would affect the behavior of ngen.
Have you had dnGrep installed before on this machine? If so what version?
Did you try downloading and running the installer directly?

**Comment by brkerez** [comment]
I tried it via Chocolatey today again and it worked like a charm so it was probably caused by sun eruption the first time :) I usually retry everything two times again when something does not work but I didn't yesterday and I immediately created the issue so I'm sorry for creating probably unnecessary one ;)
