### ISSUE TITLE
Arrow up/down should move text cursor up/down in multiline search/replace field instead of going through history

### ISSUE THREAD

**Issue by dg-wfk** [dnGrep/dnGrep#400]
Version 2.9.215.0

How to reproduce issue:
1) Choose in "Search" area "Regex", "Text" or "Phonetic".
2) Enable in "Search options" "Multiline".
3) Empty "Search for:" field and type "a", press {Enter} key for a new line and type "b".
4) Use {Arrow Up} key.
5) Use {Arrow Down} key.

What should happen:
4) The text cursor should move a line up and should be positioned behind the "a".
5) The text cursor should move a line down and should be positioned behind the "b".

What actually happens:
4) dnGrepd tries to load the search field entry next in history. If no newer history entry is present, nothing happens. If a newer history entry is present, the search field is filled with it.
5) dnGrepd tries to load the search field entry previous in history. If no older history entry is present, nothing happens. If an older history entry is present, the search field is filled with it.

**Comment by doug24** [comment]
I have a fix for this ready for the next release.

**Comment by doug24** [comment]
in release 2.9.226
