### ISSUE TITLE
Does dnGREP tries to open (and analyze) Files which should be ignored?

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#405]
Good evening

dnGREP reports a strange _Access is denied_ error:
![image](https://user-images.githubusercontent.com/8282673/76109988-e6a1dc80-5fdd-11ea-8670-d20e271fdd54.png)

Because **(1)** `*.TempPoint.ps*` Files should be ignored,
it is strange that dnGREP tries to **(2)** open (and probably) analyze the content of the File `Send-Mail-ADUser.TempPoint.ps1`.

I guess that my search pattern `*.TempPoint.ps*` matches this filename, therefore dnGREP should just skip the file. 

Thanks a lot, kind regards,
Thomas Schittli

**Comment by doug24** [comment]
I tried to reproduce your problem, but I cannot.  
I created a file:
`\\DiskStation\home\issue405\AD\Send-Mail-ADUser.TempPoint.ps1`
Search in folder:
`\\DiskStation\home\issue405\`
Paths to match:
`*.ps*`
Paths to ignore:
`- Archiv\*;-Archiv\*;= Archiv\*;=Archiv\*;*.TempPoint.ps*`

Run the search, and the file is not found.  
If I clear the Paths to ignore, then the file is found.

**Comment by schittli** [comment]
Thank you very much for trying to reproduce it!

You're right, the search does 'not find' the file, 
but if the File is locked, it is found and reported as `Access denied`. Really strange.

I have reproduced it this way:

#### Prepare File
File: `c:\Temp\¦\d\lockfile.txt`
Content: `hallo`

#### Test #1: File is not locked
Search in folder: `c:\Temp\¦\d\`
Paths to ignore: `*.txt`
Search for: `hallo`
Result: Perfect, the File `lockfile.txt` is ignored

#### Test #2: File is locked
1.  I use the freeware Easy File Locker on [www.xoslab.com/efl.html](https://www.xoslab.com/efl.html)
2. Now, I lock the File, so that it is visible, but not accessible:
![image](https://user-images.githubusercontent.com/8282673/77657663-e611bb80-6f75-11ea-9b04-f1911c68dd19.png)
3. Test dnGREP
Search in folder: `c:\Temp\¦\d\`
Paths to ignore: `*.txt`
Search for: `hallo`
Result: Access is denied:
![image](https://user-images.githubusercontent.com/8282673/77658752-700e5400-6f77-11ea-8cd5-56dd88380b58.png)

**Comment by doug24** [comment]
OK, I see what the problem is now:  it's because the "No binary" flag is set.  dnGrep applies all the filters in a sequence, and the 'Is Binary' test is run before the 'Paths to ignore' test, and testing if a file is binary means you have to read the file, and that fails.  I'll look at changing the filter order.

**Comment by schittli** [comment]
**Thanks a lot, Doug, for fixing it**
In my tests, it works perfectly now.
