### ISSUE TITLE
Problem with last release

### ISSUE THREAD

**Issue by kvknyazev** [dnGrep/dnGrep#407]
Hi!
I have installed recent version 2.9.226 and found some bug. I'm entering folder, then some text to find, click Search button, found some results and when i click on file name in result pane it is coping to folder name edit control. I'm searching in archived files, but with plain files it works too.
Thanks!

**Comment by doug24** [comment]
Yes, I see that - it's from the drag and drop, and the results tree is starting a drag even that drops on itself.  If you carefully click on the results tree so the mouse does not move, it doesn't happen.

I'll have a fix posted later.

**Comment by doug24** [comment]
fixed in 2.9.229

**Comment by kvknyazev** [comment]
thanks!
