### ISSUE TITLE
Beginning with 2.9.189.x64: Long initialization when starting the search some Network Drives

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#411]
Good afternoon

I have this dnGREP search:
Folder: `\\computername\Share\Dir\`
Paths to match: `*.*`
Path to ignore: `<empty>`
Search for: `e`, Text

Using this search configuration, I have noticed that `dnGREP.2.9.229.x64` has a long initialization time if it has to search for files on a network share: It displays `Searching…` for about 20 to 30 seconds until it starts reporting the 1st processed files.

I've got further findings:
- I went back until release `2.9.184.x64`. This one starts almost immediately processing files with the identical search configuration.
- Release `2.9.189.x64` is the first one with the long initialization time.
- **This is strange:** I have multiple network devices. On some network devices I have the long initialization time in dnGREP, other network devices have the usual fast start in dnGREP.
If I access the network shares with the long dnGREP initialization time by using e.g. the Windows Explorer, Total Commander or the Dir Command in the DOS box, then I always get immediately the file list. I use those network shares all day long and I have no issues, timeout or anything else.

Perhaps other users will be able to add further insights.

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
Do you have "Use .gitignore" enabled?  Try unchecking it.  When you have it enabled, it looks for and processes the .gitignore files first.

**Comment by schittli** [comment]
Thanks a lot Dough, you got it!, 
I really had `use .gitignore` turned on, if I turn it off it's fast as usual :-)
