### ISSUE TITLE
i cant fined dnGREP.exe

### ISSUE THREAD

**Issue by mohamed-soubhi** [dnGrep/dnGrep#413]
where can i find dnGREP.exe in the folders ?

**Comment by doug24** [comment]
The default installation is
C:\Program Files\dnGREP\dnGREP.exe
or 
C:\Program Files (x86)\dnGREP\dnGREP.exe

**Comment by mohamed-soubhi** [comment]
it needs admin approval for installation

**Comment by doug24** [comment]
yes, the installer runs as admin to install the shell integrations
