### ISSUE TITLE
Duplicate Bookmark

### ISSUE THREAD

**Issue by egoughnour** [dnGrep/dnGrep#415]
In the bookmarks dialog there are some useful changes to be made.
For instance it would be much better to have not only **edit** capability but also the ability to copy/clone/duplicate bookmarks within the bookmarks dialog and _then_ be able to edit the copy.

Looking at the code it seems like a simple fix.  

- Add Clone button
- In Bookmarks.xml, duplicate the `<Bookmark /> ` element of the selected bookmark index in the dialog (implemented in whatever would be the WPF equivalent of a winForms list box selection/index-based button handler. [Not sure how/if bindings are set up offhand]).

**Comment by doug24** [comment]
Yes, it won't be hard to add this.

**Comment by doug24** [comment]
Added in v2.9.248.0
