### ISSUE TITLE
Bookmark Parameters

### ISSUE THREAD

**Issue by egoughnour** [dnGrep/dnGrep#416]
Parameterized Bookmarks.

Would be helpful in that the number of bookmarks could be kept reasonably low for some use cases. It might possibly reduce configuration time spent by the user after selecting an existing bookmark.  

This would help searching when, e.g., the user has several inter-related searches to make.  
The evaluation of multiple combined constraints over a set of paths would be much faster.

On top of this the execution time for both operations, i.e.,  

1. finding the set of candidate files 
2. Searching the content candidate files

can be reduced in any case where (1) or (2) yield non-disjoint results across related searches.
Repeated evaluation of a single bookmark with multiple arguments sets is cacheable.

As for Implementation, it might require a data source (for non-manual batch processing).
This data source would provide the argument sets to be applied to the bookmark.

Other parameter input alternatives:
 
- present an additional dialog with text input fields for each parameter.
- temporarily adjust the tab order of the main UI window (similar to snippet evaluation in Visual Studio)

**Comment by doug24** [comment]
I'm having a hard time understanding this.  You want to run multiple searches and produce a single set of results?

When changing bookmark parameters you may be changing the set of files to search, or what to search for within a set of files, or both the set of file and the search terms.  Does that really give you a meaningful set of results?

Note that you can already run additional searches against the set of files found in a previous search by checking "Search in results".   

And you can search for multiple search terms in one pass by using the "Boolean operators".

**Comment by egoughnour** [comment]
It's a bit of a complicated use case, but I will try to create a pull request that illustrates the point.
