### ISSUE TITLE
Show context lines before not working

### ISSUE THREAD

**Issue by jimgust** [dnGrep/dnGrep#417]
Depending on the value I can sometimes get some before lines to appear.  It looks like the math to get the before lines are being calculated from the end of the search result and not the beginning.  This is causing an issue for multi-line searches.

![5LinesBefore-a](https://user-images.githubusercontent.com/891903/78455341-5b127e80-7663-11ea-81ad-f35e43e0209f.png)

**Comment by doug24** [comment]
Yes, I see the problem.  I'll have a fix in the next release

**Comment by jimgust** [comment]
New version works great.  Thanks!

**Comment by doug24** [comment]
sure!
