### ISSUE TITLE
Something broken down the program. Event: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by yanlinsun** [dnGrep/dnGrep#418]
I installed the latest version v2.9.236.0 (beta). I am able to click the following places on the first time I use the application.
![image](https://user-images.githubusercontent.com/12404789/78734294-042ae300-799c-11ea-8b04-1f8d5fb07e99.png)
After I do a replace, or something else, I coun't for sure, all places above will trigger this error.
![image](https://user-images.githubusercontent.com/12404789/78734377-2e7ca080-799c-11ea-8aed-6bad01b17891.png)
Even if I want to close the program by click the 'X' at right top corner. The only option to close the program is to right click it on the taskbar and choose close.

The event log is
![image](https://user-images.githubusercontent.com/12404789/78734407-4fdd8c80-799c-11ea-9469-fa98142c0966.png)

My OS is : Windows 10 Enterprise 1809 x64 Build 17763.973

**Comment by doug24** [comment]
Unfortunately the error is all in system code, so unless there is a way to reproduce the error, I don't know what to fix.  Can you check - does the dnGrep error log have any more details or a longer stack trace?  It is in %appdata%:
C:\Users\username\AppData\Roaming\dnGREP\logs\Grep_Error_Log.xml

**Comment by yanlinsun** [comment]
Here is the log 
[Grep_Error_Log.zip](https://github.com/dnGrep/dnGrep/files/4448031/Grep_Error_Log.zip)

**Comment by doug24** [comment]
Well, I can see how annoying that must be.  I wonder if it a number formatting or parsing problem.  What language / region settings are you running in Windows?

**Comment by yanlinsun** [comment]
My OS language is English. However, I set application language to Chinese. 
![image](https://user-images.githubusercontent.com/12404789/78742634-b2408800-79b0-11ea-8429-1f12efb95d88.png)
![image](https://user-images.githubusercontent.com/12404789/78742639-b8ceff80-79b0-11ea-914f-1978fc1c26ff.png)

**Comment by yanlinsun** [comment]
I tried to compile a debug version of dnGREP. I can reproduce it if I maximize the window. If I restore it back to normal size, no error.
But with the installed version, no matter what window size, the error always there.

**Comment by yanlinsun** [comment]
I think it is related to the window sizing calculation. With the debug version, once I resize manually to customized size, the error occurs, and no matter how the error persists. How can I delete the remembered window size and try the default size?

**Comment by doug24** [comment]
The window size is stored in the 'user.config' file under appdata\local\dnGrep.  There will be a generated folder name 'dnGREP.exe_Url_xxx' and then another folder named for the release version.  You can you dnGrep to find the most recent one :)

**Comment by yanlinsun** [comment]
Once I delete the user.config, both release and debug version back to normal. It is easy to reproduce by changing the window size.
Do you have the same issue or just on my machine?

**Comment by yanlinsun** [comment]
I googled the error message and found the root cause. It is an issue in WPF, not fixed yet.
[https://github.com/dotnet/wpf/issues/1269](url) 

BTW, do you know how to link these two issues cross projects?

**Comment by doug24** [comment]
I haven't had time to test this yet, so I don't know if I can reproduce it.  I have tested an over/under monitor configuration, but not recently and I can try that again.  The links on the [WPF issue](https://github.com/dotnet/wpf/issues/1269)  say it related to a Logitech mouse.  Do you have a Logitech mouse?  

There is a [work around](https://developercommunity.visualstudio.com/content/problem/167357/overflow-exception-in-windowchrome.html) - you've built a debug version, so do you want to try adding this to your build?  In dnGrep it would go in MainView.xaml.cs, and there is already an override to OnSourceInitialized, so you would add this line to the existing OnSourceInitialized override:
`    ( (HwndSource)PresentationSource.FromVisual( this ) ).AddHook( HookProc );`
and then copy in the HookProc.

**Comment by doug24** [comment]
Added the fix to all dnGrep windows in v2.9.248.0
