### ISSUE TITLE
Nice to have: Use standard regex annotation and preview replacement results

### ISSUE THREAD

**Issue by yanlinsun** [dnGrep/dnGrep#419]
I think the dnGREP is a great application. But it will be nice if it can use the common regular expression annotation and preview the replacement results for multiple files in one place.

For example, 
1. use \1 instead of $1 in the following screenshot. As '\1' is the standard regular expression for the first match group.
2. Preview the replace result for multiple files
![image](https://user-images.githubusercontent.com/12404789/78735067-f5453000-799d-11ea-8ffb-046975b92339.png)

**Comment by doug24** [comment]
The $1 isn't something dnGrep does, that's the pattern replacement token Microsoft used in the .net regular expression engine.  I don't know why they did that.  They do use \1 when it part of the regular expression as in [this example](https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions#substituting-the-last-captured-group).

But I can try adding code to convert backslash token to a $ token internally when doing replacements.

Preview replace:  yes I agree it would be nice, but it would be a lot of work.   It's not high my to-do list right now.

**Comment by doug24** [comment]
If you want to verify that your replacement pattern is going to do what you want, you can run and test it interactively in the Test window.

**Comment by yanlinsun** [comment]
I see where the $1 came from. It is the Microsoft way. If you can support the \1 syntax as well is much better. 

I know the test window can try the replacement. But I need to copy the file content into the sample text box, then run it. I am lazy, it would be nice if it can automatically load the content of the first search result file as the sample text.

Another place is here. When I hit the 'Replace' button from the search result this screen comes up.
![image](https://user-images.githubusercontent.com/12404789/78742189-6fca7b80-79af-11ea-882b-d7b010e4b7bf.png)
If I hit the 'Replace' button, only the colour changed from red to green. I didn't see any changes. However, the dnGREP do does the correct job. Just the screen, I thought the dnGREP does nothing.
![image](https://user-images.githubusercontent.com/12404789/78742252-9dafc000-79af-11ea-9852-6061c4ca6c28.png)
I strongly recommend showing the replaced string in the second picture. It follows what-i-see-what-i-get principle.

Cheers,
Yanlin

**Comment by doug24** [comment]
I have looked at both these requests and decided that I am not not going to implement them.

About mapping the \1 to $1:  yes, this can be done, but I'm concerned about the side effects and being able to escape the parameters when someone wants to include the character sequence of \1 in the replace test.  There are other 'non-standard' in Microsoft's .NET regular expressions, and I don't want to start down the road of trying to make it work just like other regular expression engines.

The preview replace:  the replace code in dnGrep is designed to operate on entire files, streaming the modified output as is reads in the input.  So to preview the actual changes would require either re-writing the replace code, or reload the file in the preview window after every user action.  Having different replace code for the preview window is an invitation for bugs and not an option.   The replace widow is a relatively recent change in dnGrep to allow applying the change to selected files or selected matches within a file. It was never intended to be a text editor.
