### ISSUE TITLE
Feature: preview for big files

### ISSUE THREAD

**Issue by mokujin** [dnGrep/dnGrep#426]
Right now it seems that dnGrep collapses when trying to load big files entirely to memory. It would be nice if it could load only parts of the file and dynamically fetch more content as you scroll

**Comment by doug24** [comment]
When you say 'preview' do you mean the secondary whole file preview window, and not dnGrep's search results panel?

What size file are you trying to load?  
Are there newlines in the file, or is it all one long line?
How many search matches are there in the file?

**Comment by doug24** [comment]
Also, what is the file type/file extension?

In testing I've been able to load a 225MB text file and a 40MB xml file with over 1 million lines.

**Comment by mokujin** [comment]
yes, I'm talking about secondary side preview window. I'm having problems mainly with binary files that are output of a compiler (*.a, *.so and others). It hangs noticeably with only 40mb files. Probably no line breaks is the reason. Also what is interesting, that it hangs for a minute, and only after it is back to normal, I get a warning message that file is too long for preview. (While I still don't get the preview, what is it doing then? :) ). While search results inline preview works perfectly, maybe there is a way to load only surroundings to a larger preview window? Or at least prevent hangs. Some of them last forever and happen because I accidentally select search result in the left panel.

**Comment by doug24** [comment]
I don't have any large .a or .so files, but I pulled a couple of small ones out of the Corretto rpm.  They open quickly.  The tests for large or binary files are pretty fast - large is just getting the file metadata and binary reads the first 1k bytes of the file.

Oh wait, are these files in an archive like a tarball or rpm?  If so, that would be the slow part before you get the 'binary or too large' warning - the file is being extracted from the archive to a temp directory.  It would be better to give the user the chance to skip the file preview before extracting it from the archive.

**Comment by mokujin** [comment]
well, not only archives. While *.a files technically are archives, I experience delays with some of the non-archive binary files. I can't provide you files I'm testing this on (however I will be looking further for alternatives), so I will try to debug them some time on the next week. Hopefully I could pin-point the bottleneck. Will get back to this thread as soon as I find something. Thanks for looking into this :)

**Comment by mokujin** [comment]
K, I'm back with the patch for this problem. The majority of search sources are gonna be seek-able streams, so just taking advantage of this. Are there cases when you cant do seek? If not, maybe it is reasonable to get rid of sequential search code path.
