### ISSUE TITLE
Winget

### ISSUE THREAD

**Issue by Sa1Gur** [dnGrep/dnGrep#438]
Hi, thank you for the great tool!
I have added dnGrep to the widget repository. So, if you think it's a good way to distribute your app - you can mention it in installation guidelines.

**Comment by doug24** [comment]
Thanks!  Do you plan to keep the manifest up to date with the latest release?

**Comment by Sa1Gur** [comment]
Yes, I do.
I noticed that new version released, so I will shortly update manifest. It could take some time to pass SmartScreen check.

**Comment by Sa1Gur** [comment]
dnGrep updated to the latest version (v2.9.263.0) in the widget repository
