### ISSUE TITLE
"Path to match" is wrong: "Pattern to match" correct; need Option to exclude search in path

### ISSUE THREAD

**Issue by clsven** [dnGrep/dnGrep#441]
There is an entry field "Paths to match":

A pattern entered there (e.g.*.pdf) is matched not only against paths but against filenames too.
So I suggest a rename of the entry field to "Patterns to match"

Furthermore I miss an option to exclude search in paths.
When entered a pattern it should be searched in filenames ONLY.

Furthermore it does not become clear how I can concatenated two patterns with AND or OR

By the Way: If I enter e.g. in "Paths to match" *.pdf *.txt   (with blank inside) and start a search then this search cannot be cancelled. It runs and runs and runs....->Bug?

**Comment by doug24** [comment]
> A pattern entered there (e.g.*.pdf) is matched not only against paths but against filenames too.
> So I suggest a rename of the entry field to "Patterns to match"

Yes, that's probably more accurate.  I think you will find the pattern is only matched against filenames (unless I'm missing some trick).

> Furthermore I miss an option to exclude search in paths.

If you want to exclude either directory names or file names, you can use the "Paths to ignore" field.  Unlike the "Paths to match", this will exclude either files or directories.   For example, if you are searching a directory tree, then `*test\*` will skip all test directories.  If you want to search all files except PDF files, then you can set "Paths to match" to `*.*` or just `*` and then set "Paths to ignore" to `*.pdf`

> When entered a pattern it should be searched in filenames ONLY.

I think that is way it is working now.  However, if you do want to filter sub directories, you can add patterns to the "Folder" field, or concatenate multiple directories in that field.  See [notes here](https://github.com/dnGrep/dnGrep/wiki/Search-Window).  And you can set a max depth of sub directories in the filters section.

> Furthermore it does not become clear how I can concatenated two patterns with AND or OR

You can search for multiple patterns by separating them with a comma or semicolon, such as `*.txt;*.xml;*.htm*`
There isn't any way to do and AND.  I'm not sure what you would be trying to do there.

> By the Way: If I enter e.g. in "Paths to match" *.pdf *.txt (with blank inside) and start a search then this search cannot be cancelled. It runs and runs and runs....->Bug?

I haven't been able to reproduce this.  When I try this it returns very quickly with no results.  That isn't a pattern that I think the application should try to handle.
