### ISSUE TITLE
cmdline parameters possible?

### ISSUE THREAD

**Issue by clsven** [dnGrep/dnGrep#442]
Can I call dnGREP with cmdline parameters (and immediate start) .e.g like

dnGREP.exe -folders "D:\" -pathtomatch "*.pdf" -searchfor "foobar"

If not: Can this be implemented?

**Comment by doug24** [comment]
Currently dnGrep takes just one or two command line arguments. The first is the value for the "Folder" field, and the second is the value for the "Search for" field.  If the second argument is included, it also sets type of search to "Regex".

Yes, it can be changed to add argument keys and more arguments.

**Comment by doug24** [comment]
Here's my plan for command line arguments:  Support the existing arguments as-is for backward compatibility.  Add new arguments with flags to set more properties.  I don't intended to add command line arguments for all the dnGrep properties.  

**Questions for anyone interested in this feature:  
Are there any properties you would like to see added that are not included below?  
Any other suggestions for changes?**

Usage:

dnGrep [arguments]
Using any combination of arguments from the list below.
Example:
dnGrep /f "C:\Program Files\dnGrep" /pm *.txt;*.xml /s t\w*t /st Regex

dnGrep [folderPath] [searchFor]
One or two arguments without flags: the first argument is the folder to search, the second the regular expression to search for.
Example:
dnGrep "C:\Program Files\dnGrep" t\w*t

Any arguments not specified will default to the last saved user settings.

Arguments:

/f [folderPath]
-f [folderPath]
-folder [folderPath]
    Sets the folder path to search.  May be a comma or semi-colon separated list of folder paths.

/pm [pattern]
-pm [pattern]
-pathToMatch [pattern]
    Sets the file name pattern to match files in the search path. May be a comma or semi-colon separated list of patterns.

/pi [pattern]
-pi [pattern]
-pathToIgnore [pattern]
    Sets the file or directory name pattern to exclude files or folders in the search path. May be a comma or semi-colon separated list of patterns.

/pt [type]
-pt [type]
-patternType [type]
    Sets the type of match and ignore pattern - must be one of: Asterisk, Regex, or Everything (if the Everything search tool is installed).

/s [searchFor]
-s [searchFor]
-searchFor [searchFor]
    Sets the pattern or text to search for within the set of files.  When this argument is set, the search will be run automatically.

/st [type]
-st [type]
-searchType [type]
    Sets the type of search - must be one of: PlainText, Regex, XPath, or Soundex.

/cs [True/False]
-cs [True/False]
-caseSensitive [True/False]
    Sets case sensitive search flag - True or False.

/ww [True/False]
-ww [True/False]
-wholeWord [True/False]
    Sets the whole word search flag - True or False.

/ml [True/False]
-ml [True/False]
-multiline [True/False]
    Sets the multiline search flag - True or False.

/dn [True/False]
-dn [True/False]
-dotAsNewline [True/False]
    Sets the dot as newline search flag - True or False.

/bo [True/False]
-bo [True/False]
-booleanOperators [True/False]
    Sets the Boolean operators search flag - True or False.

**Comment by doug24** [comment]
Added in v2.9.270

**Comment by vatterspun** [comment]
I was working on something 6 months ago that would have been perfect for the functionality you're putting together here, so I would have had a lot more to say on the topic.  I'll probably come back around to this in the months ahead, but just wanted to say thanks not just for the request, the added functionality, and the range of options.  I know this could be summarized with 👍 for everyone, but this is VERY helpful for better search functionality on Windows.  

I expect I'll be setting up many different batch files for a host of frequent search functions, hopefully will follow up with some additional bug reports, testing notes, and suggestions.
