### ISSUE TITLE
Rename of filenames in result list not possible

### ISSUE THREAD

**Issue by clsven** [dnGrep/dnGrep#443]
Occasionally I don't want to search for patterns inside files but for filenames containing a certain pattern.

In the resulting filelist I want to rename sometimes a certain file.

Slowly double clicking (like in WinExplorer) on such a file does not offer me to rename it.

Even the files context menu does NOT show a "rename filename"

Can this be added?

Thank you
Claudia

**Comment by doug24** [comment]
There was a request (#114 ) to search and replace filenames.  It had both positive and negative comments.  I never could figure out the case for replacing multiple filenames, but changing them one at time does make more sense.  On the other hand, making dnGrep a general-purpose file manager has never been the goal.

I'm not going to commit to doing this, I need to do some research on the implications to the application:  the file name is key to the search results and the data preview.  Changing a file name will have a lot of effects on the current search results, and I'll have to see if name can be updated internally as well as in the file system.

**Comment by doug24** [comment]
Added file rename in 2.9.277
