### ISSUE TITLE
Switch to follow symbolic links on Win10

### ISSUE THREAD

**Issue by mrsean2k** [dnGrep/dnGrep#445]
I couldn't find a way to force dnGrep to follow symbolic links on WIN10/NTFS

is this not supported, or am I just failing to spot the option?

**Comment by doug24** [comment]
Currently it's not supported, but I think it should be.  Looking at the history, this probably changed a couple years ago and I can't remember if I excluded them for some reason or if it was just an oversight.  I can add an option to enable following symbolic links.  I think I'll leave it disabled by default, but you will be able to enable it and it will be saved in the options.

**Comment by doug24** [comment]
Fixed in v2.9.270

**Comment by mrsean2k** [comment]
Thanks - I didn't even have time to thank you for acknowledging the request before you added it - much appreciated.
