### ISSUE TITLE
Feature Request: Include Capture Group Data in .csv Save/Export

### ISSUE THREAD

**Issue by diVineProportion** [dnGrep/dnGrep#448]

**Comment by doug24** [comment]
What are you thinking this would look like?  The CSV export has a record for each line with a match, showing the file name, line number and line text.  We could add another column with the match text, and capture group text.  Are you looking for just the text or the start/end positions in the line?   Keep in mind that there can be multiple (or many) matches per line, and there can be multiple capture groups in each match.  And there probably will be a different number of matches and capture groups on each record in the CSV data.

**Comment by doug24** [comment]
Reopen if you can provide more information.
