### ISSUE TITLE
Unable to search for a specific file

### ISSUE THREAD

**Issue by ooker777** [dnGrep/dnGrep#449]
I am new to this program. I just do a simple search `\d` in a folder that containing the file below, but it can only show up the other files, not this one. I wonder why is that?

[So tay kỹ năng Tình Nguyện Viên.pdf](https://github.com/dnGrep/dnGrep/files/5293991/So.tay.k.nang.Tinh.Nguy.n.Vien.pdf)

**Comment by doug24** [comment]
I was able to successfully find and search for text in this file.   Maybe there are some file filter settings that are excluding the file?  If you leave the "Search for:" field empty, and run the search, is the file found?  If you can find the file this way, then it probably isn't getting a successful match within the file.   For PDF documents, the PDF is first converted to plain text and then the plain text file is searched by dnGrep.  It could be an encoding problem either converting the PDF to text or determining the encoding of the text file.

**Comment by ooker777** [comment]
yeah, leaving the `Search for:` field empty I see the file. So since it can be the encoding problem, what can I do next?

**Comment by doug24** [comment]
Using the default encoding settings in v2.9.270 works for me., but I'm not trying to search with the Vietnamese characters.

First, I would suggest looking at the plain text file created from the PDF to see if that looks correct.  First run a search that will include the PDF file.  During the search dnGrep will call the PdfToText tool and write the temporary file to your temp directory:
C:\Users\<username>\AppData\Local\Temp\~dnGREP-Temp\dnGREP-PDF\So.tay.k.nang.Tinh.Nguy.n.Vien.txt   Open the file with a text editor - I suggest using NotePad++, but NotePad on Windows 10 should work too.  

If that file does not look correct, you can change the PdfToText output encoding in the Options dialog as shown [here](https://github.com/dnGrep/dnGrep/wiki/Archive-and-Plugin-Options).  Try changing the PdfToText command line options to just "-layout" so it will use the default encoding on your version of Windows.

You can also set the encoding used to read the file with the encoding selector in the "More..." section of the main filters panel.  If the auto detect encoding isn't working, try choosing "Vietnamese (Windows)" or "Unicode (UTF-8)" from the selector.

**Comment by ooker777** [comment]
The txt output looks correct. It seems that because the file title is in Vietnamese so dnGrep cannot find it. I copy to a new file with ASCII characters only and it works. Thanks for your support
