### ISSUE TITLE
whole word search don't detect "=" as separator

### ISSUE THREAD

**Issue by ruedi-gallati** [dnGrep/dnGrep#456]
if a word is surrounded with a leading or trailing "=", whole word serch will not detected
exampel whole word search for "RudiRatlos" will not match "=RudiRatlos="

**Comment by doug24** [comment]
I can't think of any reason why not, but '=' wasn't set as a boundary character for plain text searches (it's been that way for 10 years now).   I will add it in the next release.  In the meantime, you can use the regex search (just keep the same search text), and that will work.

**Comment by doug24** [comment]
fixed in 2.9.282
