### ISSUE TITLE
Configure file extension to use existing syntax highlighting

### ISSUE THREAD

**Issue by rekna1** [dnGrep/dnGrep#461]
Currently typescript files are not highlighted, but c# or javascript hightlighting pretty much does the job and it can be selected in the preview window. It would be nice if I could store my choice for future searches. Could add a button (store as default for this file extension) next to language dropdown  maybe ?

**Comment by doug24** [comment]
I can easily add a typescript association, and will do so in the next release.  
I'm not sure about adding user options: I don't really want to add more controls to the main UI, and I think this is the first request to add an association.

**Comment by rekna1** [comment]
Oké,  and what if you allowed us to manually add some associations inside the (or a) config file ? 
E.g. just now I was searching some MVC views (.cshtml) which should always be formatted as html.

**Comment by JVimes** [comment]
It sounds like the file extension language associations just aren't correct for certain types right now. Why make it user configurable when it could be fixed for everyone in the app? Assuming I correctly understood.

**Comment by rekna1** [comment]
So you want us to register an issue everytime we want another filetype to be supported by syntax coloring? I am ok with that...

**Comment by JVimes** [comment]
Yes. Otherwise, for example, every .cshtml user has to perform the same configuration, and do it on all their devices (desktop, laptop, work computer).

I'm just talking about "real" file types (not ones the user makes up). And I'm not talking about languages that dnGrep doesn't know how to highlight. The frequency of these issues should decrease as more types are supported.

**Comment by doug24** [comment]
I agree with JV, there just hasn't been any requests to add more associations.  So post them here, and I'll update them.  I'll probably do another release in the next few weeks.

**Comment by doug24** [comment]
Added new file associations and syntax in version [2.9.291](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.291.0)
