### ISSUE TITLE
Exporting Results to HTML page

### ISSUE THREAD

**Issue by piranah** [dnGrep/dnGrep#462]
Can the feature for **exporting** the results to an HTML page with clickable links, to open the files in 'Results' page be added ?  Also to to be able to write a script to action this via commandline in Windows that I can trigger this script either via python v3 or other scripting languages ?

**Comment by doug24** [comment]
Help me understand what you are trying to do:  
You want a web page that has the contents of the dnGrep results tree, with all nodes expanded?
You want the file name to be clickable so the file will also open in your browser window?

The match locations won't be useful:  I don't know of a way to have a link position to a location in a random file format.
The browser is going to determine the default handling of the file: I don't know of a way to create a link that would open the file in the associated application or editor.

**Comment by JVimes** [comment]
There are already command-line grep tools for automation and generating HTML reports. I think that task should be outside the scope of dnGrep.

**Comment by piranah** [comment]
Hi Doug P,

The reason for the request is to speed up the exporting of results via the
commandline into a structured format as discussed below.

   1. *Problem: *Having multiple repositories of files like: PDF, txt, rtf,
   csv, mobi, azw3 etc ... and been able to choose exactly what file type to
   target for the search item can be a daunting task and literally takes hours
   to do it manually by hand. This is what I am doing, but the results is
   displayed in the GUI, ok for single results use and view: Your app dnGrep
   does this automatically by setting a few parameters and then clicking
   'Search' from the GUI, which in my case is very slow to plough through gigs
   of data, literally takes days to generate a report
   - *Solution *By running dnGrep from the commandline and by executing the
      app by a script like python or from within a Delphi or C#.net app, speeds
      up ploughing through tons of data in mere seconds...(would really love it
      !). Would need more parameters like not needing to show the GUI
to increase
      performance and to run quietly in the background, especially when people
      are looking at your screen, *need some discretion here like a
      'discrete' parameter through the commandline ...*
   2. *Problem:* Having to open up the dnGrep app( which I can
   guarantee you a LOT of researchers like myself don't always find the time
   to do) impedes workflow and makes collecting results very slow and tedious
   and very difficult to process and analyze. the dnGrep is by far the fastest
   app I have come across *and MANY KUDOS TO THE TEAM CREATING THIS APP,
   HATS OFF TO ALL THOSE CREATING AND TESTING!!!!*
      - *Solution*: *Outputting the results in a structured format* (csv,
      html [obviously generated in high speed by running in the background not
      needing to show the GUI to preserve resources) in different columns like:
      FileName, FolderPath, FileType, NumberOfMatches, OnNumberOfLines. This
      exported results gives me the ability to IMPORT the csv file into a table
      of my choice, thus giving me the ability to tabelize the results and do
      better analysis of word/item occurrence, based on the data in the columns.

Should you decide to incorporate a solution for bullet point 2, this will
seen as a VERY welcoming feature, and commercialize this as an extra
feature, I will certainly buy the complete product as do many others I
believe will take advantage of this option. I have used many free and
commercial keyword search apps on the net and by far is dnGrep the fastest
in keyword searches. What's missing is the 'Report' generator (exported
results into a csv file).

I am looking forward to hearing from you.

Regards,
Jeanie Marcelle

**Comment by doug24** [comment]
You do know that dnGrep has three report formats already, including a CSV report? The are under the `>>` button - Save Results.   There isn't a command line argument to automatically create the report, but I will look into that (not sure if that will be easy or not).   

I'll also look a another command line argument to exit the application at the completion of the search or report.  I really can't make it run without the main window given the design of the program, it just was never intended to be a command line tool.  I'm pretty reluctant to make an option to hide the main window because that could leave you with apps running with no way to stop them other than through task manager.

I don't know of any way to commercialize features. I'm doing this on my own time for no compensation, and there's only so much time I'm willing to invest in the project.

**Comment by piranah** [comment]
Doug P,

Thank you for the feedback and I really appreciate it you taking the time
to respond.

The results window in the dnGrep app already has the answers to the
'Report' feature. *Take that inputs that and reform that into an export
function for the csv output, when the >>** button - Save Results*, is used.

Again, thanks Doug.

Regards,
Jeanie Marcelle

**Comment by JVimes** [comment]
Doug, I forgot we had export. :) I think this button is a bit cryptic:

![image](https://user-images.githubusercontent.com/6148201/102693970-5551ce80-41db-11eb-8c9b-7fc4d2c2740d.png)

Double angle brackets usually indicate direction, like in [ordered multi-select](https://i.stack.imgur.com/Sict6.png) controls.

It might be more intuitive if it just said "More", or was an icon like this (from [here](https://github.com/MahApps/MahApps.Metro.IconPacks)):

![image](https://user-images.githubusercontent.com/6148201/102694024-aa8de000-41db-11eb-9036-c3f7dd9d26da.png)

**Comment by piranah** [comment]
Mucking Afazing !

Exactly what I was looking for. Could you add this ' **>> - Save Results - CSV Results**' to the commandline as a parameter that will take an input for the filename to be used?

Reg,
JM

**Comment by doug24** [comment]
Added new command line arguments in version [2.9.291](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.291.0), and changed the cryptic `>>` button.

**Comment by piranah** [comment]
Awesome, thanks!
