### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by StoyanDimitrov** [dnGrep/dnGrep#467]
I'm using the "portable" version. After the update to the latest (2.9.291.0) after the second start the program shows the following
<details><summary>error</summary><pre>
---------------------------
Error
---------------------------
Something broke down in the program. See event log for details.
---------------------------
OK   
---------------------------
</pre></details>

I can successfully reproduce it by deleting the settings file. After the first start of the program without settings file the text "dnGREP" between the application icon in the topmost left corner and the `Search in` label is microscopic but the application starts. Closing the program, without any changes to the settings or whatsoever, and opening it again result in the error above. [Attached](https://github.com/dnGrep/dnGrep/files/5754978/dnGREP-logs-and-settings.zip) are log file and both settings files from after the first run and after the second run.

Fiddling with `%appdata%\dnGrep` folder does not change the behaviour. Copying the `Sunset.xaml` to the program folder does not remove the log entry.

The OS is Win7x64

Edit: Even installed the program behaves like that.

**Comment by doug24** [comment]
Thank-you for the detailed report and files.  As a temporary fix, did you try editing the dnGrep.settings.dat file and change the PreviewDockedWidth to a positive number, say 200?

I see the problem with the Sunset theme file, and will fix that.  

I'm not sure what is causing the other problem with the font size and width of the preview window, but I'm guessing something isn't defined in Windows 7, but unfortunately I don't have any way to test on Windows 7.  It's also not clear why the changes in this version would affect that behavior.  I can add some fallback values and prevent the PreviewDockedWidth from going negative.

Just wondering - do you have Visual Studio installed and do a build if I push a branch with some changes?

**Comment by doug24** [comment]
Looking further - I do see the problem with the font size on initial startup.

**Comment by mduran63** [comment]
I have the same error with the window size.
I uninstalled the app and now every time I try to install it again, it shows me the error, the installation hangs and doesn't finish.
what can I do?

The error that I capture in the log is the following:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="dnGREP" /> 
  <EventID Qualifiers="0">0</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-12-31T12:43:57.3994779Z" /> 
  <EventRecordID>25128</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Nebadom-MSI</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>[dnGREP.WPF.App] Unhandled exception caught System.ArgumentException: Width y Height no pueden ser negativos. en System.Windows.Rect..ctor(Double x, Double y, Double width, Double height) en DockFloat.Extensions.IsOnScreen(Rect windowBounds) en dnGREP.WPF.MainForm.<>c__DisplayClass3_0.<.ctor>b__0(Object s, RoutedEventArgs e) en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) en System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent) en System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root) en MS.Internal.LoadedOrUnloadedOperation.DoWork() en System.Windows.Media.MediaContext.FireLoadedPendingCallbacks() en System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() en System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget) en System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget) en System.Windows.Interop.HwndTarget.OnResize() en System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam) en System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</Data> 
  </EventData>
  </Event>

**Comment by rzw** [comment]
With my install it is only one item in the settings file that causes the problem:
  <item key="MainWindowBounds">100;100;1936;1056</item>

Delete the line or the values and dnGREP starts up normal.

@mduran63: uninstalling probably left the settings file. Delete and it should work.

Workaround: Delete the line or the values and make the settings file read-only. Of course changed settings aren't saved upon exit. But at least the program starts up

**Comment by doug24** [comment]
I put a number of fixes in [v.2.9.299](https://github.com/dnGrep/dnGrep/releases/tag/v2.9.299.0).   I tested both update and clean installs on Windows 10, but can't test on Windows 7, so hopefully it will work there, too.

**Comment by rzw** [comment]
@doug24
Thanks and Happy 2021

**Comment by StoyanDimitrov** [comment]
> Just wondering - do you have Visual Studio installed and do a build if I push a branch with some changes?

Unfortunately, no.

I'm very grateful to you for the very fast actions! The program now doesn't persist the window size now but others had mentioned that already. I guess you can't do much about that without some kind of developer information. At least I can access my folders and search history. Which is the most important for now. Closing as there are no errors any more.
