### ISSUE TITLE
Preview pane open at first run

### ISSUE THREAD

**Issue by StoyanDimitrov** [dnGrep/dnGrep#470]
It would be wise to be closed at first as it was until recently.

**Comment by doug24** [comment]
Is the preview window open/closed setting not getting saved/restored?   You mentioned in the other issue that the window size and position isn't getting restored.  Are there any other settings that aren't getting saved or restored?

It would be interesting to see the difference in the settings file after you make some changes in the application.  My guess is the settings do get saved, but for some reason don't get restored on Windows 7.

**Comment by StoyanDimitrov** [comment]
It is the first run I'm referring to so the settings file does not exists at this point.

**Comment by StoyanDimitrov** [comment]
> You mentioned in the other issue that the window size and position isn't getting restored.

That's correct. They are stored correctly but are not restored correctly i.e. the window position, width/height does not respond to the numbers from the XML file. Actually they reset to some default/fallback values: `<item key="MainWindowBounds">0;0;500;485</item>` after every restart.

> Are there any other settings that aren't getting saved or restored?

As I implied in the previous answer the settings seems to be saved correctly.

> My guess is the settings do get saved, but for some reason don't get restored on Windows 7.

That's correct. It is not an issue of corrupted or otherwise damaged settings but the restoration of the some coordinates related to window geometries go wrong, namely `MainWindowBounds` and `PreviewDockedWidth` settings.

**Comment by doug24** [comment]
OK, thanks.  I intentionally changed the default value for "Preview file" to true.  My thinking is that this will mostly apply to new users installing dnGrep for the first time, and makes the feature obvious.  Anyone who has run the app before and has a settings file, and it will be set to their preference of shown or hidden.

**Comment by StoyanDimitrov** [comment]
Oh, let it be, then.
