### ISSUE TITLE
Feature Request: Ability to use replace on .epub files

### ISSUE THREAD

**Issue by Anangaya** [dnGrep/dnGrep#474]
Right now I have to use calibre's editor on each .epub one by one to make a text replacement in it. This is quite tedious because I have a large amount of .epubs that requires the said cleaning. Also calibre's editor is slow. 

Right now dnGrep can only find the matches,  it can't make the necessary replacements. Which is probably because it doesn't attempt to make any change to the archives.

It would be great if dnGrep gives support to handling .epub text replacement. Maybe by making backup of the .epubs first, then uncompressing the .epubs, making the changes and saving them as .epub. Like how PowerGREP makes changes to archives. (I did try to do the same thing with PowerGREP demo, but I couldn't get it to work, the replacements were not implemented!)

**Comment by doug24** [comment]
Right, dnGrep does not have any feature to update files in archives.  Maybe you could manually unzip them, do the replace and zip them back up?  You could probably script the unzip and zip using 7zip.

I don't have time to work on this, so I won't be implementing it - anyone else?

**Comment by JVimes** [comment]
Isn't .epub usually considered an export format, and the original document is the native format of an editor like Word, Scrivener, etc.? Just trying to understand the extend of the use case.

**Comment by doug24** [comment]
[epub](https://en.wikipedia.org/wiki/EPUB) is a zip file of html pages, css, images, and svg.   The zip has a defined directory layout, and some required metadata files.

**Comment by JVimes** [comment]
I still think it's considered an "export format" by most people, but I could be wrong.

**Comment by Anangaya** [comment]
I did manage to accomplish this task using PowerGREP demo, but that obviously wouldn't be a longtime solution. So I would look forward to this feature being available in dnGrep. Maybe I should automate the compressing and decompressing part using 7zip after all.
