### ISSUE TITLE
Question or feature request : keyboard shortcut next/previous match

### ISSUE THREAD

**Issue by rekna1** [dnGrep/dnGrep#476]
Is there a shortcut (or can you add id) to jump to next/previous result , showing the highlighted result in the preview window.
In case of multiple occurrences in the same file, it would jump to each occurrence, when there are non left in the current file, jumps to first occurrence of next file.

**Comment by doug24** [comment]
It doesn't exist now, but sound like a good feature to have.

**Comment by doug24** [comment]
Added in release v2.9.319.  This turned out to be much more difficult than I thought it would be because of the way the nodes in the results tree are managed.

**Comment by rekna1** [comment]
Greatly appreciate the effort AND for the fast response ! It's working great.
