### ISSUE TITLE
Feature request: group capture on "Paths do match" and use them in "Search for" and/or "Replace with" fields

### ISSUE THREAD

**Issue by smfukaya** [dnGrep/dnGrep#477]
I was wondering if it would be possible to group capture (perhaps named) the "paths to match" field and use them to search inside the matching files and/or replace the matching contents.

**Comment by doug24** [comment]
I don't know if I understand this.   You want to take the value from a capture group in a regular expression in the "paths to match" field, and use that value in the search field?   So every file that gets matched could have a different search expression? 

Or for replace, use the captured value as the replacement text - so every file could have a different replace text?

I'm inclined to say no.  I think that would be difficult and error prone to implement.  (and I think very confusing to use)

**Comment by smfukaya** [comment]
That's it. It's very specific. I'd like to find the position inside files that matches part of their names (say a date or a timestamp for instance). I do agree that it could be very confusing to use it though.

**Comment by doug24** [comment]
I added this in release v2.9.319, but only for search and not for replace.  I hope it doesn't generate a bunch of bug reports now :) There are a few simple examples in the release notes.

**Comment by smfukaya** [comment]
Thank you, @doug24!!! You're amazing! \o/ \o/ \o/ Searching is enough for me ;) Replacing would be a surplus.

**Comment by smfukaya** [comment]
Hi @doug24,

I tested the v2.9.319 and it seems that the "Paths to match" with Regex isn't working. Please check the attached video.

https://user-images.githubusercontent.com/29984055/108751132-9ee2d080-7520-11eb-8f8e-c4c2c709e6b8.mp4

I have a file named "C:\temp\protoc01_2102192038.TXT". Using "asterisk pattern" dnGrep can find it with "protoc01_210219*.txt" (without quotes) in "Patterns to match" field. But, if I change the pattern to "protoc01_.+" and  "Regex" I get no results.

Best!
Sergio

**Comment by doug24** [comment]
I created a test file with the same name, and did the same regex search, and it works here (bottom image).  I don't see anything obvious different, other than running a different locale, but I don't think that should be an issue.   

But could it be something in the way the regex is evaluated?  Does this regex produce a match if you try it in the Test dialog?

What happens if you leave the "Search for" box empty?  It should list all the files that match the file filters -- show the list of files that would be searched if there had been a search pattern.   


![image](https://user-images.githubusercontent.com/17227248/108766979-a8f9d480-750a-11eb-8461-c9adac5dda2c.png)


![image](https://user-images.githubusercontent.com/17227248/108765780-1442a700-7509-11eb-8cc8-7387224e587a.png)

**Comment by smfukaya** [comment]
Hi @doug24!

Thanks to ur image I realized that I missed the last backslash in the "Search in folder" path. That's why "Paths to match" with a value of `protoc01_.+` wasn't matching anything. BTW, `.*protoc01_.+` matches when one doesn't use the last backslash.

I'm able to list the file (I moved it to a subfolder just to get the results faster).
![2021-02-23_09-58-18-dnGrep v2 9 319 0 - using the last backslash in Search in Folder](https://user-images.githubusercontent.com/29984055/108847124-10bd2780-75be-11eb-82cc-a391a7a4959c.png)

But now I'm struggling with the new "Capture group search" feature.

Without using it (i.e., "Capture group search" unchecked) I ablet to get the results.
![2021-02-23_10-02-37-dnGrep v2 9 319 0 - matches found with Capture group search cleared](https://user-images.githubusercontent.com/29984055/108848227-81187880-75bf-11eb-8916-90f2b593c6a9.png)

When I enable it and try to match `$1` as part of my regex I get no results
![2021-02-23_10-04-51-dnGrep v2 9 319 0 - no matches with Capture group search](https://user-images.githubusercontent.com/29984055/108848462-c8066e00-75bf-11eb-84e2-8ac397e944c9.png)

Check the following video. Hope you can shed some light again!
https://user-images.githubusercontent.com/29984055/108848692-0f8cfa00-75c0-11eb-9e21-1436404ff01c.mp4

Thank you very much!
Best!
Sergio

**Comment by doug24** [comment]
Hi Sergio,
There is a bug in the new capture group search code, when preparing the search pattern the regex replace not set to ignore case (as in the file name match), and it is failing on the .txt/.TXT case mismatch.  Until it is fixed, either change your Paths to match pattern to use .TXT, or change your filenames to .txt

**Comment by smfukaya** [comment]
Hi doug,

Thank you very much for all your support! After renaming the file extension to .txt it worked!

![2021-02-23_16-13-15-dnGrep v2 9 319 0 - Capture group search working after lowercasing file extension](https://user-images.githubusercontent.com/29984055/108895998-15e89980-75f3-11eb-8680-a098f911cb3b.png)

And more important! I could use the [tempered greedy token](https://www.rexegg.com/regex-quantifiers.html#tempered_greed) technique in order to find which files have lines that DON'T match the ones in their names.

![2021-02-23_16-13-53-dnGrep v2 9 319 0 - Capture group search - tempered greedy token](https://user-images.githubusercontent.com/29984055/108896169-51836380-75f3-11eb-8d21-e44a3094a531.png)

In order to achieve the same effect, yesterday using Cygwin I had to combine `find`, `xargs`, `sh`, `awk`, `grep` and subshells (very painful).

`
find $(pwd) -type f -regextype posix-extended -regex ".+/protoc01_([0-9]{6})[0-9]{4}\.TXT" -print | xargs -I '{}' sh -c 'awk -v var=$(echo {} | grep -oP "(?<=_)[0-9]{6}") '"'"' {x = substr($0, 721, 6)} {y = var} x != y {print FILENAME ": " FNR " x=" x " y=" y } '"'"' {}'
`

**Comment by smfukaya** [comment]
The fix in https://github.com/dnGrep/dnGrep/releases/tag/v2.9.326.0 worked like a charm! Thank you very much!
