### ISSUE TITLE
32-bit version failing after installation

### ISSUE THREAD

**Issue by mdmadonna** [dnGrep/dnGrep#481]
Downloaded dnGREP.2.9.304.x86.msi and installed on a Windows 10 32-bit OS.  Install went fine.  Opened program and entered search parameters.  Started a search and started receiving the attached message indicating 7z64.dll was not designed for Windows. Error status 0xc000035a.  Installed the 64-bit version on another machine with Win 10 64-bit OS - works fine.

![dnGREP](https://user-images.githubusercontent.com/13399841/107674144-a5da2b00-6c64-11eb-8e45-7b1366c5da4d.png)

**Comment by doug24** [comment]
The x86 process should be loading the 7z.dll, not 7z64.dll.  I'll have a fix in the next release.

Thanks!

**Comment by doug24** [comment]
This should be fixed in release v2.9.319.
