### ISSUE TITLE
One button process

### ISSUE THREAD

**Issue by major4579** [dnGrep/dnGrep#486]
![2021-02-18 dnGrep](https://user-images.githubusercontent.com/36489040/108402195-337cc400-71eb-11eb-9bcf-8ec5d50360e8.png)
I have a Search/Replace process setup, the only thing that changes is the file name and path. I'd love to be able to put the new filename/path in the folder field and click on one button and it does everything: replaces all text, save new file and exit. Is that possible? I've attached my dnGrep screen.
I've tried using the command line but there is no option for Replace.

**Comment by doug24** [comment]
Added Scripts in v3.1.197
