### ISSUE TITLE
How can I remove dngrep from the right-click context menu

### ISSUE THREAD

**Issue by peterkronenberg** [dnGrep/dnGrep#487]
How can I remove `dngrep `from the right-click context menu?

**Comment by doug24** [comment]
Run dnGrep as Administrator, open the Options window, and uncheck 'Enable Windows Explorer integration' at the top of the window.   Click the Save button and exit.

**Comment by JVimes** [comment]
@doug24 We might want to reword it for clarity as "Show dnGrep in Explorer right-click menu" or something along those lines. I'm not sure how many people know what "integration" implies in this context.

**Comment by peterkronenberg** [comment]
That would be clearer, but the thing that threw me off is that the box was already unchecked, because I was running as a non-administrator (as one normally does).  For those 2 checkboxes, it would be nice if the boxes reflected their actual state, even if non-admin, and add a note saying you need to run as Admin to change.

**Comment by doug24** [comment]
Yes, I agree it could be more clear, and it should show the current state even if you can't change.

There is already a tool tip saying why they are disabled, but again the wording could be more clear.
