### ISSUE TITLE
Missing progress indicator for remaining runtime estimation

### ISSUE THREAD

**Issue by tobwz** [dnGrep/dnGrep#493]
Sometimes I perform a search over all files on a partition.
This search could last for 20 minutes or more.

So I would appreciate if dngrep GUI could show not only of the already processed files but also of the total number of files.

Can this be added in the next release?

**Comment by doug24** [comment]
As it is, dnGrep does not know how many files will be searched until it's finished searching.  It doesn't go build a list of files first, and then begin searching within files, it searches as it walks the directories.  I'm pretty sure this was done for performance, and you start getting back results sooner.  I don't think I want to change that.
