### ISSUE TITLE
dngrep - specific sheet

### ISSUE THREAD

**Issue by Raf54** [dnGrep/dnGrep#504]
with dngrep how can I search for a string in a specific sheet of an excel file with multiple sheets?

**Comment by doug24** [comment]
Sorry, but there isn't a way to select a specific sheet to search in an Excel file.

**Comment by Raf54** [comment]
and I guess not even in a specific cell, right?

**Comment by doug24** [comment]
No, when dnGrep extracts the text from cells, it isn't recording the row or column.   But even if it did, how would you write a search string to address one or more sheets, and any number of ranges of cells?  It would become very complex - kind of sounds like SQL.

**Comment by Raf54** [comment]
sure, I thought so, thanks! but can I extract the contents of cell A2, which has no other indication on the row but only the header in cell A1?

**Comment by doug24** [comment]
dnGrep searches text, so when handling a more complex format like Excel, Word or PDF, it converts the data to text and searches that.  For Excel, it does each sheet separately, and separates the sheet columns with a tab character (\t) and rows with a newline (\n).   So you have to think of your Excel data in terms of lines of text, with each line a set of tab separated blocks (essentially CSV, but with tabs not commas).

Cell A2 will be one line below A1.  Both at the start of a line.   So you could do a multiline search to find only the matches where one line starts with your header text, and then continues to match the line below it.

For example, if the header in A1 is "Country" and you want to see the value in A2, you can do a Regex search like this:
`^Country\t.*\n\w+[^\t]`
with search option Multiline enabled.

This will match rows from the sheet where Country is the cell at the start of one row (Column A), and will match the rest of that line and the first cell of the next line.   I don't know how to match this only on the first two lines (rows) of the sheet, but there may be some clever regex to do that.
