### ISSUE TITLE
RegEx error?

### ISSUE THREAD

**Issue by Enzo4711** [dnGrep/dnGrep#505]
Hello, maybe I discovered a RegEx error in V3.9.326.0
Using the built in Test Expression tool use "{$R *.dfm}" as sample text and then try the RegEx Expression "\{\$" (without quotes) it states that the expression is OK but you get an error message like "... too many )-chars". Using another Microsoft RegEx test software it works as expected and finds "{$".

**Comment by doug24** [comment]
When I try, I don't get any error, and the expression `\{\$` works for me.  What am I doing differently?

<img src="https://user-images.githubusercontent.com/17227248/118492289-bae7af80-b6d4-11eb-9a2e-4d210ea87538.png" width="480" >

**Comment by Enzo4711** [comment]
Hm, don't understand why it suddenly works here in my Test window. I tried this way after not having success with the search engine for the same pattern.
Here is what I have now created here:

[test.zip](https://github.com/dnGrep/dnGrep/files/6495345/test.zip)
![dnGrep](https://user-images.githubusercontent.com/84304944/118523593-8fe57600-b73d-11eb-9675-17d4d5a9e9d2.PNG)

test.pas (a simple Delphi/Pascal unit) is in my temporary directory aside with other files and directories. The dnGrep.png shows an OS's German error message I suppose. The "error" text translated to English is "...is getting analyzed - Too many )-characters".

Hope this helps.
Chris

**Comment by doug24** [comment]
Thanks for the test file. Yes, that is a bug.  There is code in dnGrep checking for the `$` token, but isn't checking for the escape.

Long story - in the .net regular expression engine the `$` token matches only the newline `\n`, but most files on Windows use `\r\n`.  There were bug reports that the `$` token wasn't working so I added code to modify the user's regular expression for them to work with `\r\n`.  That code is missing the check for the escaped dollar sign.

**Comment by doug24** [comment]
Fixed in Release 2.9.345
