### ISSUE TITLE
Feature Proposal: Excel Worksheet - Limit via "search in" the search scope to a specific worksheet name 

### ISSUE THREAD

**Issue by mrvainv2** [dnGrep/dnGrep#506]
Hi,

I rediscovered dngrep. Excellent tool. 

**[Q1]** 	  Would it be possible to narrow the search to a specific worksheet name in excel (or even better,  part of a worksheet name)? Maybe it is already possible. 

with kind regards,

**Comment by doug24** [comment]
I don't get it: the Excel search has been in dnGrep for three years now, and two people have asked for the same thing in a week.  Did someone write a blog about using dnGrep to search in Excel or something?  

Yes, it can be done, but doing it is complicated.  First, what would you do in the the user interface to specify one or more sheets?  Where does this new search parameter go? Consider that this is something that is only going to apply to Excel of all file types. Is it a simple string 'contains' or does it need to support regular expressions or wildcards?

Second (and I know this isn't your problem), dnGrep has an specific method interface to passing search parameters to the various search engines that handle the different file types.  Adding a new search parameter just for Excel means changing the interface, changing all of the search engines, and all of the test code.  

So I don't know:  how necessary or useful would this be?  Is it really a problem searching all of the sheets?

**Comment by mrvainv2** [comment]
Hi Doug,

No worries and for me at least "no blog". I was just noticing the worksheet name in the results. If it was easy to implement, I could use it. But I will find a workaround. 
Thank you for considering and the extensive answer.
