### ISSUE TITLE
can't find special character

### ISSUE THREAD

**Issue by pipiscrew** [dnGrep/dnGrep#512]
**version tested** : dnGREP.2.9.326.x64

for example, using **text search** for this 

`<!-----Copyright ©PipisCrew All rights reserved.----->`

if exist on a file, couldn't identify it, no result return.

**Comment by doug24** [comment]
It is probably the Encoding setting, special characters can confuse the detection logic.  Try changing the Encoding from 'Auto detection' to UTF-8.

**Comment by pipiscrew** [comment]
^true, tested & working.
