### ISSUE TITLE
Theme: Color Window Caption when is window is inactive

### ISSUE THREAD

**Issue by Csavie** [dnGrep/dnGrep#513]
Hi,

First of all, congratulations for this great software, and thanks for make it open source.

I did a new theme, with colours more Windows XP style.

![WinXPColors](https://user-images.githubusercontent.com/86087176/122491527-7eb1b280-cfe4-11eb-92ca-d2cab2dfa9cc.png)

But I can't change the colour of window caption when the window of program is inactive. In [theme].xaml I not see the something like "Caption.Background.Inactive" and "Caption.Foreground.Inactive" . Really it doesn't exists?. 

In Light or Dark themes neither are difference between window is active or not. It's very annoying because without this functionality, the window of program seems is always active in my theme or inactive in default themes.

Many thanks in advance,

Csavie

[WinXPColors.zip](https://github.com/dnGrep/dnGrep/files/6674041/WinXPColors.zip)

**Comment by doug24** [comment]
I don't know if you are the first to create or modify a theme, but I'm pretty sure you're the first to post one back here - thanks!

Yes, I can add "Caption.Background.Inactive" and "Caption.Foreground.Inactive" - they don't exist now.

**Comment by Csavie** [comment]
Thanks for add it !!, i will wait for a new version.

Csavie

**Comment by doug24** [comment]
Added in Release 2.9.345

**Comment by Csavie** [comment]
Hi,

Thanks for add it, it works perfectly.

I let here the new theme for if someone is interested.
[WinXPColors Ver 2.9.345.zip](https://github.com/dnGrep/dnGrep/files/6767176/WinXPColors.Ver.2.9.345.zip)

Csavie.

**Comment by doug24** [comment]
@Csavie - are you still using and maintaining your theme?

In the February release of dnGrep (next week) I made two breaking changes to the theme files:

1) The key "GradientBackground" is changed to "Window.Background"

2) The Pin and Unpin bitmaps have been removed from the theme file and replaced with this:
```
    <sys:Boolean x:Key="ToggleButton.DarkImages">true</sys:Boolean>
```
set it to false for light-colored themes.

I have a [Theme Editor](https://github.com/doug24/ThemeEditor/tree/v1.1.0) on my personal page - it is an update of what I used to create the original themes - not complete, but is useful.  You can use/edit the same file in the same location for both the Theme Editor and dnGrep.

**Comment by Csavie** [comment]
Hi Doug,

I send you my theme for version 4.1.27.0.

I must say that I miss some colour options:

  	* Caption.Button.Background.Inactive
  	* Caption.Button.Foreground.Inactive
  	* Caption.Button.MouseOver.Background.Inactive
  	* Caption.Button.MouseOver.Foreground.Inactive

The "problem" without this is that the three buttons of the window 
(minimize, maximize, close) has the same colour when the window is 
active or not. And if the colour of the buttons is white when active, 
then when the windows is inactive the buttons are not visible.

Csavie.

El 2024-02-13 12:40, ***@***.*** va escriure:

> Hi Doug,
> 
> Yes, I still using my theme.
> 
> I downloaded the new version 4.1.7.0 and modified my theme. I modified 
> the theme by putting Window.Background, and added the pin's bitmaps, 
> and all seems work flawlessly. I send it attached in this mail.
> 
> I don't have access to a Visual Studio 2022, and in consequence I can't 
> compile the Theme Editor. In the moment that you put a compiled version 
> in you web I will downloaded it and I will use.
> 
> By the way, when I have time, I will try to finish the catalan 
> translation
> 
> Thanks for all your work.
> 
> Csavie.
> 
> El 2024-02-12 00:30, Doug P va escriure:
> 
>> @Csavie [1] - are you still using and maintaining your theme?
>> 
>> In the February release of dnGrep (next week) I made two breaking 
>> changes to the theme files:
>> 
>> *
>> 
>> The key "GradientBackground" is changed to "Window.Background"
>> *
>> 
>> The Pin and Unpin bitmaps have been removed from the theme file and 
>> replaced with this:
>> 
>> <sys:Boolean x:Key="ToggleButton.DarkImages">true</sys:Boolean>
>> 
>> set it to false for light-colored themes.
>> 
>> I have a Theme Editor [2] on my personal page - it is an update of 
>> what I used to create the original themes - not complete, but is 
>> useful. You can use/edit the same file in the same location for both 
>> the Theme Editor and dnGrep.
>> 
>> --
>> Reply to this email directly, view it on GitHub [3], or unsubscribe 
>> [4].
>> You are receiving this because you were mentioned.Message ID: 
>> ***@***.***>



Links:
------
[1] https://github.com/Csavie
[2] https://github.com/doug24/ThemeEditor/tree/v1.1.0
[3] https://github.com/dnGrep/dnGrep/issues/513#issuecomment-1937911612
[4]

**Comment by doug24** [comment]
If you intended to attach a new theme file here, it didn't work.  You probably need to attach it from the github website as a zip file (not from an email reply).

I will add the new color for the caption buttons.  While I'm doing that, I will make a couple of other changes to the themes - fix two misspellings, change a few keys, and add a couple of other new colors.  I will post all the changes together when it is finalized.

**Comment by Csavie** [comment]
Ok, perfect, thanks for it, I will wait.

Csavie

**Comment by doug24** [comment]
@Csavie I just published a new release of the [Theme Editor](https://github.com/doug24/ThemeEditor/tree/v2.0.0) with lots of changes.  These changes will be release in dnGrep in the March release next week.
  
See this [discussion topic ](https://github.com/dnGrep/dnGrep/discussions/1066#discussioncomment-8687260)for a full list of changes to the theme files - you can either edit your theme with the new editor, or merge in changes from one of the theme files included in the release package.  You will not be able to view the changes in dnGrep until after the March 2024 release next week.

I'll update the Readme file on the main [Theme Editor](https://github.com/doug24/ThemeEditor/tree/v2.0.0) page soon.

**Comment by doug24** [comment]
Just wanted to add that you need to make the key name changes and add the new color elements to your theme file manually before opening it in the theme editor - it will not add the missing colors or fix the keys for you.
