### ISSUE TITLE
Need help with replacing a char removing \r\n

### ISSUE THREAD

**Issue by Hexaae** [dnGrep/dnGrep#517]
I have a line like this:
```
Cia\r\n
o a tutti
```
that I want to change into:
`Ciao a tutti`

How can I specify the Replacement string to remove the \r\n only and move up the next line? A simple RegEx replacement like:
_Search:_ Cia\r\n
_Replacement_: Cia
fails and won't wrap up the next line...

**Comment by doug24** [comment]
I would use regex capture groups like this -
Search for: `(Cia)\r\n`
Replace with: `$1`

or to ensure the next line starts with `o`
Search for: `(Cia)\r\n(o)`
Replace with: `$1$2`

You can make the capture groups more generic to join lines with other text.
https://www.regular-expressions.info/refcapture.html 

<img src="https://user-images.githubusercontent.com/17227248/123521925-976a3a00-d66e-11eb-8a45-8908caa48ebd.png" width="480" >

**Comment by Hexaae** [comment]
Thanks. 
BTW, I was wrong: the example in my original message worked fine on the real file, but I thought it didn't because of the 'Replace Text' window (clicking on Replace button) not showing actual results! Ooops!
