### ISSUE TITLE
Request for file properties

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#52]
_From [Mike.McC...@gmail.com](https://code.google.com/u/115983178242417329226/) on February 11, 2010 07:04:33_

Please add some file properties, at least date created or modified

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=48_

**Comment by pawelkuras** [comment]
Is there any progress on this?

**Comment by JVimes** [comment]
@pawelkuras Unfortunately not. Right now dnGrep is entirely dependent on pull requests from the community, and nobody's submitted one for this issue. This thread's previous comments are from years ago, imported from the old Google Code project.

**Comment by doug24** [comment]
added file properties as tooltips in 2.9.189
can also right-click in the results, and choose "show file properties"
I've tried adding columns to the results tree, but it does not work well - there are problems with the dynamic sizing of lines in the tree for the text preview.
