### ISSUE TITLE
Every time I open v2.9.345.0 maximized, the viewer takes up most of the screen.

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#520]
You can see by the image what is happening.  I have been unable to figure out how to stop this.
If I resize the viewer pane and close when not maximized, when I next open, it is not maximized, the viewer pane does not take up most of the screen and the panes have the same proportions as when I last closed.  If I then only maximize, close, and re-open, I am back to the viewer pane taking most of the screen, as you can see in the attached screenshot.
![image](https://user-images.githubusercontent.com/40300659/126080717-2f8696f8-4687-4402-83a2-41b072658f7e.png)

**Comment by doug24** [comment]
Yes, it's a bug and I can reproduce it.  There doesn't look like there is a good work around until I get it fixed

**Comment by doug24** [comment]
Fixed in v2.9.349

**Comment by mdell-seradex** [comment]
Thank you!

**Comment by mdell-seradex** [comment]
After installing the new version (2.9.349.0) and opening it, it opened much better, but on the second opening it was very similar to the same issue, albeit the search pane was 2 to 3 times wider.
I found that when I unmaximized that for some reason dnGrep was about 1/4 the width of my screen.  Once I resized this appropriately, it is now opening correctly when maximized, keeping the appropriate size.

Note that I do not expect you to try to do anything about this once I adjusted the sizes of the panes while not maximized.
Instead I am including this note in case anyone else encounters this without finding what I did so that they know it is simple to overcome.
I find that some people either give up to easily, or complain about things, which are easily permanently overcome with a small set of actions.  For example, when opening a Microsoft Office file that contains VBA, instead of making the file or location trusted, they just enable the macros EVERY time they open it.

**Comment by mdell-seradex** [comment]
After installing the new version (2.9.349.0) and opening it, it opened much better, but on the second opening it was very similar to the same issue, albeit the search pane was 2 to 3 times wider.
I found that when I unmaximized dnGrep that for some reason it was about 1/4 the width of my screen.  Once I resized this appropriately, it is now opening correctly when maximized, keeping the desired size.

Note that I do not expect you to try to do anything about this once I adjusted the sizes of the panes while not maximized.
Instead I am including this note in case anyone else encounters this without finding what I did so that they know it is simple to overcome.
I find that some people either give up to easily, or complain about things, which are easily permanently overcome with a small set of actions. For example, when opening a Microsoft Office file that contains VBA, instead of making the file or location trusted, they just enable the macros EVERY time they open it.

**Comment by mdell-seradex** [comment]
Hello @doug24.
I just discovered a problem which I believe is related, but I can live with for now.
I typically keep dnGrep open maximized and close it when it is so.
What is have discovered in using v2.9.349.0 is that everytime I open dnGrep now, the width of the preview panel grows about 1/2 inch.  This means that the left side shrinks about 5 inches after opening and closing 10x without resizing the preview panel.
Note that I am running on a laptop screen at 1600x900 resolution if that matters.
I wasn't sure if this should be a new issue or not since it seems related.

**Comment by mdell-seradex** [comment]
Hello @doug24.
I just discovered a problem which I believe is related, but I do not believe is as urgent of a problem.
I typically keep dnGrep open maximized and close it when it is so.
What is have discovered in using v2.9.349.0 is that everytime I open dnGrep now, the width of the preview panel grows about 1/2 inch. This means that the left side shrinks about 5 inches after opening and closing 10x without resizing the preview panel.
Note that I am running on a laptop screen at 1600x900 resolution if that matters.
I wasn't sure if this should be a new issue or not since it seems related.

**Comment by doug24** [comment]
OK, I see this too.  I'll have a fix in the next release, but I won't make a new release just for this change.

**Comment by doug24** [comment]
Additional fix added in release v2.9.378.0

**Comment by mdell-seradex** [comment]
Yes, this does seem to be working better now.

**Comment by doug24** [comment]
This may still be a problem, but I can't reliably reproduce it.  Will keep watching it.

**Comment by mdell-seradex** [comment]
I have had no issues that I could detect since you released the previous version.
