### ISSUE TITLE
Specifying multiple paths to match

### ISSUE THREAD

**Issue by demdante** [dnGrep/dnGrep#521]
Hello.  I don't know if the functionality I am about to describe already exists, but I could not find anything in the documentation or existing issues that discusses it, so I am creating this issue.  Is it possible to specify multiple file types in the "paths to search" input to allow dngrep to search multiple file types in the same search.  For example, this is a screenshot from another tool that is similar in nature to dngrep which **does** have this functionality, and the window describes how to configure the search to include multiple file extensions in the search:

![2021-07-20 13_11_49-DOS Expression](https://user-images.githubusercontent.com/64720591/126367765-1c385482-52ac-45de-b5b7-a40f95d4f507.png)

Does this functionality exist in dngrep?  I tried configuring "paths to search" to search multiple file extensions similar to how it is displayed in the above image, but dngrep only returned the first file type results.  Thanks in advance.

**Comment by doug24** [comment]
Yes, you can specify multiple file filters in the 'Paths to match' field:  separate the individual filters with either a comma or semi-colon:
`*.txt;*.xml`
`*.htm*,*.js`
The asterisk patterns follow the normal expressions.  

dnGrep doesn't support the expressions shown in the Advanced examples above using asterisk patterns, but you can use regular expressions to that and more.  To switch to use regular expression file filters, open the expander panel with the "More..." button, and then change the radio button from 'Asterisk pattern' to 'Regex'.

The comma or semi-colon separated patterns work for both Asterisk patterns and Regex.

If you can't get multiple patterns to work, please show the exact pattern you are trying to use.
