### ISSUE TITLE
simple translate option

### ISSUE THREAD

**Issue by ronen1n** [dnGrep/dnGrep#528]
I want to help translate the software to install it to my clients 
Now they like "everything" because they have my language

**Comment by doug24** [comment]
I am surprised this hasn't been a request before now.  So there isn't a simple translate option, and making it simple to translate will very likely mean a lot of work in the changing application code to support translations.

I know there are different approaches for making an application localizable, but I haven't done one in several years now, so if anyone has recommendations, I'd like to hear about it.  Maybe it won't be as bad as I fear it would be.

My other concern with making translations available is that many of the releases will also need to update the translations.  And I won't be able to do any of them (google translate is not good for this purpose). So are there a group of people that would be willing to make a long term commitment to providing translations for the application?

**Comment by doug24** [comment]
If anyone has interest in having a localized/translated version of the app, or will would like to contribute translations to the project, please like or comment.  If there isn't significant interest, I'm not going to spend the time to work on it.

**Comment by ronen1n** [comment]
I will translate some or all to my language and I'm sure that if you make it easy (like ini file for every language in install folder with mail to send the finished file) more people will translate

**Comment by celeron533** [comment]
The 1st step is to make the WPF UI i18n compatible.
Current content and text are hard-coded in English.
```
                <CheckBox Content="Highlight Matches" Margin="10,3,6,3"                                  
                          IsChecked="{Binding HighlightsOn}"
                          Command="{Binding HighlightsCommand}" 
                          TabIndex="91"/>
                <CheckBox Content="Highlight Groups" Margin="6,3"                                  
                            IsChecked="{Binding HighlightCaptureGroups}"
                            IsEnabled="{Binding Path=IsHighlightGroupsEnabled}"
                            ToolTip="Highlight regular expression groups - changes will be applied in next search"
                            TabIndex="92"/>
```
Once each language has its own resource file, new logic could be added to check current OS language and set the default language if it is not configured in Options.

**Comment by celeron533** [comment]
Just draft a possible solution for i18n support.

https://github.com/celeron533/dnGrep/commit/f382347a54d2bfc3c12acd24d34c90b3481e9875

**Comment by doug24** [comment]
Thanks, I pulled your branch and will take a look.  Have you used this method in an application?
Have you seen [this method](https://www.codinginfinity.me/posts/localization-of-a-wpf-app-the-simple-approach/), which also uses resx files, and supports dynamic language changes?
Or using XAML resource files [like this](https://github.com/Epsil0neR/WPF-Localization)?

**Comment by celeron533** [comment]
> My other concern with making translations available is that many of the releases will also need to update the translations. And I won't be able to do any of them

Could use some online localization service to help the community to organize the translations:
https://www.transifex.com/HandBrakeProject/WinUI/
https://hosted.weblate.org/projects/switchyomega/

**Comment by celeron533** [comment]
Hi @doug24 ,

Thanks for the reply.
I haven't use this method in my application but it has been used in another opensource project called HandBrake:
https://github.com/HandBrake/HandBrake/tree/master/win/CS


resx files + static resource
====
Demoed in my draft code.
Adv:
* Has strong link between UI elements and text resources. And mismatch would block the build process.
* Possible WPF design time support
Dis:
* No tolerance for newly added UI element which is not added in all language translation resource file. May crash if a key does not exist in selected language.
* Must restart application to change the language. (not a big deal)

resx files + dynamic language changes
====
(Similar concept was used in application `shadowsocks-windows` by replacing UI text by a key-value map)
Adv:
* Application would not crash if some UI element's translations do not exist in language resource file. UI would still be displayed in default language (normally English).
* Could apply new language without restart the application.
Dis:
* Sometimes it is hard to find out which translation key is missing on specific language.
* If developer change the UI element's default text (such as change `Regex` to `Reg.`), he/she needs to update the corresponding key in all language resource files.

XAML resource files
====
Adv:
* xaml native
* Could apply new language without restart the application.
Dis:
* No resource designer. Everything is in xaml code.
* (not quite sure) CSharp backend code (message content, log, etc.) need extra work to grab and extract the translated string.
* (not quite sure) May crash if a key does not exist in selected language.

**Comment by celeron533** [comment]
Updated my demo a bit:
![image](https://user-images.githubusercontent.com/3608762/128591845-06b1cfbe-01af-49e4-b108-443dd435a061.png)

**Comment by doug24** [comment]
Thanks for doing this!  I'll also post a branch of what I've been working on.

**Comment by doug24** [comment]
I have a branch with some experiments here: [528-localization]( https://github.com/doug24/dnGrep/tree/528-localization).  There is a language selector in the Options dialog.

@celeron533: I've included some of your changes, but have also been experimenting with dynamic language switching.  As you noted, you do lose the compile time error checking.  In the place of that, I've made the fallback resource with all the strings preceded by the `@` symbol to indicate the string is missing from the current language resource.  And if the string is missing from the language resource and the fallback resource, it get shown as the resource key preceded by the `#` character.  In the current build configurations, the XAML files must be edited using the x86 configuration - the strings don't show when editing XAML in x64 - and that took me a while to figure out that the XAML designer doesn't run local code in x64, since it's running in x86 itself.

@ronen1n: the approach we are looking at is to include translations in a Resources.resx file, an XML file in a particular format that gets complied and embedded into the application.  The resx file may be edited with Visual Studio, or any text editor.  The translations will be part of the application release, not added after the fact. I think this is really the best way to implement it.  Does that qualify as 'simple translation'?   Here is a sample clip from a resx file. 

```
  <data name="About dnGREP" xml:space="preserve">
    <value>About dnGREP</value>
  </data>
  <data name="Acknowledgments" xml:space="preserve">
    <value>Acknowledgments</value>
  </data>
  <data name="after" xml:space="preserve">
    <value>after</value>
  </data>
  <data name="All dates" xml:space="preserve">
    <value>All dates</value>
  </data>
  <data name="All sizes" xml:space="preserve">
    <value>All sizes</value>
  </data>

```

**Comment by celeron533** [comment]
Thank you @doug24 . The [528-localization](https://github.com/doug24/dnGrep/tree/528-localization) looks great. I am glad to help if you've decided this is the way to do the localization.

**Comment by doug24** [comment]
I pushed another change to my experimental branch linked above.  I figured out a way to load an external resx file into the running application to load a new language from a file.   The load button is on the Options dialog.

This way translators can work on translating their language in an XML file (resx format) using any text editor, and then load it into dnGrep to see the results and fix as needed.   I'm sure this will meet the requirement of "simple" to translate.

**Comment by doug24** [comment]
I have completed the coding for this change and it is ready for contributions of translations.   

I started a discussion page here with instructions:   https://github.com/dnGrep/dnGrep/discussions/538

**Comment by doug24** [comment]
The changes to allow translation are added in release v2.9.378.0.

**Comment by celeron533** [comment]
Good work @doug24 !
I'll start work on Simplified Chinese translation (zh-cn) soon.

**Comment by doug24** [comment]
Great, thanks for you help @celeron533

**Comment by celeron533** [comment]
Simplified Chinese translation draft completed. Will create a pull request.
