### ISSUE TITLE
Option to disable the realtime check if source folders are accessible?

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#529]
Good evening

### … is this test really / usually useful?
It is not clear to me what advantage this function offers, because even if network drives are available, this test blocks the UI for a few seconds every time. I would much rather have dnGrep check if the source folders are accessible when the access is needed when we start the search-process 😃 

Anyway:
### Is there any way to disable this automatic check? 

I support about 5 non-profit organizations and of course I don't always have the VPN connection active. Therefore dnGrep becomes a pain with this automatic check:
- **if one starts dnGrep**: why does dnGrep expect that the next search task will be on the same source folder as the last time? 
- **while we're working in dnGrep**: if one selects the wrong entry in the source folder history
- **if one switch to the dnGrep window to just to see** the last results: Ony has to wait because the access is checked 😢 
- **if one switch to the dnGrep window to start a new search**: my chance is about 1:6 that the search will take place in the same directory, therefore waiting for the access-check is useless 
- ...

In my workflows, this automatic logic constantly disturbs :-(

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
Yes, I can change the valid directory check to run at the time you start an operation.  Might also save someone from wondering why the Search button isn't active.

dnGrep saves the last search path because it saves *all* the settings.  If I removed save/restore the last search path, I expect there would be a bug report no later than the day after the release.  And I think it is useful for some people, it's really not possible to know all the different ways that people use the tool.  And no, I really don't want to create another configuration option to enable/disable it.

For me, 95% of the time I start dnGrep from the Windows Explorer context menu, so I'm always starting in the location I want, and it's always a valid directory.  I don't get why some people remove the Explorer context menu, that would really slow me down.

**Comment by schittli** [comment]
Hello @doug24 

thanks a lot for your answer!

Yes, please do _not_ remove the last search path! It's great as it is, it's just as described annoying if they must be accessible if dnGrep is started or dnGrep gets the focus.

Yes, I would also not hope anything other than that the directory access check would be done just when the search is started 😃 


### Explorer Integration: The different user behaviour / workflow is very interesting: 
I have never used the Windows Explorer integration because I need the Windows Explorer maybe 3 times a year. I work in a completely different way:

- I open any program (Office, VS Code, ...) and then I have the latest projects in the MRU list. I need two click's and I'm ready to work or I open a new project once.

- When I need dnGrep, then
  - I press the `Windows Key any type `dng <Enter>` to start it. Then:
    - for a new project, I paste the new directory into the search path from the Clipboard (which I've got e.g. from VS Code)
    - or I open the current project directory from the last search paths. And I'm ready :-)

All the best!
Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
Change is added in release v2.9.378.0

**Comment by schittli** [comment]
Thank you very much!, @doug24, four your great support!

I have just installed v2.9.378.0 and, unfortunately. the improvement has still some weakness:

1. If one opens the `Search in` » `Folder` DropDown List and select an item where a path is not accessible, then dnGREP blocks for about 10 seconds.

2. Additionally, dbGREP blocks if the a Folder item is not accessible and one expand the the `Search in` » `More…` panel/expander.

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
I had been testing with a disconnected drive letter, which fails immediately, so I didn't see any delay.  When I changed to test using an invalid path on network file share, it takes much longer to fail.  So yes, I'm seeing the problem you have.

Would it be sufficient if I gave you an option to not save and restore the current and recent paths?   I'm assuming that the paths are not going to become invalid while the application is running. 

You asked earlier if there is any value to validating the path.  I'd have to say yes there is.  There is code in several places that validates the path exists, and these were added in one feature request or another.  I'm not going to remove these checks, as it will break things that someone is using.  I've looked some at making an option to bypass the checks, but this will also break some features, just leading to more bug reports.  

One example is processing the input data from the `Folder` input:  mostly it is just a single path, but it can be multiple paths, contain a path to a file, and it can contain wildcards (for example, c:\results\log* will search only sub-folders with a name starting with "log").  The code parses the input text and makes decisions based on if the current parsed substring exists as a file or folder.  The separators for multiple paths (comma and semi-colon) are valid symbols in a directory or file name which makes parsing the input text difficult.

**Comment by schittli** [comment]
Hello @doug24 

thank you very much for your analysis and answer!

Automatically save / restore the paths is a great feature and I almost always use multiple paths: 
At least for me, more than 90% of the time I don't have to copy a new path into the text box (or select the target paths), but I can easily select the path from the history. That's ingenious because it's very fast.

> I've looked some at making an option to bypass the checks, but this will also break some features, just leading to more bug reports.

I would bet that for most users dnGREP is primarily an extremely great grep tool and that these additional functions cannot be so important that they destroy the usability of dnGREP because one is blocked again and again for a very long time.

In your Example:
> The code parses the input text and makes decisions based on if the current parsed substring exists as a file or folder. 

you have described the real problem yourself:
> The separators for multiple paths (comma and semi-colon) are valid symbols in a directory or file name which makes parsing the input text difficult.

the simple and clean solution is not to write code which tries to figure out what the user actually meant (what if a path includes comma and semi-colons?), but to use a separator that is always invalid for paths / files, e.g. `|`


In 30 years of software development, I have never seen it work to patch up issues with workarounds: they were never smart enough. It always pays to get to the root of the problem - like at the dentist. Ouch! 😅


Thanks a lot for your great tool and support!
Kind regards,
Thomas

**Comment by doug24** [comment]
I believe this is fixed now.  If there is some scenario you still see, please reopen and describe it in detail.
