### ISSUE TITLE
Add hot keys for the Search and Replace fields

### ISSUE THREAD

**Issue by kevinj2016** [dnGrep/dnGrep#530]
I tried to use my keyboard to get the cursor in the Search field, but could not. 
Are there no hotkeys for jumping to the search field? (I can tab from Search to Replace, but probably Replace should have a hotkey too.)

**Comment by doug24** [comment]
I should be able to add something, just not sure what.  I don't think you can use an accelerator key on the label, so it will probably have to be a function key.  The problem with that is it's not self-documenting - you can't what key is mapped to the field.  There are already large tooltips on those controls, but maybe just add it in there.

**Comment by kevinj2016** [comment]
Hi Doug,

Thank you for your monitoring and reply!

Yes, you can use hotkeys on labels, as follows:

  *   Give the label a tab-order number to get it into the tab-order sequence.
  *   Ensure that the input field (textbox) is next in the tab-order after the label.
  *   Give the label a hotkey in the normal manner.
  *   Then when you issue the hotkey for the label, the cursor jumps to the input field, not the label.

Haha, who knew you could do that? I did not until someone told me about it.

Cheers, Kevin

**Comment by doug24** [comment]
I did try that, but couldn't get it work.  The label is currently a TextBlock that doesn't allow tab order or accelerator keys, but I changed it to a Label control, set the tab order to be one less than the search field, and set the accelerator key to be "f".   When you hit alt+f, nothing happens.  I don't know, maybe I've missed something.

**Comment by kevinj2016** [comment]
Hi Doug,

Sorry to hear that it isn't working for you yet. I know the method works (at least on my setup) because I tried it out, and others said it worked for them too.

Just some checks: (I mean no offense):

  *   Is the tab order continuous?
  *   Does any other control have the same tab order?
  *   Does any other control have the same tab order as the input box?
  *   Does the "f" (Alt-F?) conflict with any system hotkeys?
  *   Does the Alt-F conflict with any menu hotkeys?
  *   And you've already switched to a normal label control, so that was a good move.
  *   Standard windows forms controls, etc?

It's probably a hassle for you, but maybe create a tiny test project with 1 label and 1 field. That's what I did a couple of years ago.

If you still can't get it to work, I will build a project myself and help you out.

Thank you for trying!

Cheers, Kevin

**Comment by doug24** [comment]
Hi Kevin,

I found the solution - WPF doesn't use the tab order to link labels to controls, there is binding.  So the 'Search for' label gets this:
`Target="{Binding ElementName=tbSearchFor}"` to link it to the search text box.

**Comment by kevinj2016** [comment]
Hi Doug,

Excellent!

I don't know anything about WPF, so I learned something too!

Cheers, Kevin

**Comment by kevinj2016** [comment]
Hi Doug,

On another topic, I really missed having an “expand all” button to expand all the collapsed filenames in the lower-left file viewing pane.
I wanted some hotkey way of expanding the whole tree to see if a particular file contained the match string.

Should I put in this suggestion on another thread in GitHub, or is it sufficient to pass on to you here?

Thank you again for your help on the Search hotkey.
Having a search hotkey was important to me because I drive many of my tools and menus by voice (which can send hotkeys).
Positioning the mouse pointer by voice to hit a tiny search box target is a pain… 😊

Cheers, Kevin

**Comment by doug24** [comment]
This issue is fine, I'll take a look at that context menu too.

**Comment by doug24** [comment]
Changes are added in release v2.9.378.0
