### ISSUE TITLE
Use Scintilla.Net component for in-place filtering and editing?

### ISSUE THREAD

**Issue by dr-dba** [dnGrep/dnGrep#531]
My suggestion is abt to use Scintilla.Net component for in-place filtering and editing.
https://github.com/jacobslusser/ScintillaNET
https://github.com/robinrodricks/ScintillaNET.Demo

Scintilla is great for text edit and representation, it has filterable lines, that is to say, it may hide certain lines of text, so it become kind of grep results, and of course u may (un)hide lines upon certain search criteria.
Is it doable in dnGrep?
Thanks for the best grep utility i found till now

**Comment by doug24** [comment]
I don't think dnGrep should become a text editor or an IDE.  I think dnGrep should stay focused on wheat it does now, and not expand into other areas.  That's just way more work than I can take on.

Also, the problem I see with Scintilla.Net is the main project hasn't been updated in 4 years.  It has a lot of new open issues and pull requests.  All the development is happening on forks, and that means it has to be built before it can be used, making it even more work to maintain.

**Comment by dr-dba** [comment]
@doug24, ok, i may agree with you.
though, what do you think, about some decent level programmer trying to do it?
I guess how it will be hard and feasible for me, actually :)

**Comment by doug24** [comment]
What is it that you want to do with it?  If you are wanting to make it primarily a text editor with search capabilities, then you are better off starting a new project and reusing what code from dnGrep that helps you there.

Do you want to replace the existing docking Preview Panel?  Or do you want to make a new window to go with the existing windows?  How would that layout work?

If you want to replace the existing Preview Panel, it would have to re-implement all the existing features:  light and dark modes, syntax highlighting for a bunch of languages, highlighting search results and navigating to selected matches.  Basically, be a better preview panel than the existing Avalon Edit control.

Scintilla.NET is not a WPF control, and dnGrep is 100% WPF.  So you would have to put in a WindowsFormsHost.  When you do that, how does the control handle high resolution monitors, and moving between monitors of different resolutions?

Once you allow editing in the dnGrep, how are you going to handle dnGrep's Replace function? After editing, the search results are no longer valid, and the Replace function re-writes the files as it does the replace.

Putting in a control like this is not a one time event, it's a long term maintenance project.   What version of Scintilla.NET are you going to use?  The dormant main project, or your own build of one of the forks?   How are you going to handle bug reports against the control?  Are you going to fix them yourself, or pass them on to the Scintilla.NET project for them to fix?

**Comment by dr-dba** [comment]
> What is it that you want to do with it? 
> If you are wanting to make it primarily a text editor with search capabilities, 

Er.. yesss, i want editor with such excellent search capabilities, as in dnGrep.
Work with text, especially coding is mostly search and then combining pieces together.

> then you are better off starting a new project and reusing what code from dnGrep that helps you there.

that seems to be much more work then just replace on editor component to another, while both text edit components very much alike each other, just scintilla-based component is more extended with advanced stuff, nevertheless, it still simple and very much the same API.

> Do you want to replace the existing docking Preview Panel? 

Yes, exactly that scenario i meant primary

> Or do you want to make a new window to go with the existing windows? How would that layout work?

Probably a new window, as the next step

> If you want to replace the existing Preview Panel, it would have to re-implement all the existing features: 

yess, i am unclear about the volume of the stuff, thank you for your concern and answering!

> light and dark modes, syntax highlighting for a bunch of languages, 
> highlighting search results and navigating to selected matches. 

Should be relatively easy "stealed" from the existing scintilla.net-based projects i saw earlier.
and, for example, "navigating to selected matches" should be just renaming of the kind from "ScrollToLine" to "GoToLine".
API in both cases are pretty straightforward, from my experience (rather limited experience, to be honest)

> Basically, be a better preview panel than the existing Avalon Edit control.

BTW, does AvalonEdit support hiding certain lines and code folding? 
I think not, but if, of the sudden, it does, i will need to rethink something.
i will check it at home, cant open it here..

> Scintilla.NET is not a WPF control, and dnGrep is 100% WPF. 
> So you would have to put in a WindowsFormsHost. 
> When you do that, how does the control handle high resolution monitors, 
> and moving between monitors of different resolutions?

i already thought about, and i will need some help, thanks again for mention that!
i like WinForms much more, because of simplicity and lack of experience in WPF..
so it is a good point, thanks
I saw a WPF wrapper for WPF, these two, i dont know how both related to each other though:
https://github.com/RayBowman2017b/R20181229_ScintillaNET_WPF
https://github.com/Stumpii/ScintillaNET.WPF

> Once you allow editing in the dnGrep, 
> how are you going to handle dnGrep's Replace function? 
> After editing, the search results are no longer valid, and the Replace function re-writes the files as it does the replace.

Ugh, right. either discard or disable the search results, or re-evaluate on each save event.
To see what is faster to implement as the first step, than as the next step, to see what is more right and justified to do ..

> Putting in a control like this is not a one time event, it's a long term maintenance project. 
> What version of Scintilla.NET are you going to use? 

The latest one, then to stay with that, i think, merge from upstream still possible, should be straight forward, since i am not going to chenge deep internals of the Scintilla.Net itself. Probably i am missing smtg? I think yes i am, but ..

> The dormant main project, or your own build of one of the forks? 

dont know, what is better? it will be some kind of fork, i am not too worried which kind exactly, and i will gladly accept your recommendations on the matter.

> How are you going to handle bug reports against the control? 

On the best effort basis :)

> Are you going to fix them yourself, or pass them on to the Scintilla.NET project for them to fix?

I think both, I usually try to fix myself, with intent to help, and also due to some lack of patience

**Comment by doug24** [comment]
I think I made it clear that I don't think dnGrep should be an editor, it doesn't enhance dnGrep's primary purpose of be a text search tool.   There are dozens of editors already available - some using Scintilla - that have large teams of people working on them, and I'm not interested in competing with them.  I'm already putting as much time as I can in this project without taking on all the bugs and enhancement requests that will surely occur when the focus is changed being an editor with more search capabilities.

You do know that in dnGrep you can open search results in your editor of choice, right?  See Options - Custom Editor.  You can use Notepad++, which is a Scintilla editor. Or VS Code, or whatever. That's one of the problems with text editors - people love or hate different features and the UX.  Maybe there is something that can be done to improve opening files in the custom editor? 

Starting a new project is no more work.  Either way you have to create fork of dnGrep, create branch, and then start figuring out how to put in the control, and what needs to change.  The only difference is then keeping the fork as your own project. You will learn a lot along the way, I know I have.

**Comment by dr-dba** [comment]
@doug24, i totally appreciate you opinion and the excellent job and the time you investing, i do understand that, clear as a hell. that is altruism at it's best, and of that i am envy and i wish i could to do.
My problem with other editors, is that i dont like seraching, because none of them doing GREP in place :(
it is always iterating over search results, either in separate list, instead of presenting in place..
probably i should listen to you and revisit Notepad++ indeed, although i kind of dislike that editor project.

My problem with improving another editor's search is, in fact, that i will need to invest in that decent amount of effort.
* Either you invest in editor tool to improve it's search abilities, 
* either you invest in search tool to improve it's editing abilities.
Looks to me so that the pretty same problem is laying in both approaches :)
I more appreciate good searching, so i go to the best searching on the first hand, and try to go from there to better editing.

> You do know that in dnGrep you can open search results in your editor of choice, right?
> Maybe there is something that can be done to improve opening files in the custom editor?

yes i do, but that is not "in place" .. 
again, i agree, probably i should try to start using it, and probably i should invent there, for example, some way to jump/switch efficiently between dnGrep and editor, and vice versa.

> The only difference is then keeping the fork as your own project. 
> ...
> You will learn a lot along the way, I know I have.

right, i am in direction to do it myself, i am sure u have a lot to do with other more requested features or whatever bug fixing.
right, i am afraid of many-many-many stuff i will have to crush in on the way :((

Well, time will say, and thank you for your kind words :)
