### ISSUE TITLE
Replace Text in docx files doesn't work

### ISSUE THREAD

**Issue by federik95** [dnGrep/dnGrep#533]
I tried the software but it's not possible to replace the text in various .docx files, can you fix it? 
"Replace" button it's not available, I can't click on it.

Attacched a screen: 
![immagine](https://user-images.githubusercontent.com/43792676/130509951-8178cd79-1e2b-40ca-84f1-243b95edd6a5.png)

Thank you

**Comment by doug24** [comment]
That's right, replace is only supported for text files, not for any type of binary file.  That excludes Word, Excel, PDF, files in archives, digital book files, etc.  The search on those files goes through some intermediary process or library, so dnGrep cannot rewrite those files directly.
