### ISSUE TITLE
Searching a folder containing .doc files with macros runs the macros

### ISSUE THREAD

**Issue by mrb113** [dnGrep/dnGrep#539]
## Scenario 
Perform a grep search in a folder containing a .doc file with macros.
(note: must be .doc. Newer OOXML-based Office file formats such as .docm are processed safely by dnGrep 😊)

### Expected behavior
Searching does not result in arbitrary code execution on my machine

### Actual behavior
The Office macros embedded in the document run as part of the grep search.

### Impact
Similar to how I wouldn't expect grep to launch an .exe on my behalf, I wouldn't expect grep to launch macros without user interaction. If I've downloaded a file with macros, I might not want them to run without first checking out the document. If I perform a grep in my downloads folder, but I downloaded a sketchy email attachment that had macros in it, I don't want dnGrep running the macros for me without user interaction. I expect to be able to grep safely without running executable code. 

## Fix
When invoking the COM object model to launch a document, set `msoAutomationSecurity` to `msoAutomationSecurityForceDisable`. 

- [GrepEngineWord.cs](https://github.com/dnGrep/dnGrep/blob/v2.9.349.0/dnGREP.WordEngine/GrepEngineWord.cs) Fix should go here.

### Documentation References

- [Word.Application.AutomationSecurity](https://docs.microsoft.com/en-us/office/vba/api/word.application.automationsecurity)
- [MsoAutomationSecurity Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.core.msoautomationsecurity?view=office-pia)

**Comment by doug24** [comment]
Yes, I can add that, thanks for the analysis.   

By the way, do you know any way to tell Word not to add searched documents to the most recently used files list?

**Comment by doug24** [comment]
Fixed in release v2.9.378.0
