### ISSUE TITLE
Request: Pass date fields to Everything search

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#545]
Currently the date modifier fields are ignored when using Everything search. It should be a very simple matter to append the correct values from the fields into the Everything queries, however:

    datemodified:YYYYMMDD-YYYYMMDD
    datecreated:YYYYMMDD-YYYYMMDD
    datemodified:YYYYMMDD
    datecreated:YYYYMMDD
    datemodified:lastThours
    datecreated:lastThours

The only syntax I can't replicate directly in Everything with dnGrep logic is `Past P to T Hours` where both `P` and `T` are provided, without fiddling with the values by converting the hour range to component values then using `lastThours-YYYYMMDDThhmm` where `P` is formatted as `YYYYMMDDThhmm` (that's a literal T in there!) syntax. It would probably be easier to convert both values to full ISO8601 format in those cases though.

**Comment by doug24** [comment]
The intention of the code is to apply filters such as size and date after Everything returns a list of files, and this worked at one time.  But there is a bug in checking the file info data from Everything that was preventing the filters from working - I have fixed the bug.  But it also seems like a good idea to let Everything do the date and size filtering, so I added code to append the date and size filters to the Everything search string if the are not already present in the user supplied search string.

**Comment by doug24** [comment]
Fixed in release v2.9.378.0

**Comment by shawnkhall** [comment]
It mostly works now but there appears to be a bug. The first time you search either modified/created you have to put in both the from and to dates. It's not possible to use only from or to. After you set both dates and search once it allows you to remove the from or to and use a single date.

**Comment by doug24** [comment]
I am not seeing this behavior in my testing.  I can start the application with both from and to empty, set just one or the other, and the search will filter correctly.

I may have to change the way the filter is formatted for Everything:  currently dnGrep is setting both the start and end times.  If the start time is empty in the date selector, it uses Jan 01, 1970 for start time.  If the end time is empty in the selector it uses tomorrow as the end time.  It's probably better to use Everything's  less than and greater than syntax.

**Comment by shawnkhall** [comment]
Only the selected dates should be passed to Everything. Default values make assumptions that might not be true -- and simply aren't necessary for Everything to operate.

**Comment by doug24** [comment]
I agree.  I've already changed and merged this.  It will be out in the next release.
