### ISSUE TITLE
[i18n] Reused string in different context

### ISSUE THREAD

**Issue by StoyanDimitrov** [dnGrep/dnGrep#550]
The string `to` is reused in two different contexts. This while minor hinders the fluent translation of the UI. The first two occurrences could be summarized as `from ... to ...` but the last one is more or less `between ... and ...`:

![foo](https://user-images.githubusercontent.com/10962709/133000526-650e1155-4de9-42f0-870a-49b4e50a31e0.png)

While acceptable in English it's hard to impossible to come by with naturally sounding translation that fits those two/three cases.

If you are accepting PR I could try my luck with it.

**Comment by doug24** [comment]
I'm not surprised that things like this will come up.  Yes, you can create a PR.
