### ISSUE TITLE
Specified Sort is not applied when the Search results are loaded.

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#551]
In the latest version (v2.9.378.0), when the Search results are loaded (after clicking the Search button), the results are not sorted by the specified option.
Note that I currently have "Path and file name, depth first" as my selected sort option, although I don't really understand the difference between "depth first" and "breadth first".  From my testing, it appears that "depth first" is the option that I want, given that I want the results sorted alphabetically by the full path shown including the file name  `e.g. My\Folder\To\My\files\Files1.txt`

**Comment by doug24** [comment]
Are you expecting the results to sort automatically after the search completes?  dnGrep has never done that, sorting requires click/input.   Or is there a problem with the sort order?

dnGrep doesn't auto sort because you can begin looking at results before the search completes.  You don't want a sort to happen while you are working.

**Comment by mdell-seradex** [comment]
I appreciate your quick response on this.
Honestly, I could have sworn that the previous version's results were sorted based on the chosen option, otherwise why have a default?  But now I realize that it treats the drop down section of the sort button separately from the rest.  I prefer the button that way, but I have gotten used to a bunch of tools having the separation, but that separation being meaningless because it always drops down no matter where you click on their button.

I guess what is happening then is that it seems to be parsing my directory differently than it used to.  Either that or my memory is faulty 😒.

Please note that I was not expecting it to re-sort after the search completes.

It would be nice, in my opinion, for it to perform the search based on the sort method chosen, even if it required an additional option to enable this.
That said, what is "breadth first"?  I have tried to look it up, but never found anything specific to sorting, only to searching, and while similar, it didn't seem to quite apply to me.

**Comment by doug24** [comment]
There isn't a defined search order when running with `Search Parallel` enabled.  The code finding files will walk the tree down from top to bottom, then move on to next sibling branch and so on.  But the results can come back in a different order depending on on long each file search takes.  The `Sort` feature was added about the same time has running multiple search threads in parallel in response to having an un-ordered results list.   

When you click the main part of the `Sort` button, it applies the currently selected sort options to the current set of results.

Here's an example directory tree:

-Top
  - FolderA
    - FolderA1
    - FolderA2
  - FolderB
    - Folder B1
    - Folder B2
 
Depth first order:  files in Top, FolderA, FolderA1, FolderA2, FolderB, FolderB1, FolderB2
Breadth first order: files in Top, FolderA, FolderB, FolderA1, FolderA2, FolderB1, FolderB2

There is more of a difference in deeper hierarchies and files at each level.

**Comment by mdell-seradex** [comment]
Thank you for that explanation.
And I totally missed the "Search Parallel" option.
Could it have not been on by default before?
Or maybe I turned it on once and didn't realize what I was doing to myself.
Either way, as long as it didn't change then you can close this.  I apologize for the kerfuffle. 😁

**Comment by mdell-seradex** [comment]
You are too fast for me @doug24!

**Comment by mdell-seradex** [comment]
FYI, I turned "Search parallel" off, and it still came back in what seems to be a random order.

**Comment by mdell-seradex** [comment]
I will let you decide what you want to do, if anything, about that.

**Comment by doug24** [comment]
No, I'm not going to anything about that... back in 2018 the directory/file enumeration was delegated to the AlphaFS library to add support for long paths.  It is the implementation in AlphaFS that walks the directories and files.  Internally AlphaFS calls native Windows APIs FindFirstFile and FindNextFile.  The Windows documentation says:

>The order in which this function returns the file names is dependent on the file system type. With the NTFS file system and CDFS file systems, the names are usually returned in alphabetical order. With FAT file systems, the names are usually returned in the order the files were written to the disk, which may or may not be in alphabetical order. However, as stated previously, these behaviors are not guaranteed.

**Comment by mdell-seradex** [comment]
I do see that the current documentation on FindFirstFile says this:
