### ISSUE TITLE
translate to hebrew

### ISSUE THREAD

**Issue by ronen1n** [dnGrep/dnGrep#552]
I started translating the Resources file to Hebrew and I cant open the translated file in the software so I cant see how it looks and if I'm wasting my time that's why I wanted ini file that you can see the results
Also if you can add email to make it easy for everyone to translate
[Resources.zip](https://github.com/dnGrep/dnGrep/files/7165616/Resources.zip)
Thank you

**Comment by doug24** [comment]
The file you posted is the base English resource file, so you won't see any changes loading that file.  From the Option dialog, click the `Load from file...` button, and choose the Resources.he.resx file I have attached here.  This is what you should see:

[Resources.he.zip](https://github.com/dnGrep/dnGrep/files/7165792/Resources.he.zip)

I have also added Hebrew as a language on [Transifex](https://www.transifex.com/dngrep/public/), if you want to use the tools there for managing the translation file.  You can log in using your GitHub credentials and request access to the project.  Once you have made some translations, you can download the file from transifex and load it into dnGrep to review it.

![image](https://user-images.githubusercontent.com/17227248/133350352-3b405089-c158-4ace-b758-9b1b37ca6fac.png)

**Comment by ronen1n** [comment]
I tried it now and it shows only 5 words translated and I translated much more

**Comment by doug24** [comment]
The file you posted here does not have any translations in it - maybe you posted the wrong file?   The one I posted back is one I edited using Bing Translate, which is why it has only five words.  I did that to verify that the application is reading and loading the file as expected.

**Comment by ronen1n** [comment]
Can you add my translation to the transifex website?
I translated already so much in the file
I attached the updated file 
[Resources.he.zip](https://github.com/dnGrep/dnGrep/files/7180388/Resources.he.zip)

**Comment by doug24** [comment]
I uploaded your file to transifex. 

From the application Dashboard, click "View Resource" for the select language.
On the language resource page, click on the Resources.resx item, and a dialog will pop up.  The upload and download buttons are on the dialog.

As for the RTL - I think it does show in RTL in transifex, but there is an RTL button on the translate form.

If you are referring to RTF in dnGrep itself (and it's not correct), we'll have to talk, I'm still learning what to do for that.

**Comment by ronen1n** [comment]
Good work on the translated file
I think you can remove "Everything" if its the name of the software
And also I think that for now Hebrew should not be configured as default until it's finished and we can see that it shows normal on the software because some translations looks weird like this
הפעל את dnGrep לשנות הצגה של dnGrep תפריט לחצן ימני בסייר הקבצים
If you make it start from right to left the "הפעל כעת" will be the first in the sentence like in the image
![‏‏לכידה](https://user-images.githubusercontent.com/20344644/133991012-910e6acc-6888-444a-8159-3b9cde9d7dfb.PNG)
This problem is acuring in sentences that have Hebrew with English if its only Hebrew it looks ok but not perfect becuse the order of the "word" > "box to enter stuf" needs to be from right to left but its understendable

**Comment by doug24** [comment]
I won't put any translations into a release until you tell me they are ready.

The application had not been setting the flow direction property, and I'm working on that now.  Thank-you for pointing that out.  

Do these look better?  I'm curious about message box buttons on your Hebrew Windows installation - do the message box buttons appear in Hebrew?  (I can only simulate so much on my English installation of Windows.)

![image](https://user-images.githubusercontent.com/17227248/134093876-98519610-91ea-442a-adf6-9d102d7cf0d3.png)

![image](https://user-images.githubusercontent.com/17227248/134094496-e6b85f9b-44d0-4217-927b-bf7b7c2e469f.png)

![image](https://user-images.githubusercontent.com/17227248/134094762-7a17ad35-95dc-43a7-95e1-27cb8c804593.png)

**Comment by ronen1n** [comment]
These all looks good except the message box on the second line needs to be on the right too but its understendable
Now I dont know how to translate "C_ase sensitive" ware do I put the _ in the translation "תלוי רישיות"? or i dont need it?

**Comment by doug24** [comment]
I think I have a fix for the second line alignment, but will test later.

The underscore in C_ase sets the 'a' character as the accelerator key for this checkbox, so that typing Alt+a will toggle the checkmark.  It's not necessary to define accelerator keys, it's just helpful for users who like to use the keyboard for as much as possible.  You can add the underscore in front any character and it's often the first character.  That works for left to right languages, but as I am quickly learning, lots of things are different for right to left languages, so some experimentation will be needed for Hebrew.

I've been looking more into the strings than contains placeholders, such as `{0}` where the application fills a value into the string.  Strange things happen with these strings since they are mix of right to left characters and left to right characters.  I'm still trying to get my head around it.   Someone on a forum wrote:
>Keep in mind that switching between RTL and LTR is one of the most frustrating tasks out there. You have no idea how long you'll spend figuring out what to do with numbers or English words inside RTL strings.

In the main panel results list, the top level file nodes look like this in English:
`testFiles\report2.txt (6 matches on 3 lines)`
Can you show me how you would like to see that in Hebrew so I can understand the order of the elements in RTL?

**Comment by doug24** [comment]
I've been able to get this to work, but in the translated format string I needed to add the Unicode RTL mark before the open parenthesis and first number to indicate those characters need to be written right to left and not their natural left to right.   The format string looks like this:
`{0} \u200f({1} התאמות ב- {2} שורות)`

![image](https://user-images.githubusercontent.com/17227248/134258083-aa211a00-a4d1-418b-b151-1ccc8d2a85ec.png)

**Comment by ronen1n** [comment]
Looks good

**Comment by ronen1n** [comment]
In the new version I try to load the resx file that I downloaded from transifex and sometimes its only changing the direction of the app to RTL and not loading the language and sometimes its not doing anything

**Comment by ronen1n** [comment]
Some translations needs refrash after I add them like "Regex is OK!"
"Save" text in Hebrew is little bit cut on the lest letter שמור

**Comment by doug24** [comment]
>Some translations needs refresh after I add them like "Regex is OK!"
"Save" text in Hebrew is little bit cut on the lest letter שמור

Thanks for pointing both of these out.  I have fixed some that need refresh when changing languages, but I may have missed a few more.
I fixed the button layout so text is is not clipped.  Those are hard for me to spot!

**Comment by ronen1n** [comment]
Do I need to translate "Multiline" and "Phonetic" and "Regex" or it's just the name of the search algorithm or just its name

**Comment by doug24** [comment]
I think it's up to you. It isn't necessary to translate them if there isn't a common way to express the concept.

**Comment by doug24** [comment]
Released in 2.9.428
