### ISSUE TITLE
Feature request: Option to hide missing files/red lines in Everything search

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#560]
Searching for content-based results with a disconnected drive indexed by `Everything` can easily result in tens or hundreds of thousands of error rows/red lines for a single valid result, making finding the actual matches a pain.

Please provide an option to filter these records out. A checkbox below the result set or near the `stop after first match` option that simply toggles showing errors would be fine, or an option controlled in the `Options` pane would be fine, too. I can't see myself frequently wanting to toggle back and forth for the same search parameters.

Please also consider adding "missing files" details to the status bar, something to the extent of, `Search complete - Searched 41908 files. Found 1 files in 1m 39.558s. Excluded 101240 missing files.`

**Comment by doug24** [comment]
I can see making this an option on the Options page, the main form is pretty full of controls.

But isn't searching hundreds of thousands of invalid paths really slow?  dnGrep has to run a File.Exists call on every one of them.  It just seems like you would want to filter them out in the Everything query so they don't need to be processed.

**Comment by shawnkhall** [comment]
I understand your point, but `Everything` doesn't have a concept (on its own) of `disconnected drive`. The index is still present so the paths are still going to be returned. This is OK. I'd rather have them included when I am trying to find which disconnected drive a file or folder is located on. It doesn't play well with the dnGREP search, though, since the number of potentially invalid paths can be enormous. It would be ideal if dnGREP implemented this initial check for drive access (Drive.Exists) when a drive was initially returned in the initial result list and then could skip all those results where the drive was inaccessible. This would be the ideal handling of the option to `ignore disconnected drives`/`ignore errors`. 

This came to light due to reports of a recent hack targeting IIS servers with TVSPY by replacing the website with a fake security certificate warning, that then convinced users to install malware to fix their access to the website. People are stupid. Still, better safe than sorry. :)

Anyway, in order to scan all content on all server drives the simplest `Everything` syntax would be something like `dm:last1months  public_html\*`. This finds all files on **all drives** that are children of an `public_html` folder that have been modified within the last month. With Everything alone this returns the complete list of files that need to be reviewed, even if they're on a disconnected drive. With dnGREP I can search for a unique text flag from the hijack ('extended AND transition') and quickly identify if there are any files that actually match that string and get my results, as in the case above, in under 2 minutes. Since I cycle backup drives and none are connected at the moment there's going to be files that the content can't be searched from disconnected drives. Unfortunately, this means I then have 100k red lines to scroll through before I can find the single matching result. (The matching result was the dnGREP.Settings.dat file, btw. Infinite backups are a double-edged sword.)

**Comment by doug24** [comment]
this should be fixed in 2.9.400
