### ISSUE TITLE
Searching UNC paths (\\server\share) does not work properly

### ISSUE THREAD

**Issue by SNicolini** [dnGrep/dnGrep#564]
When I try to do a search on a UNC Path (or network drive), the search just sits there not finding anything and seems to not be cancelable.  If I do the search on the actual server where the files reside (a local search), it finds it immediately.

**Comment by doug24** [comment]
It does work, I use dnGrep on UNC paths.  It sounds like dnGrep is waiting on something - do you have 'Use .gitignore' checked?  I have seen that hang or take a very long time on UNC paths.

**Comment by SNicolini** [comment]
That did the trick.  Thanks.
