### ISSUE TITLE
dnGrep...x64.msi was blocked because it could harm your device

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#566]
Every time lately when I try to download the latest version on dnGrep, I am warned that "it could harm my device".
I doubt that is the case and thought I should make you aware of this in case there is anything you can do to resolve this.
Perhaps signing the msi using a certificate would eliminate this.

**Comment by doug24** [comment]
Yes, this has been a problem #276 for years now.   It is because the installer is not signed.  Signing the installer requires a code signing certificate from a trusted root authority, and last I checked these cost a minimum of $70 a year, most are $300 a year or more.  As John said, If anyone knows a free way to fix the problem, please post.

**Comment by mdell-seradex** [comment]
From what I can see, the cheapest is about $55/year, but that is likely a US price, and it is from [comodo](https://comodosslstore.com/codesigning.aspx), but you would have to get it via here: [https://www.clickssl.net/cheap-code-signing-certificates](https://www.clickssl.net/cheap-code-signing-certificates).
You can get it down to just over $60 (US?) if you use the coupons available directly on comodo's site, if you would rather not do it thru a 3rd party site.

I'm sorry, but I didn't realize that this has been an issue for years now.  I thought when I had downloaded this app previously I had not gotten this message, although I did with the last few versions.  **Although, keep in mind that I did not get this when trying to install, but instead when simply trying to download.**

I suppose one way to prevent this message would be to provide your own downloader.

**Comment by JVimes** [comment]
Oh, it's the browser warning after download. Signing might fix it. Or distributing through the Microsoft Store, which could also support auto-updating.

I think browser and OS companies are showing more warnings these days, trying to protect less savvy users (or avoid lawsuits?).

**Comment by mdell-seradex** [comment]
After, during, before d/l, I'm unsure, but yes, that warning.

**Comment by tamusjroyce** [comment]
But this isn't an issue with v2.9.345.0 and previous? That was this year. Are you sure there isn't something else going on?

**Comment by doug24** [comment]
code signing added in v3.0.0
