### ISSUE TITLE
Not opening PDF files via custom editor

### ISSUE THREAD

**Issue by Marcos-Barroso** [dnGrep/dnGrep#572]
In a configuration to search inside PDF files, I tried to configure Adobe Acrobat as a "Custom Editor". 

In a command prompt test, Acrobat opens and searches PDF file just fine, using following sintax:

> "C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe"  /A "zoom=50&navpanes=1=OpenActions&search=Text To Search" "C:\Temp\file to search.PDF"

In "command" field, I tried with and without double quotes:

>    Command..: C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe
>    Command..: "C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe"

In "arguments" field, I also tried several alternatives:

>    Arguments: %file
>    Arguments: "%file"
>    Arguments: /A "zoom=50&navpanes=1=OpenActions&search=%match" %file
>    Arguments: /A "zoom=50&navpanes=1=OpenActions&search=%match" "%file"

I my computer, Edge is default PDF viewer, not Acrobat. In all cases (via "double click" or "Right-click" plus "Open with custom editor" option), Edge was activated, not Acrobat.

Is it a dnGrep malfunction (by not calling Acrobat) or am I doing a wrong configuration?

Thanks

**Comment by doug24** [comment]
Thanks, I appreciate that.  There isn't a way to donate to the project - I do this to keep the project going and improving, and I find it very useful in my day job. There are a lot of people that have contributed to it directly and indirectly (it uses a number of other open source project libraries).  The best way is if you can find a way to contribute something to this project or another freeware project.

**Comment by doug24** [comment]
Fixed in Released in 2.9.428
