### ISSUE TITLE
Consider add an option to disable preview in replace?

### ISSUE THREAD

**Issue by yyjdelete** [dnGrep/dnGrep#589]
It may be really slow and meaningless when try to open an huge single line file(something like xxx.min.js)
All thing in red box is not required if preview is disabled
![image](https://user-images.githubusercontent.com/1819074/142140902-f904bd1c-ff31-42ba-94cb-0b2267873155.png)

**Comment by doug24** [comment]
Added new option in 2.9.482 to remove the file preview.
