### ISSUE TITLE
Language Resource Update

### ISSUE THREAD

**Issue by doug24** [dnGrep/dnGrep#592]
@celeron533 @StoyanDimitrov @comradekingu @BambuschJ @ronen1n

Two pull requests have been merged with additions to the language resources: #590 and #591.  

When you have some time, please update the language resources.  The source Resources.resx file has been updated on both [Weblate](https://hosted.weblate.org/projects/dngrep/dngrep-application/) and [Transifex](https://www.transifex.com/dngrep/dngrep-application/resourcesresx/), or you can edit/update the language resource file directly and create a pull request or post it back here and I will commit the changes.

These strings have been added:

Options Dialog:
Options_HexSearchResultLineLength
Options_FilesAndIndividualMatche
Options_FilesOnly
Options_ReplaceDialogLayout

Replace Window:
Replace_NumberOfMatchesMarkedForReplacement

<img src="https://user-images.githubusercontent.com/17227248/143786729-c1612bd4-b837-4b51-a659-cc51bb6659f1.png" width="60%" />

<img src="https://user-images.githubusercontent.com/17227248/143786831-98112623-8cb7-4081-9308-a7c7503d8df3.png" width="60%" />

**Comment by comradekingu** [comment]
What is the preferred method of improving the source files?
It is pretty grim.

**Comment by doug24** [comment]
Grim? I guess you'll have to explain that to me.  Improve in what way?

**Comment by comradekingu** [comment]
6 strings are "dnGREP", whereas the rest are "dnGrep".
From the images above
"on main panel" should be "on the main panel" (marked noun error)
"in options expander" should be "in the options expanded" (marked noun error)
I am thinking that is ~"in the options dropdown"
"tool tips" should be "tooltips"
"file path" should be "filepath" (not talking about the path of a file)
"result lines" should be "resulting lines"? or "output lines"?
"panel" is superfluous
"Show 2 preceding resulting lines and 3 after" is a better sentence, but I have no idea what it means.
"file name" should be "filename" x2
"Only allow" is the logical sequence of words 
"results tree" should be "result tree"
"show verbose match count" could be "show tally of verbose matches" (if that is what it means)
"show file info tool tips" is the type of string that 

To be continued

**Comment by doug24** [comment]
Many of these are fair criticisms, but some are intentional.  "Search for:" and "Replace with:" are done that way to match the same fields on the main window.  There isn't a natural way to do plurals - should I have created more string resources to handle both the plural and singular forms?  I did not, because I was trying to make it less work.  Yes, I could have combined the two strings on the Replace window.  I made that choice because the existing string was already translated, and the other option would be to make the existing key obsolete.

But yes, all these things can be fixed.  Some have been this way for a long time, and some are mine. Obviously my priorities have been elsewhere.  I can take a shot at fixing the base English strings, or if you want to do it, I'd be happy to take the input.

**Comment by doug24** [comment]
@comradekingu  - yes, you can make changes to the values there.  If you want to make changes to the keys, we'll need to discss and coordinate them.

**Comment by doug24** [comment]
@comradekingu - I did not realize that changing the English resource strings would cause Weblate to reset all the translations of those strings.  That seems very counter productive.

**Comment by doug24** [comment]
@celeron533 @StoyanDimitrov @BambuschJ @ronen1n @GflowerG

I know it's long, and I appreciate you reading - Doug

**Note to translators:**

I made changes to the base English resources (summary below). There are no additional new strings beyond those listed in the first post of this issue.  The changes to the English resource didn't change the meaning or use of any existing strings. The changes are intended to improve consistency and clarity.  

I assumed making these changes would not have any affect on the existing translations, and that translators could keep or update their translations at their own discretion and on their own schedule. I was wrong. When I merged the changes into the master branch, Weblate picked up the changes and reset all the translated strings back to English for every string changed in the base resource file.  That is hundreds of translations reset.  Lesson learned.

Background:  to qualify for Weblate hosting they require that Weblate has the git repo URL to pull changes from master, and a branch where it can push commits.  When the English resource was changed, Weblate reset all these translations and pushed those changes to it's branch for all of the translations, not just the ones created or edited on Weblate.

I'm guessing the rationale is that when the base string is changed, the translator should review the change, and either update or restore the previous translation.  However, many of these changes were nothing more than changing a letter from upper case to lower case.  But my biggest concern is that all of the existing dnGrep translations were done outside of Weblate (other than about a dozen Bulgarian strings), and the translators have no idea that Weblate has overwritten their translations.

With the help of git history, I made new commits to restore the previous translations.  I think that I got them all, but there were so many I may have missed some.  

I'm sure someone out there is thinking I should not have done this, but really, I can't see forcing each of you to redo your work.   And not having the translations means that I am blocked from doing a release until everything was fixed.  That is probably a good workflow for a commercial project with a dedicated translation team and a fixed project schedule.  But I don't know how it could work on an all-volunteer project like dnGrep.

I'm going to pause now, and not make anymore changes for a while.  I would like to do a release before the end of the year.  If you want to make updates to your translations, now would be a good time to do it.  Let me know if you want more than about two weeks.

***One more thing:*** one person on Weblate has started making changes to the previously released translations. I'm sure there will be more going forward.  How do you want to manage this?  Should we automatically accept submitted changes?  Do you want to review them first?  I don't know much about Weblate, so if anyone can suggest settings for managing this, I would appreciate it.

Summary:
Changes to English language resource including many of comradekingu's requests and using the Microsoft [Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/).
* Change labels to `Sentence case` consistently from `Title Case`.
* Change `dnGREP` to `dnGrep`
* Change `Regex` to `Regular expression`
* Change `Hex` to `Byte`
* Change `Asterisk` to `Wildcard`
* Expand some abbreviated terms and phrases
* Change three periods to the the Unicode ellipses character
* Revise the text in message boxes for clarity
* Removed double spaces
* Fix spelling
* Changes to the Main, Options, and Test window layouts to accommodate longer strings

**Comment by GflowerG** [comment]
> _**One more thing:**_ one person on Weblate has started making changes to the previously released translations. I'm sure there will be more going forward. How do you want to manage this? Should we automatically accept submitted changes? Do you want to review them first? I don't know much about Weblate, so if anyone can suggest settings for managing this, I would appreciate it.

I am a dnGrep user, and it doesn't matter to me what changes have been made to the localization. The main thing is that the change should be logical and without vandalism.

**If my translation is really good, then it is unlikely that anyone will want to change it. If my translation is not good enough, then I have nothing against positive changes.**

Since I am a dnGrep user, I will notice negative changes while using the application. I want to believe that the localization quality will not degrade.

**Comment by doug24** [comment]
Thank-you!

Going into the translation process, there is lots I did not know, and I didn't want to dictate tools or process, so I gave lots of options. I didn't know about these online tools. Now I'm concerned with merge conflicts and I can't be the one deciding what goes in to the release.

I have a request:  Can everyone use [Weblate](https://hosted.weblate.org/projects/dngrep/dngrep-application/) for editing and adding translations?  This way there is a single stream of commits going into the product and any change resolution will be done there and not in git merges.  

I'll update the translation instructions on the discussion page as soon as I have a chance.

**Comment by GflowerG** [comment]
> I have a request: Can everyone use [Weblate](https://hosted.weblate.org/projects/dngrep/dngrep-application/) for editing and adding translations? 

I can, but I do not know how :)

But you already answered this:
> I'll update the translation instructions on the discussion page as soon as I have a chance.

**Comment by doug24** [comment]
I revised the text in opening post on the 'Help Translate dnGrep' discussion [here](https://github.com/dnGrep/dnGrep/discussions/538), with instructions for using Weblate.

**Comment by StoyanDimitrov** [comment]
I don't mind Weblate. Go on and don't worry.

What have a slight demotivation effect is that I can not track the real progress because the non translated strings are filled with the English ones and the project is always translated 100%. But that's unfortunately how the `resx` work, I guess. I don't expect you to run and fix this as I'll catch it up sooner or later. As I said don't worry.

**Comment by doug24** [comment]
You can use the [Unchanged translation](https://hosted.weblate.org/translate/dngrep/dngrep-application/bg/?q=check%3Asame&offset=2) check, which will find most of them.
