### ISSUE TITLE
PowerPoint search

### ISSUE THREAD

**Issue by doug24** [dnGrep/dnGrep#612]
PowerPoint has been added as new searchable file type to OpenXML plugin.  

The search results are shown with the slide number as additional information, similar to the way the Excel matches are reported.

<img src="https://user-images.githubusercontent.com/17227248/147839902-b6da7629-f7da-470d-b004-53c0ef8aab2c.png" width="500"/>

@celeron533 @StoyanDimitrov @BambuschJ @ronen1n @GflowerG
There is a new string resource on Weblate for translation:
Key is Main_PowerPointSlideNumber which in English is `Slide {0}`

**Comment by celeron533** [comment]
zh_hans translations have been updated on Weblate,

**Comment by doug24** [comment]
added in v3.0.0
