### ISSUE TITLE
Feature suggestion - Option to lock folder path and file regex together

### ISSUE THREAD

**Issue by kevinj2016** [dnGrep/dnGrep#616]
This is a small feature suggestion. I find that 99% of the time I search for the same types of files in the same folder trees. *.cs in my source code folder tree, *.xml in my data storage tree, and so on. 

It would save a click if, when I chose a folder from the previous folders dropdown, the same previous file match regex was also loaded. The main idea is to treat folders+file regex as pairs in the previous folder list. That way, restoring a previous folder would also restore the previous file regex that it was using.

I suppose it would be possible to even show the folder|regex as a pair in the dropdown list, like so:
c:\my\root\data\folder | *.xml
c:\my\root\code\folder | *.cs

**Comment by doug24** [comment]
If I understand what you are asking, you can do this now with dnGrep's bookmarks.  Set up the filters you want and click the big plus symbol next to the 'Test expression' button.  That creates a bookmark and associates the bookmark with the folder.  When you choose the folder, the bookmark properties applied.

You can associate the same bookmark with multiple folders, and you can edit the bookmark from the Bookmarks menu.

**Comment by kevinj2016** [comment]
Hi Doug, thank you for your fast response. I am now aware of the bookmark facility (for search expressions) and the ability to associate a search expression with a folder. That's a triplet now (folder, file regex, and content regex). Unless I misunderstand the capabilities of bookmarks and the big plus sign, that's not quite what I was after.

I was talking about combining (bookmarking) the folder + file regexs into a pair that did not include the content regex expression. That way I could bookmark the file sets that I am always interested in, and then manually enter different content expressions as required.

**Comment by doug24** [comment]
Your use case still feels very much like the dnGrep Bookmarks, so I don't really want to add a new feature for this scenario.

Thinking out loud... originally Bookmarks were a way to store regular expressions (or XPath queries), and only a few fields were saved in the bookmark.  Then over time there requests to add more and more fields to the bookmark, and now it includes almost everything.  But the bookmarks are monolithic, replacing everything when applied.  Now it would be nice if you could choose what to include in the bookmark, and what is left untouched when applying the bookmark.  But I don't want to add a new flag and checkbox for every field in the bookmark, that's just too cumbersome.  So maybe there can be a few groups of fields...

**Comment by kevinj2016** [comment]
Hi Doug, thank you for providing some history and your thoughtful reasoning. I totally understand feature creep and complexity and the monolithic bookmark design. I can easily understand my use case of "search in my code folders and C# files" (folder+file match pair) - doesn't every programmer using dnGrep search the same folder+filematch pairs when they are working on a project? Each big project or folder tree would have such a pair. 

I can somewhat understand the use case of "search in my regular spots for my regular content regexes" if I had a steady flow of new incoming files to perform the same search/replace on. (But I can't think of where that would be the case. Under what popular use cases would the same file contents and search/replace fields be used?) I do appreciate your replies and thoughts. That's been the best part of my experience posting issues here. Thank you for at least engaging in a conversation about it.

**Comment by doug24** [comment]
added in v3.0.0
