### ISSUE TITLE
Grep Icon Improvement

### ISSUE THREAD

**Issue by Mr-Administrator** [dnGrep/dnGrep#617]
Hello, I have cleaned up dnGrep's icon, as well as increased the color saturation and contrast a tad bit. Don't know if you care about this, or not, but it looks nice on my Windows desktop. (I'm sort of fussy about theming and icons and such :))
![](https://i.imgur.com/iv5mElN.png)

![](https://i.imgur.com/4bg5n2i.png)

Folder of .png files in the .ico archive 
https://github.com/Mr-Administrator/dnGrep/tree/master/DnGrep%20%20Icon%20.pngs

https://raw.githubusercontent.com/Mr-Administrator/dnGrep/master/dnGrep.Group.ico

On your repository page:
![Screenshot ](https://user-images.githubusercontent.com/74359538/148150914-e1171004-5f7b-456b-8dda-90322c45b157.png)

On my fork of dnGrep:
![Screenshot 2](https://user-images.githubusercontent.com/74359538/148150863-51e1fd74-4741-4dbc-902c-dc7e260f832f.png)

**Comment by doug24** [comment]
Thank-you, I will use them!
