### ISSUE TITLE
Dont find regular expression with \. at the end of pattern

### ISSUE THREAD

**Issue by harri-b** [dnGrep/dnGrep#635]
Hi!

First: great tool!
But following issue in Version 3.0.0.0:
I am searching for **TreppenArt.RATE** in my sourcecode. 
When searching with regular expression **TreppenArt\\.RATE** there are several matches.
But no match, when searching with regular expression **TreppenArt\\.**
It works in "Test Expression" Dialog. Problem only, when really searching.

Greetings, Harri

**Comment by doug24** [comment]
Yes, I see this problem too, and it shouldn't be too hard to fix.  It will also fail in the Test Expression dialog if you put a newline at the end of your Sample input text.

Long story is that the .net regular expression library does unexpected things when matching newlines: it will match Unix newlines` \n` but not Windows newlines `\r\n`, or the old Mac newline `\r`.  I have code to make it match match all forms of newlines the same, but forgot to account for the case of when the trailing dot is escaped.

**Comment by doug24** [comment]
Fixed in v3.0.29.0

**Comment by harri-b** [comment]
Thank you, great work!
