### ISSUE TITLE
[UX] Give some configuration templates for "Custom editor" and "Compare application"

### ISSUE THREAD

**Issue by celeron533** [dnGrep/dnGrep#638]
Hello @doug24 ,

I am not quire sure is it worth to implement this feature...

Currently in Options window, user can set the "Custom editor" and "Compare application". However, for some well-known applications, such as `vscode`, `notepad2`, `meld`, `kdiff`, users still need to config the command and arguments by themselves, like the screenshot below.
![image](https://user-images.githubusercontent.com/3608762/154419888-6e0f4d67-c2d8-4e6f-91c6-e8f3eafda32f.png)

I also use "Git Extensions", and it has some presets for Merge tool and Diff tool.
This makes it simpler to config:
![image](https://user-images.githubusercontent.com/3608762/154420193-62938153-2b07-4f66-b365-674df6fe22fc.png)
![image](https://user-images.githubusercontent.com/3608762/154420198-fbfc0de5-136d-4900-b1df-9d39074e16aa.png)

Regards,
c533

**Comment by doug24** [comment]
Thanks for the suggestion.  There are three of examples on the [help page](https://github.com/dnGrep/dnGrep/wiki/Custom-Editor-Integration), but it would be nice to have more to add them to the Options dialog.  If anyone has another configuration they use, please reply here and I will collect them (and save me from installing several apps to test them).

**Comment by celeron533** [comment]
Perhaps we just need to give more configuration samples on wiki page and gives a hyperlink on the software's config page.

**Comment by celeron533** [comment]
# Configuration for **VSCode**:
## Custom editor
Command (depends on how you install. VSCode could be installed for everyone, like the sample below. Or it can be installed for current user only)
```
C:\Program Files\Microsoft VS Code\Code.exe
```
Arguments
```
-g "%file":%line:%column
```

## Compare application
Command
```
C:\Program Files\Microsoft VS Code\Code.exe
```
Arguments
```
-d
```

**Comment by doug24** [comment]
I created a PR to add this to the application.  I have templates for Atom, GVim, Notepad++ and VSCode for editors, and Beyond Compare, KDiff3, Meld, P4Merge, WinMerge, VSCode and VsDiffMerge for compare applications.

You can still configure them manually, as before.

If anyone is reading this and would like to add another, please reply.

**Comment by doug24** [comment]
Initial release in v3.0.29.0
