### ISSUE TITLE
Does dnGrep activate Microsoft Windows Search Indexer?

### ISSUE THREAD

**Issue by raelb** [dnGrep/dnGrep#653]
I recently installed a few grep programs, so not sure which one is the cause. But I noticed that "Microsoft Windows Search Indexer", is now showing in the Task Manager. Is this something that has been activated by dnGrep? If so, how to prevent this from happening? I don't want the Microsoft Search Indexer to be running.

**Comment by doug24** [comment]
No, dnGrep doesn't use Windows Search Indexer and does not do anything to start it.

**Comment by doug24** [comment]
Sorry, didn't mean to be so terse. The answer is the same, but welcome to dnGrep, and I hope you find it useful.  You can un-install the other grep programs now ;)

**Comment by raelb** [comment]
hehe - no offense taken. I was happy to get a quick answer from you, so thanks for that.

> You can un-install the other grep programs now ;)

Good one!
