### ISSUE TITLE
Feature Request: on Windows, add option to skip searching within SharePoint files that aren't downloaded yet

### ISSUE THREAD

**Issue by BoxingLaunch** [dnGrep/dnGrep#660]
SharePoint/OneDrive on Windows have the option to not download files from the server until they're accessed. It would be great if there was a checkbox we could use to exclude these files from the search so that the search can happen faster.

**Comment by BoxingLaunch** [comment]
That is correct!

I believe that OneDrive and SharePoint files are stored in the exact same way, so if you can test with OneDrive, that'll be sufficient!

**Comment by doug24** [comment]
This is released in v3.0.64
