### ISSUE TITLE
Docx read-only, can't replace text.

### ISSUE THREAD

**Issue by jaddel** [dnGrep/dnGrep#661]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/46263124/163408901-362de575-3db9-4e4d-9dee-c9be669f60ec.png">

I checked all the files and they are not write protected any ideas why dnGrep reads them as read-only?

**Comment by doug24** [comment]
dnGrep does text replacement in plain text files only.  It does not do replace in binary files like Word, Excel, and PDF, or any files in archives.
