### ISSUE TITLE
Feature Request: add option to search filenames for the same pattern as the main search criteria

### ISSUE THREAD

**Issue by BoxingLaunch** [dnGrep/dnGrep#662]
When I'm searching through files, I want to show all files that contain the search criteria within them, but _also sometimes files whose **names** contain the search criteria as well_, or both.

**Request:**
* Add a checkbox in the main Search section called "Also search filename for pattern". 
    * When unchecked, the search will perform exactly as it currently does. 
    * When checked, files with a filename matching the main Search pattern will also be shown, and the matching substring in their filenames will be highlighted in the search results pane.

**Comment by doug24** [comment]
I'm not sure I understand what you are asking for. dnGrep has two distinct parts:  what files to search (file filters), and what to search for in those files.  The file filters already allow you to create regular expressions to find patterns within the file names. 

If I understand correctly, when applying the main search patterns to file names, it would not expand the already filters list of files to search, but only look for a pattern in the file name.  And that file would also show up in the results as a match if the main search pattern matches the file name, even if there are no matches within the file (along with all the other results that have matches within the file).

I have to say I'm very reluctant to do things like this.  I don't think it's easily understood and unlikely to be used much. I've done some in the past and it just adds to the difficulty of maintaining the application.  This feature would require changes in a number of places in the application.
