### ISSUE TITLE
Feature Request: advanced option to change how many files to search in parallel

### ISSUE THREAD

**Issue by BoxingLaunch** [dnGrep/dnGrep#664]
How does the system currently choose how many files to search in parallel? 

It would be helpful if there was a way to configure how many files to search in parallel, because the ideal number is probably much higher when dealing with cloud sync systems (like OneDrive), as there is huge latency in fetching even small files.

**Comment by doug24** [comment]
It sets the number of concurrent tasks to be 80% of the number of logical processors.  For example, with a 4 core CPU and 8 logical processors, the max degree of parallelism is 6.  

At one time I found that not setting a max limit caused the UI to be non-responsive for periods of time.  Trying it again, I'm not that happen now.  Not setting a limit means the it will utilize however many threads the underlying scheduler provides.  That may be a better option.  But on my dev machine, I don't see any difference setting it to 80% vs. no limit.

**Comment by doug24** [comment]
Added in v3.2.279
