### ISSUE TITLE
Suggestion: `Shift-F3` / `Shift-F4` to jump to the next/previous File match?

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#665]
Good morning
**thank you very much for sharing your great work!,
the command line `grep` is great, but `dngrep` feels like the next generation :-)** 

I have a probably small suggestion.
* By using F3/F4 we can jump to the next / previous match
* Often it becomes clear very quickly that in the current file is not what you are looking for
* Then one would like to jump to the next / previous file in the search results

### Therefore my suggestion:
Could you please think about it to support e.g.:
* `Shift-F3`: Jump to the first match in next file
* `Shift-F4`: Jump to the last match in previous file

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
Thanks for the request, I have this done for the next release.

**Comment by schittli** [comment]
Thank you so much for your incredibly great product care!

**Comment by doug24** [comment]
This is released in v3.0.64
