### ISSUE TITLE
feature request: show rows preceding a keyword hit

### ISSUE THREAD

**Issue by UsykTrading** [dnGrep/dnGrep#680]
Hi all, 
When searching through PDF files, I often try and figure out the context in which my keywords are being used. 
Currently, it is possible to add lines after the keyword hit by adjusting the second "show context lines" number to a higher number. However, using a negative number instead of 0 for the first number does not result in rows/lines preceding the keyword hit showing up. Would it be possible to add this feature? 

Many thanks!

**Comment by doug24** [comment]
The context lines do work for PDF files, see an example below.

PDF files are a real pain/problem for doing text searches.  First thing to understand is dnGrep searches plain text - so when starting from documents like PDF, Word, Excel and PowerPoint, dnGrep first extracts plain text from the document as best it can.  PDF is by far the most difficult.  A PDF file is not a text document, it is a set of print instructions - as in:  put a character or range of characters with a specified format at a location on the page.  A word may be multiple print instructions.  There is not concept of a sentence, line or paragraph. The instructions may not be in reading order. Converting PDF to plain text is a completely separate operation from the visual representation you see on the screen or printed page.  The conversion software starts with a collection of letters at x,y locations and uses algorithms to collect them into words and lines of text based on 'near-ness'.  This is difficult and error prone.  I have examples of documents if you open them in Firefox, Chrome or Edge and select some text you see on the page and paste it into another application you will get a different set of characters than you see and selected on the screen.  Not surprisingly, Adobe Reader does better.

Currently dnGrep uses an external application 'pdftotext.exe' to do the conversion.  You will find the output of that conversion in your temp directory.  Look for a folder dnGrep-xyxyxy (bunch of random characters) and dnGREP-PDF under that.  You will find a text document with the same file name as your original PDF.  You can open that with notepad or other text editor to see the conversion.  I have tried other libraries to get text from a PDF file, and haven't found anything particularly better, just different.

Here is a sample:  first the PDF file in the Edge browser, second the plain text extract, and third the dnGrep results window.

Is your problem in the PDF to text conversion, or are you seeing something different?


<img src="https://user-images.githubusercontent.com/17227248/172473673-6bfc3c90-8741-42bd-9aa2-f874b36502e1.png"/>

<img src="https://user-images.githubusercontent.com/17227248/172473725-5f6dca59-5b01-4988-afc5-264e6d9fd5ea.png"/>

<img src="https://user-images.githubusercontent.com/17227248/172473764-96845b69-83c9-4bf4-b9b2-2010218c9f88.png"/>
