### ISSUE TITLE
Enhancement: Statistics and status bar

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#682]
When searching a directory with many files, and expecting numerous matches, there's no way to view the total number of matches found without saving the results as a report.

Would it be possible to include total matches found in the status bar?

Example: `Search completed in 4.783s - 692 matches found in 130 files of 1302 searched`

…or maybe add an option to view the report in the preview pane?

**Comment by doug24** [comment]
Thanks for the suggestion. I think it should be pretty easy to add to the status bar.

**Comment by doug24** [comment]
released in v3.0.84.0
