### ISSUE TITLE
Publish releases to Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [dnGrep/dnGrep#697]
With every new release of dnGrep, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

* References: https://github.com/dnGrep/dnGrep/issues/438

**Comment by doug24** [comment]
Yes, a PR for this would be great.
