### ISSUE TITLE
Option to show only matched strings

### ISSUE THREAD

**Issue by mschoebi77** [dnGrep/dnGrep#698]
When working with regex searches, I would find it useful to have an option to print and export only the matched part of a matching  line, and not always the entire line. The traditional grep provides the option --only-matching for this purpose.

Would such an option be of interest and could be added in a future release?

**Comment by doug24** [comment]
Yes, I can take a look at this.  It may be a while before I have time to work on it.

**Comment by JoPat27** [comment]
I can only agree with the previous speaker, this feature is unfortunately missing so far. At the moment I have to export/open everything in Notepad++ and search there again.
Here I can then only copy the matches or save it as a result. With the normal Grep, it is probably the -o option, which only displays the matches.
The option in dnGrep would be "Copy matches only" or "Save matches only". That would be great :-)

**Comment by doug24** [comment]
Here's what I'm planning - any comments?

* The results tree and preview windows will unchanged - showing the full search results in context.
* Make two output commands - Copy and Save - on the "More" drop-down.  
* Each match would be written on a new line, even if there are multiple matches on the same line in the source file.
* Duplicates will be preserved - or should it include unique values only?
&nbsp;

<img src="https://user-images.githubusercontent.com/17227248/178772612-5dad055e-0a7d-48b3-b028-53248b4cc1fa.png" Width=360/>

**Comment by 4rn0nym1337** [comment]
I can only support mschoebi77 and jopa27. I can also make good use of the feature if it when it is realised.
Maybe "Matches only (uniq)" as a additional point in the menu under "Matches only" would be good

**Comment by mschoebi77** [comment]
Dear Doug,

Many thanks for sharing the proposal! May I ask in which format the matches
would be saved, once the functionality is invoked? Would it still provide
the relationship to the file and the line where it was found?

At least in my usecase (which might not be representative), it would be
beneficial if it was more like an option to the existing "Save
results" mechanisms, and not an additional one.
It could be a checkbox in the same menu ("matches only"). If the checkbox
is checked, and the user then invokes any of Report/Text Results/CSV
Results, then the export contains only the matched string.

Another alternative could be to handle it like the "show context lines" in
the preview. Showing the full line could be considered like a
'horizontal context'. There could be an option "show full line", which is
by default enabled. If it is enabled, the whole line with the match is
displayed (today's behavior). If it is disabled, then only the match is
displayed in the preview. The save options would then behave identical to
before. They just export what is being displayed in the preview.

Regarding the duplicates: for me, it would be fine if the duplicates were
preserved. But I could imagine that it might be handy to have an additional
option to clean up duplicates.

But those are just suggestions. I would also be happy with the approach
suggested by you.
Thanks for your efforts!

Best Regards
Max


Am Mi., 13. Juli 2022 um 17:48 Uhr schrieb Doug P ***@***.***

**Comment by doug24** [comment]
@mschoebi77 @4rn0nym1337 @JoPat27 

The format I currently have implemented for this is plain text with each matched string on a new line.  There isn't any file context or line numbers.  This applies to both `Copy matches only` and `Save matches only`.  I also have implemented matches-only as a command line option.

My assumption was that the use case is to extract only the selected data from the files that would not need to be 'cleaned' any further by manually removing file names and line numbers.  For example, if you search using a GUID regex, you will get a plain text file with a list of GUIDs, one on each line.

Can you describe what you are trying to get by 'matches-only' but also including the file and line information?  Maybe I am just thinking of 'small' matches: is your use case to strip part of the line and retain/match most of the line? 

If there are multiple matches on the line, how would multiple matches be shown?

I am reluctant to change the results list to have another format option.  Using the GUID example again, how would you show two or more GUIDs on the same line in the results tree?  

For the existing report formats: 
- the CSV report has three columns: file name, line number, and line text
- the Report format has file and search information, then line number and line text
- the Text format has just the matched lines, with no context
 
So yes, 'matches-only' could be an option to each of these reports and the `Copy results` command.  'Unique' could be a second option. I'm not sure where to put those options right now, I will have to think about it.  And we have to figure out how to handle multiple matches on a line when written in these formats.

**Comment by mschoebi77** [comment]
Thanks for the explanation! 
In my use-case, I am frequently converting non-structured or semi-structured text into structured information. One example use-case is attached: [example-report-00001.txt](https://github.com/dnGrep/dnGrep/files/9118059/example-report-00001.txt)
 There, I have ~10.000 reports in a filesystem, each in txt files with running numbers, I'm extracing the order-id ('ABCDEFGHIJKLM'), the study quality ('excellent') and the CAD-RADS grade from the conclusion ('CAD-RADS 3'). The goal is to have one spreadsheeet that provides order-id, cad-rads grade and study quality in separate columns.  Within dnGrep I'm currently solving this by performing three regex searches (one for the order-id, study quality and cad-rads grade separately) and saving those as three CSV files. I later-on establish correspondence between the queries based on the filename and do data cleaning in a separate step outside of dnGrep. I was hoping to be able to omit separate data cleaning steps by using the "match only" option. 
=> In my use case it would be important to use an export option that preserves the filename (line numbers don't matter)

Multiple matches per line do not exist in that use-case. But if it occurred, then one way to handle it could be to save it as separate rows, with identical line numbers. 3 hits in one row would lead to 3 rows in the saved file, with the same line number.

I understand your concerns regarding the preview in the results tree. From my perspective, it could just be visualized as-is. Each of the matches would be visualized by the yellow background in the same line.  If there was an option to show the matches only, then still there would be multiple yellow matches visualized in the same row (mayb eseparated by a space, to make it comprehendible).

**Comment by JoPat27** [comment]
Dear Doug
- in case of multiple capture groups (as search regex) these should be written in one line separated by comma or semicolon
	--> foreach match.value in Capturegroup ....--> value1, value2, value3 or value1; value2; value3 (Delemiter flexible adjustable in Settings, can also be Space would be nice :-)
- if there is no or only one capture group, I think there should be a listing with New Line (one below the other with New Line)
- or leave everything as it is and additionally give the option -> to copy out the yellow marked hits or save or report ...
- for the performance a search with "Matches Only" would be better than to extract only the matches afterwards.
- Possibility to use 2 buttons "Search" and "Search (Only Matches)" or we use a checkbox "Preview Only Matches" near the "Search" button.
- with checkbox the subsequent selection of the checkbox would have to be intercepted (i.e. renewed search with the corresponding parameters)
- Checkbox above Search Button ? Here possibly also the checkbox for "Unique".
- For the results under button "More" the menu would not have to be changed, "Copy Results"/ "Save Results" only of the matches
- More" --> "Save Results" --> "Report" -> Filenames + Matches are saved
- Text Results" -> Matches only as Text
- CSV Results" -> Matches only as CSV (comma or semicolon can be set in the settings because of problems with numbers (Float: 100,55))
- haven't managed to look at the source code yet, I'm on holiday for 3 weeks now, maybe I'll make it there ;-)
- otherwise I could possibly make a more useful recommendation, ultimately you have to see what makes more sense

Regards :-)

**Comment by JoPat27** [comment]
@mschoebi77 
try out regex search with "OrderID:\s([A-Z]+)\s+PatientID:\s([0-9]+)\s+.*?(\(CAD\-RADS\s\d+\))\..*?None\."
and replace with "$1,$2,$3" -> press button "Replace" and here "Replace in File" (overwrites the file, work with a copy"
result: ABCDEFGHIJKLM,0123456789,(CAD-RADS 3)
If Doug does it in this way, the result will be only the matches from the capture groups separated by commas for each of your files ....(without Replace and overwriting)

**Comment by doug24** [comment]
@mschoebi77 @JoPat27 
Following up on this idea, I used the regex `OrderID:\s([A-Z]+)\s+.*(CAD-RADS\s\d+).*quality is\s+(\w+).*`
with options `Multiline` and `Dot as newline` and the replace pattern `$1,$2,$3`
I find the Test window really helpful for working this out.

But this is different:  using this regular expression there is one match (the whole document) and three capture groups.   An only matching option would return the whole document.  We would also need an only capture groups option, which I think would also be nice to have.  Plus, options for separators, keep all groups on a single output line or each on its own line, etc.

Side note, it looks like there is a bug in the "Highlight groups" option.

<img src="https://user-images.githubusercontent.com/17227248/179238294-06e5f91d-a5e9-4363-8631-06a3c06afe7c.png" width="400"/>

**Comment by mschoebi77** [comment]
@JoPat27 @doug24  
Thanks for hinting me towards capturing groups, this helps alot.  I agree, it would be helpful to have an option for exporting "only capture groups". Still, it would be good if it was possible to keep the relationship to the original filenames (the txt file was just a simplified example), by combining it with either the existing Save as options, or having it as a separate option. Overall, that would be a very powerful extension ;-)

**Comment by doug24** [comment]
Added in release v3.0.136

**Comment by mschoebi77** [comment]
Dear Doug,
sorry, I was on vacation the last two weeks and didn't check my e-mails.
Many thanks for integrating this feature into dnGrep. I think it is a great
extension of the already great tool. At least for me, it will be very
helpful, and I hope for others as well.
Thumbs up!
Best
Max

Am So., 21. Aug. 2022 um 00:01 Uhr schrieb Doug P ***@***.***
