### ISSUE TITLE
Feature request : Total amount of match results

### ISSUE THREAD

**Issue by mathieucloutier86** [dnGrep/dnGrep#700]
Hi Doug,

Unless I've failed to notice a way to access this information, it would be helpful to know the total amount of matching result a query produce.

Currently, at the bottom of the screen, I'll get : Search completed - searched "x" files, found "found y" files in a "z time span". But it would be useful to get the total frequency of match, for what I have in mind.

Would that easy enough to implement ?

Best regards,
Mathieu

**Comment by doug24** [comment]
This sounds exactly like what I just implemented for issue #682 and released in [v3.0.84](https://github.com/dnGrep/dnGrep/releases/tag/v3.0.84.0)

The status message now says: 
Search completed in 't' - 'n' matches found in 'x' files of 'y' searched.
'n' is the total number of matches across all files.

**Comment by mathieucloutier86** [comment]
Doug,

You are correct, indeed ! I was operating a slightly outdated version and
the new version brings the change I was looking for. Sorry for that, I
checked the forum first, but my preliminary search didn't produced any
result.

I was also wondering if you have given any thoughts on the feasibility of
including NOT as a boolean operator ?

I've started using dngrep in conjunction with a Orange, a open source tool
that I use for text mining and I index my files. The addition of NOT would
be absolutely terrific for that purpose : no need for a database to tag any
content (if the filename match the filename of the tag textfile, Everything
can also be used to retrieve the file instantly), a solution made to work
out of a few open sources softwares, it's pretty much to holy grail for a
content indexer.

I'd be willing to put some money toward this if you feel this is worth your
time. In my humble opinion, this sort of approach has a game changing
potential to index personal files and could be use by millions of
non-technical people to describe and retrieve content on their drives.

Anyhow, thank you  again for your quick assistance and steadfast
development of the tool. I truly appreciate it.

Best regards,
Mathieu

**Comment by doug24** [comment]
I'm ahead you again - NOT is already supported as a Boolean operator.   See the [wiki](https://github.com/dnGrep/dnGrep/wiki/Boolean-Operators) page.

**Comment by mathieucloutier86** [comment]
I can't wait to try it out. You rock, man ! Absolutely insane how
dedicated you are on this project!

Thank you so much !
Mathieu
