### ISSUE TITLE
Bug? Expand after search with edited files shows wrong context

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#702]
I suspect this is a late-binding context thing for the purpose of performance and isn't actually a bug, but I figured I'd better report it anyway. 

The process:

1. Perform a search for a string in a set of files. 
2. Edit one of those matching files that would effect the line+column of the match.
3. Expand match for file and it will show a different context and not the match.

One would expect the context match would be highlighted, even if the file has been modified.

Simple example to replicate:

1. Create a file with the content of "abcdefghijklmnopqrstuvwxyz". 
2. Search for "abc" so that this file matches. 
3. DO NOT EXPAND THE MATCH in the results. 
4. Now edit the file to insert "1234567890" before "abc". 
5. Expand the match. 

Note that "abc" is not highlighted, but "123" is.

**Comment by doug24** [comment]
This doesn't surprise me, and I don't consider it a bug.  dnGrep is not watching for file changes in the search results and automatically rerunning the search when they are changed.  When the search is run, dnGrep saves the location of the match, but not the contents of the match.  When you expand the results, dnGrep opens the file, finds the match by location and loads the match and content lines for display.  Saving just the address is done for performance and minimizing memory use.  I guess what you are suggesting is that dnGrep rerun the search on each file as they are expanded in the results. 

Not that it makes this right or wrong, but I will note that Visual Studio, Visual Studio Code and Notepad++ all have similar behavior - when you do a search in directory or project without the file open, modify it externally, and then open it from the search results, the match will not be aligned with the original search.

**Comment by shawnkhall** [comment]
I agree and I figured that was the case. I just need to get used to using F6 when the search is done instead of scrolling first. :)
