### ISSUE TITLE
Show context lines flag not always respected

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#703]
I am unsure why this occurs, but sometimes when I do a search, some files show context lines, even though `Show context lines` is off.  Note that I did not toggle the flag, but I did sort the results (depth-first).
![image](https://user-images.githubusercontent.com/40300659/177677303-b6f2fe70-1c4f-4305-9560-c8eb49de7bbe.png)

**Comment by doug24** [comment]
I've tried this a number of times and haven't been able to reproduce it.  You say you did not toggle the flag, but did you change it after you clicked the Search button?  In the current implementation the state of the flag is saved when the search is started, and that value is used until the next search - which is why the tooltip says: "Context line changes will be applied in the next search".

**Comment by mdell-seradex** [comment]
I just discovered that if I select a file that I had not selected previously, and then expand it, it expands, showing the context lines.  I also found that if I double click a previously unselected file, it expands, showing the context lines, and previews the file.  
I believe that the former is likely the action that I took, but even if it isn't, perhaps my action causes the code to take the same route.

Aside from that, I was still having an issue with the cancel button not immediately (or at least quickly) stopping the search, however I have now installed the latest version and it seems better.  I was running the previous version and didn't see anything in the release notes regarding it.

**Comment by doug24** [comment]
OK I do see the problem now.  Selecting the file node and showing the preview takes a different path that isn't checking the flag, just the lines before and lines after.

I didn't knowingly make any changes to the Cancel in the latest release.  The code checks for cancel many places and usually responds very quickly.  If the code is in some long running operation, the operation doesn't get halted, but there should be checks before and after.  It's not obvious where that would be, I've fixed all the ones that I have been able to find.

**Comment by mdell-seradex** [comment]
Glad to hear you have the flag problem.

I am unsure what to say about the cancel.  The one thing that I believe is that when the search takes longer, the cancel takes longer.  Basically it seems that the folder list is cached by Windows on the first run, and that cache is eventually cleared if not used.  For example, after a reboot, or if I wait a few days between searches.
I have not rebooted since I installed the latest version.
I will log a new issue if I find it still occurs (unless you find something).

It was kind of bad of me to piggy back a second issue on to this.
Sorry about that.

**Comment by mdell-seradex** [comment]
It doesn't really seem like it is a specific situation, because I did the exact same search with the latest version (after that hypothetical cache was filled), and it seemed to respond as desired.  I think with the previous version too, but I no longer have it installed.
Anyway, like I said, I'll log a new ticket if I run into it again, and will include all my settings.
Thank you.

**Comment by mdell-seradex** [comment]
Note that I logged #710 regarding the cancel issue.

**Comment by doug24** [comment]
Fixed in release v3.0.136
