### ISSUE TITLE
Show the output of PdfToText in the preview pane instead of the raw data?

### ISSUE THREAD

**Issue by Dromantor** [dnGrep/dnGrep#704]
Related: #659

Just a proposal to make the preview pane for PDFs more useful.

I know that you can't show the real PDF because there is no mapping between the text you search through and the position in the real document, but just showing the text you search through would make the program much more useful. I know that the formatting is messed up in the text file but I don't care about that most of the time, I just want to find information. Everything is an improvement over raw data.

My background: When searching pdfs I mostly search in manuals for machines (currently a CNC machine with Siemens control, where the documentation is some serious clusterfuck). There I just seach for a term/heading and want to read enough of the text to know if it's worth it to open the file because it has what I need. The 6 lines shown in the search results aren't enough for that because there are lots of empty lines in the text from your pdf2text converter because of formatting.

Would be great if this improvement is at least considered.

**Comment by doug24** [comment]
OK, I'll look at doing this.

**Comment by doug24** [comment]
Added in release v3.0.136

**Comment by Dromantor** [comment]
Great, works relly well! Much thanks.
