### ISSUE TITLE
keep existing "last modified date"

### ISSUE THREAD

**Issue by terra111** [dnGrep/dnGrep#708]
The only thing I miss, when I am modifying files, is the possibility to keep the file date. 

I always have to make mass changes to TXT files (just on eight hundred .lnk files [=web favorites] the paths to the icons have to be removed, because they contain the username(!), a privacy problem!
Of course **it makes sense that the file keeps its old modification date**, because you want to know WHEN you created the favorite. And maybe you want to sort the favorites by modification date!

A way to keep the file date in dnGrep (via switch) would be I think for many users, very helpful!

**Comment by doug24** [comment]
Seems like that is just hacking what 'Date modified" means, but yes, it is possible to reset it after it has been written by the replace command.

Have you tried using the create date for sorting instead of the modified date? You can add "Date created" to Windows File Explorer.

**Comment by terra111** [comment]
Thanks for the tip with the Windows File Explorer. Most programs can not sort by it. So this is a good tip, but I think unfortunately not a complete solution for most users.

**Comment by doug24** [comment]
Added in release v3.0.136

**Comment by terra111** [comment]
Thanks for the tip with the Windows File Explorer. Most programs can not sort by it. So this is a good tip, but I think unfortunately not a complete solution for most users.

**Comment by eirens-axiomint** [comment]
Is there a user-visible setting for this (not just in the settings file)?

**Comment by eirens-axiomint** [comment]
Is there a user-visible setting for this (not just in the settings file)?

**Comment by doug24** [comment]
It isn't in the Options dialog - it is on the bottom of the Replace dialog.

**Comment by eirens-axiomint** [comment]
Thanks, @doug24. I see the setting where you indicated. 👍
