### ISSUE TITLE
Replace not enabled

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#709]
I can't seem to get Replace to work when doing a text search.  I did not try any other types as yet.
I tried entering the "Replace" text before I performed the Search, and after.
I even closed dngrep with the "Replace" not filled in, re-opened it, performed the search, and then entered the replace text.

No matter what I have tried, it will not enable the `Replace` button.

**Comment by mdell-seradex** [comment]
I just tried regex.
It doesn't work either.

**Comment by mdell-seradex** [comment]
I just found out, the files are marked as read-only.
I guess there is no built-in method to enable over-writting those.

**Comment by doug24** [comment]
My feeling is the application should respect the read-only state of the file. It could have been set that way for endless reasons. If you want to modify it, then change the state.  

Between this and the other recent request to modify files without changing the modified date, you could modify a read-only file, reset the modified date and change it back to read-only - and no one would know the file had been changed.   Maybe I'm imposing my opinion too much, but this just doesn't sound like the behavior of a good application.

**Comment by mdell-seradex** [comment]
I didn't realize the files were marked as read-only at the time.
Generally speaking I would agree with you, however it would be nice if it showed that somewhere, and allowed us to decide to override the read-only flag.

**Comment by mdell-seradex** [comment]
OMG.  I'm blind.

**Comment by doug24** [comment]
Added in release v3.0.136
