### ISSUE TITLE
This file is either binary or too large to be shown

### ISSUE THREAD

**Issue by yuis-ice** [dnGrep/dnGrep#713]
Hi. I'm new to dnGrep. I opened up a pdf on it, searched a random word, and I expected to see where the result words is correspondent to on the pdf through a built in pdf viewer, but I got an error `This file is either binary or too large to be shown` as shown below on the image attached. What is the problem with this may I know? 

![https://yuis.xsrv.jp/images/ss/ShareX-220724T134611-vZDYF0gZ~dnGREP-COVID_in_N_secure_downloads%E3%82%A2%E3%82%B9%E3%83%88%E3%83%A9%E3%82%BC%E3%83%8D%E3%82%AB%E7%A4%BE_COVID-19_%E3%83%AF.png](https://yuis.xsrv.jp/images/ss/ShareX-220724T134611-vZDYF0gZ~dnGREP-COVID_in_N_secure_downloads%E3%82%A2%E3%82%B9%E3%83%88%E3%83%A9%E3%82%BC%E3%83%8D%E3%82%AB%E7%A4%BE_COVID-19_%E3%83%AF.png)

**Comment by doug24** [comment]
Thanks for trying dnGrep.  There have been a lot of questions about PDF recently #659 #704. See my comments on those issues.  PDF is a binary file and dnGrep does not have a way to render binary formats like PDF, Word, Excel, PowerPoint, epub, etc.  

I have completed and merged the changes for #704, so in the next release you will see the extracted plain text for PDF and MS Office documents, but showing them rendered a full document layout isn't on the roadmap unless someone else is interested in taking it on.

**Comment by yuis-ice** [comment]
Okay, that's great. Thanks for your hard work on the feature. I'll look forward to see the next release.

**Comment by doug24** [comment]
Added in release v3.0.136

**Comment by yuis-ice** [comment]
Great, thanks.
