### ISSUE TITLE
Feature Request: Maximize Size of Matched File Window

### ISSUE THREAD

**Issue by PaltryProgrammer** [dnGrep/dnGrep#716]
Greetings Kind Regards Thank You for providing dnGrep May I make a suggestion re/ the matched file window. I always find it too small in the vertical direction. Two remedies come to mind. One is the nice feature in the Preview window i.e. to wit the NW pointing arrow which permits it to become a full screen window another is to automatically change its' origin to the top of the main window and eliminating all the various controls utilized to specify a search as they are not needed as the search has completed w/ of course a [Begin another Search] button which would display all the necessary controls as per usual for another search and place the matched file window again in its' usual position and size. Thank You Kindly - Best Cheerio
PS Another suggestion I am surprised is not sine qua non for all applications is a [Copy version to Clipboard] button in the About box

**Comment by doug24** [comment]
Allowing the results pane to be undocked and maximized like the preview window would be difficult.  But I think your second suggestion is good, and I will look into that. 

If we made the filter panel collapse automatically when the first file result is returned, then I would make it a user option to enable/disable the feature. Or it could be a collapse/expand button do it on request.

**Comment by doug24** [comment]
Added these in release v3.0.136
