### ISSUE TITLE
Settings File Possible Gibberish

### ISSUE THREAD

**Issue by PaltryProgrammer** [dnGrep/dnGrep#717]
Greetings Kind Regards The attached image shows a portion of the settings file. How can that not be gibberish? The settings file is also attached. Thank You Kindly - Best - Cheerio
[dnGREP.Settings.txt](https://github.com/dnGrep/dnGrep/files/9225933/dnGREP.Settings.txt)
![Settings File Possible Gibberish](https://user-images.githubusercontent.com/48535920/181905758-e0a87272-cfaf-4b11-85bc-ba16393e6504.png)

**Comment by doug24** [comment]
But it works, doesn't it? :)  Not gibberish, Base64 encoded binary data: the keys starting with "Fast" are collections of strings. This goes back before my time on the project, and does need to be converted to another format, but I haven't gotten around to it yet.

**Comment by doug24** [comment]
This has been changed in v3.0.154
