### ISSUE TITLE
Bug: "Search in archives" option not respected with Everything search

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#718]
Using 3.0.84 and Everything 1.4.1.1017 (x64)

Options:
Everything search: "c:\folder"
Search in archives: off
No hidden, no binary, no symbolic links, all sizes, all dates, search parallel, skip remote cloud storage files, include subfolders

Search will return the matching text from within every zip, gz and tar file within "c:\folder" and its children, even with the option to search in archives off:

![dngrep-everything-archives](https://user-images.githubusercontent.com/6037167/182525885-e9b569bd-a92d-4443-afe9-74bceb26c837.png)

**Comment by doug24** [comment]
Fixed in release v3.0.136
