### ISSUE TITLE
When you delete search result, cursor disapears 

### ISSUE THREAD

**Issue by majkinetor** [dnGrep/dnGrep#725]
You can use cursor to iterate over search results. Right and left arrow open close file and DELETE within file or on file node itself deletes it from the search results. However, when you do this, cursor is lost and you can't continue. Some other GUI field becomes focused and you need to use mouse to click on search results again to continue.

This should be trivial fix and would allow keyboard centric usage.

**Comment by doug24** [comment]
I agree it should work as you describe.  But it's not trivial - it is more than just setting the focus back to the results tree.  The delete will remove all the selected items, so the code will have to select the 'next' item in the list, probably the first remaining item after what was the first deleted item

**Comment by doug24** [comment]
And thank-you for maintaining the Chocolatey package all these years!

**Comment by doug24** [comment]
Fixed in release v3.0.136

**Comment by majkinetor** [comment]
Awesome, thanks.
