### ISSUE TITLE
Show total number of matches

### ISSUE THREAD

**Issue by fade0ff** [dnGrep/dnGrep#736]
One of the most trivial things that a search tool would usually display doesn't seem to implemented: the total number of matches.
It's not something that you need all the time but over the years there have been several cases where I needed the total number of matches and since it obviously wasn't implemented, I had to use crude workarounds (like copying the matching lines into Notepad++ to count the lines).
A part of me still can't believe that this is missing and expects to be told that I overlooked it somehow. But I really, really looked pretty hard, checked the options and documentation again and again and it's just not there. Or is it?

**Comment by doug24** [comment]
What version are you running?  This was added to the status bar in v3.0.84 from the request in #682.  The "47" in the image below is the total number of matches across all files.  

<img src="https://user-images.githubusercontent.com/17227248/185184871-52a8b266-5100-4473-a245-4fddc1461cc2.png" width="400"/>

It's also in the "Report" format report (More -> Save results -> Report) if you want to save the search results.

**Comment by fade0ff** [comment]
Ah, my bad. I'm using different versions > 3.0.0 at home and at work but obviously both are not updated to the very last release yet. Wouldn't have guessed that this feature was added just with that very latest release. This probably also explains why I didn't find an open issue. Sorry.

**Comment by doug24** [comment]
No problem!  I've seen this happen a few times - years go by and no one asks for some feature, then within a short period of time there are multiple requests from different people for the same thing.
