### ISSUE TITLE
Feature request: Checkbox next to file results list

### ISSUE THREAD

**Issue by raelb** [dnGrep/dnGrep#744]
If I'm not mistaken, this option does not currently exist. Have a checkbox next to each file, so that Replace will only occur in selected files.
Thanks
btw. the show context lines in matches is really awesome!

**Comment by doug24** [comment]
Thanks for the suggestion - a few thoughts about this.
I am reluctant to add more to the results tree, it is pretty busy already.  
If the tree had a checkbox, it's not obvious what it means to check a file - and should the checkbox have meaning other than to select for Replace? 
There already two ways to do what you are asking: In the Replace dialog you can select which files to replace and which to skip. Or (and I know this is less obvious) you can exclude files from the results tree before you start the replace (select files - context menu 'Exclude from results' or hit the Delete key).  The Replace will only include the remaining file or files.

**Comment by raelb** [comment]
Oh.. I agree with you - it would make the tree quite busy. I didn't realise that there was a whole replace process in place. I had never clicked on replace before, and thought it would just do the whole lot without any control. The exclude from results will also be helpful. Thanks.
