### ISSUE TITLE
Preview window continues to display a file manually removed from the list.

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#745]
When I do a search and it finds files, sometimes I remove a file (select & press delete) from the list when I deem it is not relevant to what I am looking for.
Because I have to select the file first, it shows in the preview window, and it does not go away until I select another file.  Sometimes there is no other file, or I do it while the search is still running, but no other files have been found yet, so that file remains visible.

Can it be changed so the file is no longer displayed in the preview window when this action is taken?
I know it is not a major issue.  It is more of a minor annoyance.

Thank you.

**Comment by doug24** [comment]
Fixed in v3.0.154
