### ISSUE TITLE
Everything index search: auto-quote the path

### ISSUE THREAD

**Issue by God-damnit-all** [dnGrep/dnGrep#746]
When switching from `Regular Expression`/`Wildcard` to `Everything`, the path that follows `Folder:`, which is located [here](https://user-images.githubusercontent.com/53661808/187105680-405bbea0-3b75-458b-ad35-7f767f1b49a6.png), should be automatically surrounded by double quotes, otherwise paths that have spaces in them will have issues.

This also applies if dnGrep is opened from the context menu within a folder and the `Everything` option is active.

**Comment by doug24** [comment]
Fixed in v3.0.154
