### ISSUE TITLE
Search fails if "Search in archives" selected

### ISSUE THREAD

**Issue by dalezz** [dnGrep/dnGrep#756]
If "Search in archives" is selected, a file name pattern exits (my case was "*.dcm"), and the "Search for" text is blank, the search starts, but never gets past a *.7z file.  Have to manually stop the search which takes multiple attempts.

Version 3.0.136.0

**Comment by doug24** [comment]
I have not been able to reproduce this.  Is the file counter in the status bar incrementing?

Do you have either of these options set?
Main window: `Include binary files` (unchecked)
Options dialog `Detect file encoding when listing files using the file name pattern` (checked)

When _excluding_ binary files, dnGrep must open the file stream from the archive for each file and check for binary.
When detecting file encoding, dnGrep must open the file stream from the archive for each file and run the encoding detection.

Both of these will be slow in archives and especially slow in 7z archives if they are solid archives. Solid archives are extremely slow to read - particularly with lots of small files.  dnGrep applies all the filters it can before having to extract the file streams, so having the *.dcm helps.

Without these options, dnGrep can quickly list the files. 

In my test, I get 1518 files listed from 6 archives in 1.4 seconds.  With these two options set, it takes 1 minute 15 seconds.  Without the file filter (*.js), it would take over an hour.

**Comment by dalezz** [comment]
I have just installed the latest version, and it appears to have made no difference.
Sorry, I forgot to mention that I'm using the 64bit version.  Now version Version 3.0.154.0
"Include binary files" is turned off
I don't appear to have the option "Detect file encoding when listing files using the file name pattern"

When I'm doing the search, I'm **not** searching for any pattern within the file, I'm just trying to find files that match a pattern.  I would have thought that should be quick, even within compressed files.  Nothing visually occurs, like no status bar update.  It would be nice to have some extra feed back within the status bar to know what is currently being searched.

I have tried "Include binary files" turned on, and that has made no difference.  The crazy thing is if I have "Include binary files" turned on, **and** I search for text, I get results.  dnGrep doesn't like the "Search for" field being blank.

**Comment by doug24** [comment]
The `Detect file encoding when listing files using the file name pattern` is in the Search results section of the Options dialog.  But even if that is set, you should see the status bar update with what file is being processed.  

Something else isn't right and can't reproduce this from your description.  Can you share a screen shot of the search parameters you have set on the main window? Does this happen on all archives, or just one? Do you a have sample archive that does not work?

<img src="https://user-images.githubusercontent.com/17227248/190172606-903fd431-05a3-40b3-ad14-2a9ca5130511.png" width="460"/>

**Comment by dalezz** [comment]
Sorry, I didn't realise I could scroll the options before.  So here are my Search result settings:
![image](https://user-images.githubusercontent.com/79883454/190184720-ead8a65e-0cff-494e-914a-33868a748d82.png)

Since going into the options and saving them, I'm getting results, but very slowly - about 1 per second.  My search parameters are:
![image](https://user-images.githubusercontent.com/79883454/190185898-bdae66f7-c57a-4cf3-acd5-40a8b17dff03.png)

When I cancelled the search because it was taking so long, I got this (check the status bar message):
![image](https://user-images.githubusercontent.com/79883454/190186543-f9702058-22cf-455a-9a4f-b62316d772a6.png)

Zero matches found, yet the previous screenshot said that it had found multiple files.

**Comment by doug24** [comment]
I think if it hasn't finished the archive those results are discarded.

Definitely uncheck the "Detect file encoding" option and try it again.  It should be very fast without that option.

**Comment by dalezz** [comment]
Turning "Detect file encoding" option off appears to have resolved the issue.

What I don't understand is if the "Detect file encoding" option is turned on, why would it make a difference as the search is not interested in the contents of the file, just the file name only.  Sounds like code is being called unnecessarily.

**Comment by doug24** [comment]
Yes, the default should probably have been disabled for that option as most people don't care.  But in most cases it does not matter - if you are not searching solid archives you will never notice the difference.  I wrote about this in the [dnGrep help](https://github.com/dnGrep/dnGrep/wiki/Archive-Search).

So beware - if you are going be searching files within these archives and not just listing the files, your searches are going to be very slow. Reading file data from solid archives is just extremely slow and there is nothing I know to change this, and I have spent many hours working on just this problem. dnGrep uses 7Zip to read archives, and I've read that there are other libraries that are faster, but 7Zip has too many other advantages to change.  My recommendation is to not use solid archives (an option when creating archives with 7Zip and WinRAR).

**Comment by dalezz** [comment]
Where I work also uses 7-Zip, and I think it's a great tool too.  What I was trying to get at before, if someone is only searching for a file without searching for text, you only need to extract a file listing from the compressed file, not actually decompress the compressed file.  Obtaining a file list would be much faster and might even give you the benefit of supporting other file types where you may need a licence to decompress them, but it's okay to obtain just a file listing.
Since turning off the option for "Detect file encoding", performance has been so much better.  I would have thought that obtaining a file listing of of a directory or compressed file shouldn't be effected by "Detect file encoding".
