### ISSUE TITLE
Feature Request: Add context menu option to "Move selected files to recycle bin"

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#757]
Also, would it be possible to have the Rename file > New name field populated with the selected file?

![MoveFilesToBin](https://user-images.githubusercontent.com/1332009/189525560-d7d02f1d-3c67-4a38-b373-fcff0c906fa9.png)

**Comment by fade2gray** [comment]
Hi, is this request out of scope?

**Comment by doug24** [comment]
Yes, I can do this.  I think this would be different - the existing Delete command deletes all the matching files.  I think this would apply to just the selected files from the results list.

**Comment by fade2gray** [comment]
Great, thank you.

**Comment by doug24** [comment]
Added in v3.1.197
