### ISSUE TITLE
Feature Request: Bookmark Window - option to stay open after selection

### ISSUE THREAD

**Issue by terra111** [dnGrep/dnGrep#759]
A checkbox in the bookmark window to select whether the bookmark window should remain open even after selecting (=double-clicking) a bookmark.

dnGrep is a gem! Thanks guys!

**Comment by doug24** [comment]
Sounds like a good idea.  I'm working on some other changes to the bookmarks now.

**Comment by doug24** [comment]
Added in v3.1.197
