### ISSUE TITLE
Binaries getting always included in searches

### ISSUE THREAD

**Issue by W1nstar** [dnGrep/dnGrep#764]
It was working some time ago, but recently it doesn't matter if the checkbox is marked, it always looks inside zips and other kind of binary files.
Am I just dumb and zips are not binaries?
I've tried to exclude them with *\*.zip and the like, but they still get included.
Any help?

**Comment by fade2gray** [comment]
![ArchivesBanariesPNG](https://user-images.githubusercontent.com/1332009/194362176-d1f11313-1342-42d5-9386-4301831a714f.PNG)

**Comment by doug24** [comment]
I don't see happening.  I'm guessing it's something in your settings.  Can you share a screenshot of your whole main panel?  
What is your file filter?
Are you using Everything?
