### ISSUE TITLE
Feature request: Show PDF page number

### ISSUE THREAD

**Issue by Carlo-Mava** [dnGrep/dnGrep#765]
Hi, at the moment the results panel shows the row number of the results in a PDF file.
Is it possible for it to show the page number instead?

**Comment by doug24** [comment]
There is nothing I know of in the extracted text PDF file that indicates something is a page number.  If page numbers exist in a document, they are extracted as text - but they look just any other document text.  In a couple documents I checked, there are form feed characters to indicate the location of a page break, but that would require counting them - and they may not match up with the actual page numbers you see in the text, such as when there are title pages and other content before the first numbered page.  

I think there are just too many variables and problems to try to do something like this.

**Comment by Carlo-Mava** [comment]
According to pdftotext documentation, each page is separated by a form feed character (\\f).
It can be omitted by using the flag -nopgbrk, but the options used are only "-layout -enc UTF-8 -bom".

I think it is possible to just count the amount of past form feed characters (+1) to figure the page numbers.

**Comment by doug24** [comment]
Is this what you have in mind?  The page number is repeated for each matching line on the page.  

These numbers do match up with the page number controls in PDF readers, but not the number on page if there are non-numbered pages at the start the document.

<img src="https://user-images.githubusercontent.com/17227248/200074179-e52e98de-cd36-43ba-bec0-aa17057c22a8.png" width=600/>

**Comment by Carlo-Mava** [comment]
Yup, that's exactly what I had in mind.
I think it's more important to get the real page number, so imo it's not relevant if there are non numbered pages at the start of the document, if you can simply jump to the page using the reader's controls.

**Comment by doug24** [comment]
Added in v3.1.197
