### ISSUE TITLE
Request: Reorder columns on bookmark window to prioritize Description

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#768]
In 3.0.154.0 the `bookmark window` displays the first several columns relating to the search options but has the `Description` column well after the search behaviors. It would be much easier to use bookmarks if I didn't need to scroll to the right to see the purpose of my long-winded search patterns. Putting the description first just makes it more user friendly. Thank you!

**Comment by doug24** [comment]
I've been working on a change to add a Name property to bookmarks so they can be referenced from a script. The Name property will be the second column, so easily visible.  I would think the name property would be shorter than the description, but I'm not sure a length limit is needed.  I may want to not allow spaces in the Name.

With the addition of a name, would you still want the Description to be near the left side?

**Comment by shawnkhall** [comment]
I think the Description should be before the other properties (it does very little for you if you have to scroll for it), but if a Name property is added and at the left then I'm cool with that. Thank you!
