### ISSUE TITLE
Bug: Bookmarks insert quotes before and after search terms

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#769]
Using 3.0.154.0

When I copy & paste search values to a new bookmark so that I can replicate its behavior I expect them to be taken literally. Unfortunately, whenever I select a bookmark to use that has spaces but doesn't begin with a double-quote it automatically inserts double-quotes around the `search in` value. I'm usually using `Everything` as the engine so this breaks search functionality until I remove the quotes.

Good: `"w:\sites\" (*.htm* | *.php)`
This still results in the proper `search in` being used.

Bad: `("w:\sites\" | "b:\backup\sites") (*.htm* | *.php)`
This results in `"("w:\sites\" | "b:\backup\sites") (*.htm* | *.php)"` being used, which doesn't work.

If you're going to insert double-quotes then instead of checking just the first character, check the entire string, or alternatively, validate using negative values that aren't allowed in paths so it doesn't result in misquoting. `|`, `"`, `<`, `>`, two or more `:`'s. Since this is only checked once when the bookmark is activated it won't be a performance hit and should resolve the issue.

**Comment by doug24** [comment]
This happened when I made the change for #746 to auto quote the path.  It looks like I applied the new code in too many places.  I think that the newer auto quote code can still be used when changing from Regex or Wildcard search to Everything when there is nothing but the path.  Dealing with code to change the path while there are other query parameters on the Everything command line is difficult at best.

**Comment by doug24** [comment]
@shawnkhall Is this a valid expression in Everything?  
("w:\sites\" | "b:\backup\sites") (*.htm* | *.php)

When I try putting parenthesis in like this (via dnGrep or Everything UI) Everything does not return anything.

**Comment by shawnkhall** [comment]
You probably need to enable the "allow round bracket grouping" feature in Everything. It's not enabled by default.

`Tools` => `Options` => `General` => `Search` => Check `Allow round bracket grouping`

**Comment by doug24** [comment]
Yes, that's it.

I'm trying to figure out what to do in these two cases when Everything is enabled:
1) Click the Browse button and select a directory or file.  For the other modes, this replaces the current search location.
2) Drag and drop a file or folder onto the dnGrep window.  For the other modes, this replaces or appends (with alt key) to the current search location.

With the Everything search, it would be nice to replace or append to the path expression(s) and preserve the rest of the Everything filter expression.  But this means that dnGrep would have to parse the Everything expression, and it's not easy to replicate that, so I'm very reluctant to go down that road.  I'm thinking that these two actions would just set the directory and not attempt to preserve any part of the existing expression. 

Any comments?

**Comment by shawnkhall** [comment]
Thank you. I'd rather you not fiddle with my existing search settings since the Everything syntax options can have completely different effects based on which options are enabled within Everything, as you can see from this thread. For example, if you enable the option to `Expand Environment Variables` then search folders can be like `%userprofile%` or `%programdata%` and this would probably have unexpected behavior compared to the native search features. I have assigned new environment variables specifically so that I can use that feature. :)

I think that your best way forward would be to replace the entire expression, quoting the new folder path. If the user wants to preserve anything else they'll copy & paste it back in.

Alternatively, you could split the `Search In` box into two text boxes and the first would be for the folder/path and the second would be for additional parameters. When they Search it would simply concatenate these two fields in the underlying search with a space. While this would help address the drag & drop and browse scenarios, it would probably confuse people as much as it helped. I can see a series of "Why are there two boxes for Everything?" tickets.

**Comment by doug24** [comment]
Fixed in v3.1.197
