### ISSUE TITLE
Probably a small bug in sorting the result on last write time

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#774]
Good evening

**Thank you so much for your faithful, hard-working care of your great product!**

It looks like Version 3.0.154.0 has a bug in sorting the result based on the last write time:

I have this setting, so that the newest file / the last modified file is on top:

![image](https://user-images.githubusercontent.com/8282673/203421931-5c45fb81-5b03-43a6-8511-14d3531e76c9.png)

But in the result, the 1st file in the list is from august 2022, and therefore it is older:

![image](https://user-images.githubusercontent.com/8282673/203422060-8a0745ff-96e7-4d8a-8fcf-09f07c2929e9.png)

than e.g. the 5th file, which is from november 2022:

![image](https://user-images.githubusercontent.com/8282673/203422225-804a9cc5-2b75-434f-a41e-f84ad73f2546.png)

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
That is strange, and I have not been able to reproduce it.  Just checking - did you click the "Sort" button after the search completes?  It doesn't sort automatically.

**Comment by schittli** [comment]
Good evening @doug24 

Thank you for your support!, 
I'm very sorry!, I thought that it will sort the result automatically. If I click the Sort button, then it perfectly works. Good to know :-) 

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
No problem.  I may make an option to sort automatically.

**Comment by doug24** [comment]
@mikebz-github  No, I had forgotten about that.  I will take a look at it soon.

**Comment by mikebz-github** [comment]
Thanks @doug24 - it's netiher urgent nor essential obviously.

**Comment by mikebz-github** [comment]
Thankyou for adding this feature @doug24, much appreciated.
