### ISSUE TITLE
Feature request: open file context menu for search results

### ISSUE THREAD

**Issue by kintrupf** [dnGrep/dnGrep#782]
Please make it possible to open the standard Explorer context menu for a file from the search results.

**Comment by doug24** [comment]
If you are looking for the full context menu (as in Windows 10) and not the new Windows 11 context menu, then I know how to do that.

**Comment by kintrupf** [comment]
Yes, the "normal" context menu. Nobody needs the useless Windows 11 thingy ;-)
Thank you!

**Comment by doug24** [comment]
Added in v3.1.197
