### ISSUE TITLE
Minor issue on first time search for file listing

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#791]
I will often want to list files within a folder by just providing a file mask and no search term, but I discovered after a clean install, that if this done before having first searched for any content, an error will be returned.

![Capture](https://user-images.githubusercontent.com/1332009/206237616-b8e18b3c-2519-40bd-a564-94b012517c7e.PNG)

This does not occur if any previous search for file content has been performed.

**Comment by doug24** [comment]
Included in v3.2.242
