### ISSUE TITLE
Unable to see full list of archive file extensions

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#792]
I assume the field is a text box which can't be navigated. Would it not be better for it to be an edit box with a default list and also provide a button to restore the default list?

![Capture2](https://user-images.githubusercontent.com/1332009/206240562-d9524694-5015-4e94-8567-ba747713ffce.PNG)

**Comment by doug24** [comment]
I thought the text box would scroll with the arrow keys, but no.  As a work-around, you can click the box and ctrl-A, ctr-C to copy the list and look at it in a text editor.

I think I did it this way to make the stored configuration simpler.  I don't like changing the configuration file format, but I'll see what I can do.

**Comment by doug24** [comment]
Included in v3.2.242
