### ISSUE TITLE
Select a syntax highlighter for certain file extensions

### ISSUE THREAD

**Issue by kintrupf** [dnGrep/dnGrep#794]
When I view search results in PL/SQL packages (file extension .pck) the preview window should use the SQL or TSQL highlighter (no perfect matches, but good enough). However, only "None" is automatically selected.
Please make the default syntax highlighter configurable for unknown file types.

**Comment by doug24** [comment]
OK - that's a good suggestion - it could add associations or remap a file extension to a different syntax.

**Comment by doug24** [comment]
Included in v3.2.242
