### ISSUE TITLE
Syntax highlighter colors are not configurable

### ISSUE THREAD

**Issue by kintrupf** [dnGrep/dnGrep#795]
I've found no way to configure the colors for the syntax highlighter. It would be nice if I could choose the colors for the syntax elements according to my preferences. Thank you!

**Comment by doug24** [comment]
That is correct, you currently cannot override or extended the syntax coloring.  The language definitions and associated colors are embedded in dnGrep.exe.

The language definitions and syntax colors are defined in .xshd (XML Syntax Highlight Definition) files, which is the format used by the text editor in dnGrep (AvalonEdit).  Here are the [existing syntax files](https://github.com/dnGrep/dnGrep/tree/master/dnGREP.WPF/Resources) in dnGrep, and [many more here](https://github.com/xv/ICSharpCode.TextEditor-Lexers/tree/master/Syntax). 

My initial thoughts are that I don't want to create any kind of editor or configuration settings to override the values in these files, but I could add the ability to read in .xshd files from a configuration directory when dnGrep starts.  If dnGrep finds user supplied .xshd files, then they would either add to the existing set of languages or replace one of the built-in languages (so you can add your own improvements).

**Comment by kintrupf** [comment]
Having dnGrep pick up additional .xsdh files from a user directory would be great! That would also solve the problem of missing syntax highlighters for additional languages.

**Comment by doug24** [comment]
Included in v3.2.242
