### ISSUE TITLE
Request: Option to always have the preview pane open detached from the main window.

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#796]
I generally like to have the main window snapped to the top left corner or the left edge of my screen, but opening the preview pane in an attached state, tends to squish the main window into oblivion, needing everything to be resized.

**Comment by doug24** [comment]
I don't understand.  If you undock the preview window, it will stay undocked.  You can close and reopen the preview window, and it will still be undocked.  You can exit and restart the application, and it will still be undocked.  Just don't dock it agian.

So, I don't understand what you are asking for?

**Comment by doug24** [comment]
Unless you can show how to reproduce a problem, I'm not going to make any changes to how the docking window works.  I think you have the capability to do what you are asking.
