### ISSUE TITLE
Two Feature Requests

### ISSUE THREAD

**Issue by PaltryProgrammer** [dnGrep/dnGrep#808]
Version 3.2.242.0
Thank You for providing dnGrep
I noticed whilst searching web addresses the matches were not highlighted . Also i would find it helpful whilst navigating to each match via F3 the number of the match wrt total matches and wrt containing file would be displayed Thank You Kindly

**Comment by doug24** [comment]
I have a fix for highlighting web and email links.  

For the match counts - I'm trying to decide on the details.  Anyone's input is welcome.

 - I am experimenting with putting these on the right side of the status bar, and trying to keep them as short as possible, preferably without using text.  But there are two sets of values: number of the match relative to the file, and relative to the total.  
 -- Is this understandable?  
 -- Is it cross-culture without needing translation?  
 -- Maybe also with a tooltip for explanation?  

<img src="https://user-images.githubusercontent.com/17227248/215169934-86efaf87-be59-453b-ad23-d6be8713c13d.png" width="740"/>

 - A selected line may contain multiple, or many, matches - should the status show the range of match counts on that line? Just the first? Just the last?  I haven't come up with anything better, but this notation seems confusing to me.
<img src="https://user-images.githubusercontent.com/17227248/215171295-acb8d163-b141-4677-a6cd-e8d2e78cd71b.png" width=740/>

 - When selecting a line without any matches or multi-selecting lines, the counts will go away (there isn't a specific context to count).

 - How important is the match number relative to the total number of matches?  It would simplify things if there was only one.  And it would save the time summing the match counts in all the files before the current file in the list.

**Comment by PaltryProgrammer** [comment]
as a user i would be happy w/ either form . whichever is easier to program seems reasonable to myself . as for importance of match number wrt total this is the statistic i most wish rather than wrt file

**Comment by doug24** [comment]
Added in v3.2.279
