### ISSUE TITLE
feature: keyboard shortcut for the folder field

### ISSUE THREAD

**Issue by gilbh** [dnGrep/dnGrep#812]
Hello,

Love your tool!

Is it possible to assign a keyboard shortcut (usually comes in the form of <alt-underline letter> to the folder field?

Thanks!

**Comment by doug24** [comment]
Thank-you!  

Just making sure I understand - you want an accelerator key to jump to the Folder input box?  Yes, I can add that.  I was thinking of setting it to "o" as in this example as "f" is already used.

<img src="https://user-images.githubusercontent.com/17227248/215340107-4fe305d5-bc3e-4725-a696-dc774cf1f758.png" width="480"/>

**Comment by gilbh** [comment]
Yes, this is exactly what I meant. Thanks!

**Comment by doug24** [comment]
Added in v3.2.279

**Comment by gilbh** [comment]
Great!
