### ISSUE TITLE
No replace option in .docx?

### ISSUE THREAD

**Issue by InfoBube** [dnGrep/dnGrep#826]
Wanted to replace some text in a couple of .docx files, but the 'Replace' button is greyed out. Since replacing worked with .txt files, I assume dnGrep simply does not support replacing text in Office files. If that is the case, it would be great if the description of its functionality on its homepage / the help page were to clearly state what file formats it supports replace for. That would have saved me some time and effort.

Many thanks

**Comment by doug24** [comment]
You are correct, dnGrep does not replace in binary file formats such as Word, Excel, PowerPoint, PDF, ebooks, files in archives, images, audio files, or executable files.  It does replace in all types of plain text files.  I'll update the main page and the help page.

**Comment by InfoBube** [comment]
I didn't think it would do so for strictly binary formats but since .docx is an archive of XML files, I thought it might be possible (PowerGrep claims to be able to do it). Anyway, thanks for clarifying the situation.
