### ISSUE TITLE
Request: Ability to copy status bar statistics to the clipboard.

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#827]
Would it be possible to add this to Custom Actions, please?

**Comment by doug24** [comment]
Do you mean this?
<img src="https://user-images.githubusercontent.com/17227248/219070599-3997ae4b-6880-4413-b01a-7b49898851a8.png" width="300"/>

I mostly say yes to every request, and there are a number of things I now wish weren't in code to maintain forever...  I don't want to add things that are useful to just one person, or once ever.  And I'm having a hard time seeing how useful it would be to copy these numbers from unknown line selection in an unknown file with an unknown number of files preceding it in a list of files with unknown sort.

Can you help me understand what this for?

**Comment by fade2gray** [comment]
> Do you mean this?

Well, I don't see that format in Version 3.2.242.0.
![stats](https://user-images.githubusercontent.com/1332009/219132192-134b64b7-f631-4484-8250-e5acc83a304c.png)
... but it would be convenient to be able to copy and paste the figures into a log.

I am making many regex searches in the source code of a GitHub project, comparing the differences in the results returned between commits. Each search involves tweaking the search expression and will return a different number of hits/files. When keeping a log of the changes made to the regex, it would help to just be able to paste the changes in the stats alongside the regex rather than manually typing them in.

**Comment by doug24** [comment]
Good thing I asked! I was thinking of something else - the data shown above will be added to the status bar in the next release based on issue #808.

Are you thinking of just the raw numbers?  I'm just wondering of having a format with no context, but given your use case, I can see why you would want just the numbers without any labels.

**Comment by fade2gray** [comment]
Yes, just the raw numbers would be of great help.

**Comment by doug24** [comment]
Just a thought, but what if these numbers are written to the log file ("Grep_Error_Log.xml") after each search? If you keep the log file open with something like Notepad++, it will reload with the new data.  The fields after 'Search for' to the end of the line are the raw numbers separated by tabs so you can copy and paste them directly into Excel.  

```
<logevent time="2023-02-17 10:07:19.9029" level="Info" logger="dnGREP.WPF.MainViewModel">
  <message>Search completed in 7.652s – 787 matches found in 144 files of 11885 searched. Search for: FileStream	7.652s	787	144	11885</message>
</logevent>
```

**Comment by fade2gray** [comment]
Yes, excellent.

**Comment by doug24** [comment]
Added in v3.2.279

**Comment by fade2gray** [comment]
Thank you.
