### ISSUE TITLE
Feature Request: Delete each folder history & Favorite folder

### ISSUE THREAD

**Issue by abappl** [dnGrep/dnGrep#836]
Hi.
I really like the dnGrep program and I use it well.
There is inconvenient point because frequently searched folders and one-time searched folders are mixed in the folder search history.

Here are some things I would like to see improved:

**1. Delete each search folders history**
As shown in the picture below, when I mouse over each folder in the folder history, I want a button to delete each folder.
Or if I click the keyboard Delete button after mouse over, I want the mouse over folder record to be deleted.

![image](https://user-images.githubusercontent.com/127807627/227404266-b1235916-7a9e-44c9-bf64-e5ef06a151d9.png)
![image](https://user-images.githubusercontent.com/127807627/227405289-ed0aac5f-f616-400a-ad03-0b37b5cea46f.png)

**2. Favorite folder**
I wish there was a function to pin frequently searched folders so that they can be located at the top. 
And I would like to be able to adjust the order of the pinned folders.
Pinned folders not be deleted when click "Clear old searches" in the options.
Even if it is not the above method, I wish there was a function to manage and quickly access the favorite search folder.

![image](https://user-images.githubusercontent.com/127807627/227405982-511bd317-4929-433d-87b2-8dc39ebe40a0.png)

Thank you!

**Comment by doug24** [comment]
Yes, this can be added.  The list is a 'most recently used' list, and I would like to keep that functionality.  I'm thinking that the pinned items will stay in the order that you pin them, and the unpinned items will be ordered by the most recent at the top, just below the pinned items. When you pin an item, it will be added to the end of the pinned items.  When you unpin an item, it will become the first unpinned item. I think this will make it pretty easy to set the order without adding any other controls or special keys.  You could also set the order manually in the user settings file if you have a lot of pinned items.

I think it may be nice to also add this to the pattern filters, search and replace history lists.

**Comment by doug24** [comment]
Added in v3.2.306
