### ISSUE TITLE
Feature Request: Support for Windows 11 right click context menu

### ISSUE THREAD

**Issue by walkerreuben** [dnGrep/dnGrep#849]
As anyone who uses Windows 11 is aware, Microsoft updated the default context menu in Windows 11 to only show a limited number of options:
https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

This has been discussed for Notepad++ here, with support added in v8.5.1:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10320
https://notepad-plus-plus.org/news/v851-released/

There is also an open request for the same functionality for 7-Zip here:
https://sourceforge.net/p/sevenzip/discussion/45797/thread/100e7bb9fb/?page=1

I would love to see the same support added in dnGrep. At the moment I have to use the registry key change to revert to the classic context menu with all the unnecessary clutter.

**Comment by doug24** [comment]
I looked into this when I first moved to Windows 11.  Microsoft has made it much more difficult for applications to modify the context menu, particularly for .NET applications.  And it really complicates the installation process - registering COM servers for either x86 or x64.  It just didn't seem worth it.  If they made it easy, the new menu would soon be as long as the old menu.

I'll look into again, but I don't know if I will take this on.  If anyone wants to submit a PR for this, that would be great.

There is a project on github called NanaZip that adds 7-Zip to the Windows 11 context menu (I haven't tried it). They have 1100 lines of c++ code just for the shell extension.  Bleh.

VS Code has had this issue open since June 2021 and it's still not released.

For me, I have stopped using right-click in Explorer to open the context menu.  Instead, I press the menu key on the keyboard, which brings up the old context menu and I have access to the commands I use frequently. It's pretty automatic now :)

**Comment by doug24** [comment]
I read the Notepad++ link above.  No, I won't be doing what they did - hijacking another context menu entry and overwriting it with their command.  Lots of people unhappy about that.  

VS Code has had lots of issues as well. They asked the Windows 11 team for help and looks like they didn't get any.  But they have a solution in beta test.

The PowerToys - Power Rename has a working Windows 11 context menu using native C++ code.  It looks like working implementations are based on the [PhotoStoreContextMenu](https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages/PhotoStoreContextMenu) sample app.

Also saving this link for future reference: [Creating a sparse signed Win32 app package](https://andrewleader.medium.com/creating-a-sparse-signed-win32-app-package-9809320cfaab).

In the Notepad++ thread, a couple of users suggested using the [Custom Context Menu](https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X) app from the Microsoft store.  I installed it, set up an entry for dnGrep, restarted Windows, and it works pretty well.  The multiple file/directory selections doesn't currently work with dnGrep, but I'm going to look into making a change to support that.  If you only configure dnGrep, it will show up as a top-level menu item, but if you configure additional apps through this tool, they will appear on a sub-menu (the Custom Context Menu app is limited to just one top-level menu item by the Windows API).

Here is the configuration I am using - 'Open in dnGrep.json':
`{"title":"Open in dnGrep","exe":"\"C:\\Program Files\\dnGrep\\dnGREP.exe\"","param":"/f \"{path}\"","icon":"\"C:\\Program Files\\dnGrep\\dnGREP.exe\",0","acceptExts":"*","acceptDirectory":true,"acceptFile":true,"acceptMultipleFilesFlag":0,"pathDelimiter":";","paramForMultipleFiles":"/f {path}","index":0}`

<img src="https://user-images.githubusercontent.com/17227248/234381420-1022a13d-6ca3-479b-9511-870586417932.png" width="400"/>

**Comment by doug24** [comment]
dnGrep comes with its own Windows 11 context menu starting in [v4.2.6](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.6.0)

**Comment by ssstain** [comment]
dnGrep doesn't work from context menu in Far Manager under Windows 11 with the "not implemented" error
version: (latest from winget) 4.6.52.0

**Comment by doug24** [comment]
@ssstain Sorry, but I do not have time to support third party application integrations. dnGrep implements the COM interfaces to work from Windows 11 File Manager, and frankly I had a hard enough time getting that to work. I have no idea what else this application is expecting. If someone wants to enter a pull request, that would be great.

**Comment by VorlonCD** [comment]
Right-click works fine in Directory Opus, a 3rd party File Explorer replacement I use.   Maybe they just need to enable "Original right click menu" in Options to support Far Manager?

**Comment by ssstain** [comment]
@doug24 thank you for such a wonderful piece of software
@VorlonCD 'Original right-click menu' is disabled/greyed out

**Comment by VorlonCD** [comment]
> [@doug24](https://github.com/doug24) thank you for such a wonderful piece of software [@VorlonCD](https://github.com/VorlonCD) 'Original right-click menu' is disabled/greyed out

Agree, its pretty awesome :)

@ssstain - When you open dnGrep, try right-click > Run as administrator in order to change the setting.   Or maybe grayed out if you dont have Windows 11?

**Comment by doug24** [comment]
> [@ssstain](https://github.com/ssstain) - When you open dnGrep, try right-click > Run as administrator in order to change the setting. Or maybe grayed out if you dont have Windows 11?

You are correct, you need to run dnGrep as administrator - it is modifying the Windows Registry.  There should be a tooltip that says that.

Both the new and old context menus work on Windows 11 - one on the new context menu, and the other on the 'Show more options' context menu.

Thanks, glad to hear you like it!

**Comment by ssstain** [comment]
@VorlonCD @doug24 with 'run as administrator' I've managed to check it. Problem solved. Thank you.
