### ISSUE TITLE
Update Links to SignPath

### ISSUE THREAD

**Issue by SabotageAndi** [dnGrep/dnGrep#858]
Hi!
I am the Developer Evangelist of SignPath.

Could you change the notice about us from

    Free code signing provided by [SignPath.io](https://signpath.io/), certificate by [SignPath Foundation](https://signpath.org/).

to

    This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=dngrep), and a certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=dngrep)

If you want, I can submit a PR for that.

Thanks!

**Comment by doug24** [comment]
Maybe I'm just overly suspicious, but what is the reason for this change? 

The existing notice is in accordance with the agreement with SignPath.  If SignPath sends me an email with the requested change, then I will update it.

**Comment by SabotageAndi** [comment]
We get a lot of traffic from GitHub and would like to understand from which projects we get this traffic, to see which kind of people are interested in code signing.

I will send you an email.

**Comment by doug24** [comment]
Thank-you - it's completed.

**Comment by SabotageAndi** [comment]
Thanks!
