### ISSUE TITLE
Win 7

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#860]
Is version v3.2.279.0 the last to run Win 7?

Thanks

**Comment by doug24** [comment]
It could be, but there is more work to be done on the new .NET v7 version and I'm open to doing another release if there is something to be added or fixed.

**Comment by harryray33** [comment]
I assume though, that the latest version wont run on Win 7?

**Comment by doug24** [comment]
Sorry, I mis-read your question.  I assumed that the latest (3.2.306) would run on Windows 7, but I don't have a Windows 7 system to test it on.  

Are you seeing some problem with it?

**Comment by harryray33** [comment]
Thanks, it's working with Win 7. 

.NET 7 doesn't work with Winows 7.

**Comment by doug24** [comment]
Release 3.2.330 is the last release of dnGrep supporting Windows 7 and 8.  

Correct, Microsoft is no longer supporting old versions of the OS with the new versions of .NET.
