### ISSUE TITLE
multiple instances start after opening multiple files/folders with dnGrep.

### ISSUE THREAD

**Issue by jadedgnome** [dnGrep/dnGrep#864]
I selected multiple 2 or more folders and right-click to open with dngrep. multiple instance opened up with the one path of each folder in the folder field.

when I do the same thing with grepWin only one instance opened up and each path/file is separated by a | pipe. 

![image](https://github.com/dnGrep/dnGrep/assets/2940805/143c01dd-bdf5-495d-833d-0a9b883c679e)

can there be an option so that dnGrep functions similarly?

**Comment by doug24** [comment]
If you are on Windows 11 you can do this now using a third party app from the Windows Store as [I described here](https://github.com/dnGrep/dnGrep/issues/849#issuecomment-1534965472).

If you need this in the "classic" Explorer context menu in Windows 10 or 11, that is more difficult.  Windows Explorer doesn't provide a way to start applications passing all selected files, so a shell context menu handler is needed (this is a separate dll registered with Windows Explorer, not part of the application).  dnGrep currently does not support this, but maybe could in the future.

Here's what I do: right click on a single folder and click the dnGrep... menu item to start dnGrep.  Next, holding the <ctrl> key down, drag and drop one or more other folders onto the dnGrep main window.  That will add folders to the search path.

**Comment by doug24** [comment]
If you run dnGrep as a singleton application (added in v4.0.115), this will work as requested.  But I'll leave this open for a better solution with a shell extension. (#849)

**Comment by doug24** [comment]
dnGrep comes with its own Windows 11 context menu - shell extension starting in [v4.2.6](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.6.0) that supports multiple file/folder selection.
