### ISSUE TITLE
garbled characters for the seach result

### ISSUE THREAD

**Issue by jbxenzxy** [dnGrep/dnGrep#869]
About the seach function for chinese, there is a little bug

add the Chinese annotation in the pdf, please see the figure 1

but the Chinese annotation is garbled characters for the search result in the dnGrep, please see the figure 2

![11111111111111111111](https://github.com/dnGrep/dnGrep/assets/40913849/ad419bdf-9efe-4a29-8f4f-b3f9a0d1e4e5)
![2222222222](https://github.com/dnGrep/dnGrep/assets/40913849/6a4ca1cb-bd03-4fb2-828a-0b60f53f34f1)

**Comment by doug24** [comment]
My first guess - this is an encoding problem.  dnGrep uses a third-party application "pdftotext.exe" to extract plain text from the pdf document, and then runs the search on the plain text.  The text you see in the preview window is the plain text output of the pdftotext application.  

In the dnGrep Options window, you can specify the encoding used when extracting the text.  The default (shown below) is UTF-8.  There are some other encodings available:  Latin1, ASCII7, Symbol, ZapfDingbats, UTF-8, and UCS-2.  Symbol and ZapfDigbats probably are not what you want, but you could try changing the pdftotext command line options (in the dnGrep Options dialog) and see if you get better results.  Just replace "UTF-8" with one of the other encodings, save the option change and rerun the search.

![Screenshot 2023-06-07 174815](https://github.com/dnGrep/dnGrep/assets/17227248/18a36f1d-28d0-4dde-aaa4-f62dbbaaaccc)

**Comment by doug24** [comment]
Can you zip and attach this file, or some other file with the same problem so that I can debug it and see if there is something I can fix?

**Comment by jbxenzxy** [comment]
thanks a lot!

![1111111111111111111111](https://github.com/dnGrep/dnGrep/assets/40913849/d1372cbe-af8f-4633-a9f5-08772ca16013)
[2022年7月基金从业《证券投资基金》考试真题 2023年6月8日③.pdf](https://github.com/dnGrep/dnGrep/files/11684495/2022.7.2023.6.8.pdf)

**Comment by doug24** [comment]
I haven't found any way to help you on this.  As you found, it does not appear to be an encoding problem.  It looks like the third-party application pdftotext.exe is not converting the comments/annotations.  This isn't the first time that issues have been raised on how the pdf is converted to text.  I have looked for other pdf reader libraries and have not found any that work better.  It's unfortunate that we can't use Acrobat Reader to do this.

When using other pdf readers, I found that the comments/annotations do not render correctly when viewing the document in Google Chrome, either.  In Microsoft Edge they do not appear until you click on them.  Firefox looks OK and of course Acrobat Reader works.  
 
The pdftotext tool is part of [XpdfReader](http://www.xpdfreader.com/download.html).  XpdfReader has the same problem rendering the comments in your document.  If you want to purse this, I suggest you ask a question in [their forum](https://forum.xpdfreader.com//) and see if they can answer why this is happening.

**Comment by jbxenzxy** [comment]
Thanks again!
I will ask this question in their forum.

**Comment by jbxenzxy** [comment]
The XpdfReader forum give the answer. I am not sure whether they mean dnGrep need to install the simplified Chinese language support package.
https://forum.xpdfreader.com/viewtopic.php?t=42607
![111111111111111](https://github.com/dnGrep/dnGrep/assets/40913849/bc3be620-2d90-4aae-856e-4c1f57f4e6f0)

**Comment by doug24** [comment]
Here is the result I get after installing the simplified Chinese package:

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/b2982ee8-ad59-4761-b33a-0ac0847ea5cb" width="600"/>

Here is the xpdfrc file I used in the same directory as pdftotext.exe (remove the .txt extension to use it): 
[xpdfrc.txt](https://github.com/dnGrep/dnGrep/files/11737019/xpdfrc.txt)

I don't want to add all the language support files to the dnGrep installation, that would add hundreds of more files to the kits. So, I think I am going to add it to the dnGrep documentation page and leave the installation to the user.

I am going to reorganize the PDFSearch plugin directory and add the missing copyright and documentation files to dnGrep's `PdfSearch` folder in a new subfolder `xpdf`.  The language support files would go in subdirectories below `xpdf`, for example a subfolder named "chinese-simplified", as is detailed in the xpdf language support files installation instructions.

**Comment by jbxenzxy** [comment]
Looking forward to the updated software. thanks a lot!

**Comment by doug24** [comment]
I updated the dnGrep [help page for PDF search](https://github.com/dnGrep/dnGrep/wiki/PDF-Search) to include instructions for installing language packs.  It refers to the directory structure in the new v4.0.26 release, but it should also work on older releases by excluding the `xpdf` directory in the paths.

**Comment by jbxenzxy** [comment]
I try the new version, it is ok. thanks a lot!
