### ISSUE TITLE
Feature request: search by filename in archives

### ISSUE THREAD

**Issue by ffays** [dnGrep/dnGrep#872]
Here is the scenario:

I'm looking for MANIFEST.MF files in a bunch of jar archives.
So I entered `MANIFEST.MF` in "Patterns to match", then only were listed the MANIFEST.MF files on the file system (... and therefore not those located in the jar archives)

However if I enter `*\MANIFEST.MF` in "Patterns to match", then only were listed the MANIFEST.MF files inside the jar archives.

**Would it be possible to improve dnGrep to list both MANIFEST.MF files inside the jar archives and those on the file system by simply entering `MANIFEST.MF` in "Patterns to match" ?**

P.S. You may test this scenario using an unarchived (i.e. a deployed) [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/) and perform your search in `eclipse\plugins` were all the jar archives are located.
Each jar archive should have a "META-INF\MANIFEST.MF" entry. There are some plugins that are there as directories, so you have a mix of MANIFEST.MF files within jar archives and MANIFEST.MF files on the file system itself.

**Comment by doug24** [comment]
Yes, something isn't right with this.  I'll look into it when I have more time - in the meantime, I think you can work around this by setting the "Patterns to match" to `*MANIFEST.MF`.  In my test that found the files both in the jars and in the file system.

**Comment by ffays** [comment]
@doug24 thank you for your feedback

I confirm that the `*MANIFEST.MF` workaround worked - thank you

**Comment by doug24** [comment]
Fixed in 4.0.26
