### ISSUE TITLE
Feature request: allow moving files to...

### ISSUE THREAD

**Issue by Peppins32** [dnGrep/dnGrep#876]
It's possible to have "moving files to" of found files (when  you right click on found files), so that will be possible to move found files to different folder instead of "Recycle Bin"??

The actual recycle bin need to be Delete selected file imo.

**Comment by doug24** [comment]
It's not a right-click option, but this does already exist.  There are Copy, Move, and Delete functions on the "More" menu.  These apply to all the found files - if you only want a subset, you can remove files from the results tree by selecting them and pressing the delete key.

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/afa84dca-6f3c-4af2-a619-2809589eee7b" width="400"/>

**Comment by Peppins32** [comment]
Yes i've used the options from the "More" menu (move/copy). If isn't possible to have them from right-click it's ok anyway :-D

**Comment by doug24** [comment]
Sure, it's possible, I assumed you had missed the other.  I'll think about it, I'm not sure if it is needed both places.

**Comment by Peppins32** [comment]
Maybe only on the right menu (copy, move, delete).

**Comment by doug24** [comment]
Added in [v4.0.45](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.45.0)

**Comment by Peppins32** [comment]
Thanks, i've tested, but i've noticed that when you move files (or copy files) even from menu tab, the tool do that with folders too and not only for the files. There is a way to uncheck that?

**Comment by doug24** [comment]
Yes, it was done that way to preserve the folder layout between source and destination.  It's been that way forever, but I think there was a bug in the last release that broke that behavior. I haven't had this request before, but I can see that wouldn't always be desirable.  I can add options for Move and Copy to preserve folder layout or put all files in the same destination folder.

**Comment by doug24** [comment]
Added the new options in [v4.0.69.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.69.0)
