### ISSUE TITLE
the function to exclude the file folder

### ISSUE THREAD

**Issue by jbxenzxy** [dnGrep/dnGrep#879]
I wonder if the dnGrep can add the function to exclude the file folder, like the file exclude in the figure.

I have the book folder, which include many subfolders, for example: history, english, maths, physics, Economics, Philosophy etc.

when search something, if I know the result is not in the maths subfolder, I can exclude the subfolder to ensure the search quickly.

![111111111111111111](https://github.com/dnGrep/dnGrep/assets/40913849/4d290ebf-592a-456d-97c0-cfabb95ab855)

**Comment by fade2gray** [comment]
You can select multiple files to be searched.


https://github.com/dnGrep/dnGrep/assets/1332009/67e6a9ba-b6d1-4fcd-b49e-6a7ae5f94477

**Comment by doug24** [comment]
You can put folder names in the 'Patterns to exclude' like this:  `maths\*`
And exclude multiple folders with a comma or semicolon separated list: `maths\*;physics\*`

**Comment by jbxenzxy** [comment]
I try it, it is ok, but a little bug, the .chm and .iso files in the excluded folders still are searched.

**Comment by jbxenzxy** [comment]
I try it, it is ok, but a little bug, the .chm and .iso files in the excluded folders still are searched.
________________________________
发件人: Doug P ***@***.***>
发送时间: 2023年6月16日 22:09
收件人: dnGrep/dnGrep ***@***.***>
抄送: jbxenzxy ***@***.***>; Author ***@***.***>
主题: Re: [dnGrep/dnGrep] the function to exclude the file folder (Issue #879)


You can put folder names in the 'Patterns to exclude' like this: maths\*
And exclude multiple folders with a comma or semicolon separated list: maths\*;physics\*

―

**Comment by doug24** [comment]
Yes, I see the archive files are not filtered by the excluded folders.  I'll work on that.

**Comment by doug24** [comment]
Fixed in [v4.0.45](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.45.0)
