### ISSUE TITLE
The result area is greyed out

### ISSUE THREAD

**Issue by duesentrieb17** [dnGrep/dnGrep#880]
Version 4.0.26.0
Windows 10 21H2

Although results are found, the display area remains greyed out, please see the attached screenshot:
![dnGrep](https://github.com/dnGrep/dnGrep/assets/34717473/9c756fa3-835b-4e02-b782-9948049018e7)

**Comment by fade2gray** [comment]
I have no problem on Win10 22H2 / dnGrep 4.0.26.0 - I just used the `msi` installer to install over the previous 3.x installation.

**Comment by duesentrieb17** [comment]
This has now solved the problem: deleting the file AppData\Roaming\dnGrep\dnGREP.Settings.dat
The file was from a previous installation of version 3.x.

**Comment by doug24** [comment]
Thanks for reporting this, and the solution.  I'm going to leave this open for now as others may also experience this problem and want to see the solution.

If anyone has an old version of dnGREP.Settings.dat that causes this problem, please attach it here, I'd like to try to figure out what went wrong.
