### ISSUE TITLE
Launching URLs (eg. About/Help, Check for Updates/Download, etc.) broken in v4

### ISSUE THREAD

**Issue by AlexVallat** [dnGrep/dnGrep#881]
.NET 7 changes the default of `Process.Start` to be `UseShellExecute = false` which means whenever you do a `Process.Start("https://github.com/dnGrep/dnGrep/wiki")` (or any other url) it fails with `System.ComponentModel.Win32Exception (2): An error occurred trying to start process &apos;https://github.com/dnGrep/dnGrep/wiki&apos; with working directory &apos;C:\Program Files\dnGrep&apos;. The system cannot find the file specified.`

Need to specify now `UseShellExecute = true` for all these cases.

**Comment by doug24** [comment]
Thanks for the report - I knew there would be some things I missed in testing :)  I'll fix these for the next release.

**Comment by doug24** [comment]
Fixed in [v4.0.45](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.45.0)
