### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by denisfitz57** [dnGrep/dnGrep#887]
After updating to dnGREP.4.0.26 via dnGREP.4.0.26.x64.msi 	Microsoft Windows 11 Pro Version	10.0.22000 Build 22000
I get a popup error window that says something broke down in dnGrep - check the logs.  Here are the logs:

<logevent time="2023-06-27 20:33:59.4497" level="Error" logger="dnGREP.WPF.App">
<message>Failure in application startup</message>
<exception>System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'dnGREP.WPF.PreviewControl' that matches the specified binding constraints threw an exception. ---> System.FormatException: String 'AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAAs=' was not recognized as a valid Boolean. at System.Boolean.Parse(ReadOnlySpan`1 value) at System.String.System.IConvertible.ToBoolean(IFormatProvider provider) at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 847 at dnGREP.WPF.PreviewControl..ctor() in C:\projects\dngrep\dnGrep.WPF\Views\PreviewControl.xaml.cs:line 48 at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions) --- End of inner exception stack trace --- at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri) at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream) at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator) at dnGREP.WPF.MainForm..ctor(Boolean isVisible) in C:\projects\dngrep\dnGrep.WPF\Views\MainView.xaml.cs:line 38 at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e) in C:\projects\dngrep\dnGrep.WPF\App.xaml.cs:line 63</exception>
</logevent>

**Comment by doug24** [comment]
Older versions of dnGrep put data in the user settings in binary format, which is no longer supported in .NET 7. I put code in the last few versions to convert the binary data, but the current version cannot do that anymore. Delete dnGREP.Settings.dat in the %appdata%\dnGREP folder and restart. 

If you want to try to keep your other settings, edit the dnGREP.Settings.dat file and remove anything that looks like AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAAs=

**Comment by denisfitz57** [comment]
Thanks - deleting dnGREP.Settings.dat did the trick!

**Comment by doug24** [comment]
I'll leave this open for a while so others can see the solution.

**Comment by doug24** [comment]
I spent some more time looking into this error, and it is something I can fix. Will include it in the next release.

**Comment by doug24** [comment]
Fixed in [v4.0.45](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.45.0)
