### ISSUE TITLE
Sheet Number and Slide Number missed in report

### ISSUE THREAD

**Issue by BW0407** [dnGrep/dnGrep#898]
Hi! It's a nice feature to show slide number and sheet number in search result when searching powerpoint or excel. However, it seems they are missed when export  a report. Could add them into report? Thanks~

**Comment by doug24** [comment]
Yes, I can look into adding that.

**Comment by doug24** [comment]
Added in [v4.0.69.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.69.0)
