### ISSUE TITLE
Feature request: an alternative file to manage ignores

### ISSUE THREAD

**Issue by xfilesee34** [dnGrep/dnGrep#902]
Currently .gitignore is used to ignore some files but it may be a good feature to have custom file to manage ignores i.e .dngrepignore. such a file will also help when searching with a big exclude filter since that line for exclude definition is currently short.

**Comment by doug24** [comment]
I can look into this, but it's probably going to be a while before I can get to it.  My first thought would be to use the same syntax as is currently supported by the 'Patterns to exclude' but read them from a file with one pattern per line.

Integrating .gitignore was fairly easy - there was no file format, syntax, parser, or file processing to implement. dnGrep searches for .gitignore files and asks git for the list of files and directories to ignore.

**Comment by doug24** [comment]
@xfilesee34 - there are at least a couple of ways to implement this: 
- put the .ignore file in the start directory of the path to search, like .gitignore, and dnGrep will look for it there (with .gitignore, dnGrep will scan up directories from the start directory to try to find one). I was thinking if we limit to just the search start directory, then we wouldn't need to do extra work scanning, and maybe not even need to have a UI to enable/disable it - if one exists, it will be used.  
- put the .ignore files in a specific application data directory like the dnGrep script files.  If it is a single location, the files would need a unique name, we won't need a UI to select the file location, and dnGrep could auto-populate a selection list of .ignore files to apply. You would then choose an ignore file, or none, to use in the current search.  It would stay in effect until you change it.

Do either of these sound like what you want?  Other ideas?

**Comment by xfilesee34** [comment]
What I had in mind when I opened the ticket was closer to your 1st proposed solution.
As a start I think it is good to manage that file from the top search path.

The scenario may be:
Dngrep looks for an ignore file in the path stated in "search in folder" 
If it is there, Dngrep opens the file and treats each line in that file as a filter.
the filters in that file are appended to the "patterns to exclude"

for example if there is an ignore file in the top folder with the lines:
*.txt
*.xml
/asamplefolder/asamplesubfolder

then the "patterns to exclude" will be appended with:
*.txt;*.xml;/asamplefolder/asamplesubfolder

As a first release it may be good to limit the functionality to that. then people will probably propose more solutions.
Thanks.

**Comment by xfilesee34** [comment]
@doug24 just to clarify: please do not move the ignore file contents to the UI space allocated to "patterns to exclude" as it is already limited space. It may be better to handle the contents of that file in the background.

**Comment by doug24** [comment]
Added in v4.0.115
