### ISSUE TITLE
Old "dnGREP.Settings.dat" cannot be used in new version after update

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#914]
I downloaded the new v4.0.60 *.zip archive, extracted and copied it to my previous installation folder with v4.0.45.

In old installation folder the file "dnGREP.Settings.dat" already exists.

When I start now new dnGrep with old "dnGREP.Settings.dat" it doesn't work (on Win10).
I had to delete existing "dnGREP.Settings.dat" to get v4.0.69 working.

Thats bad.

All me previous settings are lost.

Is this a bug?

How can I preserve all my old, preferences otherwise?

**Comment by doug24** [comment]
Yes, it is a bug, your settings should be preserved.  The other issues I fixed recently have been from older settings files, but I can't imagine what went wrong between 4.0.45 and 4.0.69.

I can't fix this without more information - please attach the Grep_Error_log.xml or the copy-paste the log message written when this error occurred.  If you still have the dnGREP.Settings.dat file, please attach it here too.

**Comment by pstein** [comment]
When I start dnGrep v4.0.69 with dnGREP.Settings.dat from v4.0.45 then NO error log is created.
Instead the shown GUI looks like the attached snapshot

Here is my dnGREP.Settings.dat file (from 4.0.45):

`<?xml version="1.0" encoding="utf-8"?>
<dictionary version="2" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <item key="ApplicationFontFamily">Segoe UI</item>
  <item key="MainFormFontSize">12</item>
  <item key="ReplaceFormFontSize">12</item>
  <item key="DialogFontSize">12</item>
  <item key="ResultsFontFamily">Consolas</item>
  <item key="ResultsFontSize">12</item>
  <item key="SearchFor">Genditzki</item>
  <item key="ReplaceWith"></item>
  <item key="FilePattern">*.pdf</item>
  <item key="FilePatternIgnore"></item>
  <item key="SearchFolder">D:\</item>
  <item key="LastCheckedVersion">2023-07-12T05:51:07</item>
  <item key="FastSearchBookmarks">
    <stringArray>
      <string isPinned="false">Genditzki</string>
    </stringArray>
  </item>
  <item key="FastReplaceBookmarks">
    <stringArray>
      <string isPinned="false"></string>
    </stringArray>
  </item>
  <item key="FastFileMatchBookmarks">
    <stringArray>
      <string isPinned="false">*.pdf</string>
    </stringArray>
  </item>
  <item key="FastFileNotMatchBookmarks">
    <stringArray>
      <string isPinned="false"></string>
    </stringArray>
  </item>
  <item key="FastPathBookmarks">
    <stringArray>
      <string isPinned="false">D:\</string>
    </stringArray>
  </item>
  <item key="SortDirection">Ascending</item>
  <item key="TypeOfSort">FileNameDepthFirst</item>
  <item key="ShowResultOptions">True</item>
  <item key="ResultsTreeScale">1</item>
  <item key="ResultsTreeWrap">False</item>
  <item key="HighlightMatches">True</item>
  <item key="ShowLinesInContext">True</item>
  <item key="ContextLinesBefore">2</item>
  <item key="ContextLinesAfter">3</item>
  <item key="PersonalizationOn">False</item>
  <item key="PreviewBounds">0,0,0,0</item>
  <item key="PreviewWindowState">Normal</item>
  <item key="PreviewDocked">True</item>
  <item key="PreviewDockSide">Right</item>
  <item key="PreviewDockedWidth">368,5254798146923</item>
  <item key="PreviewDockedHeight">271,6145833333333</item>
  <item key="PreviewHidden">False</item>
  <item key="PreviewAutoPosition">True</item>
  <item key="IncludeHidden">True</item>
  <item key="IncludeBinary">True</item>
  <item key="IncludeArchive">False</item>
  <item key="SearchParallel">True</item>
  <item key="IncludeSubfolder">True</item>
  <item key="MaxSubfolderDepth">-1</item>
  <item key="FollowSymlinks">False</item>
  <item key="SkipRemoteCloudStorageFiles">True</item>
  <item key="TypeOfSearch">PlainText</item>
  <item key="CodePage">-1</item>
  <item key="TypeOfFileSearch">Asterisk</item>
  <item key="UseGitignore">False</item>
  <item key="UseFileSizeFilter">No</item>
  <item key="CaseSensitive">False</item>
  <item key="Multiline">False</item>
  <item key="Singleline">False</item>
  <item key="StopAfterFirstMatch">False</item>
  <item key="WholeWord">False</item>
  <item key="BooleanOperators">False</item>
  <item key="CaptureGroupSearch">False</item>
  <item key="HighlightCaptureGroups">False</item>
  <item key="SizeFrom">0</item>
  <item key="SizeTo">100</item>
  <item key="IsFiltersExpanded">True</item>
  <item key="PreviewFileContent">True</item>
  <item key="UseFileDateFilter">None</item>
  <item key="TypeOfTimeRangeFilter">None</item>
  <item key="StartDate" xsi:nil="true" />
  <item key="EndDate" xsi:nil="true" />
  <item key="HoursFrom">0</item>
  <item key="HoursTo">8</item>
  <item key="EnableUpdateChecking">False</item>
  <item key="UpdateCheckInterval">10</item>
  <item key="CustomEditor"></item>
  <item key="CustomEditorArgs"></item>
  <item key="CompareApplication"></item>
  <item key="CompareApplicationArgs"></item>
  <item key="ShowFilePathInResults">True</item>
  <item key="AllowSearchingForFileNamePattern">True</item>
  <item key="DetectEncodingForFileNamePattern">True</item>
  <item key="ExpandResults">False</item>
  <item key="ShowVerboseMatchCount">True</item>
  <item key="ShowFileInfoTooltips">True</item>
  <item key="MatchTimeout">4</item>
  <item key="FuzzyMatchThreshold">5</item>
  <item key="MaxSearchBookmarks">1</item>
  <item key="MaxPathBookmarks">1</item>
  <item key="MaxExtensionBookmarks">1</item>
  <item key="OptionsOnMainPanel">True</item>
  <item key="MaximizeResultsTreeOnSearch">False</item>
  <item key="MaxDegreeOfParallelism">-1</item>
  <item key="ShowFullReplaceDialog">True</item>
  <item key="DeleteToRecycleBin">True</item>
  <item key="OverwriteFilesOnCopy">Prompt</item>
  <item key="OverwriteFilesOnMove">Prompt</item>
  <item key="FollowWindowsTheme">True</item>
  <item key="CurrentTheme">Light</item>
  <item key="CurrentCulture">en</item>
  <item key="UseDefaultFont">True</item>
  <item key="HexResultByteLength">16</item>
  <item key="PdfToTextOptions">-layout -enc UTF-8 -bom</item>
  <item key="PdfNumberStyle">PageNumber</item>
  <item key="OpenxmlEnabled">True</item>
  <item key="OpenxmlPreviewText">True</item>
  <item key="OpenxmlExtensions">docx,docm,xls,xlsx,xlsm,pptx,pptm</item>
  <item key="PdfEnabled">True</item>
  <item key="PdfPreviewText">True</item>
  <item key="PdfExtensions">pdf</item>
  <item key="WordEnabled">True</item>
  <item key="WordPreviewText">True</item>
  <item key="WordExtensions">doc</item>
  <item key="MainWindowBounds">367,72,1536,1075</item>
  <item key="MainWindowState">Normal</item>
  <item key="PreviewWindowWrap">False</item>
  <item key="PreviewWindowFont">12</item>
</dictionary>`

![Snapshot](https://github.com/dnGrep/dnGrep/assets/2775875/353dd3c0-d733-4408-8374-029dcc5c7d90)

**Comment by doug24** [comment]
Thank-you for the file.  Some values - PreviewDockedWidth and PreviewDockedHeight are not being written out to the settings file using InvariantCulture so decimal separator is being misinterpreted when reading the file.

**Comment by doug24** [comment]
Fixed in v4.0.115
