### ISSUE TITLE
Headless operation

### ISSUE THREAD

**Issue by nikga123** [dnGrep/dnGrep#917]
Very nice tool.  Is there any way to run dnGrep headless and just in the command line?  (If I missed something in the documentation, I apologize). Thanks.

**Comment by doug24** [comment]
Thank-you!  Well, yes and no - it's not intended to be just a command line tool.  You can run dnGrep from a command line, but it doesn't report results back to the command line. You can run a [search, generate a report, and exit without the UI starting](https://github.com/dnGrep/dnGrep/wiki/Command-Line).  Or you can [run scripts to do more complex tasks](https://github.com/dnGrep/dnGrep/wiki/Scripting-Commands) including calling other batch or Powershell scripts.  The command line or script can also start the UI to see the results.

If you want a pure command line tool, I'd recommend [ripgrep](https://github.com/BurntSushi/ripgrep).

**Comment by nikga123** [comment]
Thanks.  And thanks for the recommendation.  

This is what I am trying to do: I want to search through a (large) number of files matching the file *name* not contents.  Grep-type tools look inside archives as well (as does yours) so this is preferable.  I want to generate a report of what is found.  But again, I do not need the contents searched at all (not in this case).  Every time I run dnGrep, it opens the UI.  Maybe this is not the right tool for my needs?

**Comment by doug24** [comment]
Yes, you're right, it is going to open the window each time (shows how often I do this), so it will be open while it is running.

There are more difficulties - you can't specify search in archives from the command line, or an empty search string from command line arguments. So, you would have to create a dnGrep script to run and then call the script file from the command line:
`dngrep.exe -script smoketest`
where `smoketest` is the name of a script file in the \Scripts directory (without the file extension).  
Make `exit` the last line of the script and the window will close.

**Comment by nikga123** [comment]
Thanks @doug24 .  Appreciated.
