### ISSUE TITLE
Preview pane: Support copy text in context menu

### ISSUE THREAD

**Issue by htcfreek** [dnGrep/dnGrep#918]
It would be very helpful if the context menu of the preview pane has a copy action to copy the selected text. yit should be the first entry.

**Comment by doug24** [comment]
You can already copy selected text in the preview pane using ctrl+C.  But, yes, I can add it to the context menu as well.

**Comment by htcfreek** [comment]
I think it should be the first menu entry.

And yes I can use Ctrl+C but this is breaking my work flow if I marked some text before by using the computer mouse.

**Comment by doug24** [comment]
Addded in v4.0.115
