### ISSUE TITLE
Feature Request: Limit dnGrep to only one instance window

### ISSUE THREAD

**Issue by xfilesee34** [dnGrep/dnGrep#924]
Right now when dnGrep is started it starts in a new window.
It may be good to have an option to limit dnGrep window limit to 1 (i.e all new searches start in the same window).

**Comment by doug24** [comment]
@xfilesee34 thanks for the request.

At my day job, I often have two or three instances of dnGrep running in different directories, so this is an option I'd never use.  But I understand and can see how this would be useful.

The simplest means to do this would just bring the singleton instance to the top.  But I'm guessing you and others would want something more than that.  Are you starting dnGrep from the Windows Explorer context menu, where it sets the search folder to the folder you launch it from?  In that case, I can also pass the new folder to the existing instance of dnGrep, changing the search starting point. (Side note, you can already do this by dragging a folder from Windows Explorer onto the running dnGrep window.  And holding the ctrl key will add the new folder to the existing search path).

There are lots of other command line arguments, but they are really only used if you are starting dnGrep from a command line, batch file, or Run command. I don't think they would be useful in the single instance scenario.  Please comment if I am missing some other option you would like to see handled.

There is a danger here and I would have to first implement this to test it:  If you select multiple folders in Windows Explorer, right click and start dnGrep, Windows will start one dnGrep instance for each folder.  I know that users would like to see all of the folders added to the search path in one dnGrep instance - that's issue #864.  Those multiple calls are going to happen very quickly - almost simultaneously. I believe the code would handle creating a single instance and blocking the others from starting, but not sure how well the messaging would work with multiple processes trying to send so close together.  Or if there is any way to determine they paths should be concatenated and not just last one in wins.

**Comment by xfilesee34** [comment]
Bringing the singleton instance to top should be enough. The user can do more complex search path edits from that window or untick the single instance option to keep the current behavior.
Thanks.

**Comment by doug24** [comment]
Added in v4.0.115
