### ISSUE TITLE
The size of the preview panel is not saved correctly

### ISSUE THREAD

**Issue by boromyr** [dnGrep/dnGrep#925]
The `<item key="PreviewDockedWidth">400</item>` setting is automatically changed during saving, and I have cost that it tends to increase on its own, e.g. from 1240 to 12408, with the bug that the preview panel covers the entire GUI, as visible in this gif:

![dngrep](https://github.com/dnGrep/dnGrep/assets/52782032/0441634d-8d80-4576-8de8-a13cea5b2b07)

**Comment by doug24** [comment]
Thanks for the report - this is the same issue reported in #914 and has been fixed for the next release. PreviewDockedWidth and PreviewDockedHeight should have been written out to the settings file using InvariantCulture so decimal separator in the settings does not change with the local culture. The comma decimal separator is being misinterpreted when reading the file.

**Comment by doug24** [comment]
Fixed in v4.0.115
