### ISSUE TITLE
[feature] save last session

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#927]
I think it will be good, if I save last search result.

![image](https://github.com/dnGrep/dnGrep/assets/11432724/0cdf7bb5-09ed-4749-9254-62a65716dc52)

**Comment by doug24** [comment]
You can save the results of a search from the More button - Save results - Report.  That includes some details of the search and all the results expanded.

I don't think it is useful to save the search results in the format used to populate the results view.  The search produces a list of files and locations within the file where a match was found - it is a very abbreviated format.  When you select or open a node in the tree, dnGrep goes back to the file to get the actual text in both the tree and the preview pane.  The search results are transient - files are modified, added, moved and deleted.  It doesn't make sense to try to open old results when you can just rerun the search.  Create a bookmark to save the search parameters and associate it with the source directory if you want.

**Comment by Aliaksandr3by** [comment]
sorry.
I told about save last session, if  I have closed window by mistaken.

**Comment by doug24** [comment]
No, there is no means to reload results. All the input settings for a search are saved and loaded when you restart so you can rerun the search.  

I am not going add a file format to save and reload the results, partial or complete - there are so many problems with doing this, and it is not worth many hours of my time to do it. Just rerun the search.

**Comment by Aliaksandr3by** [comment]
if I have many files f.e. 100gb, it is difficult.

**Comment by doug24** [comment]
I can give you a confirmation dialog so you that you have to confirm that you really want to close the application.

**Comment by Aliaksandr3by** [comment]
if I change settings that is needed to reload the program?

**Comment by doug24** [comment]
I don't understand the question.  The dnGrep settings are saved at the start of every search, when the Options dialog is saved, when the Test window is closed, and when the application exits.  The are loaded from the file when the application is started. 

If you edit the settings file with a text editor, do that only when dnGrep is not running or it will overwrite you changes.  The start dnGrep to load the settings.
