### ISSUE TITLE
Some regex patterns throw a timeout exception before the timeout expires.

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#930]
I performed a regex search for "\bQtyToStock\b(?:.*\n?.*){0,50}\bWorkOrderDetails\b" with my regex timeout set to 120 seconds, but it failed much sooner.

**Comment by doug24** [comment]
Yes, this is a bug.  It looks like when the timeout option was added - 6 years ago - it was never hooked up to the regex code in the search and replace, and it's set at the default 4 seconds. I'll fix it for the next release.

**Comment by doug24** [comment]
Fixed in v4.0.115
