### ISSUE TITLE
page numbers - not line numbers for PDF search export

### ISSUE THREAD

**Issue by bitseeker** [dnGrep/dnGrep#931]
Hi Doug,

when searching in PDF file for e.g. misspelled words, the resultpane in GUI shows the page numbers of the PDF - thats great.
But when using the 'Save results' as report/text/csv , in all three options, the results are printed with line numbers instead of page numbers in front. 
This makes it very difficult or even impossible for someone who has to change these mistyped results as you can not go to certain lines in Acrobat or Indesign.

thx Olli

**Comment by doug24** [comment]
The page numbers and line numbers should be in the "Report" format - they were just added in the 4.0.69 release.  Here is what I see in the report:

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/43c8f270-c7fb-443b-b3fe-b6d8d4c91e2c" width="400"/>

**Comment by bitseeker** [comment]
Yes, you are right. I looked in report options and in the preview panel only line numbers are shown.
![grafik](https://github.com/dnGrep/dnGrep/assets/1962359/5a030111-a787-4abf-90d9-1c860022ea15)
So report options are for saving in txt and csv format, but not for 'save as report' - is that correct?

Another issue: Sometimes PDF are secured. If you search a secured PDF, no results are found. 
Is it possible to show a message which says that the PDF is secured and can not be searched?

**Comment by doug24** [comment]
Yes, the report options are for the text and csv formats. The intention is that those formats are for exporting data to be used in another application or downstream processing.  The report option is for a human readable record of the search.  Of course, any of them can be used for anything. Do you need the page number for text or csv output?

dnGrep does not read PDF files directly. The are converted to plain text using a third-party application. I don't know if I get an output related to secured PDFs, but there probably is some way.  But I don't have a secured PDF to test it, so I don't have a way to try it right now.

**Comment by doug24** [comment]
Added file messages in v4.0.115
