### ISSUE TITLE
Notified of new version, but nothing happens when clicking "Yes"

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#935]
Installed version: 4.0.26.0

![DownloadLatest](https://github.com/dnGrep/dnGrep/assets/1332009/8ab77a6d-a0a0-4c48-abf1-dfae37087d1b)

**Comment by doug24** [comment]
Duplicate of #881.  Install the latest version here:  https://github.com/dnGrep/dnGrep/releases/tag/v4.0.69.0
