### ISSUE TITLE
No drag & drop of (path plus) folder into "Folder" entry field possible

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#937]
In general I want to search over my whole partition D:\
So in entry field "Folder" contain most of the time "D:\".

But occasionally I would like to restrict (content) search to a subsubsub folder like

E:\tools\logs\2021\branch 23\

As I found out I cannot drag & drop this folder from File Explorer into this entry field.

I have to select or enter it manually.

Thats uncomfortable and unnecessary.

Can you allow drag & drop & folders in next release

Thank you

**Comment by doug24** [comment]
Drag and dropping folders is already a feature - just drop the folder anywhere on the main window and it will change the search path.  Hold the Ctrl key to append to the existing folder.  I don't know why it is blocked if you try to drop it directly on the field, but I'll look into it when I have time.

**Comment by pstein** [comment]
Ok, drag & drop anywhere on the window works EXCEPT drag & drop on the entry field(s).

But this is counter intuitive.

Could you extend the drop area to entry fields too?

**Comment by doug24** [comment]
Fixed in v4.0.115
