### ISSUE TITLE
Making pdftotext robuster

### ISSUE THREAD

**Issue by liujunwei4321** [dnGrep/dnGrep#943]
xpdf cannot handle some pdfs right, you can using the attached version to make it robuster! It can handling more encodings. You can check it at https://www.xpdfreader.com/download.html . There are language support packages.
[xpdf_2.zip](https://github.com/dnGrep/dnGrep/files/12569824/xpdf_2.zip)

**Comment by doug24** [comment]
See the [dnGrep help page](https://github.com/dnGrep/dnGrep/wiki/PDF-Search) for how to use the language support packages with pdftotext and dnGrep.
