### ISSUE TITLE
Feature Request: search by files and folders names

### ISSUE THREAD

**Issue by VadimLL** [dnGrep/dnGrep#953]
Excellent program! Thank you much!
Just one wish: please, can you add search not only in file's content but also by files and folders names?

**Comment by doug24** [comment]
Maybe I don't understand what you are asking or what you are trying to do, but can't you already do that with the "Patterns to match" field?  You can search for any string in a file name using either wildcards or regular expressions.  

But it doesn't match strings in folder names - what would that mean? return all files in any subdirectory of a directory with a matching name?  That is how the exclusion works - exclude all files in any subdirectory of a matching directory name.

**Comment by doug24** [comment]
Since you didn't respond, I'm assuming the existing functionality does what you need and will close this.  If this isn't the case, please add additional information and reopen.
