### ISSUE TITLE
[bug] problem with *.doc processing "Document read failed"

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#955]
Document read failed

![image](https://github.com/dnGrep/dnGrep/assets/11432724/5c773d92-f105-46c4-b2f5-1974708a1a01)

**Comment by doug24** [comment]
dnGrep uses MS Word automation to search *.doc files, which means lots of things can go wrong.

Do you have the document open in another application? Word will only one a file once, close it and try again.

Is there anything in the error log?  You can get to the log directory quickly from the About - Application data and logs menu item.

**Comment by Aliaksandr3by** [comment]
may be the problem is that I don't have the ms Word?

**Comment by Aliaksandr3by** [comment]
[Grep_Error_Log.zip](https://github.com/dnGrep/dnGrep/files/12743541/Grep_Error_Log.zip)

**Comment by doug24** [comment]
Yes, that would be the problem. dnGrep cannot search in the old MS Word .doc file format without Word installed.  You can disable the Word plugin in the Options dialog, and dnGrep will treat .doc files as any other binary file, but you won't get any kind of satisfactory search results from it.

dnGrep can search the new .docx format without Word installed.  If you really want to search in these files, convert them from .doc to .docx.

**Comment by Aliaksandr3by** [comment]
thx, I convert to another format)
