### ISSUE TITLE
Bug: dnGrep v4.0.115 not able to show context lines from *.pdf in preview pane

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#957]
After upgrading to v4.0.115 on Windows 10 I performed now a search for a certain pattern in *.pdf files on my D:\ partition.

dngrep found a couple of matches for
Folder: D:\\
Patters to match: *.pdf
Search: text
Search for: \<a pattern like foo bar\>
Preview file: YES
Highlight Matches: YES
Show context lines: YES 2 lines before and after

Unfortunately the preview pane on the right does NOT show the matching (context) lines.
Instead an error text at the top is shown:

"The file is either binary or too large to be shown"

This is nonsense. All found *.pdf files are around 1 to 10 MB
When I expand the files in the files list on the left I can see a comment:

"pdftotext returned 'error related to PDF permissions' reading 'D:\aaa\bbb\ccc\sample.pdf"

Thats nonsense too: When I right click on these *.pdf files and select "open" from context menu then I can open and read all the files.

So I guess its a bug.

In previous dnGrep version it all worked successfully.

Any chance to repair it?

**Comment by doug24** [comment]
All of my test files are working. Please attach a sample file that I can reproduce this.

**Comment by doug24** [comment]
I will add here what I said in #956: There was no change to pdftotext.exe in this release, the only change was as noted in the release notes:

**Raise PDF errors:** If PDF files are secured or encrypted, they will fail to open. These errors are logged to the dnGrep log file, but not shown in the results. This has been changed so the file open errors are shown in the results tree.

Are you certain these files worked in a previous release?  Go download the portable zip version for a previous release and try it again. If dnGrep does not find expected matched in a file, check the error log.  If it does work in a previous release, attach the file here so I can find the problem and fix it.  But I can't fix something that I can't reproduce.

If it is not working in a previous release, check the security settings on the file.  In Adobe Acrobat Reader, it is on the menu -> Document Properties, and the Security tab in the dialog.  Or menu -> Protection -> Security Properties.  Pdftotext.exe checks the security properties and will not extract text if "Content Copying" is not allowed.  I checked back to old versions of pdftotext.exe (3.02) and that has always been its policy.  Yes, you can still view the file in a pdf reader if Content Copying is not allowed.

The problem you see about binary files is completely expected: if pdftotext.exe cannot extract the text from the pdf, there will be no plain text to show in the preview pane.  The preview pane does not show the PDF document rendered as you would see it in Acrobat Reader or in a web browser.

**Comment by pstein** [comment]
I found the reason (but no solution):

When I type as search pattern "show" (without double quotes) then it works as expected.

But when I type "no show" or "all show" (without double quotes) then the problem occurs as described in my first post.
So  whenever I enter two search words delimited with a blank then dngrep does not understand it.

Hmm, is this intended?

How can I avoid this?

**Comment by doug24** [comment]
I cannot see how the search pattern will have any effect on converting a PDF document to text - they are completely unrelated tasks in the application.

Searching for word separated by a space is normal, it's been done millions of times.  You are going to have to attach a file to reproduce the problem you are seeing.

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/5b0f8183-338e-4596-a17b-2d1ef444fd89" width="360"/>

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/debcdb5c-4f26-4a68-a648-6f5c83238f1e" width="360"/>

**Comment by pstein** [comment]
Hmm, here it looks like:

![dngrep snapshot](https://github.com/dnGrep/dnGrep/assets/2775875/c255eec7-8e9a-4236-b761-a2ddacb80966)

**Comment by pstein** [comment]
As far as I can see the erroneous pdfs are rather old.
Maybe this is an issue of dngrep with old PDF versions?

I attach three sample pdfs
[UML Applied (2001 Ariadne training).pdf](https://github.com/dnGrep/dnGrep/files/12860355/UML.Applied.2001.Ariadne.training.pdf)
[Oracle 9i Programming with PL SQL - Additional Practice (10.2001 Oracle).pdf](https://github.com/dnGrep/dnGrep/files/12860359/Oracle.9i.Programming.with.PL.SQL.-.Additional.Practice.10.2001.Oracle.pdf)
[Manual CasioProTrek PRG70.pdf](https://github.com/dnGrep/dnGrep/files/12860361/Manual.CasioProTrek.PRG70.pdf)

**Comment by doug24** [comment]
It's not the age of the files or the search pattern. They all have copy protection enabled.  Running pdftotext from the command line returns "Permission Error: Copying of text from this document is not allowed" for versions 3 and 4, so dnGrep has never been able to extract text from these files.  

Adobe Acrobat Reader, XPDFReader, Google Chrome, and Microsoft Bing all respect the permission flags and you cannot copy or extract text from these files.  It is possible to find other PDF tools that ignore the permissions.  Note these permissions allow viewing the file, but not extracting text, are set by the owner/creator of the file.  The Oracle file also has a copyright notice in it that disallows copying in any from or by any means. dnGrep cannot search the text without extracting the text.

The difference in v4.0.115 of dnGrep is that you are now seeing these errors in the results list where previous version of dnGrep only wrote the errors to the log file and silently ignored them in the results list - as if the file never existed. I was not aware of this issue or the security flags in PDF files until a user brought this up in another bug report.  I had to go find some PDF files with security enabled to add to my set of test files.

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/df00f1d1-cdf4-4efe-baa4-0d5842d26878" width="400"/>

**Comment by pstein** [comment]
Ok, I understand. 
So reading text from such a PDF is allowed but not copying? Hmm, interesting.
Never thought that there could be a difference.

Do you know a tool which allows me IN ONE STEP for all PDFs on my partition to allow copying text for all PDF files which allow reading?

Additionally: Could you add on option "show permission errors only in LOG file"?

**Comment by doug24** [comment]
I am not familiar with PDF tools and I don't know about tools to remove restrictions.

I will think about adding a new option.

**Comment by pstein** [comment]
Ok. One more request:

When I click on one of the critical PDFs then on the right side pane the following error text is shown (as previously mentioned):

"The file is either binary or too large to be shown"

This is very misleading and confusing.

Instead the following reason should be displayed:

"PDF allows only reading but not copying text"

Can you change it?

**Comment by doug24** [comment]
All PDF files **_are_** binary files - how is that misleading? Yes, the problem is that the text could not be extracted from the binary file - but you already know that from the message in the results list.

Up until a year ago (August 2022) dnGrep did not show any text for PDF files. It was then I added the option to show the text that was extracted from PDF, Word, PowerPoint and Excel files. These are all binary files that cannot be viewed directly with a text editor or searched without special code to get the text out of the binary file.

**Comment by doug24** [comment]
New option to hide document read errors has been added in [v4.0.151.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.151.0)
