### ISSUE TITLE
Open the PDF and jump to the corresponding page

### ISSUE THREAD

**Issue by jbxenzxy** [dnGrep/dnGrep#964]
![222222222222222222222222](https://github.com/dnGrep/dnGrep/assets/40913849/c5283e3a-fda6-4f2b-ae97-17e3fb29adf5)

Thanks a lot.

**Comment by doug24** [comment]
Double clicking on a match line will open the file in the custom editor you define in the dnGrep options.  If you haven't defined a custom editor, then it will open with the application you have associated with pdf files on your system. 

If you don't define a custom editor, there isn't any way to do this. Using the associated application is the same as double clicking a pdf file in Windows Explorer, and there isn't any way to add additional arguments to that.  And even if there was, dnGrep does not know what the application is, or what format the argument should be.

You need to configure your PDF reader as the custom editor in the dnGrep Options.  Then you can set the command line arguments as needed for your reader and then open the files with the `Open with custom editor` command or double clicking on the result line as you show above.

**Comment by jbxenzxy** [comment]
I did it according to your method, but I feel that some settings are incorrect. Can you give me some more advice? thanks
![2222222222222222222222222](https://github.com/dnGrep/dnGrep/assets/40913849/a5a43b9b-eb54-4d7c-b10b-57eaebab8f0c)
![3333333333333333333333333333](https://github.com/dnGrep/dnGrep/assets/40913849/72454243-1f87-44f8-8f26-f02407cd8816)
![44444444444444444](https://github.com/dnGrep/dnGrep/assets/40913849/26309eac-1a20-47f1-b572-46db324ad7c4)

**Comment by doug24** [comment]
If the document is not already open, using this for the arguments is working for me:
<img src="https://github.com/dnGrep/dnGrep/assets/17227248/b1cb09d4-55a7-4c6a-a165-d96ba66914ac" width="640"/>

`/A "page=%page" "%file"`

If the document is already open in Acrobat, it just stays on the same page.  But that's an Acrobat thing, nothing dnGrep can do about that.

I don't know why, but Adobe makes it very hard to find the command line syntax. I got this from googling "acrobat reader command line arguments" and looking on stackoverflow.com

**Comment by jbxenzxy** [comment]
Thanks a lot!
