### ISSUE TITLE
[feature] show books (a title ) that don't have a text layer

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#967]
may be might You add a feature, that show books (a title ) that don't have text layer?
if I will use pdftotext.exe -layout -enc UTF-8 -bom 'imagePdf.pdf' I get 'imagePdf.txt' with 0 size.
can you add information about the size or symbol count extracted from files?
I think it is a good idea to get information about files in folder that have been processed. 

100500 PDF, 500100 djvu .... 40 files dont' have o text;
![image](https://github.com/dnGrep/dnGrep/assets/11432724/d4032ab0-1338-45f6-8aab-6a631fb6b22c)

**Comment by doug24** [comment]
Yes, I agree that this would be useful information, just like when the PDF protection prevents opening or extracting text.  Conversely, when I added that feature some users complained about seeing the error messages and asked for an option to hide them again.  I can see treating this error the same way as the protection errors.

One thing to note, a PDF may contain only page images but also include annotations.  In this case the text file will not be zero size, but the majority of the PDF will not be searchable - so like with so many other PDF problems, this is not a completely reliable indicator.  In the end, of all the file formats dnGrep supports, PDF is the worst file format for searching.

**Comment by Aliaksandr3by** [comment]
I test on 460 files with powershell, and the test for null content is work, maybe only for me.

I extracted text, and testing it by the  length
`

Clear-Host
[Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("utf-8")

$pdftotext = "E:\_SOFT\xpdf-tools-win\bin64\pdftotext.exe"
$pdfinfo = "E:\_SOFT\xpdf-tools-win\bin64\pdfinfo.exe"
$resultFolder = "E:\Downloads\TMP"
$resultFolderError = "E:\Downloads\TMP\Temp"

$fileDestiny = "E:\BooksOther\Cooking"

try {

    if (Test-Path -Path $resultFolderError) {

    }
    else {
        New-Item -Path $resultFolder -Name "Temp" -ItemType Directory
    }

    Write-Warning ":"

    [regex]$rx = '(.*(?=)\.pdf|djvu)'

    $temp = Get-ChildItem -Path $fileDestiny -Recurse -File

    foreach ($item in $temp) {

        $property = $item  | Select-Object -Property *
        #Write-Output $property

        $valueRegEx = $rx.Match($item).Value
        #Write-Output "regex result $valueRegEx"

        if ($valueRegEx.Length -gt 0) {

            $fileName = $item.Name
            $fileNameFullNewPath = "$resultFolder\$fileName.txt"

            $q0 = &$pdfinfo $valueRegEx

            $q1 = &$pdftotext -layout -enc UTF-8 -bom $valueRegEx $fileNameFullNewPath

            if (Test-Path $fileNameFullNewPath) {

                #Write-Output $fileNameFullNewPath

                try {
                    $contentLength = (Get-Content $fileNameFullNewPath).LongLength
                    if ($contentLength -gt 0) {
                        #Write-Output $contentLength
                    }
                    else {
                        Write-Error "$fileNameFullNewPath is empty"
                        Move-Item -Path $fileNameFullNewPath -Destination $resultFolderError
                        #Read-Host
                    }
                }
                catch {
                    Write-Error $fileNameFullNewPath
                    #Read-Host
                }
            
            
            }
            else {
                Write-Error $fileNameFullNewPath
                #Read-Host
            }
        
        }
    }
    Write-Warning "it's done"
}
catch {
    "ERROR: $_"
    #Read-Host
}
`

**Comment by doug24** [comment]
Added to [v4.0.151.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.151.0)

**Comment by Aliaksandr3by** [comment]
I don't understand how to work this feature.
two files ocr and image,
how do I get a result from the option. and how can I view it? 
![image](https://github.com/dnGrep/dnGrep/assets/11432724/5e8c807f-c97b-4ea0-8ea7-f1eb9e07f7c2)

![image](https://github.com/dnGrep/dnGrep/assets/11432724/fbf0a3a5-d2d2-46d0-b458-9bd2979c9e83)

**Comment by doug24** [comment]
This feature will warn you if a PDF contains no text to search.  

From the results you show, it looks to me that one file searched successfully, and the other did not.  I'm guessing you think you should have gotten a warning about the other file having no text. I can't tell you why without seeing the file, but if I had to guess, the other file has some text in it.

**Comment by Aliaksandr3by** [comment]
if I use pdftotext to Bruce Weinstein, Mark Scarbrough - The Ultimate Chocolate Cookie Book - 2004.pdf
i got TXT with 0 content
[Bruce Weinstein, Mark Scarbrough - The Ultimate Chocolate Cookie Book - 2004.txt](https://github.com/dnGrep/dnGrep/files/13468290/Bruce.Weinstein.Mark.Scarbrough.-.The.Ultimate.Chocolate.Cookie.Book.-.2004.txt)

**Comment by Aliaksandr3by** [comment]
I have 20gb books for testing, and I have not got a bed result.
I don't understand what is I did wrong.

I use win11_64 with portable version of you'r program

**Comment by doug24** [comment]
Your text file has 258 characters in it - all form feed/page break characters and one line feed.  I had put a pre-check on file length and was only testing files with very few characters in it for being empty, as I did not want to waste time on larger files.  My test files were just a page or two, not 258 empty pages.  I guess I'll have to greatly increase the file size pre-check or remove the pre-check and searching PDFs will just run a little slower.

**Comment by Aliaksandr3by** [comment]
sorry, I don't view a file with couple pages.

c# have a function that test file by content ( Get-Content $fileNameFullNewPath).LongLength --> powershell

I think  do *,djvu not analysed is?

**Comment by doug24** [comment]
The method I have for finding files with no searchable text works fine.  But the check is not called if the file size is above a threshold.  When I removed the threshold, it worked on the sample file you provided.  I was just trying to save time checking files that seemed big enough to contain text.  My assumption was wrong, and I will take out the pre-check, and test every PDF file for empty text.

**Comment by doug24** [comment]
Fixed in [v4.0.189](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.189.0)
