### ISSUE TITLE
Problem: Bookmarks menu

### ISSUE THREAD

**Issue by BambuschJ** [dnGrep/dnGrep#970]
A bookmark is duplicated and only the name should be changed (Fiel source; File Filters; Content Settings are the same)
	>> Message "This Bookmark already exist".
![dnGrep_BoolmarkDetails_Maske01](https://github.com/dnGrep/dnGrep/assets/92531071/cbb2fea3-4178-4716-838d-4b8d54c9a4a9)

**Comment by doug24** [comment]
Bookmarks have grown from about 3 properties when I started on the project to 27 properties now.  The bookmark name was a recent addition (about a year ago) in part to be able to reference bookmarks from scripts.  Equality of bookmarks is done by comparing 24 bookmark properties - but name is not one of them.  First, name is optional.  Second, the UI needs to identify a set of properties that is equivalent to a bookmark at times other than when you apply a bookmark.  A name or id of the bookmark is not sufficient.  And the current set of properties on the UI doesn't have a name anywhere.

I don't understand why you would want two bookmarks that are identical but with different names. Is there a compelling reason?

I can look into adding the bookmark name to the bookmark equality.  I'll have to think about it - but my second point above is the reason it's not there now - the need to find equality without considering the name.  And an object really shouldn't have two ways to determine equality, it needs to be invariant.

**Comment by BambuschJ** [comment]
Hello Doug P,

first of all a big praise for this very good tool!!!

I use the name of the bookmark for orientation and since I now also manage bookmark sets for other users, it is not easy to keep the Überblich.

Another alternative to include the name in the index, would be to adjust the order of the bookmark columns, but unfortunately this is lost after restarting dnGrep.
![dnGrep_BoolmarkDetails_Maske02](https://github.com/dnGrep/dnGrep/assets/92531071/6e12ebda-95f5-43eb-99c2-baa25671e6ef)
![dnGrep_BoolmarkDetails_Maske03](https://github.com/dnGrep/dnGrep/assets/92531071/e8afa391-d7a2-4751-874f-ce545576c5d1)

**Comment by doug24** [comment]
After looking some more, I do need to continue excluding the name from the Bookmark equality.

But I think I could make the "This bookmark already exists" a warning, not an error, so users can create duplicates.  This will take more testing to make sure it doesn't break something.

The main UI attempts to match the current set of search parameters with existing bookmarks to highlight the bookmark symbols next to the Test button.  As long as it matches any one of the duplicates, that's OK. 

The bookmark "Plus" button adds a search folder association, the user won't know which it was added to. Again, OK, just have to be careful if modifying one of the duplicates.

If the bookmark "Star" is highlighted, clicking it will delete the bookmark.  But the duplicate bookmark will then be a match, and the Star will be highlighted again. That's unexpected behavior - it looks like the delete didn't do anything. And if you have names on the duplicates, you don't know which one was deleted.  So, the recommendation would be, don't delete bookmarks this way.

I can look at saving and restoring the Bookmark column order and sizes, and the Bookmark window size. But that's going to have to wait until I have more time to work on it.

**Comment by doug24** [comment]
Added save/restore of bookmark column order, column size and bookmark window size in [v4.0.151.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.151.0)

**Comment by BambuschJ** [comment]
Hallo Doug P,

it works great for me – it’s a new level form y using.

Mit freundlichen Grüßen / Best regards
i.V. Bambusch, Jürgen
Produktionsleiter

Tel +49 2302 177 603

[cid:c99d45ae-cb93-4a7b-a83d-a181f2fe0942]
High Precision Components Witten GmbH
Dortmunder Straße 54
58455 Witten

Sitz der Gesellschaft: Witten – Handelsregister: HRB 15647
Geschäftsführung: Cornel Müller, Peter Flaschel

Von: Doug P ***@***.***>
Gesendet: Mittwoch, 15. November 2023 01:05
An: dnGrep/dnGrep ***@***.***>
Cc: Bambusch Jürgen ***@***.***>; State change ***@***.***>
Betreff: Re: [dnGrep/dnGrep] Problem: Bookmarks menu (Issue #970)


[ACHTUNG: Diese E-Mail stammt von außerhalb der Organisation. Klicken Sie nicht auf Links und öffnen Sie keine Anhänge, es sei denn, Sie vertrauen dem Absender.]

Added save/restore of bookmark column order, column size and bookmark window size in v4.0.151.0<https://github.com/dnGrep/dnGrep/releases/tag/v4.0.151.0>

**Comment by fade2gray** [comment]
Just a cautionary note - I'd remove your phone number.

**Comment by BambuschJ** [comment]
Hallo Doug,

can you remove all adress information
sorry i have not a view on it!!

Thanks

**Comment by doug24** [comment]
Yes, no problem
