### ISSUE TITLE
[feature] to add a menu for containing external viewer 

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#973]
I think, to add a menu for containing external viewer is good.

![image](https://github.com/dnGrep/dnGrep/assets/11432724/48fa3cee-c81b-4836-a976-c8f45f2e7647)

like in the XnViewMP (free image viewer)
![image](https://github.com/dnGrep/dnGrep/assets/11432724/0d122712-e487-457e-93e9-0b819dd0f7f5)

**Comment by doug24** [comment]
Added in [v4.1.4](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)
