### ISSUE TITLE
[feature] add multiple folder for to be processed 

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#976]
some thing like this
![image](https://github.com/dnGrep/dnGrep/assets/11432724/1f1d33d3-3de4-40bb-aa09-afd72694c11d)

**Comment by doug24** [comment]
It's already there: to search multiple folders or files, separate the paths with a comma or semicolon. Add as many as you like.
If you drag a folder from Windows Explorer and drop it on the dnGrep window, hold the Ctrl key down to append the new path to the existing path.
