### ISSUE TITLE
[feature] add filtering books

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#980]
to add filter for fast search in result of Search, like program Everything (https://www.voidtools.com/downloads/) but only in results by name of a book

![image](https://github.com/dnGrep/dnGrep/assets/11432724/fc145e3c-1d1e-4785-bcaf-2f746f5360b7)

**Comment by doug24** [comment]
Based on all your requests, I'm not sure this application fits your needs.

You have the ability to filter by file name before searching, but instead, you use *.*   Your searches would run much faster if you narrowed the original search.  

You also have the ability to sort the results by file name, which makes it easy to find a file by name.

**Comment by Aliaksandr3by** [comment]
my problem is that I don't know what exactly I am seeking, therefore I am using any items that give to me any hint.
I think 80% pdf is image with OCR layer with many errors/mistakes. If I сarify the request I will get incorrect result

pan\s{0,5}cake = pancake != pan kake
pan smashed like a cake !=pan\s{0,25}cake --> logical error

I don't know to need the feature or not need. If you have time you can add option in settings and realize feature.
I think all searching in the searching is good

**Comment by doug24** [comment]
Again, it sounds like dnGrep is not a good fit for your needs.

You have more change requests than any user I've seen in the past 7 years.  I am not building a custom application for you. I am not going to spend hours of my time to save you a mouse click.  

If you didn't know, I work on this application on my own time for no compensation. That's how everyone gets it for free. I have a day job and a life, and I put more time into this project than I should.  I have plenty of things to work on.

My priorities are: 
1. Fix things that are broken
2. Work on interesting problems
3. Add features that I feel will have the most benefit to the most users.

I will never try to match features of another program just so you or anyone else can get out of paying for a license to another developer.

I will continue to work to improve the application, but I get to decide how I spend my time.

**Comment by Aliaksandr3by** [comment]
sorry, it is only my wish.
