### ISSUE TITLE
[propousal] add real batton for keyShortCuts for

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#981]
I like to sit on PC with one left hand to support the head,  and using only mouse.
![image](https://github.com/dnGrep/dnGrep/assets/11432724/f84c9dbb-29c7-41d7-a6ac-3911825ad5de)

![image](https://github.com/dnGrep/dnGrep/assets/11432724/3cf09c66-e499-4ec3-9f8b-7f330fbcaf04)

**Comment by doug24** [comment]
See the comment I wrote here: https://github.com/dnGrep/dnGrep/issues/968

Those command keys were added for people who don't use the mouse.  Everything you want can already be done using only the mouse.

**Comment by Aliaksandr3by** [comment]
might you can add to command line "show result options" ?
![image](https://github.com/dnGrep/dnGrep/assets/11432724/e6d35809-5ade-4748-8d71-9f0be7729960)

**Comment by Aliaksandr3by** [comment]
Repeat
