### ISSUE TITLE
Custom editor integration doesn't have a means to escape quotes

### ISSUE THREAD

**Issue by AlexVallat** [dnGrep/dnGrep#984]
When using a substitution keyword for the custom editor, such as %match, there is no way to have it escape quotes. So trying to pass something like `notepad3.exe /m "%match"` will fail if the matched text contains a quote mark, resulting in an incorrect command line like `notepad3.exe /m "Console.WriteLine("Hello World")"`

**Comment by doug24** [comment]
OK, I'll look at it. 

I haven't used notepad3 before, and I'm trying to see how the `/m` argument should work. I've tried many times - with and without quotes and different patterns - and can't get it to work at all - what am I doing wrong?  This command will open the file, but does not match anything, the cursor just stays at the start of the file ("Hello World" is on the second line).

`Notepad3.exe /m "World" C:\Repos\testFiles\test\issue984\helloWorld.txt`

**Comment by AlexVallat** [comment]
I've just tried downloading the latest portable Notepad3 and yeah, you're right, looks like they broke it for v6, I'll raise an issue on their github. Until then, it works fine on v5: https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_5.21.1129.1/Notepad3_5.21.1129.1_x64_Portable.zip

It also works fine with v6 if you run the command twice, for some reason.

**Comment by AlexVallat** [comment]
Oh, looks like they've already fixed it in their RC, you can use the 6.23.717.1 rc version too: https://www.rizonesoft.com/downloads/notepad3/#h-portable-edition-1

The underlying issue with passing `%match` with quotes in it is independent of notepad3, though, that just happened to be what I was using. I would expect that any tool that takes the string to highlight as a command line arg would probably need it escaped.

**Comment by doug24** [comment]
Fixed in [v4.0.151.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.151.0)
