### ISSUE TITLE
dnGREP.Engines.Pdf Exception thrown

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#99]
_From [jpcoet...@gmail.com](https://code.google.com/u/105485229236395564003/) on August 02, 2011 05:59:05_

What steps will reproduce the problem? 1. Searching a directory containing PDFs for the word "interferometer" 2. 3. What is the expected output? What do you see instead? Some positive results (since files contain the word) What version of the product are you using? On what operating system? 2.5.0 on Vista Please provide any additional information below. \* A pop-up box appears saying: 

---

  Plugin Errors

---

  The following plugins failed to load:
    \* dnGREP.Engines.Pdf (Exception has been thrown by the target of an invocation.)
  Default engine was used instead.
- I am running the portable version
- .NET 4.0 is up-to-date
- The PDF files are on my C: drive
- No XML error file is created
- I have only 1 plugin (PDF). If I load other plugins, a Windows box also appears, saying:
  Microsoft Windows
  dnGREP has stopped working
  A problem caused the program to stop working correctly. Please close the program.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=95_

**Comment by doug24** [comment]
I believe this is no longer an issue
