### ISSUE TITLE
功能请求：能否增加mobi,epub,azw3等格式的支持。

### ISSUE THREAD

**Issue by zbb7001** [dnGrep/dnGrep#997]

**Comment by doug24** [comment]
dnGrep searches in binary format documents (Word, Excel, PDF) by first extracting plain text from the document.  This would be the way I would approach searching ebook documents too.  But it will take special code for each file format to extract the text.

You can search epub files now since the file format is a zip archive of html, but you are searching in the raw html and not the plain text.  Just make sure you have the 'Search in archives' checked.

The other ebook formats are not as easy, but it's possible they could be added in the future.

**Comment by zbb7001** [comment]
### 谢谢回复！
#### 关于epub文件的原理，我明白了，我尝试搜索epub文件，但搜索结果为０。

![image](https://github.com/dnGrep/dnGrep/assets/101622397/65fc6427-fbc5-4679-a591-cac44c5087dc)

**Comment by doug24** [comment]
dnGrep treats an archive as a compressed folder.  You don't search for the folder, but the files in the folder.  Change the filter from *.epub to *.xhtml

**Comment by zbb7001** [comment]
> dnGrep treats an archive as a compressed folder. You don't search for the folder, but the files in the folder. Change the filter from *.epub to *.xhtml

### 谢谢！问题完美解决。截一张图，希望能帮助到有同样问题的兄弟。
![image](https://github.com/dnGrep/dnGrep/assets/101622397/2dd83d91-6cf4-4f67-9e59-15e26e91e297)

**Comment by zbb7001** [comment]
![image](https://github.com/dnGrep/dnGrep/assets/101622397/0b0646b4-937b-4873-8aa9-8d00e7f7f443)
> txt文件过大，软件会提示是否  `仍然预览`，请问：如何设置为不再提示  `仍然预览`，而是直接打开txt文件。

**Comment by doug24** [comment]
There isn't any way currently to disable the prompt - dnGrep will ask if the file is over 4MB.   I don't want to track what files you have already said to open anyway, but I could make an option so you can set the limit to whatever value you want based on what you find acceptable for the speed of opening the file.

**Comment by zbb7001** [comment]
> F7:: 
If WinActive("ahk_exe dnGREP.exe")
runwait, %ComSpec% /c taskkill /f /IM dnGREP.exe, , Hide
Send, {ctrl down}c{ctrl up} 
sleep, 50
 Run "E:\dnGREP\dnGREP.exe" -f "E:\txt" /pm *.xhtml;*.txt;*.md -s %clipboard% 
Return
#IfWinActive

- Autohotkey  脚本　
  - 自己用的脚本，使用起来感觉还是挺方便的。希望对大家有用，（本人不太懂编程，如有错误请自行修改）。
  - 使用时只需要选中要查询的内容，再按下快捷键F7，脚本就会打开dnGREP.exe并自动进行搜索。（从未使用过的朋友，请先行安装Autohotkey1.1）
  - 注意：要修改脚本中的软件路径`E:\dnGREP\dnGREP.exe`，并修改搜索内容路径`E:\txt`。搜索文件名后缀`*.xhtml;*.txt;*.md`可以自行添加。

**Comment by doug24** [comment]
Added option to set the file size in [v4.1.4](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)

**Comment by zbb7001** [comment]
> [v4.1.4](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)中添加了设置文件大小的选项[](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)

![image](https://github.com/dnGrep/dnGrep/assets/101622397/c0ec4946-4d51-459c-9655-5ba4d87fa1ba)
## 问题1  请问如何锁定软件的界面？
![image](https://github.com/dnGrep/dnGrep/assets/101622397/41e81ae8-8191-4f58-a6db-3ceb01f39b4a)
### 每次用Autohotkey脚本打开时，软件的界面会变成如下。
![image](https://github.com/dnGrep/dnGrep/assets/101622397/c4f39f3a-4991-4a00-9361-274e8a228183)
### 说明
- 如果直接打开dnGREP，界面是不会变的。（但我平时使用时不是直接打开dnGREP，然后输入内容进行搜索。）
- 我使用Autohotkey脚本。（选中要搜索的内容，点击F1，脚本会启动dnGREP自动进行搜索）脚本内容如下；
`F1:: `
`IfWinExist ahk_exe dnGREP.exe`
`runwait, %ComSpec% /c taskkill /f /IM dnGREP.exe, , Hide`
      `  WinMinimize`
`Send, {ctrl down}c{ctrl up} `
`sleep, 50`
 `Run "E:\3\dnGREP\dnGREP.exe" -f "d:\txt5" /pm *.xhtml;*.txt;*.md -s ^%clipboard% , ,max`
`Return`
`#IfWinActive`
问题可能是出在我的脚本上，但我找不出问题来。我不太懂编码。
## 问题2  如何设置成只保留一个dnGREP.exe进程？

**Comment by doug24** [comment]
I have never used AutoHotKey, so I can't say what it is doing.  It sure seems like you are creating more work for yourself than you saving.

dnGrep saves the window layout in the user settings file, and it looks like the layout settings are getting corrupted.  It doesn't seem like a good standard practice to kill the task of a running program unless it is hung/not responding.

As long as it works normally, that is all I can do.

**Comment by zbb7001** [comment]
感谢你的回复！还有个问题

![image](https://github.com/dnGrep/dnGrep/assets/101622397/a4b67134-e4ba-4888-a814-6955574491ce)
### 如上图，请问：这个选项的作用是什么？

**Comment by doug24** [comment]
There will only ever be one instance of dnGrep running.  If you try to start a second one, it will exit and bring the first one to the top.  

The sub-option below it - if the second instance you start has a folder command line option (/f, -f, -folder) then the folder option from the second instance will be applied to the first instance.

**Comment by doug24** [comment]
You can search epub files with Apache Tika in [release 4.1.27](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.27.0)
I have not found a solution for Kindle files.

**Comment by zbb7001** [comment]
谢谢！刚看到又更新了，正在下载。。。。
